### ISSUE TITLE
[0wd4]公开课 笔记汇总

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#10]
- 前提: 参加 0wd4 公开课,或是看过回放
- 资源:
  - [录音](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151015_0wd4)
  - [幻灯](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151015_0wd4/OMOOC2py_Kaopulity.pdf)
  - 视频....uploading
- 时限: 1wd0 20:20 前
- 行动: 回复此 Issue 给出对应笔记的 URL
  - 不用 `@` 任何人
  - 仅仅是直达链接即可
- 内容: 
  - 公开课对自己触动最大的 top 3 内容
  - 对比自己过往行动, 应该有哪些可以应用以上三点建议进行改进的?
  - 给出具体改进的方案来
    - 针对当前具体的学习/技术/提问...问题
    - 方案描述尽可能包含所有 [5W1H](http://wiki.woodpecker.org.cn/moin/5W1H) 要素!

`是也乎:`
- 151016 00:17 几乎刚刚关闭直播, 笔记就已经有发布的了?! 而且都是 MM ....这什么节奏!?
- [[0wd4]issue NoteOpenClass A new approach alive! · Issue #12 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/12) 也是可以的 ;-)
  - 但是,不算正式笔记
  - 先 closed 以免干挠讨论线索

**Comment by aJiea** [comment]
https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/1md.html

谢谢软广植入 (」゜ロ゜)」
_Miss Python and the Holy Geeks_ 里重新更新补全了top3的运用部分。

---

gitbook使用时有时不开vpn登录不了，有时开了vpn更加慢。
编辑了文档， 保存了，但是book一直处于refreshing状态。

**Comment by zjuguxi** [comment]
https://zjuguxi.gitbooks.io/hard-way-to-python/content/week/class2nd.html

**Comment by 4plus-ma** [comment]
https://4plus-ma.gitbooks.io/omooc2py/content/ke_tang_bi_ji.html

**Comment by jane325** [comment]
https://jane325.gitbooks.io/jane325/content/gong_kai_ke_bi_ji_zong_jie.html

**Comment by jane325** [comment]
https://jane325.gitbooks.io/jane325/content/ke_zong.html

>  把长长的中文命名改了下，谨记，在编程中，尽量少用中文命名。
- 非常赞的自我改进!
- 而且大胆的破除了俺的单行要求
- 其实, 你可以推想一下 大妈 为什么有这种要求?
  - 这就是明显的编程式要求了
  - 有其原因/目的以及背景条件
  - 看你何时能 got 到 ;-)

@jane325 注意!

@OpenMindClub/py2staff 跟进,凡时第一行不是单纯教程链接的,进行主动修订!

**Comment by JeremiahZhang** [comment]
https://github.com/JeremiahZhang/gopython/blob/master/PY-StarTrek-Enterprise/0w/2015-10-15-0wd4-OpenCourse-Note.md
- 内容很对味儿
- 但是:
  - 没有使用课程仓库的 fork 
    - 你将丢失和大家一样的脚脚手架
  - 虽然 github 的仓库能很好的解析 md 格式为网页
    - 但是,这种网页是他人无法快速评注反馈的
    - 这也将导致你一直自说自话,无法和学员们主题式交流起来
- 所以!
  - 请立即登录 [ZM](http://www.iomooc.com/)
  - 回顾 0w任务
  - 跟同大家 fork 课程仓库
  - 将积累的教程,迁移到对应目录中

@JeremiahZhang 注意!

@OpenMindClub/py2staff 跟进,落实,完成课程仓库的 fork/教程迁移为 Issue

---

已经移库 更新到了 gitbook
https://jeremiahzhang.gitbooks.io/pybeginner/content/02-learn/0wd4-OpenCourse-Note.html
@ZoomQuiet

**Comment by JeremiahZhang** [comment]
> https://4plus-ma.gitbooks.io/omooc2py/content/ke_tang_bi_ji.html
> @4plus-ma 你给的连接 无法打开 嗯 我的网络正常

**Comment by 4plus-ma** [comment]
@JeremiahZhang 现在应该能打开了，再试一下~

**Comment by jane325** [comment]
* 尽量少用中文命名的原因（转译大妈昨天的公开课）：
 * 编程这种将行动过程与序列编织起来的行为诞生于使用英语的国家，不同的语言交互难免产生的不必要信息与编程存在的终极目的相左。
    * eg.中文必然被拆解成拼音的模式加上下划线的假想空格才能转化成机器听懂并给予反馈的机制决定了在编程学习中使用中文的弱势（时间与精力的成本）
    * eg.反例：Markdown的发明，Git家族命令行、快捷键的使用都是在让“符号化”的编程行为更轻盈

* 编程存在的目的
 * 正如发明万维网并无私贡献的Tim Berners Lee所言，仅仅是出于实验室的需要（解决问题），而不是我们脑补的拯救全宇宙。
 * 诞生于西方的编程行为决定了要理解编程并参与项目解决问题的最快方法就是使用“行话”。大家都听得懂，才知道如何彼此协助。

* 感悟（转译来自人类简史）
 * 进化至今依靠的是---合作---划分了人与动物进化的界限---合作前提是使用语言---实现信息的共享
@ZoomQuiet 大妈，弱弱的问一句，你说的单行要求是什么？负基础，理解行话也成问题。。。

**Comment by ZoomQuiet** [comment]
2015-10-16 14:25 GMT+08:00 jane325 notifications@github.com:

> 尽量少用中文命名的原因（转译大妈昨天的公开课）：

...

> 大妈，弱弱的问一句，你说的单行要求是什么？负基础，理解行话也成问题。。。
- 单行
- 如其字面意义: 单独一行
- 笔记链接单独占第一一行
- 比如:

```
https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/1md.html
```

以上是单行链接

```
前面有文字,空行
https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/1md.html
```

以上不是单行链接

```
https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/1md.html
<-- (￣▽￣)
```

以上也不是单行链接
- 嗯哼!
- 所谓,负基础,并不是笨,只是没有习惯编程世界异常精确的思维习惯
- 因为我们日常从来都是混沌的, 比如:
  - `下午一点半,我们去喝cafe 哪`
  - 指的是 13:15:00~13:45:00 之间任何一个时间点
  - 但是,编程中就必须是: `14:42:00` 这种精确到秒以下级别的确认!
  - 否则你的程序是不可能同其它配合起来的
- 但是,如果俺每个指令都类似以上进行解释
- 很可能一周的任务, 你们的成品代码才42行,
- 但是,俺的任务说明文字就得 420 行以上!
- 俺是承受不了的...
- 所以, 脑补在编程界一样有,只是原则更加精确,少,有关键,可叠加/复用....
- 所以, 和程序猿沟通,效率是越来越高的
- 和普通人沟通相反.

**Comment by jane325** [comment]
@ZoomQuiet  嫌弃自己的表达的繁琐，最后忍不住删掉，大妈的神速捕捉让人印象深刻。正如修炼之道里说的不要自我重复，让可复用变得容易，不止是看完而已，说说而已啊。谢谢大妈的帮助。

**Comment by Cen74** [comment]
https://cen74.gitbooks.io/omooc2py/content/Week0/note.html

**Comment by LishuaiBeijing** [comment]
https://lishuaibeijing.gitbooks.io/omooc2py/content/2015-10-15_note.html

@LishuaiBeijing 亲,你和俺一样没折腾出来 DISQUS 只好回复在这儿了:
- 笔记作业没有完成哪,另外一半是如何运用触动来改进当前问题的方案?
- 另外,

![2015-10-17 00 32 20](https://cloud.githubusercontent.com/assets/22494/10547371/908de5ee-7466-11e5-936d-4b995c495570.png)
- 以上类似的 md 格式溢出说明你:
  - 并没有进行本地检验
  - 以及非常自信
- `好的问题本身已经包含了答案`
  - 请回顾录音/录像
  - 俺的原话应该是: `好问题本身必定包含了答案的解决方向`
  - 一个正确答案只能解决一个问题域的一点情况
  - 而一个好问题则能开创一个全新领域思路
  - 参考: 
    - [创新算法 (豆瓣)](http://book.douban.com/subject/3354596/)
    - [小黄鸭调试法](http://www.iomooc.com/pages/cards.html?taskId=3cfcade0-733d-11e5-a837-0800200c9a66#tip6)

---

@ZoomQuiet  
改了一些原文的内容，加入了“应用”部分和一些干货。
disqus我已经配置好了，自己测试了一下，应该没问题。
关于格式溢出，其实我最初是在简书上写的，往gitbook拷贝时没覆盖掉自动生成文档中的默认第一行。现已删除。
DAMA推荐的两个链接先收藏了。
python代码还没开始写，很惭愧，马上开始行动。
感谢DAMA，再次附上链接：
https://lishuaibeijing.gitbooks.io/omooc2py/content/2015-10-15_note.html

**Comment by wwshen** [comment]
https://wwshen.gitbooks.io/omooc2py/content/0MOOC/Lecture2.html

**Comment by wzzlj** [comment]
https://github.com/wzzlj/OMOOC2py/issues/1

**Comment by bambooom** [comment]
https://bambooom.gitbooks.io/omooc2py/content/0wd4.html

@bambooom 以上页面无法打开...

**Comment by xiangzhendong** [comment]
https://xiangzhendong.gitbooks.io/notesforpython/content/chapter_1.html

**Comment by simple2source** [comment]
https://simple2source.gitbooks.io/ompy2/content/1sTry/gong_kai_ke_bi_ji.html

**Comment by liznut** [comment]
https://liznut.gitbooks.io/omooc2py/content/0MOOC/0wd4_record.html

@liznut 以上页面无法打开...

**Comment by picklecai** [comment]
https://github.com/picklecai/OMOOC2py/blob/master/0MOOC/note.md

是也乎, (￣▽￣)
只能说完成了一小半作业哪,参考:
[[0wd4]公开课笔记任务 · Issue #1 · wzzlj/OMOOC2py](https://github.com/wzzlj/OMOOC2py/issues/1)
- 使用仓库来发布笔记是关闭了和其它同学的交流渠道哪!
- 如果 gitbook-github 体系没有打通,没有关系
  - 用 Issue+仓库吧.

**Comment by Iris-Di** [comment]
https://iris-di.gitbooks.io/omooc2py-gitbook/content/0MOOC/week1.html

**Comment by Acural** [comment]
[第一周大妈开光记](https://acural.gitbooks.io/pythonlearning/content/dama1/myfile.html)

**Comment by sunoonlee** [comment]
https://sunoonlee.gitbooks.io/omooc2py/content/0MOOC/0wd4-notes.html

**Comment by Cloudtree11** [comment]
[[0wd4]公开课 笔记 by Cloudtree](https://cloudtree.gitbooks.io/omooc2py/content/0MOOC/0wd4_class_note.html)

**Comment by zoejane** [comment]
[看到自卑，看到不敢，看到就会有新的发现 by Zoe](https://zoejane.gitbooks.io/omooc2py/content/1sTry/video1.html)

**Comment by luoquan19** [comment]
https://luoquan19.gitbooks.io/omooc2py/content/0wd4note.html

**Comment by penguinjing** [comment]
[0wd4公开课笔记 by Penguin](https://penguinjing.gitbooks.io/omooc2py/content/1sTry/0wd4notebook.html)

**Comment by ZoomQuiet** [comment]
On Sun, Oct 18, 2015 at 12:17 AM, luoquan19 notifications@github.com wrote:

> https://luoquan19.gitbooks.io/omooc2py/content/0wd4note.html

@luoquan19 亲! 404 了!

> —
> Reply to this email directly or view it on GitHub.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by liangpeili** [comment]
https://liangpeili.gitbooks.io/omooc2py/content/week1/opencource.html

**Comment by CherHu** [comment]
https://cherhu.gitbooks.io/gopython/content/0MOOC/1wnotemd.html

**Comment by LilinAndLilian** [comment]
https://lilinandlilian.gitbooks.io/omooc2py/content/

@lilinandlilian 你提交的链接不是笔记对应的链接,
- 俺找到的记要是
- https://lilinandlilian.gitbooks.io/omooc2py/content/xiaozuowen_md_md.html
- 而且没有配置好 DISQUS 所以,
  - 俺只能回复到这儿
  - 注意提醒,没有评注的教程,可以用 Issue 了

**Comment by hysic** [comment]
https://hysic.gitbooks.io/hysic-s-python-journey/content/Lect/20151015_review.html

**Comment by cxiaodian** [comment]
https://cxiaodian.gitbooks.io/omooc2py/content/0MOOC/lecture_two.html

**Comment by xpgeng** [comment]
https://xpgeng.gitbooks.io/omooc2py/content/0MOOC/0wd4.html

**Comment by hanbing718** [comment]
https://hanbing718.gitbooks.io/hanbing718-python-1016/content/0MOOC/1.2_0wd4_class2.html
