### ISSUE TITLE
[7wd6]深圳C2T2报名

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/OMOOC2py#102]
7w/8w 来了，你的[[8w~迭代作品] ](https://github.com/OpenMindClub/OMOOC2py/issues/96)酝酿已久，只等爆发？

来参加本次 C2T2 和小伙伴们分享一下吧。

本次活动主题： 如何组建团队并迭代开发作品？

参考资料：[[6wd4]公开课 笔记汇总 · 如何组建团队?](https://github.com/OpenMindClub/OMOOC2py/issues/92#issuecomment-159948219)
- C2T2 活动规则
  - 以`学员互助`为主，学员互助自由交流时间必须大于教练一对多单向输出的时间
  - 参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
    - 并附带 42 字内文字说说自己今天最大的收获
- 报名: 回复说明以下关键信息
  - github 帐号
  - 大约到达时间
  - 期望现场解决的技术问题
- 截止: 周五 24:00 前有效
- _提醒:_ 必须带上电脑,以便现场明确技术问题的细节 ;-)
- C2T2 地点及时间
  - 地点: [深圳华侨城如盒艺术空间](http://www.dianping.com/shop/19482910)（华侨城恩平街创意园东部工业区E6栋103(康佳集团))
  - 时间: 周六 14:30~17:30
    ![](http://7xjhtv.com1.z0.glb.clouddn.com/thumb.jpg)
- [录音纪要](http://7xoxk3.com1.z0.glb.clouddn.com/C2T2/7w6dc2t2/index.html)

参考:
-  [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)
-  [[1w] 各地 C2T2 要点汇总](https://github.com/OpenMindClub/OMOOC2py/issues/63)
- [[0w] 各地 C2T2 纪要及录音、讲演材料](https://github.com/OpenMindClub/OMOOC2py/issues/42)
- 注意:弃用`面基`一词, 这是个极其恶意的 KUSO 名词!

**Comment by bambooom** [comment]
- github账号: bambooom
- 大约2:20pm到达
- 还是prefer周日8wd0

**Comment by penguinjing** [comment]
是否考虑周六下午？ 广州/外地学员还可来参与。

**Comment by bambooom** [comment]
可以的呀~如果大家都周六下午比较ok的话~
我只是比较prefer周日，没说周六不可以嘛~

**Comment by ivanlau** [comment]
ivanlau
大约14:30
时间地点随意都可以

**Comment by junjielizero** [comment]
github账号: junjielizero
大约14:30到

**Comment by Langzzx** [comment]
github账号: langp618
大约2:30pm准时到
昨天被大妈鄙视了，还是要来参加，免得大家使劲的把我当反面案例说

`闪闪`：大妈那不叫鄙视，别人对于他多次示范仍视而不见时他习惯性地会这样回应，忽略情绪，注意对比他之前类似情况下怎么示范的就好

**Comment by penguinjing** [comment]
github账号: penguinjing
大约13:50到

**Comment by cxiaodian** [comment]
- github帐号 cxiaodian
- 先报名，明天确定能否到，
- 大约2点到

**Comment by xiangzhendong** [comment]
github帐号：xiangzhendong
大约14:30到

**Comment by demonmax** [comment]
github账号: demonmax
预计到处时间14:20
解决问题：1. 完善作品设想  
2. 探讨在大量坑没踩的情况下，用3w完成期望作品的最小原型。

**Comment by sunnyhuang42** [comment]
不知道这次线下活动进展如何？没有人提交纪要的话……过期关闭咯
