### ISSUE TITLE
[8wd0] 长三角大区 C2T2 报名/纪要

### ISSUE THREAD

**Issue by cp4** [OpenMindClub/OMOOC2py#104]
异星之旅进入最后阶段！
刀锋磨练已久，现在是试刃之时！

本期课程长三角最大规模C2T2，多地市学员聚会一堂，结识好友，寻找队员，交流分享，互助共创！
这次，我们邀请每位学员展示自己和自己的项目，这是创作者和创业者的时代，把你的想象变成现实吧，和战友把酒言欢共同奋斗吧，体验项目从无到有的甘苦和激动吧！
### C2T2 活动内容
- 教练 @haidao：真实项目开发中的经验分享
- 学员 @小赖分享 : py 课学习中的方法与心得
- 学员自我介绍（有项目计划的，含项目介绍/队友招募）
- 自由交流/ 疑难解决
  - 自由组队
  - 技术解答
  - 项目/组队困难求助
### 时间
- 周日 14:00~17:00
### 地点
- 上海 
  北京西路1068号1楼 [漫猫咖啡](http://j.map.baidu.com/Gjxt7)
### 报名
- 回复报名即可，有项目的请注明
- _可选_ 现场自我介绍时使用的幻灯请提前发送
  - 使用 keynote 的，发给 @haidao， email: wwulfric@gmail.com  
  - 使用 ppt 的，发给 @培炎 , email: wangppei@gmail.com  
    **注**：需要介绍项目的同学，此项为必选项  
    **注2**：个人介绍请把时间控制在 3 分钟之内；有项目的控制在 5 分钟之内  
- _可选_ 说明需解答的 top 3 问题（可以是项目与组队方面）
- _可选_ 操作系统
- _可选_ 教程地址
### **注意**
- 由于可能需要预定场地，本次报名周六 14：00 之前截至
- 包场地或租用投影仪，均需额外费用，此费用所有参加者均摊
- 项目和组队请提前参考:[8w~迭代作品](https://github.com/OpenMindClub/OMOOC2py/issues/96)

**Comment by Wangqiaoyang** [comment]
报名
系统：Mac
群内昵称：乔阳
[项目启动](https://github.com/Wangqiaoyang/RIA-Brain-truster/issues/1)

**Comment by haruhi99** [comment]
报名：haruhi99
系统：Mac

放上整理的录音。有需要的同学可以自己下载.链接：http://pan.baidu.com/s/1nuftIfZ 密码：e5pg

**Comment by jameszhou89** [comment]
报名，这次必须来！

**Comment by shawn0lee0** [comment]
报名：
系统：Win7+Python27
个人微信号：robo_one
开智群微信昵称：shawn0lee0
[项目说明](https://shawn0lee0.gitbooks.io/python-omooc2py/content/2nDev/index.html)

**Comment by Lcking** [comment]
报名：
系统：py+win7

**Comment by Iris-Di** [comment]
报名

**Comment by Sherrywangintj** [comment]
报名
系统：Win

**Comment by csyuking1989** [comment]
报名
系统：Mac  
群内昵称：陈申雨
由于种种原因，已经好几个礼拜没有跟踪课程了，汗颜..... 日后要加快补上了。

**Comment by cp4** [comment]
# C2T2 活动纪要

## 流程

### 演讲
- 肖凯：Python数据工具箱
- 路飞：如何开始一个项目
- 参会学员自我介绍及项目介绍
- 小赖：我的python 学习及使用技巧

### 自由交流 / 组队

## 资料

  现场演讲材料+音频+照片链接：http://pan.baidu.com/s/1mhvAMla 密码：2cx6

**Comment by jameszhou89** [comment]
昨天活动的总结
https://jameszhou89.gitbooks.io/moocpy2/content/c2t2_7w.html

**Comment by sunnyhuang42** [comment]
过期关闭
