### ISSUE TITLE
[7wd4]在线探讨作品构想 报名

### ISSUE THREAD

**Issue by sunnyhuang42** [OpenMindClub/OMOOC2py#105]
~ 和几位群友商量了一下，7wd4 公开课 点评大作品 idea 的时候，将尝试用电话会议的方式联系各位 作品主创人员(1-2位) 进行现场探讨，让大家听不明白时可以及时提问讨论，同时也稀释大妈单口的成分：P

So~如果你希望和大妈即时探讨自己的项目构想，需要
1. 在周四中午 14:42 前把 Idea 回复到[[8w~迭代作品] 项目公示 · Issue #96 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/96) 
2. 并在本 Issue 回复相应信息：
   - 勇猛精进组微信群昵称
   - 项目名称
   - 想现场探讨的三个问题

这样大妈届时就会现场连线你啦。

机会难得，想和大妈即时交流的小伙伴速度回复信息报名嘞。如果错过 7wd4 的即时探讨，再想找大妈参谋，就要自己用其它姿势 touch 他咯;-)

**Comment by liangpeili** [comment]
勇猛精进组微信群昵称：@liangpeili
项目名称:买房推荐系统
想现场探讨的三个问题：
- 选择大作业项目背后的原则
- 哪些项目适合基于微信平台开发？
- 没有三了

#### 关于大作业原则思考：
1.  有价值的
   能够给人带来实际帮助，解决某个问题的；买房推荐系统就是希望能达到这样一个目标：如果一个用户想买房，那么他能在这里获得最关键的信息（注意不是全部信息），关键信息就是价格、户型、年限、小区周边环境以及别人买这个小区的房子时是怎么考虑的。如果用户能在买房时获得这些关键信息，那这些信息就能够帮助他做出正确的决策。
2.  可实现的
   现有成员都有自己的工作，只能在业余时间写程序。并且大家都是10月份0基础开始学的，技术水平也都只是入门级别。因此大作业比较理想的难度是比之前的课程内容难度高一些，但不能高太多。但也不能太简单，一个人一星期就搞定的那种；对于买房推荐系统来说，大家需要学习的只有爬虫和数据库。因为我本身是一名DBA，所以数据库这边没什么压力，大家只要专心学习爬虫就好。爬虫牵扯的面还挺多的，比如HTTP包的具体内容、正则表达式、前端页面的解析等，但是在现有的基础上用三周的时间学爬虫，入门是没问题的。
3. 团队成长性
   我理想中的团队合作，应该是群策群力。在做完这个大作业之后，团队中的每个成员都能有收获，不出现那种只挂一个虚名，最后出结果了再露一次脸的情况。也不要出现一个人把代码都写了，别人只是观察员的情况。大家的职业背景不同、知识背景不同，都可以对团队有所贡献，让自己有所成长。我们团队的四个成员（杨绍顺、黄鸿志、党祎还有我）是在北京的C2T2上认识的，最后有意无意的走到了一起，成为了一个团队。相信我们能够一起去完成这个作品。

归结成一条就是：**利用现有条件，一起完成最有价值的事情。**“现有条件”、“一起”、“完成”、“有价值”四个条件缺一不可。

#### 关于微信平台的问题：

微信平台上，客户和服务端的主要沟通途径是那个编辑框，这个编辑框的局限性是很大的。它最合适的用途是用来聊天。如果想在微信上做一个公众号，也要符合这个规范。比如之前的云笔记的点子，修改笔记内容就难以通过编辑框完成，而需要额外的编辑器。

**Comment by Langzzx** [comment]
勇猛精进组微信群昵称:@langp618
项目名称: Passistant
想现场探讨的三个问题:
- 加密技术选择，简单快速易用，如何避免管理人员看到保存在服务器的信息；
- 邮件推送，选择自己搭建议的邮件服务还是选择云端，或其他的推荐；
- 项目进行中如何避免 “范围蔓延” 和 合理进行技术方面的“渐进明细”

**Comment by shawn0lee0** [comment]
勇猛精进组微信群昵称：@[shawn0lee0](https://github.com/shawn0lee0/RUNMAP/wiki)
项目名称:一个趣味运动轨迹社交应用
想现场探讨的三个问题：
- 本产品适用服务端架构的选择与建议？
  - 微信+3rd+API ：优势：适合国内用户，快速裂变推广；劣势：链接的圈子太封闭违背[开源精神](https://github.com/lifesinger/lifesinger.github.io/issues/167)
  - 手机WebView、UIWebView+ Cloud Server Api，优势：兼容性强；劣势：实时性问题。。
  - 数据库+后台系统的推荐？ 
- 游戏化反馈系统设计建议？
- 如何缩短该项目的迭代周期？
  - 核心需求提炼：1、GPS轨迹生成 2、认证登录，3、多轨迹融合 4、反馈 5、分享……
  - 我的理解：首先这是作业，其次才是产品，某时间段专攻一个需求，牺牲用户体验、放弃创意，换进度，进度，进度

**Comment by Wangqiaoyang** [comment]
勇猛精进组微信群昵称：@乔阳
项目名称：拆书智囊
想现场探讨的三个问题：
- 就产品实现的功能而言，该产品制作难度与课程作业难度对比如何？
- 微信公众号同时与豆瓣、印象笔记api进行对接的技术难点评估，通过微信后台输入关键词，抓取印象与豆瓣中特定用户的数据（恩，有点像小小书童了）此功能实现的大致过程是怎样的？
- 该项目如何分工比较合适？（目前团队2人）

**Comment by aJiea** [comment]
－ 勇猛精进组微信群昵称：珠-Mac-啊阿Jie
－ 项目名称待定： [Octodog](https://github.com/aJiea/Boss_project/issues/1)

说明：
相当于课程学员的tweeter，自动抓取在github和gitbook数据，以及教员互动数据进行推送
1.第一时间通过微信了解课程学员在什么时间做了什么（可以进行特别关注设置）
2.可以看到课程学员的即时动态和即时加分信息，并点击查看（对其他成员进行激励）+(和qpython的结合在手机上运行)
3.教员，CEO和学员之间的互动即时推送，比如在gitbook留下的意见，对其他学员也有参考性
4.结合阿西莫夫的微信聊天关键词和资料进行当日汇总（待定）
5. 固定地方，看到进度（python，团队）
6. 技术的手段取代人工观察员，提高观察反馈效率

平台：微信（符合即时性）

－ 三问：
1.项目需求设置是否合理，在哪些方面可以配合开智课程需求进行改进
2.如何抓取github和gitbook更新数据，gitbook一般写一些，保存一些，如何设置形成有效数据抓取
3.数据分类，可读性高，技术指导

**Comment by xpgeng** [comment]
来晚了, 不知道还能不能被大妈看到.
- 勇猛精进组微信群昵称    [沈浪](https://github.com/xpgeng)
- 项目名称   带它回家
- 项目简介
  - 提供web平台收集, 发布流浪宠物的信息, 如照片,文字描述等等
  - 连接微博API, 使之同步到微博发布
  - 连接微信公众号, 能在微信公众号中查阅信息, 上传信息.
  - 如果时间允许, 考虑做android端.
- 想现场探讨的三个问题
  - 图片信息如何存储. 七牛是否提供接口使得在web端上传, 自动存入七牛.
  - 随着访问量增多, 七牛是不是划算的选择? 未来费用会不会很高?

**Comment by jameszhou89** [comment]
勇猛精进组微信群昵称：@james周慧明
项目名称:社群参与者数据库
项目介绍：https://jameszhou89.gitbooks.io/moocpy2/content/project_proposal.html
想现场探讨的三个问题：
1.如何确保数据安全？

**Comment by ivanlau** [comment]
现在补来得及吗
ivanlau
项目名称:记着买（购物清单笔记）
项目简介：简便地解决购物过程中做笔记的需求，并以此为起点，形成平台式的商业项目
项目说明：https://github.com/ivanlau/jizhemai/issues/1
请教问题：图片、附件等信息的储存以及调用的实现方法。
图片从微信客户端由用户上传到项目的自有服务器端，用kvdb可以利用默认提供大量空间（默认好像是100g），但是流量耗/访问量的厉害，用sae的话费用貌似不菲（其它云服务也类似吧）。不知道在这种场景用什么方法存储和调用比较好？使用二进制流存在数据库好还是用云的存储SCS然后调用？谢谢！

**Comment by sunnyhuang42** [comment]
嗯？大家沟通了之后都没有将收到的建议和目前的打算更新到这里确认一下是否有理解偏差吗……

那先 close 了…
