### ISSUE TITLE
期末项目：个人服装搭配日记

### ISSUE THREAD

**Issue by yondjune** [OpenMindClub/OMOOC2py#106]
https://github.com/yondjune/OMOOC2py/tree/master/2nDev

进展 - 20151203

1.发起人所在城市：广州

2.发起人优势： （女生算不算是优势哈）

```
     - 主攻 **互联网+ **商业方向

     - 负责市场、内容、客服等运营， 及平面UI设计

     - 产品逻辑简单 
```

技术及功能点：

```
     - UGC 产品，从web版到 app 版 （视乎团队组建情况及项目进度而定）

     - 登陆注册页面， 连接微信，微博，豆瓣，qq，注册接口

     - 产品基础页面功能： 如图
```

![3](https://cloud.githubusercontent.com/assets/14872226/11587307/57ca4d10-9ab3-11e5-9302-02d35eb86ecf.jpg)
# 

未来发展策划，市场/用户/系统压力预测：

如果能找到胜任的技术合伙成员，会把它从兴趣项目转变成商业项目。 寻找投资方及合作的商家

安全稳定的专业电商平台 是该项目的最终走向*之一 \* 基于用户数据及外部数据进行商业分析

所以需要找到一名胜任的CTO，全栈类工程师， 能以BAT现有技术服务作为追赶点，具有高效专业的项目实现能力。

**Comment by penguinjing** [comment]
呃，作业要求issue开在自己的任务专用库中。

没太明白这个程序计划实现的功能呢？ 在线浏览图片的ACDsee浏览器？还是自动搜索某指定网站上所有可公共访问的图片进行浏览(peek)呢？

感觉还差1位：天使投资方。:-)

**Comment by yondjune** [comment]
1.发起人所在城市：广州

2.发起人优势： （女生算不算是优势哈）
     - 主攻 *_互联网+ *_商业方向
     - 负责市场、内容、客服等运营， 及平面UI设计
     - 产品逻辑简单 发展潜力大
1. 项目成员
   雷雨负责 app aka
   王海滨 负责支付接口
   stormf yondjune 负责web框架

观察员：小赖同学
1. 已知的技术难点
   手机app端 aka
   Sae  Flask
2. 最小成品要求：blog 版

现有的代码基础
http://cloudbbs.org/forum.php?mod=viewthread&tid=24360
利用SAE Storage+Flask搭建图片托管站
1. 问题场景,以及解决思路：
   作出每日的服装搭配日志记录
2. 技术及功能点：

     - UGC 产品，从web版到 app 版 （视乎团队组建情况及项目进度而定）

     - 登陆注册页面， 连接微信，微博，豆瓣，qq，注册接口  （视乎团队组建情况及项目进度而定）
     - 添加支付接口
     - 产品基础页面功能： 如图

版本规划,第几周应该完成的功能点
...

**Comment by JeremiahZhang** [comment]
@yondjune aka = all know all 呀 == == ==

**Comment by yondjune** [comment]
项目进程及issue记录

移至以下根目录

https://github.com/yondjune/imatch
