### ISSUE TITLE
开智福利：［Octodog/章鱼狗］ Prototype已出！邀请你一起去相信，去实现！

### ISSUE THREAD

**Issue by aJiea** [OpenMindClub/OMOOC2py#107]
# 迭代项目：**Octodog／章鱼狗**
### 项目背景：

> ［Octocat／章鱼猫］是Github吉祥物，而［Octodog／章鱼狗］通过其灵敏的嗅觉，追踪开智班成员的章鱼猫commits，汇总于章鱼狗平台。
> <img src="https://cloud.githubusercontent.com/assets/13810631/11613693/2d73259c-9c65-11e5-99d8-7a378798a62b.jpg" width="50%" height="50%">

---
### 产品设计：

1.一键查看各组／各成员信息，及学员相互／教学员互动信息（MVP）
- 省去一个个点击查看的低效和不便
- 省去教员整理学员名册的手工活
- 促进［学员／教学员］互动和交流

2.芝麻星分值计算开源，团队／个人“KPI”可视化

3.当天精简日报输出（优质数据筛选）

---
### 诚意成果：
- 小范围的教学员预期调查《[你想让章鱼狗做什么](https://github.com/bambooom/ProjBoard/issues/1)》
- [原型网页](http://projboard.sinaapp.com/) 功能展示 (图一)
- [proto UI](http://y8sj0d.axshare.com) 效果展示（图二图三）

---
### 效果图一

![web](https://cloud.githubusercontent.com/assets/13810631/11613700/75fef82c-9c65-11e5-8c40-53dc3987a757.jpg)
### 效果图二

![ui1](https://cloud.githubusercontent.com/assets/13810631/11613701/92a94c5c-9c65-11e5-9dab-928d46b65e39.jpg)
### 效果图三

![ui](https://cloud.githubusercontent.com/assets/13810631/11613704/986e155a-9c65-11e5-8364-b9677b1b5156.jpg)

---
### 流程
- 8w 网站基本成型
  - 框架
  - 能完成的功能点: 项目基本信息展示+留言板
  - 测试反馈
- 9w 添加功能
  - 日报
  - 各项目进展
  - 各项目成员contribution比例
  - 测试反馈
- 10w 测试+优化 若还有时间添加其他功能再继续添加~

---
### 招聘

> 好的课程配上不断优化的服务体验。
> 
> Octodog／章鱼狗，信则来！
- 前端，对数据可视化有兴趣
- 观察员
  - 章鱼狗仔队：观察小组情况进行记录
  - 章鱼狗测试队：观察其它小组，进行章鱼狗平台测试

联系@bambooom 或 @aJiea 报名！

---

章鱼狗代码仓：https://github.com/bambooom/ProjBoard
章鱼狗血泪史：https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/8wd0.html

**Comment by aJiea** [comment]
8w 网站基本成型, 先有框架 
能完成的功能点: 项目基本信息展示+留言板
9w 添加: 日报+各项目进展+各项目成员contribution比例
10w 测试+优化 若还有时间添加其他功能再继续添加~

**Comment by aJiea** [comment]
reopen

**Comment by hysic** [comment]
@aJiea @bambooom 报名章鱼狗gogogo! 
坐标北京, 独立完成前5周作业, [5w作业](http://hysic1986.sinaapp.com/). 之前用过一点[ECharts](http://echarts.baidu.com/doc/example.html), 对数据可视化也比较感兴趣, 可以帮忙做可视化的工作, 也可以上手写 python 代码, 当然也可以观察与测试.

**Comment by huijuannan** [comment]
@aJiea @bambooom 
[带TA回家](https://github.com/xpgeng/straypetshelper)项目前端，报名做章鱼狗观察员
坐标哈尔滨，之前用matlab处理气象数据、计算、作图，独立完成前5周作业

**Comment by aJiea** [comment]
### 8wd1 小组讨论

时间：2015-12-07 周一晚上 21h 
平台：暂定[webex](http://www.webex.com.cn/)会议，房间号20h30在微信Octodog群更新 

### 暂定内容：
- 分工
- 项目流程
- 本周mvp
  - 定位
  - 难点
  - 分工
  - 反馈（反馈给教员或大妈寻求帮助）

### 准备工作：

最好20h30前issue回复下列信息，以便匹配和高效沟通
- 自我介绍
- 自我介绍和章鱼狗的匹配（思考职位需要做的事）
- 其它建议
- 疑问

---

其实对这次会议的观察，也算是观察员的重要工作之一啦，希望做观察员的可以特别留意下

**Comment by 4plus-ma** [comment]
报名加入🐙🐶~

@4plus-ma，4+，大四广告学在读学生，同时摄影类APP创业小公司COO（运营就我一个，姑且算首席吧：）。爱学习，爱折腾，喜欢新鲜事物。会点设计（PS），能拍些小片（照片/视频），能剪辑视频（Pr），能做Keynote，敢想能说执行力强。希望下次能加上会python编程（目前水平堪忧T T，但我还是很有用的对吧，笨办法刷到21课。）。之前参加了「开智写作班」「开智产品经理班」，正在参加「像黑客一样学习」。

**Comment by hysic** [comment]
- 自我介绍: @hysic, 坐标北京, python 课完成到5w SAE作业, 用过一点 [ECharts](http://echarts.baidu.com/doc/example.html).
- 小组讨论问题: 人员分工? MVP 中的评论如何实现?

**Comment by aJiea** [comment]
- 自我介绍：@aJiea，珠海，系统MAC
- 小组讨论：
  1. 展示：之前画的web界面是我对mvp的初步理解，大家提意见补充
  2. 技术：这里概念比较模糊，需要根据mvp功能进行数据挖掘，github API等问题，正在查询中
  3. 两个产品：
     - 开发的技术产品［Octodog🐙🐶］，符合开智课程对技术的要求
     - 团队工作汇报内容产品，简称［🐶报］，符合开智课程思维训练目标

🐙🐶：
- @bambooom 开发
- @hysic 数据可视化
- @aJiea 前端
- @huijuannan 前端指导&观察（已经是另一个小组的前端）

🐶报：
- @Scott 小组观察员（本组和其它组）
- @4plus-ma 产品运营&观察
- @zero 待定观察员

探讨具体两个产品的工作方向及分配

**Comment by ZoomQuiet** [comment]
![2015-12-07 20 50 29](https://cloud.githubusercontent.com/assets/22494/11627295/5b6bbe22-9d24-11e5-950e-61f54835ab16.png)
- 能技全开! 
- 有用有趣有种 三有项目!

**Comment by aJiea** [comment]
## 2015-12-07 8wd1 21h-21h30 Octodog🐙🐶一次会议

> 我对章鱼狗的本质看法是通过学习别人来学习。——竹子🐶

### 参加🐶：
- @bambooom 开发
- @hysic 数据可视化
- @aJiea UI设计
- @huijuannan 观察员
- @Scott 观察员
- @4plus-ma 产品运营

[录音](http://7xnvqn.com1.z0.glb.clouddn.com/Octodog8wd1.mp3)

### 🐶论：
1. 数据
   － 理性数据交给🐙🐶
       － 仓库录入
       － github数据抓取
       － 留言板展现
       － 数据可视化
       － 日报
   － 弹性数据交给🐶报
       － 问卷调查

2.任务分配：8w为学习观察周
    － 一起学习API
    － bambooom建立Octodog仓库，大家一起contribute（工作反馈方式）
    － 记录各组仓库地址，谢谢素封帮完成了
    － Disqus可以插入博客，如何插入网页
    － 任意姿势进行观察，看看有什么值得观察的数据

3.Octodog产品运营
    － goanimate展现Octodog未来
    － 和开智的结合

### MVP：留言板

### 🐶问：
1. 就目前来看Octodog可以如何同开智进行更深入的集合
   。。。请补充

---

啊捷🐶个人任务认领：
- 和hysic对接前端展示问题
- API学习
- UI设计学习
- 对本小组的观察

**Comment by aJiea** [comment]
录音已更新，团队详情以后移至[Octodog仓库](https://github.com/bambooom/Octodog/issues)

**Comment by junjielizero** [comment]
报名加入🐙🐶~，当观察员
- 自我介绍：@junjielizero，以独立完成前6w任务，坐标广州

**Comment by leonpak** [comment]
弱弱的问一下，观察员主要负责什么呢？

**Comment by aJiea** [comment]
1. 产品分析：🐙🐶 是基于内容上的平台，通过内容整合达到高效沟通。🐙🐶作为一个观察的平台，要展示大家关于迭代项目想看到的东西。
2. 难点：对内容的控制。可用内容分为具象内容和抽象内容，两种内容如何抓取，如何进行有效内容筛选
3. 解决方案：
   - 具象内容：API抓取，小赖对接gitbook
   - 抽象内容：观察，探析用户需求（🐙🐶wish list），有效内容筛选，展示

综上所诉，在8w阶段🐙🐶的观察员需要观察：
1. 什么是大家想看的
2. 根据大家想看的去搜集信息并将信息和信息渠道反馈给团队
3. 草拟了一个问卷调查表 供参考 https://github.com/bambooom/Octodog/issues/6

**Comment by ouyangzhiping** [comment]
@leonpak  观察员，也可以充当「内测用户」角色:D

**Comment by ouyangzhiping** [comment]
@aJiea  很棒的产品设计！
