### ISSUE TITLE
「带 TA 回家」招募测试伙伴ing...

### ISSUE THREAD

**Issue by xpgeng** [OpenMindClub/OMOOC2py#114]
## 项目简介
- 「带 TA 回家」的诞生是因为项目组员都有这样的经历
  - 捡到流浪宠物但是由于种种原因自己无法收养, 想送给有能力收养的人, 可是相关信息渠道特别少, 于是大家一起建立这样一个平台, 为流浪宠物们找到一个温暖的家.
## 招募测试伙伴
- 随着项目的进行, 越发的认识到测试的重要
  - 项目人员有限, 很多bugs简直逆天一样的存在, 出现bug时才会意识到: 咦, 我怎么没想到..T_T 
- 于是十分渴望大家加入我们的测试. 
- [点这里](http://testpet.sinaapp.com)帮我们测试吧 ;-）
- [点这里](https://github.com/xpgeng/straypetshelper/issues/22)吐嘈、给建议
## 其他
- [仓库地址](https://github.com/xpgeng/straypetshelper)
- [功能checklist](https://github.com/xpgeng/straypetshelper/issues/15)
- [团队开发日志](https://github.com/xpgeng/straypetshelper/issues/3)

**Comment by ZoomQuiet** [comment]
过期 clodes
