### ISSUE TITLE
[11w~人生首秀] 项目演示迭代

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/OMOOC2py#115]
- 背景: 根据课程大纲
  - 11wd4(12月31日) 将在微信群进行人生首秀项目演示
    - 嗯,`人生首秀` 即是 `跨年演出`
  - 请在此提交 demo/文案/幻灯/视频/音频
    - 任何可以在线演示的形式都可以!
    - 参考 旗舰班优秀学员项目:[小小书童](http://v.qq.com/boke/page/b/0/l/b015562y5ol.html)
- 使用:
  - @OpenMindClub/py2student
  -  `人生首秀`乃 11w 任务,大家可在 9wd2~11wd3 内持续提交项目演示迭代
  - 迭代说明可`原地更新`,注明迭代时间即可
  - 教练及导师可在此提点学员项目
  - 学员们可参看彼此项目,协力做出最佳作品
- 提议:
  - 最好有链接到自个儿仓库的专用 Issue 中
  - 此处回复,只给出项目简述:
    - 名称:
    - E文代号:
    - 项目说明链接 ~ 指向对应仓库 Issue
    - 项目演示百度云地址:
## 直播提点

若想和大妈在线即时探讨项目迭代/演示想法，请在 9wd4 14:42 前回复[[9wd4]广州 直播现场 报名/记要 · Issue #113 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/113)
## 参考资料

![](http://openmindclub.qiniudn.com/team/cnfeat/image/team_show_0_1.jpg)

![](http://openmindclub.qiniudn.com/team/cnfeat/image/team_show_0.jpg)

![](http://openmindclub.qiniudn.com/team/cnfeat/image/team_show_1.jpg)

![](http://openmindclub.qiniudn.com/team/cnfeat/image/team_show_2.jpg)

强烈推荐下载:[团队协作工具书](http://www.frogdesign.com/sites/default/files/pdf/frog_collective_action_toolkit_cn.pdf),就地使用!

**Comment by yondjune** [comment]
# :heart: iMatch :shirt:  [项目进度](https://github.com/yondjune/iMatch/blob/master/iMatch/README.md)

## 讨论智能衣橱的可行性及实施的技术要点

方向: 基于以下点为用户推送
- 添加文字标签 进行语义分析
- 链接及时天气 数据库
- 分析图片服装的颜色

## 实现以下功能的技术要点:
- 搜索关键词抓取电商平台的在售商品图片进行搭配

`cnfeat`占坑记得填
`yondjune` 那当然咯
`cnfeat`项目进度不错嘛，貌似已经做出原型了？可以在这里展示。需要补充一下：项目演示迭代偏向对外说明，例如为何做这个产品？解决什么问题……项目进度适宜在[[8w~迭代作品] 项目公示 · Issue #96 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/96)补增

**Comment by xpgeng** [comment]
# 「带 TA 回家」

[测试地址](http://testpet.sinaapp.com/)
[欢迎吐槽](https://github.com/xpgeng/straypetshelper/issues/22)
`cnfeat`可尝试用文案/幻灯/视频/音频 辅助说明

**Comment by aJiea** [comment]
［🐙🐶Octopuppy／章鱼狗］
仓库地址：https://github.com/OctoPuppy/Octodog
演示版本：http://2.octodog.sinaapp.com/

`cnfeat`故事,嗯哼

**Comment by liangpeili** [comment]
名称：买房推荐系统
E文代号：House Recommend System
项目代码地址：https://github.com/liangpeili/housebuy
演示视频地址：待更新
`cnfeat`咦，之前不是有过视频演示么？

**Comment by demonmax** [comment]
### 名称:「书游」

E文代号：_BookU_

项目简述:  提供一个平台，记录同城社群内部各个人的可流动实体书目，提供查询和借阅记录服务，实现社群内部实体图书资源的共享。

仓库地址: https://github.com/Cloudtree11/OMOOC_Project

演示: 待更新

`cnfeat`期待更新~

**Comment by ZoomQuiet** [comment]
过期,进入抢跑路演!
