### ISSUE TITLE
[10wd0] 上海 C2T2 报名/纪要

### ISSUE THREAD

**Issue by cp4** [OpenMindClub/OMOOC2py#117]
演示迭代周已经开始,大家的作品可以考虑用合适的形式呈现啦.
当然，紧张的开发活动中，有问题，有焦急，有要向小伙伴展示的渴望……
没有比和同行者一同探讨，互通有无，同侪加速更爽快的啦
- C2T2 活动规则
  - 以`学员互助`为主，学员互助自由交流时间须大于教练一对多单向输出的时间
- 时间: 
  周日 14:00~17:00
- 地点: 
   [Mlily梦百合咖啡厅](http://map.baidu.com/detail?qt=ninf&uid=8b1a15e214544eafcf06a40c&wd=mlily%E6%A2%A6%E7%99%BE%E5%90%88%E5%92%96%E5%95%A1%E5%8E%85&b=%2813517218.97,3633500.75;13534130.97,3644812.75%29&query=&qid=&page_num=&detail=cater&from=map&ugc_ver=1)，
  卢湾区 西藏南路1592号(西藏南路中山南一路交叉口，近第九人民医院)
- 报名: _回复说明以下关键信息_
  - 你在做的项目，立项及进展链接
  - 遇到的问题
- 参考资料：
  [[11w~人生首秀] 项目演示迭代 · Issue #115 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/115)

**Comment by sunnyhuang42** [comment]
嗯？照片和录音，麻烦 @cp4 尽快更新一下~

**Comment by cp4** [comment]
没有照片，就俩人参加。 录像已提交给 @cnfeat , 没必要公开了吧，剪辑后自用吧。@ishanshan

**Comment by sunnyhuang42** [comment]
好收到， close ~
