### ISSUE TITLE
[9wd6]深圳C2T2报名

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/OMOOC2py#118]
9w 咯,演示迭代周正式开始,大家的作品可以考虑用合适的形式呈现啦.

所以,本次活动主题：

**如何演示你的作品?**

参考资料：[[11w~人生首秀] 项目演示迭代 · Issue #115 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/115)
- C2T2 活动规则
  - 以`学员互助`为主，学员互助自由交流时间须大于教练一对多单向输出的时间
  - 参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
    - 并附带 42 字内文字说说自己今天最大的收获 
- C2T2 地点及时间
  - 地点: [深圳华侨城如盒艺术空间](http://www.dianping.com/shop/19482910)（华侨城恩平街创意园东部工业区E6栋103(康佳集团))
    - **如有其他建议直接回复**
  - 时间: 周六  14:30~17:30  
    - **请大家同时回复建议时间** 
- 报名: 回复说明以下关键信息
  - github 帐号
  - 电脑操作系统
  - 你想做的项目，当前对项目的构想/疑问/支持
  - 项目描述参考:[[8w~迭代作品] 项目公示 ](https://github.com/OpenMindClub/OMOOC2py/issues/96) 描述格式
- 截止: 周六 11:29 前有效
- _提醒:_ 尽可能带上电脑,以便现场明确技术问题的细节 ;-)

![](http://7xjhtv.com1.z0.glb.clouddn.com/thumb.jpg)

@OpenMindClub/py2student 

参考:
- [OMOOC2py 历次 C2T2 回顾](https://github.com/OpenMindClub/OMOOC2py/issues?q=label%3A%E5%85%AC%E5%91%8A+is%3Aclosed)
- [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)
- 注意:弃用`面基`一词, 这是个极其恶意的 KUSO 名词!

**Comment by bambooom** [comment]
- github: @bambooom
- os: win7
- 项目: 🐙🐶 OctoDog
- 时间: 为了广州来的June妹子, 时间选周六吧~

**Comment by yondjune** [comment]
报名
建议周六 早点总结完周日可以赶项目进度

技术资源的探讨:

七牛数据库 照片的储存
彩云的天气数据接口
电商的数据接口

**Comment by demonmax** [comment]
github:demonmax
项目：书游
预计到达时间：14:00
