### ISSUE TITLE
[0wd4]issue NoteOpenClass A new approach alive!

### ISSUE THREAD

**Issue by WhaleChen** [OpenMindClub/OMOOC2py#12]

**Comment by WhaleChen** [comment]
# 我竟然发了issue!!

在听课~
大妈所说：去自我审查！
玩一下，大家别介意，参加玩一下！！

**Comment by WhaleChen** [comment]
形式决定内容~ 现场直播~

**Comment by WhaleChen** [comment]
QQ 娱乐化BBS是有毒的 #可以查一下 BBS的真正作用
微博 和 Twitter 是不同的~
立即写代码~

**Comment by WhaleChen** [comment]
固定时间，固定节奏。
如果不行，需要“止损”
输出是更加残酷的输入！

**Comment by WhaleChen** [comment]
## 输出是更加残酷的输入

-提取内容
-反编译
-作品  
- 要有种！
- 慎独 ！ **无监督的机械学习**  ~~混混混~~ **搏斗**

**Comment by WhaleChen** [comment]
## Desirable Difficulties

阻滞 
**持续不断的输出**
~~惰性~~
**相信**  

```
if alive:
     do according to the plan
```

4500 教程输出
200 代码
/ per week

**Comment by WhaleChen** [comment]
## 巧克力！

Keep calm and eat cholocate~
https://en.wikipedia.org/wiki/Chocolate

**Comment by WhaleChen** [comment]
## Google: 问对问题！

会用吗？
Google 帮助:
https://support.google.com/websearch/answer/134479?hl=en
Search operator:
https://support.google.com/websearch/answer/2466433?vid=1-635805120007651578-1473977798

**Comment by WhaleChen** [comment]
## Qisqus

**Python 开发的！！**

https://disqus.com/

曾经难住了大妈

> 发红包到邮箱的比喻

大妈的解决：
http://openmindclub.qiniudn.com/res/tr/tr_02_gitbook.html

**Comment by WhaleChen** [comment]
## 总结

**编程思维**的培养必须**要编程**
**靠谱行为**的基础只能是**靠谱**
**提问**是获得技能的**唯一起点**
教练价值**源自**你真诚的行动
**合意阻滞**是学习的**最佳动力**

Enjoy ！

> 中微子的发现 并行计算 ?!@#

**Comment by WhaleChen** [comment]
## 提问的智慧

wiki:
https://zh.wikipedia.org/wiki/%E6%8F%90%E9%97%AE%E7%9A%84%E6%99%BA%E6%85%A7
中文原文：
http://doc.zengrong.net/smart-questions/cn.html

大妈总结：
http://wiki.woodpecker.org.cn/moin/AskForHelp

Also could see here:
https://github.com/WhaleChen/How-To-Ask-Questions-The-Smart-Way

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)

weibo 式 吐糟点 时间线型现场记录!

俺以前经常玩的 ;-)

**Comment by ZoomQuiet** [comment]
创意笔记 happy closed
