### ISSUE TITLE
OMOOC2PY-replay 计划 召集伙伴

### ISSUE THREAD

**Issue by sunoonlee** [OpenMindClub/OMOOC2py#123]
### OMOOC2PY-replay 计划 召集伙伴

replay 计划要点：
- **每周发布目标+分享进展和成果** --> `issues`
- **持续输出成果**，让自己的代码和教程的数量/质量有明显提升 -> your `github repo` & `gitbook`
- 交流、提问、资源分享 --> `slack`
- 每周节奏建议：
  - 周四~五：发布目标
  - 周六~日：集中突破
  - 周一~三：继续探索、整理教程

建议的整体安排（初步设想，仅供参考）：
- w0-1 (0104-0117)：`Basics replay`
  - 工具与方法提升，比如：git使用、shell配置、搜索技巧、代码规范、搭建技术博客等等
  - python 基础提升：可学习 [google's python class](https://developers.google.com/edu/python/?hl=zh-CN) 
- w2-3 (0118-0131)：`Web replay`
  - 重构已有的 web 版作业（如果没有，从零开始也无不可）
  - flask 进阶使用
  - 优化数据库的代码，尝试不同的数据库技术
  - 把 flask app [部署到云主机上](https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uwsgi-and-nginx-on-ubuntu-14-04)
  - 以及：其他的各种可能
- w4 (0131-0206)：`WeChat/Qpython replay`
  - 优先完成微信，有余力时继续 Qpython
- (maybe) w5-6：`project replay`
  - 做一个自己感兴趣的小APP
  - 或者打磨、重构已有的应用

有意的同学请报上你的邮箱，并**说明你对自己学习计划的设想**。我来邀请各位加入 SLACK 团队。

@OpenMindClub/py2student

**Comment by bambooom** [comment]
nmz89825@gmail.com

作业之前是都做完了的, 单纯对web开发感兴趣~想继续玩这方面

**Comment by jameszhou89** [comment]
zhouhuiming1989@gmail.com
之前落下蛮多课的，希望可以补起来一些

**Comment by penguinjing** [comment]
这个肯定来要玩呀。
penguinjing AT gmail.com

**Comment by WhaleChen** [comment]
18621050278@163.com WhaleChen

**Comment by sunoonlee** [comment]
以上四位同学：已发送邀请，请查收邮件

**Comment by ivanlau** [comment]
email@ivanlau.com 想回顾的主要是以py基础以及web开发为主

**Comment by liangchaob** [comment]
liangchaob@163.com
同样是web，还一个是爬虫

**Comment by ddtnt** [comment]
lichunliang99@gmail.com
只看了第一周的，希望能跟上末班车

2016-01-03 18:27 GMT+08:00 liangchao notifications@github.com:

**Comment by xpgeng** [comment]
xpgeng.me@gmail.com

虽然能够完成作业, 但是还有很多围绕着作业值得探索的内容还没做.

**Comment by huijuannan** [comment]
huijuannan@gmail.com
还有两周的作业没做

**Comment by Cen74** [comment]
52993580@qq.com 还想继续探索

**Comment by sunoonlee** [comment]
@liangchaob @ddtnt @xpgeng @huijuannan @Cen74 
已发送 slack 邀请，请查收邮件

**Comment by yondjune** [comment]
带上我！！！

80568771@qq.com

**Comment by tiezipy** [comment]
Sleepingbag.li@gmail.com
加我一个

**Comment by sicunchen** [comment]
chensicun94@gmail.com
很好的提议，想加入

2016-01-03 20:57 GMT+08:00 tiezipy notifications@github.com:

**Comment by yangshaoshun** [comment]
yangshaoshun@gmail.com
后期作业未完，缺少教程，想加入，谢谢

**Comment by whb1990111** [comment]
whb1990111@icloud.com
想加入啊

**Comment by lethinkrong** [comment]
还想继续全情投入，加我一个：D
lethinkrong@gmail.com

**Comment by aJiea** [comment]
perso.anastasia.chen@gmail.com

aJiea always pay her debts.

**Comment by shawn0lee0** [comment]
必须支持！
robo_one@foxmail.com

**Comment by soul2867** [comment]
soul2867@gmail.com

提议太赞，需要集中学习。感谢@sunoonlee

2016-01-03 23:13 GMT+08:00 robo_one notifications@github.com:

**Comment by sunoonlee** [comment]
@yondjune @tiezipy @buermen @yangshaoshun @whb1990111 @lethinkrong @aJiea @shawn0lee0 @soul2867 @scottming 
邀请邮件已发送，若未收到请给我发邮件反馈

没想到会有这么多人响应。这样的话，同城的同学可以继续 C2T2 啦！

**Comment by ZoomQuiet** [comment]
注意约定,定期的输出成果,否则,很容易骗到自己努力了又...

**Comment by scottming** [comment]
xiaowan5219@gmail.com

**Comment by sunoonlee** [comment]
谨记大妈叮嘱，希望 replay 之后每个人代码和教程的数量/质量能有看得见的提升

> 注意约定,定期的输出成果,否则,很容易骗到自己努力了又...

**Comment by cxiaodian** [comment]
支持，之前的项目只做到够自己用，想继续突破web开发方面的。
caixd55@gmail.com

**Comment by sunoonlee** [comment]
关闭归档
有意加入 slack 团队参与交流的同学 仍可发邮件给我
