### ISSUE TITLE
[replay] 每周目标设定与成果发布

### ISSUE THREAD

**Issue by sunoonlee** [OpenMindClub/OMOOC2py#124]
#### replay 规则

本 issue 作为每周目标发布、成果提交的平台（slack 供日常交流用）。

1、Plan
- （在提交上周总结的同时，）确定新一周的目标
- 目标最好是具体、可实现的

2、Do
- 分解目标，各个击破
- 可以在 slack 相应频道上交流、讨论
- 过程中可以对目标进行修正

3、Submit
- 总结当周战况，提交成果（代码/教程/感想）
- 若是补做之前的作业，可直接回复到已有的相应 issue：
  - web https://github.com/OpenMindClub/OMOOC2py/issues/70 || sae  https://github.com/OpenMindClub/OMOOC2py/issues/74 ||  wechat  https://github.com/OpenMindClub/OMOOC2py/issues/82 ||  mobile https://github.com/OpenMindClub/OMOOC2py/issues/91
- （然后，发布新一周的目标，继续 PDS 循环）

---
##### 附：replay 计划说明
- 时间：160104-0207 共五周，有兴趣可再延长两周
- **每周发布目标+分享进展和成果** --> `issues`
- **持续输出成果**，让自己的代码和教程的数量/质量有可见的提升 -> `your github repo & gitbook`
- 讨论、资源分享 --> `slack`
- 每周节奏建议：
  - 周六~日：整理当周笔记，确定新一周的目标 （0112 修改）
##### `replayers`名录

@bambooom @jameszhou89 @penguinjing @WhaleChen @ivanlau @liangchaob @ddtnt @xpgeng @huijuannan @Cen74 @yondjune @tiezipy @buermen @yangshaoshun @whb1990111 @lethinkrong @aJiea @shawn0lee0 @soul2867 @scottming @cxiaodian

**Comment by sunoonlee** [comment]
replay计划大致如此。接下来，默默地督促自己继续学习~

##### `replay-4w小结`

0202-0207(Tue-Sun) ：只投入1番。荒废了好多时间。

##### `replay-3w小结`

0126-0201(Tue-Mon)：共9番
- 6001x：8番。完成了pset2，读教材 ch1、ch4.3
- cs50x：1番

状态不佳，需要勇猛精进呀！

##### `replay-2w小结`

0118-0125(Mon-Mon) 共22番，其中
- 6.00.1x：lec3, lec4, pset1 - 15番
- cs50x：week0 两个 lecture, pset0 预备 - 5番
- python 相关其他：2番

##### `replay-1w小结`

0113-0117(Wed-Sun) 共14番
- 6.00.1x：完成第一周课程，11番
- cs50x：课程内容探索，1番
- corePython：ch1-2，2番

##### `replay-0w小结`

共约14番 (番=番茄=25min)
- 完成了 udacity 公开课 [Linux Command Line Basics](https://www.udacity.com/course/linux-command-line-basics--ud595)  --> [linux 笔记](https://sunoonlee.gitbooks.io/omooc2py/content/0MOOC/linux.html)
- 学习谷歌搜索技巧  --> [google 笔记](https://sunoonlee.gitbooks.io/omooc2py/content/0MOOC/google.html)

**Comment by yondjune** [comment]
replay-0w-目标 

以项目实现为导向的replay计划：
- 整合及阅读下已有的学习资源
  
  [ ]python开发实战项目 看到 管理数据 篇

1w目标
- 阅读蟒周刊 2015项目

延期任务
- 有一个域名…那搭个博客…咯？
- 尝试部署 iMatch 到云主机 
  [x]阅读sae教程
- 研究下七牛(有余力的话）

**Comment by huijuannan** [comment]
## replay-0w-目标
- 为了更好地学习微信API、微信机器人、爬虫等技术，参照小小书童做一个小东西——豆瓣电影小助手，即电影版的小小书童。[仓库](https://github.com/huijuannan/moviemate)
- 这周的任务有：
  - [ ] 实现豆瓣授权登录
  - [ ] 微信接口

**Comment by bambooom** [comment]
## replay-0w-over
- linux 基本操作
  - [x] 阿里云主机 -> 一点笔记: [linux系统初接触](http://bambooom.github.io/2016/01/04/first-touch-of-ubuntu/)
  -  ~~在主机上配置 python 开发环境~~
- 数据库
  -  ~~MySQLdb module学习 by [this](http://zetcode.com/db/mysqlpython/)~~ 
  - [x] [basic MySQL in Ubuntu](https://www.digitalocean.com/community/tutorials/a-basic-mysql-tutorial) -> 一点翻译: [mysql初接触](http://bambooom.github.io/2016/01/05/first-touch-of-mysql/)
  - [x] Lesson1/2 [这门课](https://www.udacity.com/course/intro-to-relational-databases--ud197)
  - [x] week1 coursera这门课[Using Databases with Python](https://www.coursera.org/learn/python-databases) -> [一点笔记](http://bambooom.github.io/2016/01/07/a-little-class/)
- ipython
  - [x] ipython notebook 安装成功

**Comment by cxiaodian** [comment]
这次主要学web端的知识

## replay-0w-目标
- 申请一个阿里云主机，部署开发环境，折腾玩玩
- web 框架 flask 
  - 读[Flask Web Development](http://www.amazon.com/Flask-Web-Development-Developing-Applications/dp/1449372627/ref=sr_1_1?ie=UTF8&qid=1451963493&sr=8-1&keywords=flask+web)
  - 把flask 用户登录模块做好。

## 0w 任务情况
- 配置pyenv ，跟并使用起来

阅读:
- basic application structure 
- Templates.
- Web Forms 
  - [WTForms](http://wtforms.readthedocs.org/en/latest/)  是个很好用的插件 

## replay-1w-目标
- 0w 主要是读flask web dev 前几节，这周继续。
- 跟sunoonlee 同学一起报名 看[MIT 导论](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-6)
  - 完成 week1
- 把之前读的 [A Byte of Python](http://www.swaroopch.com/notes/python/#sequence)剩下的几小节读完。

## replay-1w-任务完成情况
- 读完Flask Web Development 前七章
- 看[MIT 导论](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-6) week1 
- 读完了  [A Byte of Python](http://www.swaroopch.com/notes/python/#sequence)
- 学了点SQL语句

## 2w- 任务
- 继续Flask Web Development ，后面几节实践部分
- 继续MIT 
- 读 [SQL in 10 Minutes, Sams Teach Yourself](http://www.amazon.com/Minutes-Sams-Teach-Yourself-Edition/dp/0672336073)

## 2w- 任务完成情况
- Flask Web Development 读到 第10章，创建博客文章
- MIT week2 还未完成
- SQL in 10 Minutes, Sams Teach Yourself ，这本书把SQL语句分解成很短的一小结，最后搭配一个时间练习，我在mysql里实际操作，容易懂，读到第10章

这周主要是读 sql 跟flask 这两本书

## 3w- 任务
- 读完Flask Web Development 剩余的节章，并把blog 整合进[nginx](https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uwsgi-and-nginx-on-ubuntu-14-04) 
- 读完SQL in 10 Minutes, Sams Teach Yourself  并把 Flask Web Development  书里面的sqlite3 数据库，换成Mysql 
- 如果有时间，把flask web dev 里面的社交blog 搭建上阿里云。
- 继续 MIT week2

**Comment by shawn0lee0** [comment]
## Replay-0w-目标

### 基础
- [ ]  [正则表达式练习](http://wiki.ubuntu.org.cn/Python%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F%E6%93%8D%E4%BD%9C%E6%8C%87%E5%8D%97)
- [x]  [博客搭建](http://shawn0lee0.github.io/)
  - [github搭建blog](http://shawn0lee0.github.io/github-pages/)
  - 本地搭建 `jekyll serve`
  - [ ] 增加Disqus
- [x] [笔记整理](https://shawn0lee0.gitbooks.io/python-omooc2py/content/)

### 进阶
- [ ] [CS109 Data science L1~L5](http://cs109.github.io/2014/pages/schedule.html)

**Comment by penguinjing** [comment]
## replay-0w-目标

时间：060104 - 060110
- [x] 完成Web周编程任务
- [ ] 启动ipython notebook，掌握基础操作
- [x] 明白使用Pyenv / pyenv-virtualenv的用法

## replay-1w-目标

时间: 060111-060117
- [ ] 完成PaaS周编程任务
- [ ] 阅读 _Flask Web Development_ , 入门Flash框架
- [x] 完成 _[Python Data Structures](https://www.coursera.org/learn/python-data)_ 课程视频和作业, 回顾Python 数据结构知识
- [ ] 完成 _[Using Databases with Python](https://www.coursera.org/learn/python-databases/)_ 课程视频和作业, 简单入门数据库知识

**Comment by WhaleChen** [comment]
## replay-0w- 目标

to 20160107
![0w](https://cloud.githubusercontent.com/assets/11818114/12114797/e84fd8f8-b3e7-11e5-98cb-a6714ee030cd.png)

0106
![0w _0106](https://cloud.githubusercontent.com/assets/11818114/12145714/d19499f8-b4ca-11e5-946d-8c5bf948ea14.png)

**Comment by xpgeng** [comment]
## replay-0w- 目标
- [x] 学习正则表达式
  - https://developers.google.com/edu/python/regular-expressions
  - http://deerchao.net/tutorials/regex/regex.htm
  - [Python正则表达式操作指南](http://wiki.ubuntu.org.cn/Python%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F%E6%93%8D%E4%BD%9C%E6%8C%87%E5%8D%97)
- 小结:
  - 啃完了正则表达式, 但还缺乏必要的联系. 
  - 顺便刷了4周的 Using Databases with Python.
  - 同样也是需要进一步做更多的练习.

**Comment by Cen74** [comment]
# replay-0w- 目标
- [ ]  建立自己的学习节奏，每天至少2个番茄时间
- [ ]  代码/写作切换到vim 编辑器
- [ ]  完成微信端作业

**Comment by liangchaob** [comment]
# replay-0w-目标

搞清楚js和jquery库，尤其是ajax，使用其改造原项目表单的js

**Comment by ZoomQuiet** [comment]
On Sun, Jan 10, 2016 at 5:05 PM, liangchao notifications@github.com wrote:

> replay-0w-目标
> 
> 搞清楚js和jquery库，尤其是ajax，使用其改造原项目表单的js
- js 是开发语言
- jQuery 是 js 功能库
- Ajax 是技术方案

嗯哼,都是不同领域对象,别折腾混了

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by sunoonlee** [comment]
#### replay-0w小结

这周在replay目标上投入了7小时左右。主要收获是学习了 linux 的一些入门级知识。

写了两篇简单的笔记：
* [linux 初体验](https://sunoonlee.gitbooks.io/omooc2py/content/0MOOC/linux.html)
* [更好地使用 google 搜索](https://sunoonlee.gitbooks.io/omooc2py/content/0MOOC/google.html)

replay 计划实行一周了。略显尴尬的是大家目标多不相同，基本上以各自求索为主，互相的交流并不多。后面希望和大家一起探索更好的互相促进的方法。

每周的节奏提议改为，以周一作为起点，然后在周末回顾一周的学习情况，整理笔记，并发布下一周的目标。

加油，继续探索编程的奇妙世界！

-----
#### replay-1w目标

这周想开始学习一些计算机科学与编程基础知识。主要是这两门导论课：
* [MIT 导论](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-6)（刚好1月13日开课）
    * 关注课程动态
* [CS50x](https://courses.edx.org/courses/HarvardX/CS50x3/2015/)
    * [ ] 看完 week0 视频

**Comment by cxiaodian** [comment]
## replay-1w-目标

- 0w 主要是读flask web dev 前几节，这周继续。
- 跟sunoonlee 同学一起报名 看[MIT 导论](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-6)
    - 完成 week1
- 把之前读的 [A Byte of Python](http://www.swaroopch.com/notes/python/#sequence)剩下的几小节读完。

**Comment by junjielizero** [comment]
各位好，按照@ZoomQuiet 大妈意思，将本次大妈编程习惯与技巧公开给大家，很多内容公开课并没有提及，期望能帮助各位课后的自学效果。[详见这里](https://github.com/junjielizero/OMOOC2py/tree/master/Expertise)，如有疑问，欢迎在 Q&A issue 提问。

**Comment by ZoomQuiet** [comment]
2016-01-19 12:04 GMT+08:00 junjie_li notifications@github.com:

> 各位好，按照@ZoomQuiet 大妈意思，将本次大妈编程习惯与技巧公开给大家，很多内容公开课并没有提及，期望能帮助各位课后的自学效果。详见，如有疑问，欢迎在 Q&A issue 提问。

嗯哼,有些技巧,俺自个儿看了都不明觉厉,
但是,作者在!
使劲问!

**Comment by sunoonlee** [comment]
一次失败的尝试。反思一下：1、没有共同的目标，不好玩；2、没有很好的激励机制。学习之路漫长，让我们继续努力 : )

**Comment by yondjune** [comment]
haha 不是这样的
http://git.oschina.net/
我正踏上新的实战旅程~

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)
终于有人意识到了
git 项目托管不仅仅一个 github 其它同类的有很多
嘦能方便的完成任务,尽可折腾!

On Tue, Mar 29, 2016 at 3:03 AM, yondjune notifications@github.com wrote:

> haha 不是这样的
> http://git.oschina.net/
> 我正踏上新的实战旅程~
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/OpenMindClub/OMOOC2py/issues/124#issuecomment-202769349

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
