### ISSUE TITLE
作业：《红玫瑰与白玫瑰》读后感触

### ISSUE THREAD

**Issue by luopengpeng** [OpenMindClub/OMOOC2py#127]
一个年青的男人，在正当年龄的时候，情欲无从觉知。从妓女的身上，他人妻子的身上，得来的一点有限的经验，用来过自己的生活的时候，却选择了一种偏平的规则的女性，从一极偏到另外一极。唉，这男子，简直是倒霉透了，无论用了多大的力气与热情，终究只是在情爱的世界之外转圈，哪怕使尽性子，却还是要复归于常。而女人，在这样的男性的眼中，看过去的女人，有生命的活力，她还是流浪者。而有归宿的女人，却只空有归宿之壳。深的落寞横在两性中间。哪里有红玫瑰与白玫瑰，得到与得不到之苦，这分明是无奈现实中的自我安慰。

附：
在表象世界里迷失的男女爱情————《红玫瑰与白玫瑰》

佟振保活在世人的眼睛里，所以他的生命里有两个女人，一个是圣洁的妻，一个是热烈的情妇。圣洁的妻是给外人看的，是装点的门面，热烈的情妇，才是自己的热情所在，可它终究还是别人的，却又因为是别人的，充满了无限的偷欢的刺激。就象淘气的孩子，使性子地索取，不必负担世人所要求负的责任。
在这样心口不一的男人的心里，红玫瑰与白玫瑰，永远是没有得到的那一朵，最值得想念。因为不必被琐碎的责任，把追逐的热情耗散光了。最后剩下无数的疲备，与自我的放逐。不得不重新穿上好男人的衣裳，在这世间继续孤寂的世间继续活下去。

一个一无所知的童男成长到男人，
男人对自我的认识，终究却还是在与女人的情爱当中发生的。“这样的一个女人。就连这样的一个女人，他在她身上花了钱，也还做不了她的主人。和她在一起的三十分钟是最羞耻的经验。”。
才有后来的“从那天佟振保就下了决心要创造一个“对”的世界，随身带着。在那袖珍世界里，他是绝对的主人。“

可是女人并不是物，对方的情感也非由他的主观意志所定。
哪怕他自以为他爱了玫瑰了。”车窗外，还是那不着边际的轻风湿雾，虚飘飘叫人浑身气力没处用，只有用在拥抱上。玫瑰紧紧吊在他颈项上，老是觉得不对劲，换了一个姿势，又换一个姿势，不知道怎样贴得更紧一点才好，恨不得生在他身上，嵌在他身上。振保心里也乱了主意。他做梦也没想到玫瑰爱他到这程度。他要怎样就怎样，可是……这是绝对不行的。"
深的落寞在两人中间。哪怕肉体的拥抱，也不能抚平。但是这次，“玫瑰到底是个正经人。这种事不是他做的。”“玫瑰的身上从衣服里蹦出来，蹦到他身上，但是他是他自己的主人。”他做了他自己的主人。

振保从一种肉欲的迷茫世界里，开始踏入情感世界之门。却又在对别人妻子的窥探中迷失了。

“振保当着她，总好像吃醉了酒怕要失仪似的，搭讪着便踱到阳台上来。冷风一吹，越发疑心刚才是不是有点红头涨脸了。他心里着实烦恼，才同玫瑰永诀了，她又借尸还魂，而且做了人家的妻。而且这女人比玫瑰更有程度了，她在那间房里，就仿佛满房都是朱粉壁画，左一个右一个画着半裸的她。”

情感的寂寞，自然是经不住善弄风情的女人的撩拨。两人可以相互支使了，而且不必负责任。燃烧起来的热情，终究因为先天不足，内心里有着莫种下坠的失落。

"他自己认为是堕落了。从高处跌落的物件，比他本身要重许多倍，那惊人的重量跟娇蕊撞上了，把她砸得昏了头。"
"再拥抱的时候，娇蕊极力紧匝着他，自己又觉羞惭，说：“没有爱的时候，不也是这样的么？若是没有爱，也能够这样，你一定看不起我。”她把两只手臂勒得更紧些，问道：“你觉得有点两样么？有一点两样么？”振保道：“当然两样。”可是他实在分不出。从前的娇蕊是太好的爱匠。"

再有情爱，终究还是陌生。“至于振保，他所有的一点安全，他的前途，都是他自己一手造成的，叫他怎么舍得轻易由它风流云散呢？阔少爷小姐的安全，因为是承袭来的可以不拿它当回事，她这是好不容易的呀！……”
还是因为不必负责任。而且也负不起这样女子的责任。

病了，这时候，才想起家人的重要来了。情爱在病中，才品出不一样的味道来。人在病中的时候，需要照顾，需要安全，已是付不出额外的情感了，那额外的情感，自然也是不想沾惹了，那怕对方再真心，听到耳中的话，已是说什么，什么不对味了。他想要有自己的生活了。

“等天黑了，她趁着房间里还没点上灯，近前伏在他身上大哭起来。即使在屈辱之中她也有力量。隔着绒毯和被单他感到她的手臂的坚实。可是他不要力量，力量他自己有。”

可真要结婚的时候，他那点可怜的经验并不够用，他从一极偏向另一极，把自己装进了套子里。“然而真到了结婚那天，她还是高兴的，那天早上她还没十分醒过来，迷迷糊糊的已经仿佛在那里梳头，抬起胳膊，对着镜子，有一种奇异的努力的感觉，像是装在玻璃试验管里，试着往上顶，顶掉管子上的盖，等不及地一下子要从现在跳到未来。现在是好的，将来还要好——她把双臂伸到未来的窗子外，那边的浩浩的风，通过她的头发。”

很快就厌倦了。“烟鹂因为不喜欢运动，连“最好的户内运动”也不喜欢。振保是忠实地尽了丈夫的责任使她喜欢的，但是他对她的身体并不怎样感到兴趣。起初间或也觉得可爱，她的不发达的乳，握在手里像睡熟的鸟，像有它自己的微微跳动的心脏，尖的喙，啄着他的手，硬的，却又是酥软的，酥软的是他自己的手心。后来她连这一点少女美也失去了。对于一切渐渐习惯了之后，她变成一个很乏味的妇人。”

“他把一条腿搁在膝盖上，用手巾揩干每一个脚趾，忽然疼惜自己起来。他看着自己的皮肉，不像是自己在看，而像是自己之外的一个爱人，深深悲伤着，觉得他白糟蹋了自己。”
这一瞬间的自我怜惜之后，一种麻木，连落寞也没有了。

“三轮车在波浪中行驶，水溅潮了身边那女人的皮鞋皮夹子与衣服，她闹着要他赔。振保笑了，一只手搂着她，还是去泼水。”

“笃保走了之后，振保听见烟鹂进房来，才踏进房门，他便把小柜上的台灯热水瓶一扫扫下地去，豁朗朗跌得粉碎。他弯腰拣起台灯的铁座子，连着电线向她掷过去，她急忙返身向外逃。振保觉得她完全被打败了，得意之极，立在那里无声地笑着，静静的笑从他的眼里流出来，像眼泪似的流了一脸。”

隔着老远的人，连战争也是这样的快无声无息了。

落寞，连战争，也是乏味的。

**Comment by sunnyhuang42** [comment]
@luopengpeng  麻烦将笔记发布到自己的课程仓库里，而不是别的仓库哦。
