### ISSUE TITLE
[0wd6]C2T2 北京报名

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/OMOOC2py#16]
- 时间: 周六 14:30~17:30
- 地点: 北京 中关村东路18号 财智国际大厦 B 座 601
- 报名: 回复说明以下关键信息
  - github 帐号
  - 电脑操作系统
  - 当前课程 top3 问题, 参考: [[0w]当周课程 技术问题讨论](https://github.com/OpenMindClub/OMOOC2py/issues/3) 描述格式
- 截止: 周六 14:29 前有效
- _提醒:_ 尽可能带上电脑,以便现场明确技术问题的细节 ;-)

@OpenMindClub/py2student 

参考: [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)

**Comment by hongzhih** [comment]
报名：hongzhih，win7，问题：gitbook中如何安装插件Disqus。

**Comment by s32n** [comment]
报名：s32n  系统：Mac OS X   问题：和大家交流学习进度

2015-10-16 22:01 GMT+08:00 hongzhih notifications@github.com:

**Comment by JQ-K** [comment]
> 报名：JQ-K 
> 系统： linux 
> 问题 : github 相关；python语法基础；python中模块的理解

**Comment by summer724** [comment]
帐号:summer724
操作系统:mac
问题:如何理解github生态系统；gitbook中如何安装插件Disqus；python的简单应用

**Comment by liangpeili** [comment]
github 帐号：liangpeili
电脑操作系统:windows 10
当前课程 top3 问题:
1.gitbook的用法；
2.github生态；

**Comment by dyelaine** [comment]
报名：dyelaine win7 问题：Github生态环境的使用；学习进度交流

**Comment by ghost** [comment]
报名账号：xiaoyuer
电脑操作系统：win7
当前课程问题：gitbook中安装disqus；github和gitbook的双推；python常用环境的使用

**Comment by yangshaoshun** [comment]
- github 帐号：yangshaoshun
- 电脑操作系统：Mac OS X
- 当前课程问题
  - github和gitbook的双推、三推、多推...
  - github生态

**Comment by caosbad** [comment]
问题收到

**Comment by tttv** [comment]
报名：tttv，Mac，问题：gitbook中如何安装插件Disqus；

**Comment by supperqiuqiu** [comment]
github 帐号: supperqiuqiu, 北-win-木球
电脑操作系统：win7
当前课程 top3 问题：
1，基本环境配置
2，了解GitHub
3，Gitbook的关联和用法（Disques的关联和用法）
备注：超级小白落后生T_T

**Comment by liangchaob** [comment]
报名：liangchaob  系统：Mac OS X   问题：交流进度，使用github实现互推

**Comment by Eloisechou1** [comment]
报名：eloisechou  系统：Mac OS X   问题：git系统的理解

**Comment by luoquan19** [comment]
报名：luoquan19
系统：Windows 10
问题：git 系统的理解

**Comment by andreachin** [comment]
报名：andreachin 
系统：Mac OS X 
问题：git系统的理解

**Comment by dyelaine** [comment]
https://dyelaine.gitbooks.io/pythonme/content/0MOOC/discussion1.html

**Comment by dyelaine** [comment]
https://dyelaine.gitbooks.io/pythonme/content/0MOOC/discussion1.html

**Comment by liangpeili** [comment]
第一次线下活动纪要 https://github.com/liangpeili/OMOOC2py/blob/master/week0/c2t201n.md
更新下链接，gitbook出了点问题

`闪闪`：
二推三推四推是啥？可以说说你现在的理解吗？
github 生态圈，你觉得有哪些东西，关系是什么，可以写出来和大家分享一下不;-)

**Comment by ghost** [comment]
https://xiaoyuer.gitbooks.io/xiaoyuer-python-/content/0MOOC/0w/C2T2.html

**Comment by sunnyhuang42** [comment]
![2015-10-17 171111](https://cloud.githubusercontent.com/assets/8518968/10657192/37c09c92-78ba-11e5-9f6f-6b5915550c04.jpg)

现场内容回顾——

### Github 生态的理解  @ImCaos

讲演录音：
- 链接: http://pan.baidu.com/s/1o6ELn1C 密码: g56u

参考资料：
- 助你开始使用 git 的简易指南，木有高深内容
  http://www.bootcss.com/p/git-guide/
- [多用Git少交税](http://mp.weixin.qq.com/s?__biz=MzAxNDE2NzAxOQ==&amp;mid=207950642&amp;idx=1&amp;sn=277266b722ee43e1b4773776e4a8a425&amp;scene=1#rd)

### 0w 任务讲演+芝麻星系统的使用 @chientung91

讲演录音链接: http://pan.baidu.com/s/1eQhlGvo 密码: y55i

---

更多内容，欢迎参看 @xiaoyuer 的笔记 https://xiaoyuer.gitbooks.io/xiaoyuer-python-/content/0MOOC/0w/C2T2.html
