### ISSUE TITLE
[0w]GitHub和Gitbook的双推实现

### ISSUE THREAD

**Issue by wp-lai** [OpenMindClub/OMOOC2py#17]
受一休君启发，写了一段实现GitHub和Gitbook双推功能的代码，[地址点这](https://github.com/wp-lai/double_push)

希望大妈、各位助教和同学们帮我看看，提提意见和建议^_^

---

_Update Oct 17, 2015_

居然得到了阳老@ouyangzhiping的称赞，受宠若惊，也倍受鼓舞，我会继续努力的^_^

---

_Update Oct 17, 2015_
### CHANGELOG

Version 1.1  
_Sat Oct 17 13:19:27 2015_

> - 将主要内容写进一个函数里，这样用户可以把double_push当作一个模块，调用里面add_pushurl()函数
> - 将从命令行命令里获得用户输入改为通过交互问答获得用户输入

---

_Update Oct 17, 2015_
### 背景

我的设置是gitbook repo链接github的repo，然后在本地repo进行编辑，推到github上，gitbook内容也随之变化。这个方法用的很顺，也没有碰到gitbook抽风的情况，所以之前看到同学们在微信群里讨论联动和双推的问题，我也没有太过关注。

直到10月16号中午看到一休君的发言，以及沈浪同学@xpgeng与一休的对话，受到了很大的启发：
1. gitbook其实也是一个git
2. 在一个git remote里可以推送多个git地址
3. github repo可以允许他人进行推送

此外，一休君还布置了一个隐藏作业：

> 如何根据160位同学的github用户名，批量生成git config的git remote160推的内容

我把这个任务分解成两个子任务：
1. 写一个脚本1，实现github和gitbook的双推设置
2. 写一个脚本2，将脚本1自动分发部署到每位同学的github里

子任务2现在也还在摸索中，所以下面主要说子任务1。
### 原代码

先放[代码](https://gist.github.com/wp-lai/509834776fa5bab5189b)
![代码](http://i13.tietuku.com/1768a8de41b4b391.png)

下面是代码的解析
### git remote set_url --add --push

在了解到一个git remote里可以允许推送多个git地址之后，我就在网上[搜索](https://www.google.com/?gws_rd=ssl#q=git+one+remote+multiple+url)相关资料，在stackoverflow上搜到的[一个问答](http://stackoverflow.com/questions/14290113/git-pushing-code-to-two-remotes)特别有帮助，里面解释了

```
git remote set-url --add --push origin git://original/repo.git
git remote set-url --add --push origin git://another/repo.git
```

这两条命令会将`git://original/repo.git`和`git://another/repo.git`添加进`origin`这个远端里

使用命令之后，会在`.git/config`这个文件的[remote "origin"]下面看到多了这么两行：

```
pushurl = git://original/repo.git
pushurl = git://another/repo.git
```

这之后，只要用`git push origin master`就能同时推到这两个git repo里。

那个问答里还提到的一点就是`git remote set-url --add --push`添加的pushurl会override本来远端对应的url，所以需要将远端对应的url也用这个命令加入到pushurl里。

在上传完double_push.py第一版的代码之后，我又挖到了大妈@ZoomQuiet 之前解决双推问题的[一篇文章](https://github.com/ZoomQuiet/OMOOC2py/issues/1)，知道了
- 在config里直接添加`url = yyy/xxx.git`也行
- 在url里可以添加[用户名]和[口令]这些验证参数，

```
[remote "origin"]
    url = https://[用户名]:[口令]@git.gitbook.com/[帐号]/[图书名].git
    url = git@github.com:OpenMindClub/[图书名].git
    fetch = +refs/heads/*:refs/remotes/origin/*
```
### python中调用命令行命令

由于上面的git命令需要在命令行中输入，所以需要找到在python中调用命令行命令的参数。

我在之前实现一个[代码](https://wp-lai.gitbooks.io/learn-python/content/0MOOC/taobao.html)的过程中，接触到了`subprocess`库中的`call`函数，知道用这个可以调用命令行命令。

例如：

``` python
import subprocess
subprocess.call(["open","https://github.com"])
```

这段代码等同于在`shell`里输入`open https://github.com`，这个命令的作用是在浏览器里打开`GitHub`主页

但是subprocess.call函数接受的参数是一个链表，这个链表由命令行的命令和参数组成。这样未免有点麻烦，那有没有一个方式能让我将整句命令作为一个字符串传递进函数里呢？我又接着查看官方文档上对这个函数的[说明](https://docs.python.org/2/library/subprocess.html#using-the-subprocess-module)，发现将shell这个参数的值改为True就能传递整行命令，官方给出了一个使用的例子是：

```
>>> subprocess.call(["ls", "-l"])
0

>>> subprocess.call("exit 1", shell=True)
1
```

注意第一句里是将`ls -l`命令拆进了一个链表里，而第二句里`exit 1`命令是直接整个字符串传了进去

掌握了`添加多个pushurl`和`通过subprocess.call调用命令行命令`这两个知识点之后，我就能写出代码里`第11行`和`第16行`的两行核心代码。

ps: 代码其实可以改为

``` python
command = "git remote set-url --add --push origin "+github_repo_url
subprocess.call(command.split())
```
### 读取用户输入

因为我现在还没有能力做到自动获取用户名和repo名，所以得让用户自己提供这些信息。

在笨办法学python的[Exercise 13](http://learnpythonthehardway.org/book/ex13.html)里学到了sys.argv这个值会储存用户在命令行中输入的参数，
使用这个知识，我写出了第4、5、6这三行读取用户输入信息的代码。

ps：在v1.1版本里，我改为用raw_input(some_prompt)来获得用户信息，因为觉得这样更user friendly
### 格式化字符串

获得了用户名、repo名等信息之后，我需要用这些来替换原本GitHub和Gitbook链接里的用户名和repo名，一种方法是用字符串串联建立新的链接，但这种做法太不cool了。

在笨办法学python的[Exercise 6](http://learnpythonthehardway.org/book/ex6.html)中学到了使用%来替换文本中的内容，例如

``` python
x = "There are %d types of people." % 10
print x

# outcome:
# There are 10 types of people.
```

之后在[网上搜索](https://www.google.com/?gws_rd=ssl#q=python+format+string+%25)，发现string.format()这个函数也能达到同样的功能，而且更美观。更多的知识可以查官方文档，也可以看这个[学习教程](https://mkaz.github.io/2012/10/10/python-string-format/)。

学会了sting.format的用法，我就写出了第8行和第9行的代码。

通过上面4个知识点，也就完成了能实现双推设置的一个小代码，之后在写个README文档就push到[`GitHub`](https://github.com/wp-lai/double_push)。

综上看来，其实这个代码特别简单，没有用到什么高级的技巧，倒是我觉得我对变量的命名还是挺到位的。

接下来要做的是思考怎么将这个代码分发配置到多人repo里。感兴趣的同学可以跟我组队一起完成这个任务，fork，提交pull request，或者邮件联系我techwplai@gmail.com都行。

---

**Comment by ouyangzhiping** [comment]
@wp-lai  精彩至极！加油:D

**Comment by wzzlj** [comment]
@wp-lai 远远走在咱们学员的前列，佩服佩服！

**Comment by ZoomQuiet** [comment]
用自己的方法解决了当前的特殊问题,那么立即的就应该多问自己:
- 是否有更加优雅的解决方案?
- 是否有现成的解决方案?
- 是否能通用更多类似的多操作依赖事务...

~ [Fabric](http://www.fabfile.org/)

**Comment by wp-lai** [comment]
@ZoomQuiet 

这两天根据fabric的[tutorial](http://docs.fabfile.org/en/1.10/tutorial.html)学会了一些基础的用法，发现这真是很方便的一个库。

将fabric运用到日常生活中，我把git的使用流程改为

在每个git本地仓库里新建fabfile.py，内容为

``` python
def update():
    local("git add -p && git commit")
    local(git push)
```

在.gitignore里加入fabfile.py

之后每次推到git远端仓库时，使用shell命令`fab update`就行

这比之前连续使用三个git命令

```
git add
git commit
git push
```

用fabric方便了许多。

<br>
关于让我思考的几个问题，下面是我的一些想法。

> 是否能通用更多类似的多操作依赖事物

我理解的大妈问这个问题的本意是想说，当解决了一个特殊问题时，能不能把它背后的本质进行抽象化，形成对一般问题的概括和描述，然后改进程序，使得程序可以解决更广范围的一般问题。

GitHub和Gitbook的双推问题，表面上是.git/config文件的设置问题，但仔细想想，其实是如何完成将本地仓库同时推到GitHub仓库和Gitbook仓库的问题，也即是如何使用简单命令同时完成多操作多任务的一个问题。朝这个方向持续思考，我也许会从只为解决双推问题开发脚本，进化到为了解决多任务问题开发出类似fabric的第三方库，然后用类似`fab task1 task2 task3`这样的简单命令，就能同时完成task1、task2、task3等多个任务。

<br>

> 是否有现成的解决方案

比起使用double_push.py的脚本，更现成的方式其实是直接修改git的config文件。

以我用的Mac系统为例，在编辑器(如sublime text) 用`command+o`选择要打开文件，然后使用`command+shift+.`显示隐藏文件，打开.git/config，然后添加GitHub和Gitbook的双推地址

```
[remote "origin"]
    url = https://github.com/wp-lai/OMOOC2py.git
    url = https://git.gitbook.com/wp-lai/learn-python.git
    fetch = +refs/heads/*:refs/remotes/origin/*
```

或者也可以使用fabric

fabfile.py里写进

``` python
from fabric.api import *

def double_push(user_name, github_repo_name, gitbook_repo_name):
    code_dir = '/Users/alan/version-control/double_push/'
    command_github_pushurl = "git remote set-url --add --push origin https://github.com/{name}/{repo}.git".format(name=user_name, repo=github_repo_name)
    command_gitbook_pushurl = "git remote set-url --add --push origin https://git.gitbook.com/{name}/{repo}.git".format(name=user_name, repo=gitbook_repo_name)

    with lcd(code_dir):
        local(command_github_pushurl)
        local(command_gitbook_pushurl)
```

然后命令行里用`fab double_push:wp-lai,OMOOC2py,OMOOC2py`来设置双推

<br>

> 是否有更加优雅的解决方案

我这两天一直在思考**优雅**的含义，有了一些自己的理解。
- 从问题解决的角度来说
  - 优雅指的是用最少的资源来解决问题，也就意味着用最少的代码量，最少的第三方库依赖来解决问题。
- 从作为产品被使用或作为API被调用的角度来说
  - 优雅指的是代码的易用性，能被用户快速学习和方便使用。那么double_push.py或许可以添加一个gui模块，通过弹出交互框来获得用户输入，比起命令行的交互，这样也许对用户更友好。
  - 优雅指的是代码不被误用。那么double_push.py可以添加对用户输入进行检查的功能，当用户提供的用户名不在学员列表里，对应名称的仓库不存在时，给予用户相应的错误信息。

以上是学生我的一些思考，也不知道是否正确，希望得到大妈的指正。

**Comment by ZoomQuiet** [comment]
2015-10-19 10:18 GMT+08:00 Alan Lai notifications@github.com:

> @ZoomQuiet
> 
> 这两天根据fabric的tutorial学会了一些基础的用法，发现这真是很方便的一个库。
> 
> 将fabric运用到日常生活中，我把git的使用流程改为
> 
> 在每个git本地仓库里新建fabfile.py，内容为
> 
> def update():
>     local("git add -p && git commit")
>     local(git push)
> 
> 在.gitignore里加入fabfile.py
> 
> 之后每次推到git远端仓库时，使用shell命令fab update就行
> 
> 这比之前连续使用三个git命令
> 
> git add
> git commit
> git push
> 
> 用fabric方便了许多。
> 
> 关于让我思考的几个问题，下面是我的一些想法。
> 
> 是否能通用更多类似的多操作依赖事物
> 
> 我理解的大妈问这个问题的本意是想说，当解决了一个特殊问题时，能不能把它背后的本质进行抽象化，形成对一般问题的概括和描述，然后改进程序，使得程序可以解决更广范围的一般问题。
> 
> GitHub和Gitbook的双推问题，表面上是.git/config文件的设置问题，但仔细想想，其实是如何完成将本地仓库同时推到GitHub仓库和Gitbook仓库的问题，也即是如何使用简单命令同时完成多操作多任务的一个问题。朝这个方向持续思考，我也许会从只为解决双推问题开发脚本，进化到为了解决多任务问题开发出类似fabric的第三方库，然后用类似fab
> task1 task2 task3这样的简单命令，就能同时完成task1、task2、task3等多个任务。
> 
> 是否有现成的解决方案
> 
> 比起使用double_push.py的脚本，更现成的方式其实是直接修改git的config文件。
> 
> 以我用的Mac系统为例，在编辑器(如sublime text)
> 用command+o选择要打开文件，然后使用command+shift+.显示隐藏文件，打开.git/config，然后添加GitHub和Gitbook的双推地址
> 
> [remote "origin"]
>     url = https://github.com/wp-lai/OMOOC2py.git
>     url = https://git.gitbook.com/wp-lai/learn-python.git
>     fetch = +refs/heads/_:refs/remotes/origin/_
> 
> 或者也可以使用fabric
> 
> fabfile.py里写进
> 
> from fabric.api import *
> 
> def double_push(user_name, github_repo_name, gitbook_repo_name):
>     code_dir = '/Users/alan/version-control/double_push/'
>     command_github_pushurl = "git remote set-url --add --push origin
> https://github.com/{name}/{repo}.git".format(name=user_name,
> repo=github_repo_name)
>     command_gitbook_pushurl = "git remote set-url --add --push origin
> https://git.gitbook.com/{name}/{repo}.git".format(name=user_name,
> repo=gitbook_repo_name)
> 
> ```
> with lcd(code_dir):
>     local(command_github_pushurl)
>     local(command_gitbook_pushurl)
> ```
> 
> 然后命令行里用fab double_push:wp-lai,OMOOC2py,OMOOC2py来设置双推
> 
> 是否有更加优雅的解决方案
> 
> 我这两天一直在思考优雅的含义，有了一些自己的理解。
> 
> 从问题解决的角度来说
> 
> 优雅指的是用最少的资源来解决问题，也就意味着用最少的代码量，最少的第三方库依赖来解决问题。
> 
> 从作为产品被使用或作为API被调用的角度来说
> 
> 优雅指的是代码的易用性，能被用户快速学习和方便使用。那么double_push.py或许可以添加一个gui模块，通过弹出交互框来获得用户输入，比起命令行的交互，这样也许对用户更友好。
> 优雅指的是代码不被误用。那么double_push.py可以添加对用户输入进行检查的功能，当用户提供的用户名不在学员列表里，对应名称的仓库不存在时，给予用户相应的错误信息。
> 
> 以上是学生我的一些思考，也不知道是否正确，希望得到大妈的指正。
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by ZoomQuiet** [comment]
归档
