### ISSUE TITLE
[1w] 学员教程 报到处

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#19]
首周第一个 发布作业 交付处:
- 所有学员, 将个人仓库和 gitbook 完成联动
  - 编译发布成功 个人教程
  - 并配置好 DISQUS 插件令大家可评注
- 将 `个人教程` 发布地址提交在此 Issue
- 已经在: [[0w] 学员教程 报到处 · Issue #5 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/5) 完成报道的不用再次提交

`提示:` 
- gitbook 帐号,最好同自己的 github 帐号相同! 以便形成一致性体验
  比如大妈的:
  - https://github.com/ZoomQuiet/OMOOC2py
  - https://zoomquiet.gitbooks.io/omooc2py
  - 两个链接,有最多的重复信息
- [tr_02_gitbook.html](http://openmindclub.qiniudn.com/res/tr/tr_02_gitbook.html)

如果至今( `0wd5` ) 
- 依然无法搞掂 github->gitbook 的双推联动,以及 DISQUS 插件
- 请立即放弃这一不稳定的组合环境:
  - 回归 github 本身
  - 使用自己仓库的 Issue 发布体验
  - 例如: [[0wd5]dpush · Issue #1 · ZoomQuiet/OMOOC2py](https://github.com/ZoomQuiet/OMOOC2py/issues/1)
- 要求:
  - 所有教程,要使用 `教程` 标签
  - 标题前缀发布的课程日标:
    - `[0wd5]` ~ 表示 第0周第6天即, 2015-10-16 星期五
    - 参考: [缩写规约](http://www.iomooc.com/pages/cards.html?taskId=3cfcade0-733d-11e5-a837-0800200c9a66#tip7)

**Comment by crazy-tea** [comment]
@OpenMindClub/py2dama
https://crazy-tea.gitbooks.io/openmindclub-studynote-by-tea

**Comment by leonpak** [comment]
https://www.gitbook.com/book/leonpak/new-star/details

**Comment by JeremiahZhang** [comment]
@OpenMindClub/py2dama 

再次迁移教程到OMOOC2py：
https://jeremiahzhang.gitbooks.io/omooc2py

**Comment by Awlter** [comment]
[1wd3]教程   －－－－－是这样么？
https://awlter.gitbooks.io/omooc2py

**Comment by cnfeat** [comment]
以上学员教程地址已巡，教程地址变动已经补增到：[开智学院.编程思想 Python 入门班 学员索引 ](https://github.com/OpenMindClub/OMOOC2py/issues/11)

**Comment by StoryTelr** [comment]
@OpenMindClub/py2dama
https://storytelr.gitbooks.io/omooc2py/
