### ISSUE TITLE
教学反馈，请在这里跟帖

### ISSUE THREAD

**Issue by ouyangzhiping** [OpenMindClub/OMOOC2py#2]
关于教学的反馈，请在这里。

**Comment by tedxt** [comment]
看直播体验很卡. 
环境: 杭州, 移动宽带10M, 桌面浏览器各种线路切换和移动端在播放几分钟之后均会卡顿.

**Comment by StoryTelr** [comment]
第一节下来感觉互动时间很少，还是说把问题收集回去了统一回复？

**Comment by cnfeat** [comment]
刚刚已经将大家问题统一收集起来了，届时在 issue 回复~

**Comment by ZoomQuiet** [comment]
On Sat, Oct 10, 2015 at 9:07 PM, StoryTelr notifications@github.com wrote:

> 第一节下来感觉互动时间很少，还是说把问题收集回去了统一回复？
- 俺的原因, 第一次斗鱼主持
- 完全没有反馈好象面对空墙自说自话...
- 下次肯定吼足 90 分钟 ;-)

**Comment by ZoomQuiet** [comment]
- 151010 开学典礼
- 记要: [0wd0 开课手册](https://github.com/OpenMindClub/OMOOC2py/wiki/Ml0wd0)

## QA:
1. 大妈教入门班过程中的最大乐趣是什么？会不会觉得有时候沟通起来有点抓狂 因为大家都是零基础 太多要教的 
   - `是也乎:` 这才是俺福利哪
     - **输出是更残酷的输入**
   - 如果俺吼的事儿,大家都听不懂,一定是俺的姿势不对
   - 这种持续的思维模式 PK 过程中,俺就能发现自个儿的思维惯性,以及角度偏差
   - 一定得找到大家都能听懂的隐喻来! 原创的!
2. 学完之后能达到什么水平，能自己学完后写什么样的程序
   - `是也乎:` 这取决于你的努力程序
   - 课程内容的设定,涵盖的技术点已经在 开课手册中列出了
   - 是大妈心目中有基础独力工程能力的水平
3. 看完互联网之子与第四公民，感觉程序员还是蛮理想主义的存在，大妈自认是理想主义者吗？呵呵
   - `是也乎:` 之前就曰过, 编程其实是种手艺活儿
   - 编程技艺和木工/雕塑等等完全类似的艺术活动
   - 艺术总是倾向理想化的
   - 所以....
4. 阿西莫夫自动整理聊天记录的功能，可以通过py完成吗？
   - `是也乎:` asimov 本身一直就是 py 开发的哪
5. 如何更好地学习使用python进行数据分析？
   - `是也乎:` 嗯哼,从字面上的含义,俺只能这么回答:
     - 首先学会 数据分析
     - 然后使用 Python 进行数据分析
     - 最后,就知道如何在 Python 中更好的完成 数据分析 ;-)
6. OMOOC2py的wiki链接是什么？
   - `是也乎:` 嗯哼,这个问题太简单,以致俺怀疑有什么深意,容俺想想....

@OpenMindClub/py2student 今日 QA 汇总答复

**Comment by lixiguangzhou** [comment]
【课程反馈】
昨天错过了一个小时的课程，后来补看了大妈的视频。还是没有找到如何设置学员仓库的方法。是我错过哪个地方吗？暂时只见到大妈的视频以及教学团队的视频，加起来不够两个小时。

我尝试自己建立了仓库，但是不想其他学员的仓库里面有好多文件的。希望尽快跟上大家的步伐。github的使用还是很陌生，再给予多点支持。

大妈的讲课还是挺有激情的，能调动起情绪。强调在用的过程中学东西是最有效，马上投身到编程之中。这个过程必定是不断遇到挑战，克服自己畏难的情绪。教学团队设有“首席士气官”来帮助大家，实在太贴心了。我觉得心态调整有时候比技术支持更重要。

无论如何，感受到教学团队满满的诚意。靠你们明灯指路。KEEP GOING!

**Comment by ddtnt** [comment]
明显试验性课程设计，激励学员是好事，还是希望多些具体内容。

**Comment by ZoomQuiet** [comment]
2015-10-11 6:53 GMT+08:00 lixiguangzhou notifications@github.com:
...

> 昨天错过了一个小时的课程，后来补看了大妈的视频。还是没有找到如何设置学员仓库的方法。

@lixiguangzhou 欢迎反馈,但是:
- 私人体验, 最好集中在私人教程中持续输出
- 技术问题, 请到: [[0w]当周课程 技术问题讨论](https://github.com/OpenMindClub/OMOOC2py/issues/3)
  - 给出了详尽的思考模板
  - 另外, `设置学员仓库` 本身就是任务内容之一
  - 参考过往邮件中给出的提示:
    - [典章:提问的智慧 | PyChina.org Static Wiki](http://wiki.pychina.org/hd/ZenForAsk.html)
- `没有找到如何...` 这不是靠谱的提问思维
  - 如果想让大家给出有效的帮助
  - 你也应该给出足够的诚意, 描述:
    - 你的环境
    - 你的思路
    - 你的尝试
    - 过程中发生了什么?
    - 进行了什么思考? 如何验证的?
    - 当前最大的困惑?
    - 有哪些方案? 你的看法?
    - ....
  - 很多时候, 审视自个儿的思考过程中,答案就能自然浮现

# PS:

阳老的分享中, 反复驳斥了传统的有害的学习思路,
并给出了工程师样的学习途径,
请认真理解,果断尝试!

**Comment by suluren** [comment]
- 有个跟任务无关的问题，我真的好奇：gitbook用户名后面跟着个数字一，即suluren1；这是为什么，对后续有影响吗？  
- 我是通过github登陆gitbook，用户名不能改，tag是灰的，My Account也是灰色的，点不进去；但是三方联动是没问题的；
- 可能是github登陆gitbook默认这样，可是很奇怪，为什么不能同名；
- 搜索重名，改名，同名没有结果，官方文档说和github重名需要删除一个账户

**Comment by JQ-K** [comment]
目前win系统想换Linux ，折腾过程发现对Linux完全不熟悉，请问花费时间去钻研一个新系统是不是不划算，或者说对于Python的学习是舍本求末？）（

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=7.1.2]
On 周六, 10月 10, 2015 at 22:21, Zoom.Quiet notifications@github.com wrote:
- 151010 开学典礼
- 记要: 0wd0 开课手册 [https://github.com/OpenMindClub/OMOOC2py/wiki/Ml0wd0]

QA:
1. 大妈教入门班过程中的最大乐趣是什么？会不会觉得有时候沟通起来有点抓狂 因为大家都是零基础 太多要教的 \* 是也乎: 这才是俺福利哪 \* 输出是更残酷的输入
   - 如果俺吼的事儿,大家都听不懂,一定是俺的姿势不对
   - 这种持续的思维模式 PK 过程中,俺就能发现自个儿的思维惯性,以及角度偏差
   - 一定得找到大家都能听懂的隐喻来! 原创的!
2. 学完之后能达到什么水平，能自己学完后写什么样的程序 \* 是也乎: 这取决于你的努力程序
   - 课程内容的设定,涵盖的技术点已经在 开课手册中列出了
   - 是大妈心目中有基础独力工程能力的水平
3. 看完互联网之子与第四公民，感觉程序员还是蛮理想主义的存在，大妈自认是理想主义者吗？呵呵 \* 是也乎: 之前就曰过, 编程其实是种手艺活儿
   - 编程技艺和木工/雕塑等等完全类似的艺术活动
   - 艺术总是倾向理想化的
   - 所以....
4. 阿西莫夫自动整理聊天记录的功能，可以通过py完成吗？ \* 是也乎: asimov 本身一直就是 py 开发的哪
5. 如何更好地学习使用python进行数据分析？ \* 是也乎: 嗯哼,从字面上的含义,俺只能这么回答: \* 首先学会 数据分析
       \* 然后使用 Python 进行数据分析
       \* 最后,就知道如何在 Python 中更好的完成 数据分析 ;-)
6. OMOOC2py的wiki链接是什么？ \* 是也乎: 嗯哼,这个问题太简单,以致俺怀疑有什么深意,容俺想想....

@OpenMindClub/py2student [https://github.com/orgs/OpenMindClub/teams/py2student] 今日 QA 汇总答复

—
Reply to this email directly or view it on GitHub
[https://github.com/OpenMindClub/OMOOC2py/issues/2#issuecomment-147093059] .[https://github.com/notifications/beacon/AOL40ice7Q9LlJYhCs9_YW69KedxDadoks5o6RZugaJpZM4GIvcu.gif]

**Comment by ZoomQuiet** [comment]
2015-10-11 12:46 GMT+08:00 仞 notifications@github.com:

> 有个跟任务无关的问题，我真的好奇：gitbook用户名后面跟着个数字一，即suluren1；这是为什么，对后续有影响吗？
> 我是通过github登陆gitbook，用户名不能改，tag是灰的，My Account也是灰色的，点不进去；但是三方联动是没问题的；

技术问题请提交到:
[[0w]当周课程 技术问题讨论](https://github.com/OpenMindClub/OMOOC2py/issues/3)

使用正确的描述形式

> 可能是github登陆gitbook默认这样，可是很奇怪，为什么不能同名；
> 搜索重名，改名，同名没有结果，官方文档说和github重名需要删除一个账户

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by ZoomQuiet** [comment]
2015-10-11 12:47 GMT+08:00 kqj notifications@github.com:

> 目前win系统想换Linux ，折腾过程发现对Linux完全不熟悉，请问花费时间去钻研一个新系统是不是不划算，或者说对于Python的学习是舍本求末？）（

是也乎,(￣▽￣)
看你如何定义花费时间了:
- 如果你准备从今以后都用 Linux 作为日常环境了, 那么用 OMOOC2py 作为动力是没有问题的
- 如果只是为了 OMOOC2py 的任务完成, 可能就有点儿偏了...
- 当然, 作为过来人, 折腾 Linux 或是 MAC 对编程思想的形成是绝对有好处的
- 唯一限制就是时间投入了
- 建议进行风控, 如果你在4天中无法适应,立即切换回 win 别多想 Py 在哪儿都用的起来

**Comment by sunoonlee** [comment]
关于issues的使用，有个问题：
既非教学反馈，也非与当周课程相关的技术问题，是否就可以新建issue讨论？对issue的内容，有何指导性意见？看着issue列表里屈指可数的“官方”issue，不敢贸然地掺和呢。

**Comment by ZoomQuiet** [comment]
2015-10-11 21:18 GMT+08:00 sunoonlee notifications@github.com:

> 关于issues的使用，有个问题：
> 如果既非教学反馈，也非与当周课程相关的技术问题，是否就可以新建issue讨论？对issue的内容，有何指导性意见？看着issue列表里屈指可数的“官方”issue，不敢贸然地掺和呢。

try it ! 没有明令禁止的,都应该大胆尝试 ;-)

**Comment by Acural** [comment]
作为一名不懂编程的小白，不断在大妈、阳老的push下远离思维舒适区的感觉的确很棒。课程设计与以往教学有很大不同，更看重的是学生的自学能力。不过能不能在每节课的开始阶段对上节课所留的作业进行一次思路的梳理与演示？  作为第九区的学员（为啥武汉就只有我一个人 (＞﹏＜)），面对面学习教练的指导跟其他同学比肯定有差距，大妈或者教练能否提供下线下面基答疑时演示的视频？  我喜欢视频教学模式，因为他可以暂停，可以倒带，自己能提供强有力的反馈。   一点个人的小意见~

**Comment by ZoomQuiet** [comment]
2015-10-18 19:58 GMT+08:00 Acural notifications@github.com:

> 作为一名不懂编程的小白，不断在大妈、阳老的push下远离思维舒适区的感觉的确很棒。课程设计与以往教学有很大不同，更看重的是学生的自学能力。不过能不能在每节课的开始阶段对上节课所留的作业进行一次思路的梳理与演示？ 作为第九区的教练（为啥武汉就只有我一个人 (＞﹏＜)），教练的指导方面跟其他同学比有差距，大妈或者教练能否提供下线下面基答疑时演示的视频？ 我喜欢视频教学模式，因为他可以暂停，可以倒带，自己能提供强有力的反馈。 一点个人的小意见~
- 你喜欢看视频, 不代表视频是最好的自学参考
- 以俺的体验, 视频从来没有很好的解决俺的技术问题
- 进一步的, 录制视频对 教练们 也是个很大的压力, 我们在想办法解决
- 但是,另外一方面, 如果你能及时的将你的具体困惑反馈回来,我们可以及时的提供即有的海量相关视频给你...

公开课的情况:
- 0wd4 首次公开课,大家并没有一个完整的任务周
- 也即对一周任务的反馈不足的情况下
- 教练无法进行经典问题的回顾,指导
- 此时进行任务解析时,等于提前公布答案对大家的 合意困难 是种人为破坏...

**Comment by ZoomQuiet** [comment]
到期自然关闭
