### ISSUE TITLE
[1w] 学员分支仓库 报到处

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#20]
首周第一个任务环境配置环节,作业交付处:
- 所有学员, [Fork](https://help.github.com/articles/fork-a-repo/) 课程模板仓库
  - https://github.com/OpenMindClub/OMOOC2py
  - 到个人空间
- 将个人分支仓库地址提交在此 Issue:
  - 已在 [[0w] 学员分支仓库报到处 · Issue #4 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/4) 提交链接的学员不用再次报道.
  - 形式如下示范....

**Comment by ZoomQuiet** [comment]
@OpenMindClub/py2dama
https://github.com/ZoomQuiet/OMOOC2py

**Comment by wuxianliang** [comment]
@OpenMindClub/py2dama
https://github.com/wuxianliang/hyppy

**Comment by henryopenmind** [comment]
@OpenMindClub/py2dama
https://github.com/henryopenmind/OMOOC2py

**Comment by crazy-tea** [comment]
@OpenMindClub/py2dama
https://crazy-tea.gitbooks.io/openmindclub-studynote-by-tea

**Comment by leonpak** [comment]
https://github.com/leonpak/OMOOC2py

**Comment by JeremiahZhang** [comment]
将之前的仓库

https://github.com/JeremiahZhang/pybeginner

迁移到了OMOOC2py：

https://github.com/JeremiahZhang/OMOOC2py

@OpenMindClub/py2dama

**Comment by dayuhomes** [comment]
@OpenMindClub/py2dama
https://github.com/dayuhomes/OMOOC2py

**Comment by linttutu** [comment]
https://github.com/linttutu/OMOOC2py
@OpenMindClub/py2dama
之前仓库fork错，重新发送

**Comment by ivanlau** [comment]
https://github.com/ivanlau/OMOOC2py
@OpenMindClub/py2dama

**Comment by xiangshan** [comment]
@OpenMindClub/py2dama
https://github.com/xiangshan/OMOOC2py

**Comment by StoryTelr** [comment]
@OpenMindClub/py2dama
https://github.com/StoryTelr/OMOOC2py
