### ISSUE TITLE
[1w]课程相关 技术问题 讨论

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#21]
- 参考: 
  - [缩写](https://github.com/OpenMindClub/OMOOC2py/wiki/HbShortRule)
  - [典章:说与菜鸟 | PyChina.org Static Wiki](http://wiki.pychina.org/hd/FreshProposeFor.html)
  - [提问的智慧](http://wiki.woodpecker.org.cn/moin/AskForHelp)
    - [5W1H](http://wiki.woodpecker.org.cn/moin/5W1H)
    - [SMART原则 - MBA智库百科](http://wiki.mbalib.com/wiki/SMART%E5%8E%9F%E5%88%99)
  - ...
- 技术讨论一定要认真的提供可以复现问题的足够信息
- 否则其他人是无法用脑补来还原你的场景的
- 特此草拟如下提问模板,以便学员使用:

:

```
## 背景
- 系统:
- 版本:
- 代码:
- ...

## 现象
- 输入: ..
- 触发: ..
- 问题: 非期待...

## 分析
- 尝试0:
    - 参考:
    - 判断:
    - 实验:
    - 结论:
- 尝试1:
    - 参考:
    - 判断:
    - 实验:
    - 结论:
- 尝试2:
    - 参考:
    - 判断:
    - 实验:
    - 结论:
- ...

## 方案
- 解决思路0:
    - 参考:
    - 设想:
- 解决思路1:
    - 参考:
    - 设想:
- 解决思路2:
    - 参考:
    - 设想:

哪种思路正确,或是其它思路?
```

**Comment by rayxiehui** [comment]
### 问题：github本地命令行设置生成ssh key无法通过验证

描述：按照官方帮助文档生成的key在填写ssh验证时报错：
Key is invalid. It must begin with 'ssh-ed25519', 'ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', or 'ecdsa-sha2-nistp521'. Check that you're copying the public half of the key

这是我自己生成的key值
The key fingerprint is:
SHA256:QBfjDAxIkdaewajD/9sCcWBqmImMB3RLQZjc2LKGAzI xiehuiray@gmail.com

实例key 格式
The key fingerprint is:
01:0f:f4:3b:ca:85:d6:17:a1:7d:f0:68:9d:f0:a2:db your_email@example.com

#### 问题解决思路：

1.先googol搜索ssh key 格式。没有搜出相同情况
2.按照其他博客重新生成ssh key 。还是同样的格式。
3.花费时间已经太久，直接发出来。

### 问题更新

大妈提醒的好
首先，我实在mac 环境中想通过ssh访问github。
第一步是按照官方文档安装。https://help.github.com/articles/generating-ssh-keys/
然后出现的key格式不相同。

#### 没折腾出来，暂时放弃，还是听大妈的，把简单模式用起来再说，折腾别的。

在折腾DisQus时，搜索出http://pizn.github.io/2011/11/22/mac-git-and-github.html 这篇文章。
解决办法是用命令打开 ssh文件夹下的id_rsa.pub文件，key值在这个文件里面，可以通过验证。

**Comment by ZoomQuiet** [comment]
On Sun, Oct 18, 2015 at 8:43 PM, xiehui notifications@github.com wrote:

> 问题：github本地命令行设置生成ssh key无法通过验证
- github 命令?! 这是什么鬼?!
- windows 环境? 用 putty 中包含的 ssh key 生成器!
- 另外, 你完全可以不用 key 来访问 github 的, 选择最简单模式,先用起来!

> 描述：按照官方帮助文档生成的key在填写ssh验证时报错：
> Key is invalid. It must begin with 'ssh-ed25519', 'ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', or 'ecdsa-sha2-nistp521'. Check that you're copying the public half of the key
> 
> 这是我自己生成的key值
> The key fingerprint is:
> SHA256:QBfjDAxIkdaewajD/9sCcWBqmImMB3RLQZjc2LKGAzI xiehuiray@gmail.com
> 
> 实例key 格式
> The key fingerprint is:
> 01:0f:f4:3b:ca:85:d6:17:a1:7d:f0:68:9d:f0:a2:db your_email@example.com
> 
> 问题解决思路：
> 
> 1.先googol搜索ssh key 格式。没有搜出相同情况
> 2.按照其他博客重新生成ssh key 。还是同样的格式。
> 3.花费时间已经太久，求助大妈。
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by liangdl** [comment]
@rayxiehui 你是什么系统win、mac、linux方法不一样。而且不生成ssh也没事，就是每次git push输入密码而已

**Comment by sherlockhoatszx** [comment]
大妈你好，
关于w1的任务要求我不是特别清楚，有些疑问能否明确下？
quote1:完成一个极简交互式日记系统,需求如下:
一次接收输入一行日记
保存为本地文件
再次运行系统时,能打印出过往的所有日记
quote1 end

comment:交互＝可以读、写、保存？
日记系统我的理解是两种场景：1、日记是指本地目录下的txt格式文件？ 2、还是指网页blog或者gitbook?
保存为本地文件是指：1、python程序保存为本地 ，还是日记保存为本地？
再次运行系统能打印出所有日记，我的理解是同一目录下的批处理？

quote2:
首先,得有一个稳定的代码记录容器: 脚本

以之前上传的 _src/om2py0w/
/main.py 为例
如何调用之?
并确保每次调用返回相同的结果?
quote2 end

comment: 调用之 的之时指代脚本还是指代网页（通过接口？）

基于极简的交互这个意思，应该是这样的场景吧:本地某目录下，存放了n个txt格式的日记（n>2)。编写python程序实现t：1、每次打开程序时全部打印出目录下的n个txt中的内容；2,实现txt文档的创建打开，写入，保存。3、txt文件名是中文名。4、终端中调用程序（不要做成exe格式）

以上对场景情解惑，不对的地方请指正。

谢谢！

sherlock

**Comment by xpgeng** [comment]
刚刚写完了[如何拼出git config并实现"one command, 160 pushed"?](https://xpgeng.gitbooks.io/omooc2py/content/guide/push160.html)    希望大家能测试一下, 最好能说说你的看法,或者建议. 感激不尽.

Thx  ;-)

**Comment by bambooom** [comment]
觉得还是不另建issue比较好。。。
看了已经出来溜的几位同学都很好很强大，但基本都是mac吧，弱弱的win党上班摸鱼求comment
https://github.com/bambooom/OMOOC2py/issues/3

**Comment by picklecai** [comment]
## 背景
- 系统: win7
- 版本: python 2.7.8
- 代码:
  <pre><code>
  # 新内容另存为文件
  filename = raw_input("存储今日记录，请输入文件名：")
  output = open(filename + ".txt", 'w') #规定好扩展名，以免出现用户保存的文件打不开的情况。
  output.write(filename + ".txt"+"\n") #在文件中写入文件名。
  output.write(time.strftime("%d/%m/%Y %H:%M:%S"+"\n")) #在文件中写入当前时间。
  output.write(newline)
  output = open(filename + ".txt")
  output.close
  </pre></code>

## 现象
- 问题一： 如果缺少倒数第二行的<pre><code>output = open(filename + ".txt")</pre></code>新文件就不写刚刚输入端 内容，要到下次运行程序才写入。
  为什么需要重新读文件，才会写入？同一个程序的上一段代码就不会这样。  
- 问题二：因为多写了一个重新以读的方式打开文件，所以之前是先写了关闭，再写这个打开的：
  <pre><code>
  output.write(newline)
  output.close
  output = open(filename + ".txt")
  output.close
  </pre></code>

发现去掉第一个output.close程序也能运行。open和close难道不是应该成对出现的吗？  

附：不需要重新读文件就能正常写入的代码：
<pre><code>
#输入新的内容
    txt = open("tempfile.txt", 'a')
    newline = raw_input("今日记录，请输入： ")
    txt.write(time.strftime("%d/%m/%Y %H:%M:%S"+"\n")) #在保存当前输入的同时，也保存当前时间。
    txt.write(newline)
    txt.write("\n"+"\n")
    txt.close()
</pre></code>

代码全文：https://github.com/picklecai/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py

**Comment by ZoomQuiet** [comment]
@liangdl [交互 101-脚本调用 问题 · Issue #25 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/25)

**Comment by ZoomQuiet** [comment]
@Jaspereclipse [pyenv管理版本工具安装的问题 · Issue #36 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/36)

**Comment by doreenduo43** [comment]
系统：mac yosemite 10.10.5
python: Python 2.7.10

问题：
当指定mode时，则无法读取文件

例：写为
f = open('diarybook.txt','a+')

print f.read()
返回结果为 一个空行。

写为
f = open('diarybook.txt','r')

print f.read()
则返回文件中已经写入的内容。

把mode指定为w
也会正常运作，把文件清空。等待写入。

看了笨方法关于文件读取与写入的章节，外加python系统自带help(file)，外加google搜索（关键词为： python 文件 读取 a+）。仍然无解。

虽然在最后我提交的代码里，我换成了“打开，读取，关闭”之后，再“打开，追加写入，关闭”的方式写了代码。但是我还是不明白mode为a+的话为什么就不能一起实现先打开，再追加写入呢？

这个问题昨天折磨了我两个小时，希望能帮帮忙，谢谢。

**Comment by ZoomQuiet** [comment]
2015-10-22 18:29 GMT+08:00 doreenduo43 notifications@github.com:
...

> 虽然在最后我提交的代码里，我换成了“打开，读取，关闭”之后，再“打开，追加写入，关闭”的方式写了代码。但是我还是不明白mode为a+的话为什么就不能一起实现先打开，再追加写入呢？
- "...为什么就不能一起实现先打开，再追加写入呢"
- 这又不是量子态,一个文件句柄同一时刻只能有一种模式的哪!
- 恭喜你在本地文件阶段就触发了网络编程时的锁问题 ;-)

> 这个问题昨天折磨了我两个小时，希望能帮帮忙，谢谢。
- 为什么折磨?
- 用其它方式能完成任务嘛?!
- 你是否相通和代码是否可用有直接关联嘛?
- 如果没有, 以什么为先?!
- 当然想不通却能作到,这的确是一种折磨!
  - 所以, 你的问题应该转化为
  - 为什么俺要想通?!
  - 想通对俺整体 py 技能提高有什么本质好处?
  - 如果想不通,但是,能用?!
  - 那么先这么用起来,问题挂着,挂好...
  - 某天必然能自然而然通的...

**Comment by jorylu** [comment]
![image](https://cloud.githubusercontent.com/assets/12541111/10782022/c24f700a-7d87-11e5-9c06-85f4b82ca2a1.png)
gitbook的MAC客户端登陆不上去，提示邮件有问题

  ##  分析： #
- 之前是用github账号登陆的，没有验证邮件（在网页版填写的邮箱并提交，还是没有解决）
- 重新通过邮箱修改密码（密码已修改OK，但还是不能在客户端登陆，用用户名也不行）
  
  ## 暂时还是用网页版吧
