### ISSUE TITLE
[0w]课程意见反馈

### ISSUE THREAD

**Issue by sunnyhuang42** [OpenMindClub/OMOOC2py#23]
@OpenMindClub/py2student  还没填写课程反馈表的小伙伴，
请在 1wd0 19:00 前把意见砸到这里-->[OMOOC2py 0w 课程反馈表](http://openmind.mikecrm.com/f.php?t=1VXBMt)

**Comment by csyuking1989** [comment]
# 建议
1、安排任务之前，最好给一个基础知识清单（只要罗列出基本概念就可以，了解和理解需要学员自行解决），给出what和why，这样对于完全零基础的学员，有更好的代入感。不过，我发现芝麻星上已经有很多基础概念了，自己耐心一点，慢慢读下去很多问题都清晰了.....

**Comment by ZoomQuiet** [comment]
2015-10-18 16:40 GMT+08:00 csyuking1989 notifications@github.com:

> 建议
> 
> 1、安排任务之前，最好给一个基础知识清单（只要罗列出基本概念就可以，了解和理解需要学员自行解决），给出what和why，这样对于完全零基础的学员，有更好的代入感。不过，我发现芝麻星上已经有很多基础概念了，自己耐心一点，慢慢读下去很多问题都清晰了.....

建议和自我发现都非常靠谱!

ZMS 系统就是为了给大家一个分解任务的知识树来创造的

> —
> Reply to this email directly or view it on GitHub.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by ZoomQuiet** [comment]
归档
