### ISSUE TITLE
交互 101-脚本调用 问题

### ISSUE THREAD

**Issue by liangdl** [OpenMindClub/OMOOC2py#25]
这里理解有点困难

> 首先,得有一个稳定的代码记录容器: 脚本  

代码记录容器不就是.py文件么? 我所理解的脚本是指 python 这种解释性语言的代码，不稳定是指什么情况？

> - 如何调用之？

这里是指把这个脚本定义成 module？

> - 并确保每次调用返回相同的结果?

代码写好了每次调用会返回不同的结果？这是怎么做到的。。。。     

昨天的作业做完了。。还没commit，还在配置vim中。。。

**Comment by ZoomQuiet** [comment]
嗯哼, 你的水平很髙,能用编辑器之神的人是无法想象普通人的困惑的
- 有的学员跟随有的教程, 一直在使用 python 的交互界面
- 所以, 在 REPL 中的代码,是无法长期运行的,每次都要重新输入
- 所以, 这里强调了一个元知识: 只有 .py 的文件才是我们应该持续修订的开发容器

对了,如果回答,解决了你的问题, 请确认后关闭 Issue 
这就完成了一问一答再confirm closed 的完整 Issue 生命周期

**Comment by liangdl** [comment]
其实我说的配置vim只是。。安装spf13-vim而已。。。-_-! 之所以久是因为下载plugin慢啊。。

**Comment by ZoomQuiet** [comment]
并入 [[1w]课程相关 技术问题 讨论 · Issue #21 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/21)
