### ISSUE TITLE
[1w任务尝试]小小日记

### ISSUE THREAD

**Issue by zoejane** [OpenMindClub/OMOOC2py#26]
今天看到芝麻星卡包发布的[第一周行动](http://www.iomooc.com/pages/cards.html?taskId=313a2360-6db3-11e5-a837-0800200c9a66)，尝试着自己去做了一个自己能用的小小日记文件。
因为平常只有周末还有点时间编程，工作日时间真的太不确定，所以虽然做的还有很多不完善的地方，但还是决定先发布出来啦，请大家批评指正^_^
### 下载

这个是[我的代码](https://github.com/zoejane/OMOOC2py/tree/master/_src/om2py0w)，也写了个不太成熟的README，不知道你们是否可以正常使用呢？
### 笔记

今天具体的尝试过程，我有写在自己的笔记里——[交互101 - 小小日记系统](https://zoejane.gitbooks.io/omooc2py/content/1sTry/diary101.html)，给大家参考
#### 1.关于中文参数

芝麻星的“交互 101-输入中文”，问道“脚本如何获得外部中文文本?如果给的参数是中文字符, 运行脚本会发生什么事儿?” 
在实际使用过程中，我发现我输入的参数是中文，也没有影响功能的实现。
是我的解决思路和芝麻星预先设计的思路有所不同么？
或者是在我使用的MAC OS10.10，python3的配置下不会出现这个问题吗？
#### 2.关于代码路径

为什么默认情况下，代码要放在_src/om2py0w/0wex1/这种复杂的路径下呢？
我在使用过程中，发现代码放在层层叠叠的文件夹中有些头晕，而且字母和数字放一块有时候也容易弄混。
尤其是如果想在终端直接调用.py文件的话，要涉及到把.py文件的路径添加到PATH里，以及将py的权限用"chmod +x xxx.py"的方式更改，感觉越发复杂了。
我现在尝试的是把自己的代码都放在MyPythonScripts文件夹下，因为比较一目了然一些，做完了再移到O2MOOC里的。
用这种复杂的路径设定有什么好处么？是我现在没有理解到么？

欢迎大家一起来探讨，谢谢你们啦:)

**Comment by ZoomQuiet** [comment]
![2015-10-19 00 03 21](https://cloud.githubusercontent.com/assets/22494/10564852/16920dfc-75f5-11e5-8d39-38869e2f1464.png)
- 嗯嗯嗯,这么夜都在编程!
- 只是,俺在 MAC 10.11 , Python 2.7.10 (default, Jul 14 2015, 17:03:28)
  - [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
  - 环境中运行效果如上

'''...层层叠叠的文件夹中有些头晕
'''
- 复杂嘛? 
- "要涉及到把.py文件的路径添加到PATH里，以及将py的权限用"chmod +x xxx.py"的方式更改..."
- 嗯哼, 这肯定不是 .py 在 win 环境中正确的调用姿势哪
- 另外, 能观察出当前的模板目录有什么规律嘛?
- 以及, 如果你用 d/dd/dddd/dddddddd 作为你的脚本名
- 半年后的你是否知道怎么使用嘛?
- 进一步的, README.md 应该写什么,谁来看,这是个隐藏的问题
  - 你想过没有?

**Comment by ZoomQuiet** [comment]
![2015-10-19 00 09 57](https://cloud.githubusercontent.com/assets/22494/10564877/c13e0026-75f5-11e5-80c0-54f7857d4e01.png)

눈_눈, 以上特效是如何编辑出来的?!
- 为什么?
- 如何避免?
- 有更好的办法来解决嘛?

**Comment by zoejane** [comment]
今天太晚，很多问题还要明天起来好好想一下，一步步改过来。
python2我写的py脚本是dd.py，不过我发现d.py也可以运行。（现在发现自己程序名字写得太烂了。）  
刚刚在自己的机子上测试了一下
![Imgur](http://i.imgur.com/nshwt3J.png?1)
- 1.“是也乎,(￣▽￣)”确实不能正确运行，初步判断和特殊符号，尤其是括号有关
- 2.单独打特殊符号的时候，好像有时候又可以加入成功，有待继续探索
- 3.我这边测试的时候，发现中文，以及某些时候的特殊符号是可以显示的。  
  但是同样的内容，在你的机器上运行结果就是完全不成功。  

这次我的测试环境是Mac OS10.10和python2.7.6。
不知在我的机器上，有什么办法复现你的运行错误，以便自己更好的进行调试吗？
不过，当没有办法复现错误的时候（毕竟不可能复现所有操作系统下的所有错误），我有什么别的办法可以调试吗？
这个有待自己有空上网搜索和测试，进一步探索一下。

个人推测，这次运行结果不同，是不是还是因为运行环境不同的缘故。
不知道这个推测方向对吗？有没有遗漏掉别的线索和可能性？

**Comment by zoejane** [comment]
P.S. 
刚刚自己尝试下载自己的代码的时候，才发现，原来github里的代码，不是我原先以为的用“右键-另存为”的方式下载。囧囧囧。
因为以前都是fork,clone之类的，整个项目的文件夹一把下载下来的，对这件事情居然完全木有察觉。
所以重新把源文件(.py)上传到自己的网站上，修复了README中的下载链接。

**Comment by faketooth** [comment]
Zoe真是认真极了……个人教程里记录了那么多内容，让人压力山大啊

**Comment by wzzlj** [comment]
@zoejane @ZoomQuiet

#### 下载的问题我今天研究了下
- 把脚本文件打包成 zip，push 到仓库内
- 在仓库内点开 zip 文件，
  - 原始方法是点击右上角的`Raw`下载文件
  - 也可以将文件地址中的 `blob` 改成 `raw` ，这样可以将下载地址插入 readme.md，点击就能下载

#### 另外我的日记脚本完成了自己的初步设想，不另开 Issue 了
- 可以在 [Gitbook《简单日记脚本思路》](https://wzzlj.gitbooks.io/wzzljomooc2py/content/_src/om2py0w/0wex1/think.html)下评论
- 也可以在我的 [《简单日记脚本》Issue](https://github.com/wzzlj/OMOOC2py/issues/3) 下讨论
- 这是 [代码地址](https://github.com/wzzlj/OMOOC2py/tree/master/_src/om2py0w/0wex1)

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)
那这就关闭了
