### ISSUE TITLE
[1wd4]广州 线下活动报名

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#29]
- 地点: 广州 天河区 珠江新城 华夏路30号 富力盈通31F 3110 会议室
- 时间: 周四 19:42~22:22
- 报名: 回复说明以下关键信息
  - github 帐号
  - 大约到达时间
  - 期望现场解决的技术问题
- 截止: 周四 10:10 前有效
- _提醒:_ 必须带上电脑,以便现场明确技术问题的细节 ;-)

参考: [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)
### 无责任记要
- 录音: [151022_1wd4/](http://openmindclub.qiniucdn.com/res/tapes/omooc/omooc2py/151022_1wd4)
- 签到: ![151022C2T2Gz_sign.jpg](http://openmindclub.qiniucdn.com/res/tapes/omooc/omooc2py/151022_1wd4/151022C2T2Gz_sign.jpg?imageView2/2/w/150)
- 合影: ![151022C2T2Gz_all.jpg](http://openmindclub.qiniucdn.com/res/tapes/omooc/omooc2py/151022_1wd4/151022C2T2Gz_all.jpg?imageView2/2/w/240)
- 记要:
  - 再次对不起从各地赶来的弟兄们了
  - 一时准备的内容太多
  - 给 本地 C2T2 的交流时间太少
  - 下次要调整!
- 提醒:
  - 1wd6 20:20 前
  - 来现场参加公开课的学员,应该在这儿提交笔记的链接了!

@OpenMindClub/py2prd

**Comment by hujianfei1989** [comment]
github : hujianfei1989
大约到达时间:19:30
期望现场解决的技术问题:…现场说…

**Comment by ivanlau** [comment]
账号: ivanlau
大概19:30到
先报名，晚上先学习下看能不能发现问题

**Comment by lixiguangzhou** [comment]
github:lixiguangzhou
到达时间：19:30
过来朝拜大妈。

**Comment by simple2source** [comment]
账号：simple2source
到达时间19：30
先交流~~

**Comment by penguinjing** [comment]
github : penguinjing
大约到达时间:19:12
期望现场解决的技术问题: 如何确定企业公众号发红包的流程及如何开发?

更新: [线下公开课笔记](https://penguinjing.gitbooks.io/omooc2py/content/1sTry/1wd4notebook.html)

**Comment by demonmax** [comment]
github:demonmax
到达时间：18:42
前期没赶上各种开光仪式 脑袋缺根弦 亟需大妈开智
0w 1w 功课没完成 这几天也补充了很多知识 希望现场再理顺下课程思路 然后正式开始寻蟒

**Comment by demonmax** [comment]
还有还有还有 说好的python-T怎么不见了  我是s我是s我是s = =

**Comment by ZoomQuiet** [comment]
On Thu, Oct 22, 2015 at 10:00 AM, Max notifications@github.com wrote:

> 还有还有还有 说好的python-T怎么不见了 我是s呀我是s呀我是s呀 = =
- 只有首次来的才有
- 再来的,就没有了
- 嗯哼,除非给出理由说服俺: 为什么应该送你?
