### ISSUE TITLE
极简交互式日记系统开发记录

### ISSUE THREAD

**Issue by faketooth** [OpenMindClub/OMOOC2py#31]
作业是周日晚上匆匆做完的，并且私自加了一些大妈没有提到的东西。卡片中提到的中文参数和中文内容，应该是跟编码格式或者`UnicodeError`相关的坑，环境是Mac + Python 2.7.10，没有撞坑。
<B>
代码：[main.py](https://github.com/faketooth/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py)
文档：[README.md](https://github.com/faketooth/OMOOC2py/blob/master/_src/om2py0w/0wex1/README.md)
</B>

本周练习题目公布在[芝麻星](http://www.iomooc.com/pages/login.html)，要求开发一个简易的日记系统，连夜做完，特来补充文档。题目要求如下：

> 本周整体任务概述:
> - 完成一个极简交互式日记系统,需求如下:
>   - 一次接收输入一行日记
>   - 保存为本地文件
>   - 再次运行系统时,能打印出过往的所有日记
> - 时限: 0wd4~1wd3
> - 发布: 发布到各自仓库的 `_src/om2py0w/0wex1/` 目录中
> - 指标:
>   - 包含软件使用说明书: `README.md`
>   - 能令其它学员根据说明书,运行系统,完成所有功能
## 设计思路

先根据具体功能需求，分析需要完成什么功能：

> 一次接收输入一行日记

需要支持用户从键盘输入，最好的方法莫过于调用`raw_input('> ')`，函数的返回结果存入变量`input`中，等待后续处理。

> 保存为本地文件

用户输入的内容需要保存到文件中，因此涉及文件的基本操作。

> 再次运行系统时，能够打印出过往所有日记

这个功能涉及文件读取，将读取到的文件内容全部打印到屏幕。

由于觉得只是实现这几条小功能过于简陋，因此自作主张，设计增加了脚本其他功能，例如：
- 增加更多的提示信息，告诉用户当前正在打印历史信息、现在可以接受输入、如何退出脚本等
- 记录日记过程中，添加`while`死循环，保证用户在输入`exit`并回车之前，可以一直输入下去
- 因为前几天写一个解析 XML 文件的脚本工具时，用到了 Python 自带的`logging`模块，决定将写文件的操作直接交给`logging`模块来处

这是初期的运行效果：
![初期运行效果](https://cloud.githubusercontent.com/assets/1687273/10608557/1e6eb2c2-7772-11e5-8877-e15dde84e8b9.png)
## 第一轮迭代

没弄明白 DAMA 所说的容器是什么东东，就自作主张拆分了脚本，`run.py`作为运行入口，`main.py`作为一个module导入到其中。第一次这么玩，竟然稀里糊涂成功了。
## 第二轮迭代

使用`sys`模块的`sys.argv`获取脚本运行时传入的变量，并判断参数个数。在参数个数小于1时，打印`usage`信息：

![usage](https://cloud.githubusercontent.com/assets/1687273/10608515/e6be8726-7771-11e5-85cf-842b047dd934.png)

脚本运行后，会根据给出的文件名查找历史日记所在的文件，如果文本不存在，打印提示信息；如果文件存在，读取文件内容并打印到屏幕。
## 第三轮迭代

DAMA 的要求中提到读写中文、参数中文，直接运行脚本发现功能正常不报错，暂且先通过，明天再研究编码问题。因为上周写工具解析 XML 的时候，遇到几次UnicodeError，感觉这个迭代的坑在编码问题。
## 第四轮迭代

要求做到持续交互，输入指定命令退出。但是这个功能已经在最开始的时候被我擅自主张得给做了=。=！
![持续交互，exit退出](https://cloud.githubusercontent.com/assets/1687273/10608537/095041c6-7772-11e5-96ec-5eca3193761a.png)

<del>明天我再重构一把功能好了，用户在写日记的时候可以随时敲`history`命令，查看整个日记内容</del>。
## 第五轮迭代

直接借助`logging`模块，将日记内容逐行写入文件中，每行带有对应的时间戳，而文本的换行问题也不需要关心了......
## 重构
1. 合并了`run.py`和`main.py`，不再拆成两个；
2. 用户在输入日记期间，支持`history`命令，打印日记文件中目前为止的所有日记内容；
   ![qq20151020-0](https://cloud.githubusercontent.com/assets/1687273/10608835/671b8b3e-7773-11e5-8f55-961573cc206d.png)

**Comment by ZoomQuiet** [comment]
2015-10-20 21:45 GMT+08:00 faketooth notifications@github.com:

> 作业是周日晚上匆匆做完的，并且私自加了一些大妈没有提到的东西。卡片中提到的中文参数和中文内容，应该是跟编码格式或者UnicodeError相关的坑，环境是Mac + Python 2.7.10，没有撞坑。
- 先点赞,然后
- 嗯哼?! 已经完成48小时现在才释放笔记?!

> 代码下载：0wex1.zip
- 严令要沉浸 github 生态
- 为何要这么折腾 git 仓库!?
- 给仓库链接不就好了!?
- 在版本仓库中应该放什么文件?!
  - 这是一个基础又严肃以及非常细思恐极的问题
  - 涉及:
    - 什么是版本
    - 什么是版本仓库
    - 仓库的使命是什么
    - 什么是工程文件
    - ....
  - 请 24 小时以内认真回答,并形成私人教程章节公开出来

> 文档：README.md
> 
> 本周练习题目公布在芝麻星，要求开发一个简易的日记系统，连夜做完，特来补充文档。题目要求如下：
> 
> 本周整体任务概述:
> 
> 完成一个极简交互式日记系统,需求如下:
- 有任务要求的陈列以及分析理解
- 这是一个极好的习惯
  - 对应的是工程中的需求分析阶段
  - 不能缺少!
  - 非常重要!

...

> 由于觉得只是实现这几条小功能过于简陋，因此自作主张，设计增加了脚本其他功能，例如：
- 大爱这种自作主张!
- 嘦注意,先完成看不上眼的功能
  - 然后看看自个儿在允许的时间里能将功能扩展到什么程度!?
  - 当然,过程中的所有折腾都应该记录下来
  - 并自个儿总结:
    - 哪些很容易就实现了
    - 哪些相反
    - 这种和自个儿的目测情况不匹配的情况,多数是怎么发生的?!
    - 原因何在?
    - 自个儿在什么领域的目测很准? 什么领域是相反?
      - 为什么?
      - 如何改进?!
      - 哪种改进方式最合适自个儿?!
      - 为什么?
      - 这种经验能复用在其它人身上嘛?!
      - ...

...

> 第一轮迭代
- 有证据嘛!?
- 迭代过程都有版本历史嘛?!
- 代码是越来越少,还是越来越多?
- 功能的增加,代码必须增加嘛?
- 为什么?
- 能更加优雅些嘛?
- 有什么好处?!
- ...

**Comment by WhaleChen** [comment]
## 第一篇用户体验：
1. run 的很好！
2. 命令行最好 有一个默认路径 。提示 'Run the script like this:\n\tpython main.py history.log'  虽然可以，但每一次打文件名有些复杂。可以 参考 [sluren](https://github.com/suluren/OMOOC2py/commit/a45288f607fb5fbb0480a568144d0ffbaec1e907)
   直接给一个默认的 文件，在没有 argv[1] 的情况下已经可以默认执行。
3. 中文是OK的，再次赞，学习了！

**Comment by wzzlj** [comment]
提个意见，个人代码和想法最好放在自己仓库的issue下。  

参考我的https://github.com/wzzlj/OMOOC2py/issues/3

放在这里的话一两个人还好，如果160多个学员每个人都把自己的issue都放在这的话...

**Comment by faketooth** [comment]
@ZoomQuiet 求继续虐：[极简交互式日记系统开发复盘](https://faketooth.gitbooks.io/omooc2py/content/0MOOC/1w/%E6%9E%81%E7%AE%80%E4%BA%A4%E4%BA%92%E5%BC%8F%E6%97%A5%E8%AE%B0%E7%B3%BB%E7%BB%9F%E5%BC%80%E5%8F%91%E5%A4%8D%E7%9B%98.html)

**Comment by faketooth** [comment]
@WhaleChen 多谢建议，马上把这个功能加进去
@wzzlj 主要是受到@zoejane的影响，以后单独@大妈找虐

**Comment by zoejane** [comment]
@wzzlj @faketooth @OpenMindClub/py2staff 
喵，其实我也很纠结，是不是不该单开issue。
主要是有时候想要大家一起讨论，不仅仅是自己记录或者是让助教指导，
有尝试去翻大家写的gitbook看， 不过一百多号人也翻不过来呢 T_T
微信有时候刷不过来，芝麻星也是自己和自己玩，就这里还是一个大家聚集的地方了，
好不容易大家有机会在一个班里学习，不交流一下感觉好浪费的说.....

**Comment by ZoomQuiet** [comment]
On Wed, Oct 21, 2015 at 1:17 AM, faketooth notifications@github.com wrote:
...

> @wzzlj 主要是受到@zoejane的影响，以后单独@大妈找虐

得咸鱼不若得渔哪!
- 俺在吐糟其它学员时,你也同样可以问问自个儿相同的问题
- 俺的问题出发点一直是单纯的,没有变化的:
- 好奇心!
- 认真!
- 想!

**Comment by ZoomQuiet** [comment]
并入

[[1w]学员任务 提交处 · Issue #41 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/41)
