### ISSUE TITLE
让编程更有爱一点-给哥哥的小小日记本

### ISSUE THREAD

**Issue by zoejane** [OpenMindClub/OMOOC2py#32]
喵，话说今天改代码，不知怎么突然想起以前看过的一门python课程。
课程其实很简单，但是最感动我的是，他们用python和他们所爱的人一起分享的时刻。
无论是给自己的小孩子上一课超简单的python课，还是用python做出一个小小照片游戏，告诉自己亲爱的人，说爱你。
这是我觉得python最有爱的时刻，也是最最让我感动的时刻。
那些程序是那样的简单，却让我真的感觉到，这样简单的事情是如此的有意义。

所以，今天就想学着让自己的编程更有爱一点。
把这个日记系统改成了给哥哥的Special Version ^_^
也希望大家可以测试一下这个小小程序的使用感觉哟。
## 截图

![](http://i.imgur.com/MkycR5f.png)
## 下载

http://zoejane.net/python/diary.py
## 笔记

https://zoejane.gitbooks.io/omooc2py/content/1sTry/love-of-programming.html
## 源代码

https://github.com/zoejane/OMOOC2py/blob/master/_src/om2py0w/0wex1/diary.py
## 使用
- 使用命令行进入你存放文件的目录( "cd 你的下载目录" )
- 运行"python diary.py"

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣) 无法同意更多!
- 软件是人写的
- 想感动其它人,首先得感动自个儿!
- 也只有 Python 能以最薄的阻碍来理性化任何感动了!
- 加油! 将你的感动批量运行起来吧!

**Comment by tonyyet** [comment]
测试过，可用，而且还非常有爱，喜欢！

**Comment by ZoomQuiet** [comment]
并入

[[1w]学员任务 提交处 · Issue #41 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/41)
