### ISSUE TITLE
【BUG汇总】日记本

### ISSUE THREAD

**Issue by shawn0lee0** [OpenMindClub/OMOOC2py#33]
https://github.com/shawn0lee0/OMOOC2py/tree/master/_src/om2py0w/0wex1
- 在不退出程序的前提下， 再次运行w，写日记， 程序报错。。。~~~~(>_<)~~~~ 
- 日期的‘   ’如何消除掉。。。

![](http://i11.tietuku.com/5680fd4224cf054b.jpg)

**Comment by faketooth** [comment]
- 错误的原因已经提示：`I/O operation on closed file.` 你看一下`diary_write`的最后一行就懂了
- 关于日期的单引号问题，建议先用`type()`检查一下那个时间的变量的类型，然后琢磨一下`print`的格式化参数`%s`和`%r`都有啥效果

**Comment by shawn0lee0** [comment]
@faketooth 谢谢，你的建议。问题解决。不过时间模块有问题。只有在main初次执行时候调用，在main()循环中，不会载入当前时间。我晚上再排查下。

**Comment by ZoomQuiet** [comment]
并入 [[1w]学员任务 提交处 · Issue #41 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/41)
