### ISSUE TITLE
[1wd3]还要在这提交issue啊？

### ISSUE THREAD

**Issue by Awlter** [OpenMindClub/OMOOC2py#34]
https://awlter.gitbooks.io/omooc2py/

**Comment by xpgeng** [comment]
@Awlter 点进去什么也没有啊， 你确认没弄错链接？

**Comment by Awlter** [comment]
@xpgeng 哈哈，这回好了

**Comment by ZoomQuiet** [comment]
并入 [[1w]学员任务 提交处 · Issue #41 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/41)
