### ISSUE TITLE
pyenv管理版本工具安装的问题

### ISSUE THREAD

**Issue by Jaspereclipse** [OpenMindClub/OMOOC2py#36]
我在补0W的课，里面提到用pyenv管理版本，但我发现用pyenv install 2.7.8的方法安装python会卡在半路（patching file ./Lib/site.py）。我不知道是不是因为我原本已经安装过Python的缘故

**Comment by cp4** [comment]
提问的智慧需要再学习呀
~~
你在什么环境下操作？
卡在半路？之后呢？你强行中断了，还是出现错误提示了？
错误提示说什么？
你做了哪些探索？

**Comment by ZoomQuiet** [comment]
并入: [[1w]课程相关 技术问题 讨论 · Issue #21 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/21)
