### ISSUE TITLE
1W 任务交作业

### ISSUE THREAD

**Issue by hysic** [OpenMindClub/OMOOC2py#37]
没有找到提交地址, 只好新开一个 issue 了, 请大妈和各位指正
issue 地址: hysic/OMOOC2py#1
gitbook 地址: https://hysic.gitbooks.io/hysic-s-python-journey/content/1sTry/Week_1/Interactive101.html
上述两个内容是一样一样的, 二选一即可

**Comment by chientung91** [comment]
功能实现完整，开发过程清晰，赞！

**Comment by ZoomQuiet** [comment]
并入 [[1w]学员任务 提交处 · Issue #41 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/41)
