### ISSUE TITLE
[1w]小赖的交互日记系统

### ISSUE THREAD

**Issue by wp-lai** [OpenMindClub/OMOOC2py#38]
貌似已经过截止时间了，那就把现在已经做出来的东西，整理下发布出来吧

现在实现了的功能是
- 通过`Sublime Text 3`来输入要记录的信息
- 输入支持Markdown语法
- 在浏览器里显示已经记录的日记信息

代码发布在我的[`GitHub`仓库](https://github.com/wp-lai/alan_diary)里，`README.md`文档写的有些匆忙，有没说清楚的地方请向我反馈，可以通过[issue](https://github.com/wp-lai/alan_diary/issues)或者<a href="mailto:techwplai@gmail.com">邮件</a>，意见和建议我都欢迎。

代码的开发记录发布在我的[`Gitbook`](https://wp-lai.gitbooks.io/learn-python/content/2nDev/diary.html)里，感兴趣的同学可以看看。

> ps: 代码更新了几个版本才想起来该用`git`来管理，建立分支去探索新功能。
> 
> 反思了下原因
> - 最初觉得只会写一个版本
>   - 所以没`git init`
> - 对要实现的功能没有一个清晰的描述
>   - 没想清楚后继版本中哪些是对现有版本的改善，哪些是新功能的探索
>   - 想到哪就去做哪，没有明确地规划
>   - 所以没有用起来`git`的`branch`和`merge`

@bambooom 
首先说说我的想法，我主要想做到的是
- 信息输入，储存，展示三者分开
  - 这样的好处是每次迭代时可以只修改三个部分其中的一个
  - 输入层面可以继续扩展功能，让用户选择自己喜欢的文本编辑器来进行信息输入
  - 储存成为现在是存为文本文档，之后可以扩展为`json`格式、`csv`格式，甚至使用数据库
    - 可以自动储存进更多的元数据，如时间、位置、天气等
    - 可以更好的提取信息，如根据时间提取内容
  - 展示现在的作法是用网页进行展示
    - 可以修改`css`样式，美化界面
    - 可以结合一些网页开发的库，更好地建立动态网站
  - 信息输入、储存、展示三个部分的代码分别都可以被用于其他项目中
    - 例如信息输入的代码可以用于笔记本系统的开发中
    - 信息展示的代码可以用于博客系统的开发中

再回到你提的问题

> 就是安装步骤是不是太繁琐了？
- 确实是
- `Sublime Text`和`subl`只是权益之计
  - \- [ ] #todo# 让用户提供参数，描绘用户想要使用的浏览器，并提供默认值
- `pandoc`确实不必要
  - `pandoc`是个很强大的软件，但放到我这个程序里有点大材小用了，不是很必要
  - \- [X]  使用`python`的第三方库`markdown`来进行格式转换，并补上其他html需要的信息

> 为什么我不直接建一个txt写东西保存就好了？
- `Sublime Text`编辑的是一个临时文件
  - 编辑完保存关闭之后，临时文件会自动被删除
  - 而输入的信息会传入到程序中
- 还是之前说的，我想做到信息输入和储存两个部分的分离

不知道这样有没有能完全回答你的问题。

**Comment by chientung91** [comment]
开发记录挺完整，赞过程！

**Comment by bambooom** [comment]
想到直接预览md以及格式转换很赞！

但是看了Readme后提个问题，就是安装步骤是不是太繁琐了？sublime
text就算了，为什么要安装subl？为什么还要安装pandoc？如果我作为一个什么都不懂的user，一看到要安装这么多奇怪的我不知道的东西，我会直接叉掉这个页面哦~

再以及交互的操作是不是也有点奇怪？假设前面的安装我都装了，然后我使用命令行打开了sublime
text3的页面，我输入了我想写的dairy，然后我还要点保存并关闭窗口？那为什么我不直接建一个txt写东西保存就好了？。。。用最简单的raw_input不可以嘛？

Milky NI Mengzhu
Tel: (852)66759692
Email: nmz89825@gmail.com

**Comment by ZoomQuiet** [comment]
并入 [[1w]学员任务 提交处 · Issue #41 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/41)
