### ISSUE TITLE
1W 交作业

### ISSUE THREAD

**Issue by ivanlau** [OpenMindClub/OMOOC2py#39]
- 目录: https://github.com/ivanlau/OMOOC2py/tree/master/_src/om2py0w/0wex1
- 说明: https://github.com/ivanlau/OMOOC2py/tree/master/_src/om2py0w/0wex1/readme.md
- 讨论:
  - https://github.com/ivanlau/OMOOC2py/issues/1#
- 感想:   
  - 我觉得文字应该倒序存储，但实现起来有点波折；  
  - 体验应该是形成闭环，在程序内完成，这涉及到两个内涵：
    - 不应该用工具提示给用户使用的其它方法来中断程序，我觉得这样体验不好；
    - 不要调用外部程序，会造成兼容问题。  
  - 我把说明放到工具里面，觉得能保证更好提升体验。

**Comment by ZoomQuiet** [comment]
并入 [[1w]学员任务 提交处 · Issue #41 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/41)
