### ISSUE TITLE
[0w] 学员分支仓库报到处

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#4]
首周第一个任务环境配置环节,作业交付处:
- 所有学员, fork 课程模板仓库
  - https://github.com/OpenMindClub/OMOOC2py
  - 到个人空间
- 将个人分支仓库地址提交在此 Issue:
  - 形式如下示范....

**Comment by ZoomQuiet** [comment]
@OpenMindClub/py2dama 
https://github.com/ZoomQuiet/OMOOC2py

**Comment by zoewang91** [comment]
@OpenMindClub/py2dama 
https://github.com/zoewang91/OMOOC2py

**Comment by ZoomQuiet** [comment]
这也忒敏感了,
还没有发布的任务哪...

On Tue, Oct 6, 2015 at 4:12 PM, 艾自由 notifications@github.com wrote:

> @OpenMindClub/py2dama https://github.com/orgs/OpenMindClub/teams/py2dama
> https://github.com/zoewang91/OMOOC2py
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenMindClub/OMOOC2py/issues/4#issuecomment-145777713
> .

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by William-Shen** [comment]
@ZoomQuiet 
https://github.com/William-Shen/OMOOC2py

**Comment by liangdl** [comment]
@liangdl
https://github.com/liangdl/OMOOC2py

**Comment by wp-lai** [comment]
@OpenMindClub/py2dama 
https://github.com/wp-lai/OMOOC2py

**Comment by shawn0lee0** [comment]
@OpenMindClub/py2dama
https://github.com/shawn0lee0/OMOOC2py

**Comment by Lcking** [comment]
@OpenMindClub/py2dama 
https://github.com/Lcking/OMOOC2py

**Comment by wzzlj** [comment]
@OpenMindClub/py2dama 
https://github.com/wzzlj/OMOOC2py

**Comment by conn820** [comment]
@OpenMindClub/py2dama
https://github.com/conn820/OMOOC2py

**Comment by suluren** [comment]
@OpenMindClub/py2dama 
https://github.com/suluren/OMOOC2py

**Comment by 4plus-ma** [comment]
@OpenMindClub/py2dama
https://github.com/4plus-ma/OMOOC2py

**Comment by Awlter** [comment]
@OpenMindClub/py2dama
https://github.com/awlter/OMOOC2py

**Comment by JeremiahZhang** [comment]
@OpenMindClub/py2dama
https://github.com/JeremiahZhang/pybeginner

**Comment by ghost** [comment]
@OpenMindClub/py2dama
https://github.com/ibrother/OMOOC2py

**Comment by hysic** [comment]
@OpenMindClub/py2dama
https://github.com/hysic/OMOOC2py

**Comment by hujianfei1989** [comment]
@OpenMindClub/py2dama
https://github.com/hujianfei1989/OMOOC2py

**Comment by Jaspereclipse** [comment]
@OpenMindClub/py2dama
https://github.com/Jaspereclipse/OMOOC2py

**Comment by tedxt** [comment]
@OpenMindClub/py2dama
https://github.com/tedxt/OMOOC2py

**Comment by bambooom** [comment]
@OpenMindClub/py2dama 
https://github.com/bambooom/OMOOC2py

**Comment by penguinjing** [comment]
@OpenMindClub/py2dama 
https://github.com/penguinjing/OMOOC2py

**Comment by doreenduo43** [comment]
@OpenMindClub/py2dama 
https://github.com/doreenduo43/OMOOC2py

**Comment by Sokratesjr** [comment]
@OpenMindClub/py2dama
https://github.com/Sokratesjr/OMOOC2py

**Comment by wanderingdopamine** [comment]
https://github.com/wanderingdopamine/OMOOC2py

**Comment by Acural** [comment]
重新修改了个人仓库  不好意思呢@OpenMindClub/py2dama
https://github.com/Acural/OMOOC2py

**Comment by WhaleChen** [comment]
@OpenMindClub/py2dama
https://github.com/WhaleChen/OMOOC2py

**Comment by BigMasonFang** [comment]
@OpenMindClub/py2dama 
https://github.com/BigMasonFang/OMOOC2py

**Comment by lixiguangzhou** [comment]
@OpenMindClub/py2dama
https://github.com/lixiguangzhou/OMOOC2py

**Comment by Cen74** [comment]
https://github.com/Cen74/OMOOC2py

**Comment by junjielizero** [comment]
@OpenMindClub/py2dama 
https://github.com/junjielizero/OMOOC2py

**Comment by wong-github** [comment]
@OpenMindClub/py2dama 
https://github.com/wong-github/OMOOC2py

**Comment by Wangqiaoyang** [comment]
@OpenMindClub/py2dama 
https://github.com/Wangqiaoyang/OMOOC2py

**Comment by zjuguxi** [comment]
@OpenMindClub/py2dama 
https://github.com/zjuguxi/OMOOC2py

**Comment by jane325** [comment]
@OpenMindClub/py2dama
https://github.com/jane325/OMOOC2py

**Comment by fqlxxxxx** [comment]
@OpenMindClub/py2dama
https://github.com/fqlxxxxx/OMOOC2py

**Comment by PursuitCane** [comment]
@OpenMindClub/py2dama 
https://github.com/PursuitCane/OMOOC2py

**Comment by Cloudtree11** [comment]
@OpenMindClub/py2dama 
https://github.com/Cloudtree11/OMOOC2py

**Comment by zoejane** [comment]
@OpenMindClub/py2dama 
https://github.com/zoejane/OMOOC2py

**Comment by huijuannan** [comment]
@OpenMindClub/py2dama 
https://github.com/huijuannan/OMOOC2py

**Comment by xpgeng** [comment]
@OpenMindClub/py2dama 
https://github.com/xpgeng/OMOOC2py

**Comment by Eloisechou1** [comment]
@OpenMindClub/py2dama 
https://github.com/Eloisechou1/OMOOC2py

**Comment by zengyumi** [comment]
@OpenMindClub/py2dama 
https://github.com/zengyumi/OMOOC2py

**Comment by sunoonlee** [comment]
@OpenMindClub/py2dama 
https://github.com/sunoonlee/OMOOC2py

**Comment by bingosummer** [comment]
@OpenMindClub/py2dama 
https://github.com/bingosummer/OMOOC2py

**Comment by OctoberEmma** [comment]
@OpenMindClub/py2dama 
https://github.com/OctoberEmma/OMOOC2py

**Comment by happylumia** [comment]
@OpenMindClub/py2dama 
https://github.com/happylumia/OMOOC2py

**Comment by aJiea** [comment]
@OpenMindClub/py2dama 
https://github.com/aJiea/OMOOC2py

**Comment by zengyumi** [comment]
@OpenMindClub/py2dama
https://github.com/zengyumi/OMOOC2py

**Comment by inodi** [comment]
@OpenMindClub/py2dama 
https://github.com/inodi/OMOOC2py

**Comment by picklecai** [comment]
@OpenMindClub/py2dama
https://github.com/picklecai/OMOOC2py

**Comment by wanderingdopamine** [comment]
@OpenMindClub/py2dama
https://github.com/wanderingdopamine/OMOOC2py

**Comment by OctoberEmma** [comment]
@OpenMindClub/py2dama 
https://github.com/OctoberEmma/OMOOC2py

**Comment by faketooth** [comment]
@OpenMindClub/py2dama 
https://github.com/faketooth/OMOOC2py

**Comment by joey-zq** [comment]
@OpenMindClub/py2dama 
https://github.com/zhouqian3/OMOOC2py

**Comment by CherHu** [comment]
@OpenMindClub/py2dama
https://github.com/CherHu/OMOOC2py

**Comment by ziz9** [comment]
@OpenMindClub/py2dama 
https://github.com/ziz9/OMOOC2py

**Comment by jimmy0717** [comment]
@OpenMindClub/py2dama
https://github.com/jimmy0717/OMOOC2py

**Comment by yondjune** [comment]
https://github.com/yondjune/OMOOC2py

**Comment by mac-naxin** [comment]
@OpenMindClub/py2dama 
https://github.com/mac-naxin/OMOOC2py

**Comment by LilinAndLilian** [comment]
https://github.com/LilinAndLilian/OMOOC2py

**Comment by AaronCopperfield** [comment]
@OpenMindClub/py2dama 
https://github.com/AaronCopperfield/OMOOC2py

**Comment by Iris-Di** [comment]
@OpenMindClub/py2dama 
https://github.com/Iris-Di/omooc2py.git

**Comment by veratulips** [comment]
@OpenMindClub/py2dama 
https://github.com/veratulips/OMOOC2py

**Comment by cupid668** [comment]
https://github.com/cupid668/OMOOC2py

**Comment by cupid668** [comment]
@OpenMindClub/py2dama
https://github.com/cupid668/OMOOC2py

**Comment by Langzzx** [comment]
@OpenMindClub/py2dama 
https://github.com/Langp618/OMOOC2py

**Comment by whb1990111** [comment]
@OpenMindClub/py2dama 
https://github.com/whb1990111/OMOOC2py

**Comment by ellenzhuang** [comment]
@OpenMindClub/py2dama 
https://github.com/imxdxd/OMOOC2py

**Comment by Iris-Di** [comment]
@OpenMindClub/py2dama 
https://github.com/Iris-Di/OMOOC2py

**Comment by cxiaodian** [comment]
@OpenMindClub/py2dama
https://github.com/cxiaodian/OMOOC2py

**Comment by YFantasy** [comment]
@OpenMindClub/py2dama
https://github.com/YFantasy/OMOOC2py

**Comment by lotusofblue** [comment]
@OpenMindClub/py2dama
https://github.com/lotusofblue/OMOOC2py

**Comment by LishuaiBeijing** [comment]
@OpenMindClub/py2dama
https://github.com/LishuaiBeijing/OMOOC2py

**Comment by JQ-K** [comment]
https://github.com/JQ-K/OMOOC2py

**Comment by JQ-K** [comment]
@OpenMindClub/py2dama 
https://github.com/JQ-K/OMOOC2py

**Comment by tttv** [comment]
@OpenMindClub/py2dama 
https://github.com/tttv/OMOOC2py

**Comment by AaronCopperfield** [comment]
@OpenMindClub/py2dama 
https://github.com/AaronCopperfield/OMOOC2py

**Comment by janice-lu-zeng** [comment]
@OpenMindClub/py2dama 
https://github.com/janice-lu-zeng/OMOOC2py

**Comment by luoquan19** [comment]
@OpenMindClub/py2dama 
https://github.com/luoquan19/OMOOC2py

**Comment by lyltj2010** [comment]
https://github.com/lyltj2010/OMOOC2py

**Comment by lyltj2010** [comment]
@OpenMindClub/py2dama 
https://github.com/lyltj2010/OMOOC2py

**Comment by xiangzhendong** [comment]
@OpenMindClub/py2dama 
https://github.com/xiangzhendong/OMOOC2py

**Comment by jasonycliu** [comment]
@OpenMindClub/py2dama
https://github.com/jasonycliu/OMOOC2py

**Comment by sherlockhoatszx** [comment]
@OpenMindClub/py2dama
https://github.com/sherlockhoatszx/OMOOC2py.git

**Comment by ghost** [comment]
@OpenMindClub/py2dama
https://github.com/xiaoyuer/OMOOC2py

**Comment by sherlockhoatszx** [comment]
@OpenMindClub/py2dama
https://github.com/sherlockhoatszx/OMOOC2py

**Comment by letsplay1879** [comment]
@ OpenMindClub / py2dama 
https://github.com/lk1879/OMOOC2py

**Comment by nightie** [comment]
@ OpenMindClub / py2dama
https://github.com/nightie/OMOOC2py

**Comment by wwshen** [comment]
@ OpenMindClub / py2dama
https://github.com/wwshen/OMOOC2py

**Comment by dyelaine** [comment]
@OpenMindClub/py2dama 
https://github.com/dyelaine/OMOOC2py

**Comment by liangpeili** [comment]
@OpenMindClub/py2dama 
https://github.com/liangpeili/OMOOC2py

**Comment by hongzhih** [comment]
@OpenMindClub/py2dama 
https://github.com/hongzhih/OMOOC2py

**Comment by chenyan423** [comment]
@OpenMindClub/py2dama 
https://github.com/chenyan423/OMOOC2py

**Comment by dougherty930** [comment]
@OpenMindClub/py2dama 
https://github.com/dougherty930/OMOOC2py

**Comment by dougherty930** [comment]
@OpenMindClub/py2dama 
https://github.com/dougherty930/OMOOC2py

**Comment by liznut** [comment]
@OpenMindClub/py2dama 
https://github.com/liznut/OMOOC2py

**Comment by shuliw** [comment]
@OpenMindClub/py2dama 
https://github.com/shuliw/OMOOC2py

**Comment by Inspirabbits** [comment]
@OpenMindClub/py2dama 
https://github.com/Inspirabbits/OMOOC2py

**Comment by jameszhou89** [comment]
@OpenMindClub/py2dama 
https://github.com/jameszhou89/OMOOC2py

**Comment by s32n** [comment]
@OpenMindClub/py2dama 
https://github.com/s32n/OMOOC2py

**Comment by haruhi99** [comment]
@OpenMindClub/py2dama
https://github.com/haruhi99/OMOOC2py

**Comment by lethinkrong** [comment]
@OpenMindClub/py2dama
https://github.com/lethinkrong/OMOOC2py

**Comment by zou23cn** [comment]
https://github.com/zou23cn/OMOOC2py

**Comment by simple2source** [comment]
https://github.com/orgs/OpenMindClub/teams/py2dama
https://github.com/simple2source/OMOOC2py

**Comment by simple2source** [comment]
@OpenMindClub/py2dama
https://github.com/simple2source/OMOOC2py

**Comment by rusell123** [comment]
@OpenMindClub/py2dama
https://github.com/rusell123/OMOOC2py

**Comment by soul2867** [comment]
@OpenMindClub/py2dama
https://github.com/soul2867/OMOOC2py

**Comment by letsplay1879** [comment]
@OpenMindClub/py2dama https://github.com/orgs/OpenMindClub/teams/py2dama
https://github.com/lk1879/OMOOC2py

2015-10-13 9:36 GMT+08:00 soul2867 notifications@github.com:

**Comment by andreachin** [comment]
@OpenMindClub/py2dama 
https://github.com/andreachin

**Comment by andreachin** [comment]
@andreachin

**Comment by demichen0824** [comment]
@OpenMindClub/py2dama 
https://github.com/demichen0824/OMOOC2py

**Comment by tiezipy** [comment]
@OpenMindClub/py2dama
https://github.com/tiezipy/OMOOC2py

**Comment by jinxiaochong** [comment]
@OpenMindClub/py2dama 
https://github.com/jinxiaochong/OMOOC2py

**Comment by muzakkk** [comment]
@OpenMindClub/py2dama 
https://github.com/muzakkk/OMOOC2py

**Comment by sicunchen** [comment]
@OpenMindClub/py2dama 
https://github.com/buermen/OMOOC2py

**Comment by yangshaoshun** [comment]
@OpenMindClub/py2dama 
https://github.com/yangshaoshun/OMOOC2py

**Comment by jiaoqing** [comment]
@OpenMindClub/py2dama 
https://github.com/jiaoqing/OMOOC2py

**Comment by Raffia** [comment]
@OpenMindClub/py2dama 
https://github.com/Raffia/OMOOC2py

**Comment by liangchaob** [comment]
@OpenMindClub/py2dama 
https://github.com/liangchaob/OMOOC2py

**Comment by hanbing718** [comment]
@OpenMindClub/py2dama 
https://github.com/hanbing718/OMOOC2py

**Comment by feilalala** [comment]
@OpenMindClub/py2dama 
https://github.com/feilalala/OMOOC2py

**Comment by siyuany** [comment]
@OpenMindClub/py2dama 
https://github.com/siyuany/OMOOC2py

**Comment by baicaiby** [comment]
@OpenMindClub/py2dama
https://github.com/baicaiby/OMOOC2py

**Comment by csyuking1989** [comment]
@OpenMindClub/py2dama
https://github.com/csyuking1989/OMOOC2py

**Comment by linttutu** [comment]
@OpenMindClub/py2dama 
https://github.com/linttutu/omooc.py

**Comment by mqyqlx** [comment]
https://github.com/mqyqlx/OMOOC2py

**Comment by scottming** [comment]
@OpenMindClub/py2dama 
https://github.com/scottming/OMOOC2py

**Comment by arctic-snow** [comment]
@OpenMindClub/py2dama 
https://github.com/arctic-snow/OMOOC2py

**Comment by summer724** [comment]
@OpenMindClub/py2dama 
https://github.com/summer724/OMOOC2py-1

**Comment by crazy-tea** [comment]
@OpenMindClub/py2dama
https://github.com/crazy-tea/OMOOC2py-1

**Comment by supperqiuqiu** [comment]
@OpenMindClub/py2dama
https://github.com/supperqiuqiu/OMOOC2py

**Comment by wo343096281** [comment]
@OpenMindClub/py2dama
https://github.com/wo343096281/OMOOC2py

**Comment by pennnnnnnnnn** [comment]
@OpenMindClub/py2dama 
https://github.com/snatching/OMOOC2py
