### ISSUE TITLE
1w 简易日记本系统

### ISSUE THREAD

**Issue by picklecai** [OpenMindClub/OMOOC2py#40]
代码：https://github.com/picklecai/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py
说明书：https://github.com/picklecai/OMOOC2py/blob/master/_src/om2py0w/0wex1/README.md

对这条不甚了然：

> 首先,得有一个稳定的代码记录容器: 脚本
> 以之前上传的 _src/om2py0w/
> /main.py 为例
> 如何调用之?
> 并确保每次调用返回相同的结果?

运行难道不是在py中？难道在其他网页或者啥？为什么调用会出现不同结果呢？

（很奇怪这周为什么不是开一个交作业issue？这样好乱……）

**Comment by ZoomQuiet** [comment]
并入: [[1w]学员任务 提交处 · Issue #41 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/41)
