### ISSUE TITLE
[1w]学员任务 提交处

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#41]
- 现象:
  - ![2015-10-22 10 50 23](https://cloud.githubusercontent.com/assets/22494/10655805/b9c7214e-78aa-11e5-9226-42fd3bbbdc49.png)
  - @picklecai 在 [1w 简易日记本系统](https://github.com/OpenMindClub/OMOOC2py/issues/40) 也反应:
    - `很奇怪这周为什么不是开一个交作业issue？这样好乱……`
- 分析: 大家完成了任务都希望第一时间为大家所知!
  - 毕竟,并不是所有学员都关注了其它学员仓库
  - gitbook 也必须订阅后才有提醒
- 方案:
  - 每周课程创建一个 `任务 提交处`
  - 任务开发完成后,即可提交关键信息到 Issue 中
  - 这样:
    - 谁完成的快自然排序
    - 谁完成的好,点击可知
    - 应该看哪个,统一知晓
    - 也不会破坏课程 Issue 的整体秩序
- 要求:
  - 嘦提交必要信息
  - 大家想评论,应该去学员 giitbook 或是 Issue 
  - 应该追加提醒: @OpenMindClub/py2student 
- 提交模板:

```

https://github.com/[学员名]/OMOOC2py/tree/master/_src/om2py[某]w/[合理子目录]

- 说明: https://github.com/[学员名]/OMOOC2py/tree/master/_src/om2py[某]w/[合理子目录]/README.md
- 讨论:
    + https://github.com/[学员名]/OMOOC2py/issues/[编号]
    + or
    + https://[学员名].gitbook.io/OMOOC2py/content/[合理页面]
- 感想: ...140字以上,希望大家关注/讨论的技术点,或是自个儿的体验点

```

**Comment by ZoomQuiet** [comment]
@faketooth [极简交互式日记系统开发记录 · Issue #31 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/31)

**Comment by ZoomQuiet** [comment]
@zoejane [让编程更有爱一点-给哥哥的小小日记本 · Issue #32 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/32)

**Comment by ZoomQuiet** [comment]
@shawn0lee0 [【BUG汇总】日记本 · Issue #33 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/33)

**Comment by ZoomQuiet** [comment]
@Awlter [[1wd3]还要在这提交issue啊？ · Issue #34 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/34)

**Comment by ZoomQuiet** [comment]
@beelives [简单交互日记系统开发记录 · Issue #35 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/35)

**Comment by ZoomQuiet** [comment]
@hysic [1W 任务交作业 · Issue #37 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/37)

**Comment by ZoomQuiet** [comment]
@wp-lai [[1w]小赖的交互日记系统 · Issue #38 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/38)

**Comment by ZoomQuiet** [comment]
@ivanlau [1W 交作业 · Issue #39 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/39)

**Comment by ZoomQuiet** [comment]
@picklecai [1w 简易日记本系统 · Issue #40 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/40)

**Comment by ZoomQuiet** [comment]
@hysic [1W 任务交作业 · Issue #37 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/37)

**Comment by ZoomQuiet** [comment]
@beelives [简单交互日记系统开发记录 · Issue #35 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/35)

**Comment by wzzlj** [comment]
代码仓库：https://github.com/wzzlj/OMOOC2py/tree/master/_src/om2py0w/0wex1
讨论：
- Issue：https://github.com/wzzlj/OMOOC2py/issues/3
- Gitbook：https://wzzlj.gitbooks.io/wzzljomooc2py/content/_src/om2py0w/0wex1/think.html

@OpenMindClub/py2student

**Comment by junjielizero** [comment]
代码仓库：https://github.com/junjielizero/junjielizero/blob/master/_src/om2py0w/0wex1/main.py
- 说明：https://github.com/junjielizero/junjielizero/blob/master/_src/om2py0w/0wex1/README.md
- Issue: https://github.com/junjielizero/junjielizero/issues/1

@OpenMindClub/py2student

**Comment by Cen74** [comment]
代码仓库：https://github.com/Cen74/OMOOC2py/blob/master/_src/om2py0w/0wex0/main.py
- 说明：https://github.com/Cen74/OMOOC2py/tree/master/_src/om2py0w/0wex0/101.md
- Gitbook：https://cen74.gitbooks.io/omooc2py/content/Week1/test1.html
- 感想：前几天主要在补第一周的gitbook和github的坑，程序上没有太多时间完成，目前只完成了基础第一版，后面会持续改进。不过体会到写程序真是一件愉悦的事情。可关注的地方：
  - Win下对文件write后再用read函数会造成乱码
  - Stackoverflow 上对一次输入多行的解决方案

@OpenMindClub/py2student

**Comment by bambooom** [comment]
代码仓库：https://github.com/bambooom/OMOOC2py/blob/master/_src/om2py0w/0wex1/diary.py
- 说明：https://github.com/bambooom/OMOOC2py/blob/master/_src/om2py0w/0wex1/README.md
- issue：https://github.com/bambooom/OMOOC2py/issues/3

@OpenMindClub/py2student

**Comment by JeremiahZhang** [comment]
日记交互系统 说明

[README.md](https://github.com/JeremiahZhang/OMOOC2py/blob/master/_src/om2py0w/README.md)

PS：更新 与 开发日志 都在其中

@OpenMindClub/py2student

**Comment by liangpeili** [comment]
@OpenMindClub/py2student
[代码](https://github.com/liangpeili/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py)
[README.md](https://github.com/liangpeili/OMOOC2py/tree/master/_src/om2py0w/0wex1)

**Comment by picklecai** [comment]
代码仓库：https://github.com/picklecai/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py
- 说明：https://github.com/picklecai/OMOOC2py/blob/master/_src/om2py0w/0wex1/README.md
- 疑问：  
  对这条不甚了然：  

> 首先,得有一个稳定的代码记录容器: 脚本
> 以之前上传的 _src/om2py0w/
> /main.py 为例
> 如何调用之?
> 并确保每次调用返回相同的结果?

运行难道不是在py中？难道在其他网页或者啥？为什么调用会出现不同结果呢？  

@OpenMindClub/py2student

**Comment by wong-github** [comment]
代码：https://github.com/wong-github/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py
说明：https://github.com/wong-github/OMOOC2py/blob/master/_src/om2py0w/0wex1/README.md
Gitbook：https://wong-github.gitbooks.io/omooc2py/content/_src/om2py0w/0wex1/index.html
@OpenMindClub/py2student

**Comment by yangshaoshun** [comment]
https://github.com/yangshaoshun/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py
- 说明: 晚上补上，暂只有基本功能（python main.py journal.txt）
- 讨论: 暂无
- 感想: 不知道大家是如何完成整个任务的，是按照任务卡片的顺序一点点分解和进行的吗？我编写的过程中，开始的时候把卡片按顺序看了很多遍，还是不知道如何下手。后来想起大妈提到只要《笨方法学python》前21课的内容就够了。最终，我是一边翻着《笨方法》一书，一边对着三条任务要求，一块一块把代码拼凑出来的（**习题13-习题17**）。过程很像小时候做数学题，对照着例题解法，把例题的数字换成作业中数字。完成之后，重新查看卡片，卡片的顺序变得好有道理，发现自己看懂了。最大的感概是，为什么初期我按照卡片顺序就进行不下去呢？
  （看了大家提交的代码，又发现很多我可以拼进来的代码了）

@OpenMindClub/py2student

**Comment by sunoonlee** [comment]
[0wex1] EasyNote 开发记录 issue：https://github.com/sunoonlee/OMOOC2py/issues/5
- 内含代码目录链接
- 一开始没有认真做记录，这不是好的学习习惯
- v0做得很简单，正计划着向 v1 进化，给自己挖了个比较大的坑
- 从功能需求到技术实现，如何更好地思考？
- 看了@wp-lai 的作业，被闪瞎了眼。最大的触动是**要善于利用现成模块**。

@OpenMindClub/py2student

**Comment by shawn0lee0** [comment]
- 代码：https://github.com/shawn0lee0/OMOOC2py/tree/master/_src/om2py0w/0wex1
- 说明：https://github.com/shawn0lee0/OMOOC2py/blob/master/_src/om2py0w/0wex1/readme.md
- 感想：
  - 为了让用户体验更简单，我们只能做到更复杂！
  - 学会复杂问题简单化，任务分解，各个击破，最后在组合起来，这就是函数的哲学！
  - 相关代码大部分是参考笨方法思路的，但是真正自己开始写的时候感受到莫名的心理阻力，自己容易被自己所设想的功能给吓到，而一直纠结于一些非核心功能点上；
  - 一定要善于查看官方资料，可以避免很多干扰信息，谨记。

![](http://i11.tietuku.com/68c362feb5f597c1.jpg)
@OpenMindClub/py2student

**Comment by penguinjing** [comment]
penguinjing的简单交互式日记记录程序
[程序文件及说明书](https://github.com/penguinjing/OMOOC2py/tree/master/_src/om2py0w/0wex1)
[对应的开发日志记录](https://penguinjing.gitbooks.io/omooc2py/content/draft/0wd4_1wd3Task.html)
@OpenMindClub/py2student

**Comment by simple2source** [comment]
- 代码：https://github.com/simple2source/OMOOC2py/blob/master/_src/om2py0w/0wex1/ow4.py
- gitbook：https://simple2source.gitbooks.io/ompy2/content/_src/xiao_xing_ji_shi_ben_xi_tong.html
- 说明：https://github.com/simple2source/OMOOC2py/blob/master/_src/om2py0w/README.md
  @OpenMindClub/py2student

**Comment by dyelaine** [comment]
代码：https://github.com/dyelaine/OMOOC2py/blob/master/_src/om2py1w/1wex0/week1_diary.py
gitbook：https://dyelaine.gitbooks.io/pythonme/content/_src/om2py1w/index.html
说明：https://github.com/dyelaine/OMOOC2py/blob/master/_src/om2py1w/README.md

**Comment by doreenduo43** [comment]
代码：https://github.com/doreenduo43/OMOOC2py/blob/master/_src/om2py0w/0wex1/diarybook.py
说明：https://github.com/doreenduo43/OMOOC2py/blob/master/_src/om2py0w/0wex1/README.md
Issue: https://github.com/doreenduo43/OMOOC2py/issues/2
gitbook: https://doreenduo43.gitbooks.io/omooc2py/content/_src/om2py0w/0wex1/index.html
@OpenMindClub/py2student

**Comment by cxiaodian** [comment]
代码:  https://github.com/cxiaodian/omooc2py/blob/master/_src/om2py0w/0wex1/main.py
说明:  https://github.com/cxiaodian/omooc2py/tree/master/_src/om2py0w/0wex1
gitbook: https://cxiaodian.gitbooks.io/omooc2py/content/_src/om2py0w/0wex1/index.html
@OpenMindClub/py2student

**Comment by liangchaob** [comment]
代码: https://github.com/liangchaob/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py
说明: https://github.com/liangchaob/OMOOC2py/tree/master/_src/om2py0w/0wex1
issue: https://github.com/liangchaob/OMOOC2py/issues
@OpenMindClub/py2student

**Comment by siyuany** [comment]
代码: https://github.com/siyuany/OMOOC2py/tree/master/_src/om2py0w/0wex1/main.py
说明: https://github.com/siyuany/OMOOC2py/tree/master/_src/om2py0w/0wex1
@OpenMindClub/py2student

**Comment by wwshen** [comment]
代码：https://github.com/wwshen/OMOOC2py/blob/master/_src/om2py0w/0wex1/simpleblog.py
说明：https://github.com/wwshen/OMOOC2py/blob/master/_src/om2py0w/0wex1/README.md
@OpenMindClub/py2student
内啥……我我课还没听，交完这个先听课去……

**Comment by fqlxxxxx** [comment]
代码及说明: https://github.com/fqlxxxxx/OMOOC2py/tree/master/_src/om2py0w/0wex1
感想及小结: https://fqlxxxxx.gitbooks.io/learnpython/content/ji_jian_ri_ji_ben.html

@OpenMindClub/py2student

**Comment by Acural** [comment]
不好意思  上周作业作业交迟了 
利用笨方法学Python中15 16 17课的提示，尝试用简单的语法实现了作业要求，但整个脚本略显啰嗦，还要多像其他学员学习
[代码](https://github.com/Acural/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py)
[README](https://github.com/Acural/OMOOC2py/blob/master/_src/om2py0w/0wex1/README.md)
@OpenMindClub/py2student

**Comment by jameszhou89** [comment]
其实还没写完，明天继续写
代码地址：https://github.com/jameszhou89/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py
gitbook地址：https://jameszhou89.gitbooks.io/moocpy2/content/1st%20edition.html

**Comment by xiangzhendong** [comment]
按照大妈1wd4提到的几个技术倒腾了下，远未完善，继续倒腾中...
代码地址：https://github.com/xiangzhendong/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py
gitbook地址：https://xiangzhendong.gitbooks.io/notesforpython/content/ji_jian_jiao_hu_shi_ri_ji_xi_tong.html
感想：
1、大妈给到技术和效果演示后更知道如何下手了，否则光看任务不知道从何下手
2、使用记事本记、截图记录下自己的探索过程，方便回顾、总结
3、带着思考和目标去解决问题，暂时绕开次要矛盾。例如，在编写代码过程中遇到输入中文后返回错误的情况： UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)。这时完全可能输入英文看看程序能不能得到想要的结果，再去解决这一次要矛盾。解决（层出不穷的）次要矛盾只会徒增烦恼，解决主要矛盾才能获得成就感。

**Comment by JQ-K** [comment]
代码: https://github.com/JQ-K/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py

gitbook :https://jqk.gitbooks.io/python-learning/content/1sTry/211_xiao_ri_ji_ren_wu.html

**Comment by sherlockhoatszx** [comment]
代码： https://github.com/sherlockhoatszx/OMOOC2py/_src/om2py1w/1wex0/main.py
gitbook:

**Comment by sherlockhoatszx** [comment]
code: https://github.com/sherlockhoatszx/OMOOC2py/blob/master/_src/om2py1w/1wex0/main.py
github上的总结：https://github.com/sherlockhoatszx/pythonsinging/blob/master/w1task.md
gitbook:https://sherlockhoatszx.gitbooks.io/pyjourney/content/

@OpenMindClub/py2student

**Comment by aJiea** [comment]
代码仓：https://github.com/aJiea/OMOOC2py/tree/master/_src/om2py1w
第一个程序的曲折故事（非抒情版）：https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/bday_code.html
W1课程反馈（抒情版）：https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/2015-10-18zh.html

@OpenMindClub/py2student

**Comment by lyltj2010** [comment]
代码：https://github.com/lyltj2010/OMOOC2py/blob/master/_src/om2py1w/MyDiary.py
折腾录：https://yongle.gitbooks.io/-python-/content/_src/om2py1w/%E6%8A%98%E8%85%BE%E5%BD%95.html
@OpenMindClub/py2student

**Comment by zjuguxi** [comment]
代码仓库：https://github.com/zjuguxi/python/blob/master/1week/mydiary/mydiary.py
Gitbook：https://zjuguxi.gitbooks.io/hard-way-to-python/content/1week/mydiary.html
@OpenMindClub/py2student

**Comment by tiezipy** [comment]
@OpenMindClub/py2student 

## Daily 1.0

代码仓库：https://github.com/tiezipy/OMOOC2py/blob/master/_src/om2py1w/1wex0/main.py
软件说明：https://github.com/tiezipy/OMOOC2py/tree/master/_src/om2py1w/1wex0

## Daily 1.1

代码仓库：https://github.com/tiezipy/OMOOC2py/tree/master/_src/om2py1w/1wex1/mai.py
软件说明：https://github.com/tiezipy/OMOOC2py/tree/master/_src/om2py1w/1wex1
- Daily1.0 折腾过程：  
  - 完这个任务前做过《笨办法》的练习，ex13到ex17没有认真思考，后来又去翻芝麻星再从头来过
    才有了思路，虽然代码很简单，却花了一个下午的时间才完成
  - 纠结于用sublime写过的代码在powershell 上出现乱码，搞好好长时间，也是芝麻星的一些提醒才     过了关：
    print "你好！！"  ------print  u"你好！！"
- 问题解决    
  - sublime编码出现缩进问题，解决方案是：
    View----Indentation -----Convert Indentation to Tabs 
- 不足之处：  
  - markdown 不熟练
  -  敲键速度慢
  - gitbook 无法本地操作，一直用web方式，双推还是有问题，暂时放弃
- 反思    
  - 最大的反思就是视而不见，挖的不够深
  - 代码继续改进
  - class 不用过于纠结 

### 视而不见！视而不见！视而不见！重要的事情说三遍 ！

**Comment by joey-zq** [comment]
代码：https://github.com/zhouqian3/OMOOC2py/blob/master/_src/om2py1w/dairy.py
Gitbook：https://zhouqian.gitbooks.io/omooc2py/content/0MOOC/Week1.html

**Comment by Jessicamiejiu** [comment]
代码：https://github.com/Jessicamiejiu/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py
说明：https://github.com/Jessicamiejiu/OMOOC2py/blob/master/_src/om2py0w/README.md

**Comment by leonpak** [comment]
代码:https://github.com/leonpak/OMOOC2py/tree/master/_src/om2py1w/1wex0/main.py
说明：https://github.com/leonpak/OMOOC2py/tree/master/_src/om2py1w/1wex0/README.md
