### ISSUE TITLE
[0w] 各地 C2T2 纪要及录音、讲演材料

### ISSUE THREAD

**Issue by sunnyhuang42** [OpenMindClub/OMOOC2py#42]
0w 各地CT2T纪要及录音、讲演材料，欢迎观摩;-)

[[0wd6]C2T2 北京](https://github.com/OpenMindClub/OMOOC2py/issues/16#issuecomment-150100491)
- 亮点：GitHub 生态的理解

[[0wd6]C2T2 深圳](https://github.com/OpenMindClub/OMOOC2py/issues/14#issuecomment-149081368)
- 亮点：0w 任务效果演示 —— Github push 视频演示

[[1wd0]C2T2 珠海](https://github.com/OpenMindClub/OMOOC2py/issues/9#issue-111523506)
- 亮点：win 上SSH 概念/工具、git 仓库形态/配置

**Comment by sunnyhuang42** [comment]
@OpenMindClub/py2student

**Comment by ZoomQuiet** [comment]
归档
