### ISSUE TITLE
[1wd6]北京 C2T2 报名

### ISSUE THREAD

**Issue by sunnyhuang42** [OpenMindClub/OMOOC2py#43]
- 时间: 周六 14:30~17:00
- 地点: 
  北京 海淀区 五道口地铁站附近，根据报名人数选择合适场地，周六中午 12:00 通知具体地址
  - 若报名人数>15人，在 [五边公社咖啡厅](http://www.dianping.com/search/keyword/2/0_%E4%BA%94%E8%BE%B9%E5%85%AC%E7%A4%BE%E5%92%96%E5%95%A1%E5%8E%85)， 每人消费一杯饮品即可
  - 若报名人数≤15人，在 中关村东路18号 财智国际大厦 B 座 601  
- 报名: 回复说明以下关键信息
  - github 帐号
  - 电脑操作系统
  - 当前课程 top3 问题, 参考: [[0w]当周课程 技术问题讨论](https://github.com/OpenMindClub/OMOOC2py/issues/3) 描述格式
- 截止: 周六 11:29 前有效
- _提醒:_ 尽可能带上电脑,以便现场明确技术问题的细节 ;-)

@OpenMindClub/py2student 

参考:
-  [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)
- [[0w] 各地 C2T2 纪要及录音、讲演材料](https://github.com/OpenMindClub/OMOOC2py/issues/42)

**Comment by hongzhih** [comment]
报名：

hongzhih
win7
各种问题，难以备述。

黄鸿志

在 2015年10月22日 下午2:50，ishanshan notifications@github.com写道：

**Comment by ZoomQuiet** [comment]
2015-10-22 15:00 GMT+08:00 hongzhih notifications@github.com:

> 报名：
> 
> hongzhih
> win7
> 各种问题，难以备述。
- 绝然这是误解!
- 一个无法描述的问题,不存在! 因为无法证伪,也无法解决
- 一批无法描述的问题,不存在! 因为根本就没有进入我们的智力
- 尝试一下,从问题的 3+1 方面描述?!

**Comment by liangpeili** [comment]
github 帐号:liangpeili
电脑操作系统:Windows 10+Ubuntu14.04
当前课程 top3 问题：
本周暂无问题(也可能是没发现)，或许讨论下用Jekyll+Github pages搭建博客？

**Comment by liangchaob** [comment]
github 帐号:liangchaob
电脑操作系统:OSX+Ubuntu14.04
当前课程 top3 问题：求大妈的日常开发环境具体配置，只要关键词即可
@ZoomQuiet

**Comment by yangshaoshun** [comment]
- github 帐号：yangshaoshun
- 电脑操作系统：Mac OS X
- 当前课程问题
  - 与大家交流完成1w作业的过程
  - 大家都是如何使用任务卡片的

**Comment by xiangshan** [comment]
- github帐号：xiangshan
- 电脑操作系统：Mac OS X
- 当前课程问题
  - 与大家交流学习追赶进度 
  - 完成1w的作业

**Comment by chenyan423** [comment]
- github帐号：chenyan423
- 电脑操作系统：Mac OS X
- 当前课程问题
  - 与大家交流1w作业完成过程

**Comment by muzakkk** [comment]
github 帐号：muzakkk
电脑操作系统：windows 8
当前课程问题：1w任务理解 + 如何更好的使用芝麻星卡片

**Comment by hysic** [comment]
github 帐号: hysic
电脑操作系统: Mac OS X
当前课程问题:
- 前7周任务的关系
- 交流 w1 任务的实现方法

**Comment by dyelaine** [comment]
github 帐号：dyelaine
电脑操作系统：windows 7
当前课程问题：1w作业如何优化

**Comment by liznut** [comment]
github账号：liznut
电脑操作系统：Windows
当前课程问题：一些python 命令的意思，Windows下的中文输入

**Comment by sunnyhuang42** [comment]
报名人数10人，今天下午 C2T2 地点确认，在
中关村东路18号 财智国际大厦 B 座 601

@liznut @dyelaine @liangpeili  @liangchaob @yangshaoshun  @hongzhih @hysic @muzakkk @chenyan423 @xiangshan 

和上周地址一样，下午两点半见啦！

**Comment by chientung91** [comment]
# 1wd6 帝都 C2T2 纪要

## 活动召集

共10位小伙伴参加线下活动
- [召集令](https://github.com/OpenMindClub/OMOOC2py/issues/43)

## 录音

本期没有特殊的讲解，由教练先强调一些规范，随后自由讨论居多，故没有录音

## 活动流程
- `5min`个人介绍
  - 个人信息
  - 学习的简单心得
- `5min`1w学员闪耀榜
  - 重点推荐了 Alan Lai 同学值得大家借鉴的优点
- `~END`学员内部交流+教练现场巡山
  - 重点安利小步快速迭代原型进行开发的方法

## 活动总结
- 多多面基进步很大
- 多思考问题，充分使用google

## 常见问题
- 看不懂大妈的文字

**Comment by liangpeili** [comment]
https://liangpeili.gitbooks.io/omooc2py/content/week1/week1-C2T2.html

竟然没有评论的地方,,,好忧桑!----闪闪

**Comment by hysic** [comment]
[[1wd6]北京 C2T2 个人总结](https://hysic.gitbooks.io/hysic-s-python-journey/content/Lect/C2T2_20151024.html)

mark! 可以作为纪要的优秀案例了!----闪闪
