### ISSUE TITLE
[2wd0] 杭州 C2T2 报名

### ISSUE THREAD

**Issue by wwulfric** [OpenMindClub/OMOOC2py#45]
- 时间: 周日下午3点-5点
- 地点: 杭州西湖区万塘路 alface 咖啡厅，当天早上在 2OMOOCpy-长三角 群里发具体的通知
- 报名: 回复说明以下关键信息
  - github 账号
  - 操作系统
  - 当前课程 top3 问题, 参考: [[0w]当周课程 技术问题讨论](https://github.com/OpenMindClub/OMOOC2py/issues/3) 描述格式
- 截止: 周日中午12点
- 提醒: 尽可能带上电脑,以便现场明确技术问题的细节 ;-)

时间和地点非常有困难的请提出，可议

@OpenMindClub/py2student

**Comment by shawn0lee0** [comment]
- github 账号
  - shawn0lee0
- 操作系统
  - win 7 32
- 当前课程 top3 问题
  - 函数调用的一些坑
  - 查bug大法
  - 需求拆解思维

**Comment by wp-lai** [comment]
- github 账号
  - [wp-lai](https://github.com/wp-lai)
- 操作系统
  - OS X
-  问题
  - 代码调试的技巧和习惯
  - 找工作的历程

**Comment by tedxt** [comment]
- github 账号 
  - @tedxt
- 操作系统
  - OS X
- 问题
  - 拉下进度两周了, 还问不出问题, 这次过来主要以面基为主 Orz

**Comment by wp-lai** [comment]
说说今天的收获
- 学到了使用[proxychains-ng](http://wp-lai.github.io/2015/10/25/proxychains4/index.html)，可以通过代理加速`git push`
- 了解到了iPython notebook，可以将`Markdown`写作和代码运行结合起来
- 认识了杭州区的小伙伴们

**Comment by tedxt** [comment]
# 录音

链接: [2wd0C2T2Hangzhou.MP3](https://www.fangcloud.com/share/c0453bf794c861235a7dc43a71) 密码: openmind
存储空间使用 @wwulfric 公司提供的服务 :-P

**Comment by shawn0lee0** [comment]
[杭州面基小结](https://shawn0lee0.gitbooks.io/python-omooc2py/content/0MOOC/hz_c2t2_mj.html)

**Comment by wwulfric** [comment]
@tedxt 没想到还无形中做了个广告哈哈～建议尝试我们的 sync 客户端哈哈，sync 客户端的后台逻辑是我写的，有bug报给我～

**Comment by wwulfric** [comment]
## 杭州 1026 C2T2 活动纪要

这是杭州第一次组织活动，共 4 人参加活动，包括 @shawn0lee0  @wp-lai  @tedxt 

经验不足各种忘了做事情……

### 照片：

![img_0912](https://cloud.githubusercontent.com/assets/8315997/10735245/02ab9c88-7c42-11e5-843c-dc0d20bb327d.JPG)
![d70e2ad3-d6f0-47cf-b743-5aaf95eca62a](https://cloud.githubusercontent.com/assets/8315997/10735243/0299111c-7c42-11e5-8c59-d753313e1001.jpg)
![img_0914](https://cloud.githubusercontent.com/assets/8315997/10735246/02b21f7c-7c42-11e5-98e6-6c6c810f2934.JPG)
![img_0915](https://cloud.githubusercontent.com/assets/8315997/10735244/02a42908-7c42-11e5-9ca2-336bf8618efb.JPG)

### 录音：

自由讨论，提出问题，设想解决方案，现场 google 

链接: [2wd0C2T2Hangzhou.MP3](https://www.fangcloud.com/share/c0453bf794c861235a7dc43a71) 密码: openmind 感谢 @tedxt 

### 流程：

不太对，直接上来就聊……各种遇到的问题，当前的进度等2小时，快结束的时候互相介绍了一下

### 主要问题：
- ipython notebook 的使用
- git 和 github 的一些操作使用
- win 和 Mac 系统中文编码问题
- gitbook 的使用

### 活动总结：

地点大家都挺接受的，离大家都很久，以后也基本是这里了。
先消费吧，不然服务员姐姐不高兴 -_-!
