### ISSUE TITLE
[2wd0] 深圳 C2T2 报名

### ISSUE THREAD

**Issue by csufuyi** [OpenMindClub/OMOOC2py#46]
时间: 10.25 周日 14:30~17:00
地点: 深圳 南山区 科技园附近（默认）. 根据报名人数及分布地点选择合适场地，周日中午 11:00 通知具体地址

报名: 回复说明以下关键信息

github 帐号
期望集合地点：南山，福田，罗湖，龙华
电脑操作系统
当前课程 top3 问题, 参考: [0w]当周课程 技术问题讨论 描述格式
截止: 周日 11:29 前有效

提醒: 尽可能带上电脑,以便现场明确技术问题的细节 ;-)

**Comment by bambooom** [comment]
github 帐号：@bambooom
期望集合地点：优先福田，不过地铁可到达也接受
电脑操作系统：win7
当前课程 top3 问题：
1. ·`class` `__init__` 不太理解
2. 怎么把代码写得好看
3. 2w任务交流

**Comment by sherlockhoatszx** [comment]
github 帐号：@sherlockhoatszx
期望集合地点：福田、南山均可
电脑操作系统：mac
当前课程 top3 问题：官方文档查询技巧请教（如何判断问题，英文关键字如何选择）w1课程代码请教，w2作业的流程思路讨论

**Comment by ivanlau** [comment]
账号：ivanlau
期待地点：科技园或者车公庙
当前系统：win+linux
问题我再想想

**Comment by Jessicamiejiu** [comment]
github账号: Jessicamiejiu
期待地点：福田，龙华
系统:mac

**Comment by siyuany** [comment]
github账号: siyuany
期待地点：福田、罗湖
操作系统：mac
问题，先想想

**Comment by rayxiehui** [comment]
github:rayxiehui
期待地点：均可
操作系统：mac
问题：好多呀，都是基础问题。

**Comment by crazy-tea** [comment]
github 帐号：@crazy-tea
期望集合地点：南山/福田
电脑操作系统：win10
问题：待增补

**Comment by RichardSZ** [comment]
github 帐号：@RichardSZ
期望集合地点：南山/福田，地铁可到达也接受
 电脑操作系统：win7
当前课程 top3 问题：待增补

**Comment by xiangzhendong** [comment]
github账号：@xiangzhendong
期望集合地点：南山
电脑操作系统：OS X 10.10.5
问题：待增补

**Comment by William-Shen** [comment]
github 帐号:William-Shen
期望集合地点：福田或者罗湖
电脑操作系统：Win
当前课程 top3 问题:Git路径

**Comment by csufuyi** [comment]
- 时间： 2015 年 10月25日（周日） 14:30-17:00
- 地点： [深圳华侨城如盒艺术空间](http://t.dianping.com/deal/8199297)

**Comment by joey-zq** [comment]
github账号: zhouqian3
系统:mac
问题：进度太慢了容我赶一赶

**Comment by balsamleo** [comment]
github帐号：balsamleo
系统：ubuntu
问题：暂无

**Comment by zjuguxi** [comment]
github帐号：zjuguxi
电脑操作系统：Mac

**Comment by csufuyi** [comment]
# 2wd0 深圳 C2T2 纪要

## 活动召集

共13位小伙伴参加线下活动（包括一位一期小伙伴过来交流），7位参加了[0wd6](https://github.com/OpenMindClub/OMOOC2py/issues/14)的活动

@William-Shen 
@zhouqian3  
@xiangzhendong
@rayxiehui
@ivanlau
@demonmax
@zjuguxi

@RichardSZ 
@crazy-tea 
@Jessicamiejiu 
@sherlockhoatszx 
@bambooom 

@balsamleo（一期学员闻讯而来）
@siyuany（报名后未参加）

![场地](http://7xjfyz.com1.z0.glb.clouddn.com/C2T2_2wd0.jpg)
照片汇总:
http://7xjfyz.com1.z0.glb.clouddn.com/C2T2_2wd0.jpg
http://7xjfyz.com1.z0.glb.clouddn.com/C2T2_2wd0_1.jpg
http://7xjfyz.com1.z0.glb.clouddn.com/C2T2_2wd0_2.jpg
http://7xjfyz.com1.z0.glb.clouddn.com/C2T2_2wd0_3.jpg
http://7xjfyz.com1.z0.glb.clouddn.com/C2T2_2wd0_4.jpg
- [召集令](https://github.com/OpenMindClub/OMOOC2py/issues/46)

## 录音

本期没有特殊的讲解，由教练掌握进度，汇总问题，快帮慢，分三拨（0w,1w,2w）自由讨论居多，故没有录音

## 活动流程
- `30min`个人介绍和当前进展，问题
  - 个人信息
  - 学习进展，问题概述
- `2hour`学员内部交流+教练现场巡山
  这次主要以仓库fork, gitbook配置，disqus配置，42行代码，cli程序，tk使用作为任务节点同步进度，对茫然的同学明确前进的方向.

## 主要问题
- 芝麻星访问
- disqus坑
- 双推(主要是对git操作理解不深入)
- 如何理解类
- cli文件流程的处理
- github 命令行操作
- python indentation

## 经验小结
- 可以选择网络环境更好的场地
- 场地缺少小白板
- 场地是周五到周日，打电话预订低消50.直接去低消30

**Comment by sherlockhoatszx** [comment]
今次面基选在了文艺清新的华侨城，见到了耐心又认真的free教练，以及许多小伙伴，

个人化的收获体验：
1. 今天free给我们讲了下学习方法，深以为然啊。感受是这样的：你以为授课流程是先讲语法，再做个小例子1＋1=2，然后布置作业1+1＋1=？no no no，那样是x青鸟的培训方式，是木有用的，是会被群嘲的。开智班是有理想有思想有逼哥的好吗。所以在这里的方式是首先教大家如何分解问题，尝试，验证，如何正确的提问，解决问题，直到输出经验。养成良好的思维习惯，在实践中体会python.不是说要看完了笨办法学编程才能开始编程。
2. 写程序的时候，最好先理清楚模块和逻辑图。
3. 双推的逻辑，本地－中转－github,gitbook，以及wehook的实现。

https://github.com/sherlockhoatszx/pythonsinging/blob/master/about_c2t2_szx.md

**Comment by bambooom** [comment]
上次很谢谢 @csufuyi free教练给我初步讲解了一下class，但是还是比较朦胧的
这两天就努力整理了点笔记 https://github.com/bambooom/OMOOC2py/issues/6
但是对于inheritance还是似懂非懂，还有有关metaclass之类的就.....求各种指教~
嗯，持续学习~边用边学~:laughing:
