### ISSUE TITLE
[1wd6]上海 C2T2 报名

### ISSUE THREAD

**Issue by cp4** [OpenMindClub/OMOOC2py#47]
- 时间: 周六 14:30~17:00
- 地点:  
  暂定 [Mlily梦百合咖啡厅](http://map.baidu.com/detail?qt=ninf&uid=8b1a15e214544eafcf06a40c&wd=mlily%E6%A2%A6%E7%99%BE%E5%90%88%E5%92%96%E5%95%A1%E5%8E%85&b=%2813517218.97,3633500.75;13534130.97,3644812.75%29&query=&qid=&page_num=&detail=cater&from=map&ugc_ver=1)，
  卢湾区 西藏南路1592号(西藏南路中山南一路交叉口，近第九人民医院)
- 报名: 回复说明以下关键信息
  - github 帐号
  - 电脑操作系统
  - 当前课程 top3 问题, 参考: [[0w]当周课程 技术问题讨论](https://github.com/OpenMindClub/OMOOC2py/issues/3) 描述格式
- 截止: 周六 11:29 前有效
- _提醒:_ 尽可能带上电脑,以便现场明确技术问题的细节 ;-)

@OpenMindClub/py2student 

参考:
-  [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)
- [[0w] 各地 C2T2 纪要及录音、讲演材料](https://github.com/OpenMindClub/OMOOC2py/issues/42)

**Comment by haruhi99** [comment]
•github账号:haruhi99
 •电脑操作系统:mac
 •当前课程TOP3问题：
     1.推送和双推相关的基础问题。
     2.mac系统下包括mac自带命令行的一些坑。。
     3.零基础如何尽快破壁，自主解决问题。

**Comment by cupid668** [comment]
•github账号:cupid668
•电脑操作系统:Win
•当前课程TOP3问题：
1.零基础尽快破壁需要打实的基础及顺序。
2.Win系统下python具体的环境配置。
3.推送和双推相关的基础问题。

**Comment by ZoomQuiet** [comment]
2015-10-23 0:57 GMT+08:00 Vito notifications@github.com:

> •github账号:cupid668
> •电脑操作系统:Win
> •当前课程TOP3问题：
> 1.零基础尽快破壁需要打实的基础及顺序。
- LPTHW 前21课

> 2.Win系统下python具体的环境配置。
- 如官方文档

> 3.推送和双推相关的基础问题。
- 如 git.md
  https://github.com/ZoomQuiet/OMOOC2py/blob/master/0MOOC/git.md

> —
> Reply to this email directly or view it on GitHub.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by Sherrywangintj** [comment]
github：SherryWangInTJ
OS:win
当前课程 top3 问题:
1.推送和双推相关的基础问题

**Comment by Lcking** [comment]
- github账号：Lcking
- 电脑操作系统：win10
- 当前课程Top3问题：
  - 1.双推是没问题了，但是双推使用的编辑器却总是非常的卡顿，sublime。
  - 2.对python的一些函数和类的知识很混乱。
  - 3.开发小日记的这个需求理不清。

**Comment by jameszhou89** [comment]
github 帐号: jameszhou89
电脑操作系统: Mac

**Comment by cupid668** [comment]
•github账号:cupid668
•电脑操作系统：Win10

**Comment by CherHu** [comment]
- github账号：Cherhu
- 电脑操作系统：mac
- Top3问题：
  - github和gitbook如何互推的原理很迷茫，以至于互推成功也是偶然的感觉。
  - disqus is unable to load.

**Comment by bingosummer** [comment]
github账号:bingosummer
•电脑操作系统:Linux
•当前课程TOP3问题：
1.gitbook相关的基础问题。

**Comment by jameszhou89** [comment]
发了下自己的总结
https://jameszhou89.gitbooks.io/moocpy2/content/offline_c2t2.html

**Comment by jameszhou89** [comment]
发了下自己的总结
https://jameszhou89.gitbooks.io/moocpy2/content/offline_c2t2.html

**Comment by jameszhou89** [comment]
发了下自己的总结
https://jameszhou89.gitbooks.io/moocpy2/content/offline_c2t2.html

**Comment by cp4** [comment]
## 交流现场纪要

### 流程

#### 自我介绍
-   着重介绍自己的创作目标，或有助于发现潜在合作者，交流创意

#### 解答共性问题
-  版本控制系统的意义
- git 和 github
- 练习命令行认识功能背后的逻辑

#### 个别解答/自由交流
-   当场练习 git 系列操作
-   对双推的逻辑进行讲解
  
  对git 操作进行逻辑分解：
  -   针对 github 仓库进行 clone，修改，push 循环
  -   针对 gitbook 仓库进行 clone， 修改， push 循环
  -   在同一个仓库中使用 git remote add <name> <url> 命令，通过 push
    两次完成“双推”
  -   修改 .git/config 完成双推。
-   对 if “__name__” == “__main__”语句含义的解答
  -   现场演示 print “my name is %s” %__name__ 文件在被直接调用和在 import
    中被调用运行结果的区别。
  -   举例解释，为什么 import 时可能不需要模块被直接执行。
-   作业问题
  -  怎样构造一个循环

### 资料

#### 讲解录音及现场照片

链接：http://pan.baidu.com/s/1fYkRc 密码：xkto
