### ISSUE TITLE
[2w]学员任务 提交处

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#49]
- 引发: [[1w]学员任务 提交处 · Issue #41 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/41)
- 要求:
  - 嘦提交必要信息
  - 大家想评论,应该去学员 giitbook 或是 Issue 
  - 应该追加提醒: @OpenMindClub/py2student 
- 提交模板:

@OpenMindClub/py2student 

```

https://github.com/[学员名]/OMOOC2py/tree/master/_src/om2py[某]w/[合理子目录]

- 说明: https://github.com/[学员名]/OMOOC2py/tree/master/_src/om2py[某]w/[合理子目录]/README.md
- 讨论:
    + https://github.com/[学员名]/OMOOC2py/issues/[编号]
    + or
    + https://[学员名].gitbook.io/OMOOC2py/content/[合理页面]
- 感想: ...140字以上,希望大家关注/讨论的技术点,或是自个儿的体验点

```

**Comment by wzzlj** [comment]
- 仓库地址：https://github.com/wzzlj/OMOOC2py/tree/master/_src/om2py2w/2wex0
- 讨论：
  - [Issues](https://github.com/wzzlj/OMOOC2py/issues/4) ←【推荐】
  - [Gitbook](https://wzzlj.gitbooks.io/wzzljomooc2py/content/_src/om2py2w/2wex0/mydaily_think.html)
- 感想：
  - 怎么形容这一次的任务对我来说的难度，就是一开始根本无法进入「心流」状态。关于 Tkinter 的认识完全为0好嘛，俺英文水平一般，看英文教程跟看天书似得，看一会儿就走神，看一会儿就走神。
  - 于是先曲线救国，去找了一些中文教程，先摸索下大概的框架，入入门。把教程里面的例子用「笨方法」都敲一下，试着去理解每个命令、每个组件的作用，看一下出来的效果。
  - 然后发现中文教程确实有点坑，有的例子试不出来，有的理解不能。再回头去看 http://effbot.org/tkinterbook/ 下的教程，突然发现理解起来变轻松了，能看懂大概了，不走神了！可能是看中文教程先熟悉了大概的框架有关。
  - 最折磨人的是 IDLE 中不能用中文输入法的问题，怎么都找不出问题来。后来睡了一觉起来似乎歪打正着地解决了。详情请看 → https://github.com/OpenMindClub/OMOOC2py/issues/54
  - （暂时）解决了中文输入法的问题之后，一切就变得顺利了，突然就能进入「心流」状态了呢。当然坑还是很多的，一个一个照着教程填。
  - 最后整出来的「桌面版简单日记」虽然不太美观，但是基本功能都有了，自己瞧着好开心啊，毕竟是自己第一个有 GUI 的程序啊。
  - 看教程也发现有的程序员喜欢用 class，有的不喜欢用。虽然我的程序里用了 class，但是理解起来，挺绕的。可能不用 class 的情况下更直观和便于理解一点。不知道大家怎么认为。
  - 最后，程序改进的地方还挺多的，一是让它实现更多功能，二是还需要把交互做好，三就是更加美观一些吧。
  - 人生苦短，Python 当歌！就酱！

---

## 更新简单日记本2.0
- 仓库：https://github.com/wzzlj/OMOOC2py/tree/master/_src/om2py2w/2wex1
- 说明：见 README
- 讨论：~~还没写~~
- 感想：
  - 在不断填坑的过程中，对 mac 的环境越来越熟悉了。
  - 2.0更贴近大妈演示的版本了。
  - 这次完全用 vim 码的代码，编辑器之神，感天动地~ T_T。顺便对「神之编辑器」 emacs 的学习曲线表示2333333  
    ![](http://blog-resource.qiniudn.com/vim-emacs.png)
  - 插入图片是个坑儿~用 PIL 模块导入图片必须要与 mainloop 放在同一级上。在函数里要设定全局变量导入。
  - 用 Grid 进行布局，比 pack 更容易控制。
  - 界面：  
    ![](http://7xn3v1.com1.z0.glb.clouddn.com/15-10-28/81884108.jpg)

@OpenMindClub/py2dama

**Comment by faketooth** [comment]
@OpenMindClub/py2student 
https://github.com/faketooth/OMOOC2py/tree/master/_src/om2py2w/2wex0
- 说明：https://github.com/faketooth/OMOOC2py/blob/master/_src/om2py2w/2wex0/README.md
- gitbook迭代记录：https://faketooth.gitbooks.io/omooc2py/content/0MOOC/2w/SprintLog.html
- 感想：
  - Tkinter虽然表示跨平台，但感觉还是有不一直的地方。例如鼠标消息，看到不少教程中`<Button-3>`作为鼠标右键，但实际在`OSX`上测试那是鼠标中键，右键为`<Button-2>`。另外，`OSX`上没有子菜单的`Toplevel Menu`是不显示的，这点与`Windows`不一致。
  - 遇到两处官方的坑：[A Simple Hello World Program 示例代码](https://faketooth.gitbooks.io/omooc2py/content/0MOOC/2w/ASimpleHelloWorldProgram.html)和[Tk 版本问题导致OSX上`Tkinter`不支持输入中文](https://faketooth.gitbooks.io/omooc2py/content/0MOOC/2w/SprintLog.html#chinese-support)
  - 界面控件布局没有练习到，只是简单调用`pack()`方法来停靠控件
  - 边实践边学习的过程中会遇到很多问题，既要保持专注又不能遗漏任何问题，所以要及时开ISSUE跟踪
  - 感觉这周涉及到需要自学的东西有点多，如果不是周末没被喊到公司加班，还真不一定能及时搞定
  - 界面与后台功能分离绝对是有必要的，对日后代码复用、重构都有极大的好处 
  - 没有给文本框添加滚动条控件，因为从搜到的教程来看，因为布局问题需要整份代码，还是等有时间再重构吧

**Comment by bambooom** [comment]
- 仓库：https://github.com/bambooom/OMOOC2py/blob/master/_src/om2py2w/2wex0/diarygui.py
- 说明：https://github.com/bambooom/OMOOC2py/blob/master/_src/om2py2w/2wex0/README.md
- issue：https://github.com/bambooom/OMOOC2py/issues/5 （issue没怎么写清楚，需要理清思路的最好参考前两位同学）
- 感想：
  - 官方文档也有不太清楚的地方，这次我主要都是看http://effbot.org/tkinterbook/ 的教程看懂Tkinter都有些什么功能。
  - 针对于GUI，觉得上图最重要，什么参数/组件对应什么功能设置看个图就能明白大半，然后尝试一下更改设置，就能具象理解是什么意思。
  - 看懂别人的代码在干嘛，也是一种很好的学习。深切感谢 @wzzlj @faketooth 两位同学的代码，让我学习到不少细节。特别关于class的理解和使用，准备再仔细学习一下。

@OpenMindClub/py2student

**Comment by dyelaine** [comment]
@OpenMindClub/py2student 
仓库：https://github.com/dyelaine/OMOOC2py/blob/master/_src/om2py2w/2wex0/week2.py
说明：https://github.com/dyelaine/OMOOC2py/blob/master/_src/om2py2w/README.md
gitbook：https://dyelaine.gitbooks.io/pythonme/content/_src/om2py2w/index.html
感想：
针对GUI编程，个人感受是首先设计下界面，明确界面上需要用到哪些组件，再有针对性的学习如何调用比较有效。当然，完成作业之余还是要全面了解下GUI的相关组件哒。
另外，看到前面几位同学的程序都使用到了class，代码看起来更加整洁，可移植性和拓展性也会更好吧，接下来找时间仔细研究一下。我自己写的的代码虽然实现了私人日记的基本要求，但是代码结构并不利于日后改进和移植呢。
继续加油咯O(∩_∩)O~

**Comment by Awlter** [comment]
@OpenMindClub/py2student 
- 传送门(loading)：https://github.com/Awlter/OMOOC2py/tree/master/_src/om2py2w/2wex2
- 心情
  - 当Tkinter 遇上 Class，会涌现出很多self.......................
  - 功能不难，静静地看文档，相信自己

**Comment by yangshaoshun** [comment]
https://github.com/yangshaoshun/OMOOC2py/tree/master/_src/om2py2w/2wex0
- 说明: https://github.com/yangshaoshun/OMOOC2py/blob/master/_src/om2py2w/README.md
- 讨论:
  - 待更新
- 感想: 第二周使用卡片的方式
  - 卡片作为出发点，了解接下来可能遇到的问题，切入点：布局和后台
  - 卡片背面的参考链接，作为学习的起点，最适合我这个新手的教程 [An Introduction To Tkinter](http://effbot.org/tkinterbook/tkinter-index.htm)
  - 完成代码之后，对照卡片的要求对代码测试和查缺补漏，进一步改进代码。初始为了完成任务本身，比较仓促，可以有很多修改的地方。比如说如何复用1w的代码，比如说大妈的演示中有颜色提示...

> 卡片只作为一个指导，是一个个路标。至于具体的历程，还得通过其他入门教程去学习，去摸索。

@OpenMindClub/py2student

**Comment by picklecai** [comment]
代码：https://github.com/picklecai/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py

说明：https://github.com/picklecai/OMOOC2py/tree/master/_src/om2py2w/2wex0

@OpenMindClub/py2student

（先提交，再修改不合理处。）

**Comment by junjielizero** [comment]
代码：(https://github.com/junjielizero/OMOOC2py/tree/master/_src/om2py2w/2wex0/demo.py)

说明：(https://github.com/junjielizero/OMOOC2py/tree/master/_src/om2py2w/2wex0)

讨论：(https://github.com/junjielizero/OMOOC2py/issues/1)

感谢 @bambooom ，看了你的代码某些难题变得清晰了

感想：代码可以再精简和符合pythonic，近一周工作时间较多，较少投入，之后日子再补
@OpenMindClub/py2student

**Comment by suluren** [comment]
@OpenMindClub/py2student 
- 代码: https://github.com/suluren/OMOOC2py/blob/master/_src/om2py2w/2wex1/main.py
- 笔记和讨论: https://suluren.gitbooks.io/omooc2py/content/1sTry/2wNote.html
- 笔记都是废话, 八成内心戏,,,
  - 没有具体写实现功能的过程, 有点鸡汤....
  - 有需要扫扫黑体字,,,,
- 建议: 目标清晰, 摸清例子, 减少同时考虑的事,,, 
  - 和熟悉的笨方法联系起来...
- 你会发现真是大半都是内心戏......

**Comment by liangpeili** [comment]
@OpenMindClub/py2student

代码：https://liangpeili.gitbooks.io/omooc2py/content/week2/code.html
说明：https://liangpeili.gitbooks.io/omooc2py/content/week2/code-Readme.html

对class还不太熟，就没有使用class。这个代码基本实现了大妈在课堂上演示的功能，后期随着学习的深入及知识的增加还会慢慢优化(用class的形式来写，控件Frame及Scrollbar的使用等)。

**Comment by janice-lu-zeng** [comment]
@OpenMindClub/py2student
代码: https://github.com/janice-lu-zeng/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py
说明: https://github.com/janice-lu-zeng/OMOOC2py/blob/master/_src/om2py2w/2wex0/README.md
记录：https://janice-lu-zeng.gitbooks.io/omooc2py-the-book/content/0MOOC/GUI.html

**Comment by rayxiehui** [comment]
代码： https://github.com/rayxiehui/OMOOC2py/tree/master/_src/om2py2w/2wex0
说明 ：https://github.com/rayxiehui/OMOOC2py/blob/master/_src/om2py2w/2wex0/README.md
@OpenMindClub/py2student

**Comment by jasonycliu** [comment]
@OpenMindClub/py2student 
代码: https://github.com/jasonycliu/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py
说明: https://github.com/jasonycliu/OMOOC2py/blob/master/_src/om2py2w/README.md
记录: https://jasonycliu.gitbooks.io/omooc2py/content/1sTry/gui.html
- 感想: 没有写过GUI的程序,对事件的绑定不太熟悉,还有就是大妈在演示的时候留下了不少的埂.完成看似简单的功能耗费了太多的时间,主要是没有集中精力解决主要问题.代码还有很多需要改进的地方,没有多余的时间研究ttk.这周不想再错过大妈的直播,一旦错过真的会浪费很多时间.

**Comment by shawn0lee0** [comment]
仓库：https://github.com/shawn0lee0/OMOOC2py/tree/master/_src/om2py2w/2wex0
说明：https://github.com/shawn0lee0/OMOOC2py/blob/master/_src/om2py2w/2wex0/readme.md
讨论：https://shawn0lee0.gitbooks.io/python-omooc2py/content/_src/om2py2w/2wex0/readme.html

### 感想
- Python思想：不论函数命名、类、变量的定义力求简单明了
- Tk.pack布局太坑了~反人类的设计，我想要的是所见即所得的GUI，目前了解的有
  - [PyQT](https://wiki.python.org/moin/PyQt)
  - [kivy](http://kivy.org/)
    -  [github_kivy](https://github.com/kivy/kivy)
- 未完待续

效果图：
![](http://i11.tietuku.com/451ba10adb620be6.jpg)

**Comment by wp-lai** [comment]
- [代码](https://github.com/wp-lai/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py)
- [说明](https://github.com/wp-lai/OMOOC2py/blob/master/_src/om2py2w/2wex0/README.md)
- [教程](https://wp-lai.gitbooks.io/learn-python/content/1sTry/tkinter.html)

**Comment by wong-github** [comment]
代码：https://github.com/wong-github/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py
说明：https://wong-github.gitbooks.io/omooc2py/content/_src/om2py2w/2wex0/index.html
@OpenMindClub/py2student

**Comment by zoejane** [comment]
@OpenMindClub/py2student
- [代码](https://github.com/zoejane/OMOOC2py/blob/master/_src/om2py2w/2wex0/diary-gui.py) [修改历史](https://github.com/zoejane/diary-gui/commits/master)
- [心得与教程](https://zoejane.gitbooks.io/omooc2py/content/1sTry/%08diary-GUI.html)
- [说明](https://github.com/zoejane/OMOOC2py/blob/master/_src/om2py2w/2wex0/README.MD)

![](http://zoejane.net/images/gui1.png)

 感想
- 完全要跟不上进度的节奏啊，很想请教各位神一样的同学们，如何挤出这么多时间来完善和修改代码的，完全觉得时间不够用啊，对下周能否完成作业表示严重怀疑
- 其实代码框架是在stackoverflow上看别人回答的时候借鉴的，然后再他的基础上再进行思考和修改的，完全凭空自己写，我肯定写不出来，这样也算今晚捣鼓一晚赶上交作业了啦，觉得要学会学习和借鉴别人的好的代码和思路
- 觉得看大家交的任务的时候，有种一图胜千言的感觉，图片看上去更直观

**Comment by xpgeng** [comment]
@OpenMindClub/py2student 
https://github.com/xpgeng/OMOOC2py/tree/master/_src/om2py2w/2wex0
- 说明: https://github.com/xpgeng/OMOOC2py/blob/master/_src/om2py2w/2wex0/README.md
- 感想: 自己的痛点是由于异常的不熟悉， 导致很长一段时间都是在乱逛于各种文档之间。尽管知道自己的需求， 可是在保证了基本功能的情况下， 好多自己想要的点不知道该怎么去实现。所以只能先上传一个简陋版本， 待逐步更新。这次的体验应该好好总结。

**Comment by lyltj2010** [comment]
代码https://github.com/lyltj2010/OMOOC2py/blob/master/_src/om2py2w/Gui.py
第一版。
@OpenMindClub/py2student

**Comment by Cen74** [comment]
- 代码：https://github.com/Cen74/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py
- 说明：https://github.com/Cen74/OMOOC2py/blob/master/_src/om2py2w/2wex0/README.md
- 感受：回顾一下大概90%以上的时间都花在熟悉class和tkinter上，因为主要想训练英文文档阅读能力，主要参考芝麻星给出的文档没有看其它同学的教程，昨天才开始逐渐理解class和tkinter的机制，编码和解决bug主要是昨天和今天。前面的基础不熟悉导致阅读理解程度很低。现在总结下来需要把知识拆解成更小点，在基础部分多练习，官方文档对于初学者并不友好，多找实例练习可能会更好。
- 具体总结今天完成
  @OpenMindClub/py2student

**Comment by JeremiahZhang** [comment]
@OpenMindClub/py2student 

仓库：https://github.com/JeremiahZhang/OMOOC2py/tree/master/_src/om2py2w
- 代码：https://github.com/JeremiahZhang/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py
- 说明：调用脚本 有help帮助 https://github.com/JeremiahZhang/OMOOC2py/blob/master/_src/om2py2w/README.md
- 教程：https://jeremiahzhang.gitbooks.io/omooc2py/content/2nDev/week02_LogGUI.html  
- 感受：自己给自己挖坑容易 填坑真是体力活

**Comment by beelives** [comment]
# 代码

## 函数实现

https://github.com/beelives/OMOOC2py/blob/master/_src/om2py2w/2wex0/V1/main.py

## 类实现

https://github.com/beelives/OMOOC2py/tree/master/_src/om2py2w/2wex0

**Comment by hysic** [comment]
@OpenMindClub/py2student 
[代码](https://github.com/hysic/OMOOC2py/blob/master/_src/om2py0w/0wex2/diary_gui.py)
[说明](https://github.com/hysic/OMOOC2py/blob/master/_src/om2py0w/0wex2/README.md)
[开发记录](https://hysic.gitbooks.io/hysic-s-python-journey/content/1sTry/Week_2/gui_diary.html)

**Comment by liangchaob** [comment]
@OpenMindClub/py2student 
代码: https://github.com/liangchaob/OMOOC2py/blob/master/_src/om2py2w/2wex0/linenotegui.py
说明: https://github.com/liangchaob/OMOOC2py/tree/master/_src/om2py2w/2wex0
issues: https://github.com/liangchaob/OMOOC2py/issues

感想: 本来一开始打算实现的功能很多，结果太多不必要的额外功能与参数花费了太多额外的宝贵时间，而且最后实现的不是很好，最终权衡半天又把所有的小功能点砍掉，尤其是主要功能还未完全实现的情况下就做优化深感没必要；值得欣慰的是最终还是成功把1week的库作为独立模块导入，并仔细优化了1week模块，实现了一些额外参数，为之后的几周的模块化开发做好了铺垫

**Comment by sunoonlee** [comment]
- 代码目录(含说明): https://github.com/sunoonlee/OMOOC2py/tree/master/_src/om2py2w/2wex0
- 讨论issue: https://github.com/sunoonlee/OMOOC2py/issues/7 欢迎点评拍砖
- 感想
  - 读 Tkinter 文档很花时间. 从周二起投入了17个番茄, 包括学习 class 的基本概念.
  - 上周六到这周二一直在折腾 cli 版代码的升级, 结果进度就有所落后. 
  - 所以每周的时间真的很紧张, 若想跟上前七周每周一个花样的节奏, **对时间投入得精打细算**.
  - 程序只用了较简单的 entry 和 label 两种插件, 但原理应该是相通的, 有时间再来改进吧
  - 时间仓促, 还未解决中文支持问题

**Comment by tiezipy** [comment]
@OpenMindClub/py2student 
代码：https://github.com/tiezipy/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py
说明：https://github.com/tiezipy/OMOOC2py/tree/master/_src/om2py2w/2wex0
-  总结
  -  这周的代码写起来感觉有点吃力，一直纠结在class上而且无头绪
  -  找来小伙伴的代码从头学习了一遍，并把每行代码学习了一下
  -  结合芝麻星给的提示的官方文档，基本能看明白代码
  -  不太习惯看全英文的文档，基本上是遇到不认识的就百度
  -  效率很低，大妈每次的讲课都得花大量的时间才能搞懂

**Comment by Jessicamiejiu** [comment]
代码：https://github.com/Jessicamiejiu/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py
说明：https://github.com/Jessicamiejiu/OMOOC2py/blob/master/_src/om2py2w/README.md
总结：基本上参考前几名同学的代码和官方文档，貌似打印历史记录有些问题。。。线下去了解一下

**Comment by penguinjing** [comment]
[代码](https://github.com/penguinjing/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py) / [说明](https://github.com/penguinjing/OMOOC2py/tree/master/_src/om2py2w/2wex0)
之前一直卡在类的理解上，先用函数式编程完成初版GUI极简日记程序，还有不少Bug/不符合通常窗口程序的操作习惯，后续再改进。

**Comment by leonpak** [comment]
代码：https://github.com/leonpak/OMOOC2py/tree/master/_src/om2py2w/2wex0/dailyGui.py
说明：https://github.com/leonpak/OMOOC2py/tree/master/_src/om2py2w/2wex0/README.md
