### ISSUE TITLE
[0w] 学员教程 报到处

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#5]
首周第一个 发布作业 交付处:
- 所有学员, 将个人仓库和 gitbook 完成联动
  - 编译发布成功 个人教程
  - 并配置好 DISQUS 插件令大家可评注
- 将 `个人教程` 地址提交在此 Issue:
  - 形式如下示范....

`提示:` 
- gitbook 帐号,最好同自己的 github 帐号相同! 以便形成一致性体验
  比如大妈的:
  - https://github.com/ZoomQuiet/OMOOC2py
  - https://zoomquiet.gitbooks.io/omooc2py
  - 两个链接,有最多的重复信息
- [tr_02_gitbook.html](http://openmindclub.qiniudn.com/res/tr/tr_02_gitbook.html)

**Comment by ZoomQuiet** [comment]
@OpenMindClub/py2dama
https://zoomquiet.gitbooks.io/omooc2py/

**Comment by wp-lai** [comment]
@OpenMindClub/py2dama
https://www.gitbook.com/book/wp-lai/learn-python/

**Comment by wzzlj** [comment]
@OpenMindClub/py2dama 
https://wzzlj.gitbooks.io/wzzljomooc2py

**Comment by Awlter** [comment]
@OpenMindClub/py2dama
https://awlter.gitbooks.io/omooc2py/

**Comment by JeremiahZhang** [comment]
@OpenMindClub/py2dama
https://jeremiahzhang.gitbooks.io/pybeginner/

**Comment by ghost** [comment]
@OpenMindClub/py2dama
https://ibrother.gitbooks.io/omooc2py/

**Comment by zoejane** [comment]
@OpenMindClub/py2dama
https://www.gitbook.com/book/zoejane/omooc2py/

https://zoejane.gitbooks.io/zoe-py-tutorial/ 原来自己写的版本备份

**Comment by hujianfei1989** [comment]
@OpenMindClub/py2dama
https://hujianfei1989.gitbooks.io/omooc2py/content/

**Comment by tedxt** [comment]
@OpenMindClub/py2dama 
https://tedxt.gitbooks.io/omooc2py/

**Comment by happylumia** [comment]
https://happylumia.gitbooks.io/omooc2py

**Comment by happylumia** [comment]
@OpenMindClub/py2dama
https://happylumia.gitbooks.io/omooc2py

**Comment by zjuguxi** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/zjuguxi/omooc2py

**Comment by joey-zq** [comment]
@OpenMindClub/py2dama
https://zhouqian.gitbooks.io/omooc2py/

**Comment by picklecai** [comment]
@OpenMindClub/py2dama
https:/picklecai.gitbooks.io/omooc2py/

**Comment by sunoonlee** [comment]
@OpenMindClub/py2dama
https://sunoonlee.gitbooks.io/omooc2py/

**Comment by yondjune** [comment]
https://yondjune.gitbooks.io/omooc2py

**Comment by Jaspereclipse** [comment]
@OpenMindClub/py2dama
https://www.gitbook.com/book/jaspereclipse/jaspers-pythonic-journey

**Comment by cxiaodian** [comment]
@OpenMindClub/py2dama
https://cxiaodian.gitbooks.io/omooc2py/

**Comment by huijuannan** [comment]
@OpenMindClub/py2dama
https://huijuannan.gitbooks.io/omooc2py/

**Comment by junjielizero** [comment]
@OpenMindClub/py2dama
https://junjielizero.gitbooks.io/junjielizero/

**Comment by ivanlau** [comment]
@OpenMindClub/py2dama 
https://github.com/ivanlau/LearnPy
https://ivanlau.gitbooks.io/LearnPy

**Comment by suluren** [comment]
@OpenMindClub/py2dama 
https://suluren.gitbooks.io/omooc2py/

**Comment by veratulips** [comment]
@OpenMindClub/py2dama 
https://veratulips.gitbooks.io/omooc2py/

**Comment by OctoberEmma** [comment]
@OpenMindClub/py2dama 
https://octoberemma.gitbooks.io/python

**Comment by tttv** [comment]
@OpenMindClub/py2dama 
https://tttv.gitbooks.io/omooc2py/

**Comment by wanderingdopamine** [comment]
@OpenMindClub/py2dama 
https://wander­ingdop­amine.gitbooks.io/omooc2py/

**Comment by wanderingdopamine** [comment]
@OpenMindClub/py2dama 
https://wander­ingdop­amine.gitbooks.io/omooc2py/

**Comment by wanderingdopamine** [comment]
@OpenMindClub/py2dama 
https://wander­ingdop­amine.gitbooks.io/omooc2py/

**Comment by wanderingdopamine** [comment]
@OpenMindClub/py2dama 

https://www.gitbook.com/book/wanderingdopamine/omooc2py/welcome

**Comment by xiangzhendong** [comment]
@OpenMindClub/py2dama 
https://xiangzhendong.gitbooks.io/notesforpython/

**Comment by jasonycliu** [comment]
@OpenMindClub/py2dama 
https://jasonycliu.gitbooks.io/learningpy/

**Comment by letsplay1879** [comment]
@OpenMindClub/py2dama
https://lk1879.gitbooks.io/lk1879-001/

**Comment by Lcking** [comment]
@OpenMindClub/py2dama
https://lcking.gitbooks.io/ck-python/content/
好像没有配置好，我再仔细按照教程做做~

**Comment by tiezipy** [comment]
https://www.gitbook.com/book/tiezipy/python/details

**Comment by tiezipy** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/tiezipy/python/details

**Comment by fqlxxxxx** [comment]
@OpenMindClub/py2dama
https://fqlxxxxx.gitbooks.io/learnpython/

**Comment by inodi** [comment]
@OpenMindClub/py2dama 
https://inodi.gitbooks.io/-python-/

**Comment by Langzzx** [comment]
@OpenMindClub/py2dama 
https://langp618.gitbooks.io/lang_omooc_py

**Comment by hysic** [comment]
@OpenMindClub/py2dama
https://www.gitbook.com/book/hysic/hysic-s-python-journey/details

**Comment by dyelaine** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/dyelaine/pythonme/details

**Comment by aJiea** [comment]
@OpenMindClub/py2dama 
https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks

gitbook页面加入disqus插件，卡死在中英文输入法上卡了n天。
觉悟过来后，想撞墙。。。
大伙儿引以为鉴，不要像我这样单纯。

**Comment by penguinjing** [comment]
@OpenMindClub/py2dama 
https://penguinjing.gitbooks.io/omooc2py

**Comment by Cloudtree11** [comment]
@OpenMindClub/py2dama
https://cloudtree.gitbooks.io/omooc2py

**Comment by luoquan19** [comment]
@OpenMindClub/py2dama

https://luoquan19.gitbooks.io/omooc2py

终于配置成功DISQUS
之前被官方说明里面第一句说的啥NPM卡住了几天，也没有好好搜索大家邮件列表的相关讨论，以至于几天没有进展，真的是思维方式问题啊。。。

Disqus integration for GitBook
Install the Disqus plugin via NPM, which should be installed globally using the  -g  option:

**Comment by mac-naxin** [comment]
@OpenMindClub/py2dama
https://mac-naxin.gitbooks.io/omooc2py/

**Comment by bambooom** [comment]
@OpenMindClub/py2dama
https://bambooom.gitbooks.io/omooc2py

**Comment by s32n** [comment]
@OpenMindClub/py2dama
https://s32n.gitbooks.io/omooc2py

**Comment by janice-lu-zeng** [comment]
@OpenMindClub/py2dama
https://www.gitbook.com/book/janice-lu-zeng/omooc2py-the-book/

**Comment by faketooth** [comment]
@OpenMindClub/py2dama 
https://faketooth.gitbooks.io/omooc2py/

**Comment by CherHu** [comment]
@OpenMindClub/py2dama 
https://cherhu.gitbooks.io/gopython/

**Comment by lixiguangzhou** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/lixiguangzhou/omooc2py

**Comment by haruhi99** [comment]
https://www.gitbook.com/book/haruhi99/haruhi99/details

**Comment by shuliw** [comment]
@OpenMindClub/py2dama
https://www.gitbook.com/book/shuliw/guidebookpy/

**Comment by letsplay1879** [comment]
@OpenMindClub/py2dama https://github.com/orgs/OpenMindClub/teams/py2dama
https://lk1879.gitbooks.io/lk1879-001/
https://awlter.gitbooks.io/omooc2py/

2015-10-13 14:18 GMT+08:00 shuliw notifications@github.com:

**Comment by letsplay1879** [comment]
@OpenMindClub/py2dama https://github.com/orgs/OpenMindClub/teams/py2dama
https://lk1879.gitbooks.io/lk1879-001/

2015-10-13 14:18 GMT+08:00 shuliw notifications@github.com:

**Comment by LilinAndLilian** [comment]
https://github.com/orgs/OpenMindClub/teams/py2damahttps://lilinandlilian.gitbooks.io/omooc2py/content/

**Comment by LilinAndLilian** [comment]
@OpenMindClub/py2dama https://lilinandlilian.gitbooks.io/omooc2py/content/

**Comment by ziz9** [comment]
@OpenMindClub/py2dama 
https://ziz9.gitbooks.io/omooc2py/

**Comment by sherlockhoatszx** [comment]
@OpenMindClub/py2dama 
https://sherlockhoatszx.gitbooks.io/pyjourney/

**Comment by WhaleChen** [comment]
@OpenMindClub/py2dama 
https://whalechen.gitbooks.io/whale_road_by_python/

**Comment by ellenzhuang** [comment]
@OpenMindClub/py2dama 
https://imxdxd.gitbooks.io/omooc2py/

**Comment by soul2867** [comment]
@OpenMindClub/py2dama 
https://soul2867.gitbooks.io/omooc2py/

**Comment by sherlockhoatszx** [comment]
@OpenMindClub/py2dama 
https://sherlockhoatszx.gitbooks.io/pyjourney/

**Comment by jameszhou89** [comment]
@OpenMindClub/py2dama 
https://jameszhou89.gitbooks.io/moocpy2/

**Comment by nightie** [comment]
@OpenMindClub/py2dama
https://nightie.gitbooks.io/python/

**Comment by lyltj2010** [comment]
@OpenMindClub/py2dama 
https://yongle.gitbooks.io/-python-/content/

**Comment by wong-github** [comment]
@OpenMindClub/py2dama
https://wong-github.gitbooks.io/omooc2py

**Comment by RichardSZ** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/richardsz/my-python-learning-at-github/details
https://github.com/RichardSZ/my-python-learning-at-github

**Comment by wwshen** [comment]
@OpenMindClub/py2dama
https://wwshen.gitbooks.io/omooc2python

**Comment by sherlockhoatszx** [comment]
@OpenMindClub/py2dama
https://sherlockhoatszx.gitbooks.io/pyjourney/

**Comment by chenyan423** [comment]
@OpenMindClub/py2dama 
https://chenyan423.gitbooks.io/learnpy

**Comment by xpgeng** [comment]
@OpenMindClub/py2dama
@cnfeat   素封老师，请按手印。 
https://xpgeng.gitbooks.io/omooc2py

**Comment by liangpeili** [comment]
@OpenMindClub/py2dama
https://liangpeili.gitbooks.io/omooc2py

**Comment by liznut** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/liznut/omooc2py

**Comment by liangdl** [comment]
@OpenMindClub/py2prd 
http://liangdl.gitbooks.io/learn-program/

**Comment by Iris-Di** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/iris-di/omooc2py-gitbook/

**Comment by doreenduo43** [comment]
@OpenMindClub/py2dama
https://doreenduo43.gitbooks.io/omooc2py/

教程更新ing...

**Comment by YFantasy** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/yfantasy/learnpython

**Comment by cnfeat** [comment]
2015-10-14 18:49:21 巡山第一次，以上已安装好DISQUS 的教程我已留下爪印，各位可挖一挖。

**Comment by fqlxxxxx** [comment]
看了一遍，有漏掉的没回复的。@CnFeat

—

**Comment by Jessicamiejiu** [comment]
https://www.gitbook.com/book/jessicamiejiu1/a-journey-to-python-jessica/details

**Comment by rayxiehui** [comment]
https://github.com/rayxiehui/OMOOC2py
https://www.gitbook.com/book/rayxiehui/omooc2py/details

**Comment by zoewang91** [comment]
@OpenMindClub/py2dama 
https://zoewang91.gitbooks.io/omooc2py2

**Comment by liangchaob** [comment]
@OpenMindClub/py2dama
https://liangchaob.gitbooks.io/itdmb-python/content/

**Comment by simple2source** [comment]
@OpenMindClub/py2dama
https://simple2source.gitbooks.io/ompy2/

**Comment by yangshaoshun** [comment]
@OpenMindClub/py2dama 
https://yangshaoshun.gitbooks.io/omooc2py/

**Comment by buermen** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/buermen/omooc2py/

**Comment by buermen** [comment]
@OpenMindClub/py2dama
https://zoomquiet.gitbooks.io/omooc2py/

**Comment by sicunchen** [comment]
@OpenMindClub/py2dama
https://buermen.gitbooks.io/omooc2py/

**Comment by Wangqiaoyang** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/wangqiaoyang/omooc2py

**Comment by jiaoqing** [comment]
@OpenMindClub/py2dama 
https://jiaoqing.gitbooks.io/omoocpy/

**Comment by cnfeat** [comment]
2015-10-15 09:31:43  二次巡山，有漏掉的联系我一下~~

**Comment by JQ-K** [comment]
@OpenMindClub/py2dama @cnfeat 
https://www.gitbook.com/book/jqk/python-learning/details

**Comment by Eloisechou1** [comment]
@OpenMindClub/py2dama 
https://eloisechou1.gitbooks.io/screamypython/

**Comment by LishuaiBeijing** [comment]
@OpenMindClub/py2dama  
@cnfeat 
https://lishuaibeijing.gitbooks.io/omooc2py

**Comment by Cen74** [comment]
https://cen74.gitbooks.io/omooc2py/content/
@cnfeat 
@OpenMindClub/py2dama

**Comment by muzakkk** [comment]
@OpenMindClub/py2dama 
https://muzakkk.gitbooks.io/pythonnote/content/

**Comment by Raffia** [comment]
@OpenMindClub/py2dama 
https://raffia.gitbooks.io/omooc2py

**Comment by feilalala** [comment]
@OpenMindClub/py2dama 
https://feilalala.gitbooks.io/omooc2py/content/

**Comment by SophieXS** [comment]
@OpenMindClub/py2dama 
https://sophiexs.gitbooks.io/summergrass/content/

**Comment by wayson1990** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/@wayson1990

**Comment by PursuitCane** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/pursuitcane/omooc2py

**Comment by summer724** [comment]
@OpenMindClub/py2dama
@cnfeat 
https://summer724.gitbooks.io/omooc2py/

**Comment by rusell123** [comment]
@OpenMindClub/py2dama 
@cnfeat
https://www.gitbook.com/book/rusell123/omooc2py

**Comment by shawn0lee0** [comment]
@cnfeat @OpenMindClub/py2dama 
https://www.gitbook.com/book/shawn0lee0/python-omooc2py/details

**Comment by siyuany** [comment]
@OpenMindClub/py2dama
https://www.gitbook.com/book/siyuany/omooc2py

**Comment by 4plus-ma** [comment]
@OpenMindClub/py2dama
https://4plus-ma.gitbooks.io/omooc2py

**Comment by zou23cn** [comment]
@OpenMindClub/py2dama
https://zou23cn.gitbooks.io/omooc2py

**Comment by ghost** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/xiaoyuer/xiaoyuer-python-/

**Comment by AaronCopperfield** [comment]
@OpenMindClub/py2dama
https://aaroncopperfield.gitbooks.io/omooc2py/

**Comment by baicaiby** [comment]
@OpenMindClub/py2dama
https://baicaiby.gitbooks.io/omooc2py/

**Comment by Inspirabbits** [comment]
@OpenMindClub/py2dama 
https://inspirabbits.gitbooks.io/python_201510/content/

**Comment by leonpak** [comment]
https://www.gitbook.com/book/leonpak/learn-python/details

**Comment by scottming** [comment]
@OpenMindClub/py2dama
https://scottming.gitbooks.io/omooc2py/

**Comment by supperqiuqiu** [comment]
@OpenMindClub/py2dama
https://www.gitbook.com/book/supperqiuqiu/omooc2py/details

**Comment by andreachin** [comment]
https://github.com/orgs/OpenMindClub/teams/py2dama
https://www.gitbook.com/book/andreachin/my-python-documentation/details

**Comment by andreachin** [comment]
@OpenMindClub/py2dama 
https://www.gitbook.com/book/andreachin/my-python-documentation/details

**Comment by linttutu** [comment]
@OpenMindClub/py2dama
https://www.gitbook.com/book/linttutu/omooc2py

**Comment by hanbing718** [comment]
https://hanbing718.gitbooks.io/hanbing718-python-1016

@OpenMindClub/py2dama
@cnfeat

**Comment by linttutu** [comment]
https://linttutu.gitbooks.io/omooc2py/
@OpenMindClub/py2dama

**Comment by arctic-snow** [comment]
@OpenMindClub/py2dama 
https://arctic-snow.gitbooks.io/python-study

**Comment by hongzhih** [comment]
@OpenMindClub/py2dama 
https://hongzhih.gitbooks.io/hongzhih-/

**Comment by zengyumi** [comment]
@OpenMindClub/py2dama  
https://zengyumi.gitbooks.io/omooc2py

**Comment by cnfeat** [comment]
以上，已补增修订
