### ISSUE TITLE
[2wd4]公开课件 提案收集

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#50]
- 背景: 类似 [tr_MDP2py1w_3_doc](http://openmindclub.qiniucdn.com/res/tr/tr_MDP2py1w_3_doc.html) 的全真回放形式
  - 能保证原汁儿原味的还原程序猿真实的编程过程
- 问题: 但是,大妈不知道哪点编程时的困难是大家最想知道如何折腾的?!
  - 因为,大妈们的编程习惯已经凝固入肌肉了,早已忘记怎么习得的了
  - 每次从肌肉中抽取出一个知识点,并设计为一个案例,都象是那什么...
- 方案:
  - 由大家提出想看什么技术/知识点的实地演练
  - 大妈们从中选取最经典的,着意提取
  - 形成回放,公开演示,长期放映,持续改进!
- 多谢哉!
- 倡议形式:

```
### 42字以内标题
~ 简单的期望说明

- 场景: 说明实际编程中经常遇到的难以独自解决的问题
- 代码: 如果有具体代码最好,当然,更加好的是给出 仓库中样本代码的链接
- 问题: 对此困难你的内心问题是什么?!
    - 猜想:
    - 失败:
    - ...

```

@OpenMindClub/py2student

**Comment by ZoomQuiet** [comment]
48小时过过期!

**Comment by wp-lai** [comment]
@ZoomQuiet 
我想到的是

关于GUI
- `Tk`和`Qt`的区别

关于`Tkinter`
- 选择哪些组件
- 如何进行布局
- mainloop的作用
- 事件触发与处理的方法
- 变量的get和set方法
- `python2`和`python3`中使用`Tkinter`的区别

**Comment by faketooth** [comment]
### GUI 编程典型过程

需要大妈们讲解一下`GUI 101`这个任务接到之后，自己是怎么分析、学习和实现的。初学者当然可以不用知晓太多的东西，直接从模仿入手；可以不用懂每行代码是什么意思，按照《Learn Python the Hard Way》里的练习一行一行的敲出来。但仅限于此的话，有点像我厂用外包员工的感觉：基础薄弱不要紧，有模板可以抄，至于背后的原理、思想，完全不在意他们是否能够理解。项目结束释放掉就完事儿了。
- 大妈们会如何进行需求分析、功能设计，并逐步实现
- GUI 编程会要求前台界面和后台功能分离，以本周任务为例，如何来做
- 之前看过一部分《与孩子一起学编程》，书中的GUI是使用**_[easygui](http://easygui.sourceforge.net/)**_来做的，这周的练习是使用tkinter，也许还有其他基于Python的GUI库，更有其他的编程语言、平台有多种多样的GUI库。面对一个新的GUI编程库，需要从哪些方面入手就能提纲挈领做一个Demo出来？控件、消息机制、布局是否足够？

总的来说这周的任务的难度系数要比上周高不少，应该有同学觉得像是要吃一只蜷起来的刺猬，不是扎嘴唇就是扎舌头。自己则像是在吃一个开口太小的夏威夷果，没撬开，决定暴力方式砸开。不知道是该高兴自己砸开了还是该羡慕扎舌头的。加入OMOOC2.py有三个目的，增强自我管理能力，认识更多人，学习Python。所以，欢迎有小伙伴用自己领域的知识来送一个刺猬到我微信：faketooth。

**Comment by ZoomQuiet** [comment]
嗯哼, 前一位学员是经典的研究派,

后一位,是经典的实践派, 

都对,都不对,完成任务才重要...
然后才有其它的, 无论哪种经验都得在自个儿经验基础上才能衍生成功的

以上
