### ISSUE TITLE
[1wd4]公开课 笔记汇总

### ISSUE THREAD

**Issue by sunnyhuang42** [OpenMindClub/OMOOC2py#51]
- 前提: 参加 1wd4 公开课,或是看过回放
- 资源:
  - [录音](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151022_1wd4/index.html)
  - [幻灯](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151022_1wd4/OMOOC2py1wd5_cli.pdf)
  - 视频,见[芝麻星](http://www.iomooc.com/)系统卡包
- 时限: 2wd0 20:20 前
- 行动: 回复此 Issue 给出对应笔记的 URL
  - 不用 `@` 任何人
  - 仅仅是直达链接即可
- 内容: 
  - 公开课对自己触动最大的 top 3 内容
  - 对比自己过往行动, 应该有哪些可以应用以上三点建议进行改进的?
  - 给出具体改进的方案来
    - 针对当前具体的学习/技术/提问...问题
    - 方案描述尽可能包含所有 [5W1H](http://wiki.woodpecker.org.cn/moin/5W1H) 要素!

**Comment by bambooom** [comment]
https://bambooom.gitbooks.io/omooc2py/content/notes/1wd4.html

**Comment by doreenduo43** [comment]
https://doreenduo43.gitbooks.io/omooc2py/content/1sTry/2wnote.html

**Comment by wong-github** [comment]
https://wong-github.gitbooks.io/omooc2py/content/0MOOC/Week1/1wd4%20Note.html

**Comment by sunoonlee** [comment]
https://sunoonlee.gitbooks.io/omooc2py/content/0MOOC/1wd4-notes.html

**Comment by jameszhou89** [comment]
先给出草稿
https://jameszhou89.gitbooks.io/moocpy2/content/1w4_gong_kai_ke.html

**Comment by xpgeng** [comment]
https://xpgeng.gitbooks.io/omooc2py/content/0MOOC/1wd4.html

**Comment by liangpeili** [comment]
https://liangpeili.gitbooks.io/omooc2py/content/week2/week2-opencource.html

**Comment by zoejane** [comment]
[当时间和精力有限，当你遇到一个坑 - Week2课程笔记 by Zoe](https://zoejane.gitbooks.io/omooc2py/content/1sTry/face-problem.html)

**Comment by penguinjing** [comment]
[线下公开课笔记](https://penguinjing.gitbooks.io/omooc2py/content/1sTry/1wd4notebook.html)

**Comment by hysic** [comment]
[[1wd4]大妈讲座之 Top 3](https://hysic.gitbooks.io/hysic-s-python-journey/content/Lect/20151022_review.html)

**Comment by CherHu** [comment]
https://cherhu.gitbooks.io/gopython/content/0MOOC/13_2wnote.html

**Comment by wp-lai** [comment]
3点内容
- [CLI与GUI](https://wp-lai.gitbooks.io/learn-python/content/reflection/CLI_GUI.html)
- 待补充
-  待补充

**Comment by Cen74** [comment]
https://cen74.gitbooks.io/omooc2py/content/note/w1d4_note.html

**Comment by ivanlau** [comment]
- 我觉得以我gitbook的完整程度，还是交issue比较靠谱
  - https://github.com/ivanlau/OMOOC2py/issues/2
  - of 
  - https://ivanlau.gitbooks.io/omooc2py/content/1sTry/w1d4_note.html

**Comment by picklecai** [comment]
https://github.com/picklecai/OMOOC2py/blob/master/0MOOC/note2.md

**Comment by shawn0lee0** [comment]
https://shawn0lee0.gitbooks.io/python-omooc2py/content/0MOOC/2015_10_22.html
