### ISSUE TITLE
[doc]芝麻星排行榜 beta 1.0 上线啦！

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/OMOOC2py#52]
大家在听大妈讲课，看琅琊榜的的时候，我们工程师也没有闲着，继在十天内开发了芝麻星之后，又在三天内开发出了属于芝麻星的「琅琊榜」。

现在芝麻星学员 gihub 评分榜 已经上线，同学们快快登陆，查看自己的位置吧！

查看方法：登录芝麻星>我的卡包>我的评分>OMOOC2py的 github 排名

![](http://7d9mjz.com1.z0.glb.clouddn.com/20151023-151540.jpg)

正所谓：人在做，天在看；出来混，都要还！各位同学，压力山大没？

排名低的同学不要怕，课程才刚刚开始，笑到最后才是赢家。

没上榜的同学也不要着急，原因可能是
- 情况一：还没有 fork 课程的指定仓库；
  - [课程唯一指定仓库](https://github.com/OpenMindClub/OMOOC2py)
- 情况二：已经 fork 了，但是还没有做任何的提交
  - 速速 commit，看看能不能上榜？
- 情况三：已经 fork 了，但改了仓库名
  - 悬崖勒马，回头是岸，改回去，还追得上~

所以，想上榜，就快快地 fork 课程仓库，勤快地提交吧！希望大家都榜上有名！
### P.S.

为了让大家速速上榜，我打算给大家放两个隐藏技：
- 查看排名靠前学员库中的「SUMMARY.md」
  - 「SUMMARY.md」乃是联动 gitbook 的目录，学习别人的思考路径，走别人成功的路，自然少踏坑
- 勤快地巡[闪耀榜](https://github.com/OpenMindClub/OMOOC2py/issues/48)
  - 原理同上。
### P.P.S.

想必部分醒目的人已经明显地看到，芝麻星排行榜目前是以 commit 数为指标的。嗯哼，放心，芝麻星排行榜才 1.0 ，自然会迭代的。

况且，监榜人是大妈呀！

人在做，天在看；出来混，都要还！

好吧~就酱~有问题 issue 见~

课程陪练：陈素封

2015-10-23

**Comment by sunoonlee** [comment]
看出来了，commit 得分 = 历次 commit 包含的 additions 数目之和。deletions 不计。
上面截图之时，应该是还没有提取完所有学员数据，教练心急了哈 : D
