### ISSUE TITLE
Mac 下 Python 的 IDLE 无法输入中文

### ISSUE THREAD

**Issue by wzzlj** [OpenMindClub/OMOOC2py#54]
## 背景：
- OSX 10.11
- python 2.7.10
## 现象：
- 做 2w 的任务时，发现在 IDLE 内无法输入中文
## 尝试
- 切换系统中文输入法、搜狗输入法，皆无法输入中文
- google 『python IDLE 无法输入中文』，几乎所有的答案都指向https://www.python.org/download/mac/tcltk/#activetcl-8-5-18-0

>  在 IDLE 下中文输入法失效。这是因为 IDLE 界面使用的 Tkinter 需要依赖 Tcl/Tk，而系统自带的 Tcl/Tk 版本太低，造成了不兼容的问题。
- 要求升级 tcl/tk，下载 Activetcl 8.5.18.0，安装，无效果。
- 尝试过不匹配的 Activetcl8.6.4.1，依然无效。
## 分析
- 基本上排除了因为 tcl/tk 版本低不兼容的原因造成的无法输入中文
- 搜索发现在个别论坛上有发出同样的疑问者，同样尝试过 Activetcl 后无效后提问，但下面要么无回复，要么直接要求不要使用 IDLE（俺会考虑的=。=），说明并非个案。
  - https://groups.google.com/forum/#!topic/python-cn/-qpkD16D2AY
  - http://bbs.fishc.com/thread-61637-1-1.html
- 有看到涉及『环境变量』的字眼，不知是否相关，但信息太少，无从入手。
## 求助
- MBA 的电量从100%到现在的10%了，依然没有找到答案，遂求助。
- 是否有遇到 IDLE 无法输入中文的问题？
- 如果有，是否用升级 tcl/tl 的方式成功了呢？
- 如果依然无法成功，最后是怎么解决的？

**Comment by wzzlj** [comment]
## 今天怀疑是 tcl/tk 的升级出了问题
- 发现 idle 下提示的 tcl/tk 版本一直是 8.5.9
- 安装了 pyenv，通过`pyenv install 2.7.9`，切换后输入 idle，显示的tk 版本就是8.6.4，且可以输入中文

## 分析
- 我用`where python`看到有三个文件  

```
/usr/local/opt/pyenv/shims/python  
/usr/local/bin/python  
/usr/bin/python  
```

第一个是 pyenv 安装的 python，下面两个是之前的。
- 系统自带 python，我之后又用 brew 安装了一次
- 难道是升级 tk 时一直升级的其中一个版本内的tk，而我一直调用的是另一个版本的？

目前在 pyenv 管理下，可以输入中文了，问题暂时解决。

**Comment by suluren** [comment]
- 我遇到同样的问题,  目前尚在坑里
- mac: OS X EI 10.11
- python 2.7.10
- 问题开始同@wzzlj 第一条 comment 一样
- 后来看到brew 安装的 python 就会使 tk 为新版, 我想通过 pyenv 安装 python 版本  
- pyenv 安装使用[pyenv-installer](https://github.com/yyuu/pyenv-installer), [依赖](https://github.com/yyuu/pyenv/wiki/Common-build-problems)装了
- `pyenv install`报错如下: `BUILD FAILED (OS X 10.11 using python-build 20151006-3-g1550129)`

# 
- 卸载 pyenv 相同方法重装又好了= =,  文本框能键盘输入中文了

**Comment by faketooth** [comment]
升级一下Tk版本就可以了

[MAC 系统中，Tkinter 无法用 中文输入法 输入中文](http://www.jianshu.com/p/f9e30bdc5806)

**Comment by ZoomQuiet** [comment]
这个梗大家都 got 到了哪!
但是,都是只有一个关键字: 升级,可是没有见详细的教程给半年前的自个儿哪!
- 如何升级?
- 安装哪个版本?
- 如何证明安装成功?
- python 脚本中调用的是哪个版权的 Tk?
- Tkinter 和 Tk 的关系?
- 多版本 Tk 的发觉?测试?控制?
- 如何令 Python 用相同的 Tkinter 调用不同的 Tk 版本?
  ...

**Comment by wzzlj** [comment]
再次来看看这个坑
- 在终端用`wish`命令，可以看到目前的 tk 版本
  ![](http://7xn3v1.com1.z0.glb.clouddn.com/15-10-26/72409985.jpg)
- ~~看到 tk 的版本是最新的，而且我无论怎么安装下面哪个版本的 tk，这里的版本查看都是8.6.4~~
  ![](http://7xn3v1.com1.z0.glb.clouddn.com/15-10-26/31519095.jpg)
- 然而在终端下输入 `idle` 调用
  ![](http://7xn3v1.com1.z0.glb.clouddn.com/15-10-26/52054015.jpg)
- 分析：
  - 一是安装的问题，tk 到底安装到哪了？
  - 二时调用的问题，python 是如何调用 tk 的？
- 嗷~码到一半看到大妈的回复了，顺着思路走走看先~

**Comment by wzzlj** [comment]
## 新进展！
- 用 `where`和`which`指令对几个 python、wish 进行查找 
- 并顺藤摸瓜找到这些 python 的老家
- 发现用 `python` 指令调用的 python 的 tk 一直没有得到更新（在/System/Library/ 下 ），而用 wish 调用的已经更新了的 tk 所在的 python 在另外一个文件包里（/Library/ 下）
- 更改，使得指令 python 调用指向后一个 python，问题解决！(用 `ln -s` 软链接命令）
- 我用暴力的，直接把/System/Library 下的 python 包改名（→_→）  
  `sudo mv /System/Library/Frameworks/Python.framework x`

### 分析
- 原本系统自带一个 python，安装 xcode 后又添加了一个 python（而不是覆盖，坑），另外 brew 或者其他方法也会安装新的 python，好多好多 python。
- 然而 tk 更新包双击就安装了也不告诉我他要装的是哪个=。=

## By the way
- OSX 10.11 版本，引入了新的 Rootless，也就是说：

> 即使是root用户，将无法对以下路径有写和执行权限：
> /System
> /bin
> /sbin
> /usr (except /usr/local)
> 只有Apple自身签名的软件（含命令行工具）可以。
- 就是因为这个！造成了许许多多不必要的麻烦。目前网络上相当多的教程，甚至包括官方文档（jekyll 就有这个坑），都没有对这个 Rootless 进行更新。
- 所以10.11的童鞋们，如果遇到坑，看看会不会是这个原因。
- 提供关闭Rootless权限的方法
  1、开机按住Command + R键，让电脑进入恢复模式
  2、打开终端，在终端中键入：csrutil disable 并回车
  3、重新启动电脑进入普通模式即可。
- 亲测有效！
  ![](http://7xn3v1.com1.z0.glb.clouddn.com/15-10-9/73107951.jpg)

**Comment by Awlter** [comment]
不是说csrutil disable 有些危险啊，弄完之后你还敢上小网站吗？

**Comment by wzzlj** [comment]
@Awlter 
虽然这么说……
但是既然是10.11新加的功能，那就说明以前并没有这个功能啊。
10.11之前的小伙伴难道就不敢上小网站了吗……

**Comment by mac-naxin** [comment]
环境：OSX 10.11  &  python 2.7.10 （内置）按照官网的说明安装了 ActiveTcl 8.5.18
遇到同样的问题， 查了半天，虽然大妈的提案是解决问题最好的思路，但实在是能力有限，臣妾做不到啊， 请大妈指条明路吧。
我的理解是，OSX内置的Python 似乎是硬连接（hard-wired）到8.5.9版，还不能改，也不能识别最新的ActiveTcl 版本。似乎是苹果的bug.
我自己的办法是：使用Pyenv 再安装一个 python 2.7.10， 把新装的python设为全局使用的python版本，打开2w任务测试中文输入无误。

**Comment by csufuyi** [comment]
这个问题之前认为不必要就忽略了, 今天重新试了下.

## 问题

之前系统上用pyenv装的python 2.7.10, tk是mac默认版本, 有中文问题;

## 解决

按照官网的说明安装了 ActiveTcl 8.5.18, 
https://www.python.org/download/mac/tcltk/#activetcl-8-5-18-0

问题依然存在;

pyenv install 2.7.10 重装之后问题解决.

## 原因

那么python究竟是以什么方式选择Tk?
还是看Tk安装官方文档里,
https://www.python.org/download/mac/tcltk/#activetcl-8-5-18-0

这一节:
How Python Chooses Which Tk Library To Use

The Tcl/Tk major version is determined when the installer is created and cannot be overridden. 

In either case, the dynamically linking occurs when tkinter (Python 3) or Tkinter (Python 2) is first imported (specifically, the internal _tkinter C extension module). 

"first imported" 说的正是安装python解释器的时候,其实是某些情况静态链接了Tk/tcl库.

安装时的查找路径:
 /Library/Frameworks 自己安装的路径 
 /System/Library/Frameworks 苹果自带的路径

## 总结

 也就是说,如果要更换Tk模块,既要下载与OS适配正确的版本, 还要重装下解释器.

还有没有其它的方式, 一起讨论, 请拍砖~

**Comment by lostical** [comment]
Python 3.5.1 提示后安装了 ActiveTcl 8.5.18，没出现这个状况。

**Comment by the5more** [comment]
小白一枚，我的解决方法是更新完Tcl/Tk后，找到两个版本的Tcl/Tk，旧版在system/library/framework下，新版在/library/framework下，用新版Tcl.framework和Tk.framework替换旧版的。测试，works.

**Comment by loszer** [comment]
解决了一半，关键是不要安装最新的，http://www.jianshu.com/p/f9e30bdc5806

**Comment by chousawa** [comment]
我的系统：OS X 10.12.2 ,安装了对应ActiveTcl 8.5.18，仍然不能使用中文输入法，看到说要重装python，之前用pynev安装的python 3.5.2，所以直接在终端`pyenv uninstall 3.5.2`，然后`pyenv install 3.5.2`,再尝试，顺利使用了中文输入法。感谢之前的同学提供资料。
