### ISSUE TITLE
[2wd6] 广州 C2T2 报名/聚会地址已放出

### ISSUE THREAD

**Issue by penguinjing** [OpenMindClub/OMOOC2py#56]
参考：[C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)
- C2S2 含义 ~ Merged with C2T2 ;-)
- 时间: 10.31 周六 14:00~16:30
- 地点: 广州 天河区天河南一路84号101(近体育西地铁站B出口) **来回咖啡馆**。该地址不接受预订，13:30我左右会先到占位。
- 备注：无技术教练参与，该活动属于学员互相交流学习。
- 报名: 回复说明以下关键信息
  - github 帐号
  - 推荐候选地点（如有的话）
  - 电脑操作系统
  - 当前课程 top3 问题, 参考: [[0w]当周课程 技术问题讨论 描述格式](https://github.com/OpenMindClub/OMOOC2py/issues/3)
- 截止: 周六 10:00 前有效
- 提醒: 尽可能带上电脑,以便现场重现和明确技术问题的细节 ;-)

@OpenMindClub/py2prd

**Comment by yondjune** [comment]
#github & gitbook 账号:
yondjune

#操作系统
win 7 32； python 2.7.

#当前课程 top3 问题
- 需要系统地听讲解的专题及应用：  
# 变量

 （从高中数学开始就跟不上这一块）
- 需要系统地听讲解的专题及应用：  
#交互
- 遇到的其他意外问题


# 补充

- ##PRD微信群的名称：June（账号：qq80568771）
欢迎大家加我交流课程进度及线下学习事宜
- ##留下github 及 gitbook 账号 平时可以互相浏览进度及教程


# 热切期待小伙伴们参与首次学员线下聚会哦！

**Comment by yondjune** [comment]
- github & gitbook 账号:yondjune
- 操作系统 win 7 32； python 2.7.
- 当前课程 top3 问题
- 需要系统地听讲解的专题及应用：  
  
  # 变量
  
  （从高中数学开始就跟不上这一块）
- 需要系统地听讲解的专题及应用：  
  
  # 交互
- 遇到的其他意外问题

# 补充
-  PRD微信群的名称：June（账号：qq80568771）
  欢迎大家加我交流课程进度及线下学习事宜
-  留下github 及 gitbook 账号 平时可以互相浏览进度及教程

# 热切期待小伙伴们参与首次学员线下聚会哦！

**Comment by sunnyhuang42** [comment]
> 留下github 及 gitbook 账号 平时可以互相浏览进度及教程

亲，这里早就公布了啊！
[开智学院.编程思想 Python 入门班 学员索引 · Issue #11 · OpenMindClub/OMOOC2py](https://github.com/OpenMindClub/OMOOC2py/issues/11)

**Comment by StoryTelr** [comment]
GitHub & GitBook 帐号: StoryTelr
OS: Mac OSX
问题：纯属配置好Python，GitHub，GitBook，会看邮件列表，会看Issue，会看芝麻星，然后就没有然后的负基础小白。希望有同学可以交流一下如何起步。

**Comment by lixiguangzhou** [comment]
github 帐号：lixiguangzhou
os：Windows

**Comment by leonpak** [comment]
想问到时有技术教练在吗？

**Comment by whb1990111** [comment]
github 帐号：whb1990111
os：Mac

**Comment by penguinjing** [comment]
> > On Oct 28, 2015, at 2:29 PM, leonpak wrtoe: 
> > 想问到时有技术教练在吗？
> > 
> > 没在的，目前仅是学员间交流。

请问你的技术问题是什么？有需要我们提前约技术教练给予联线指导。

**Comment by simple2source** [comment]
## github帐号：simple2source

## Os：Windows

**Comment by sunnyhuang42** [comment]
归档
