### ISSUE TITLE
[3w]任务 讨论/交付/展示

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#57]
- 参考: 
  - [缩写](https://github.com/OpenMindClub/OMOOC2py/wiki/HbShortRule)
  - [典章:说与菜鸟 | PyChina.org Static Wiki](http://wiki.pychina.org/hd/FreshProposeFor.html)
  - [提问的智慧](http://wiki.woodpecker.org.cn/moin/AskForHelp)
    - [5W1H](http://wiki.woodpecker.org.cn/moin/5W1H)
    - [SMART原则 - MBA智库百科](http://wiki.mbalib.com/wiki/SMART%E5%8E%9F%E5%88%99)
  - ...
- 技术讨论一定要认真的提供可以复现问题的足够信息
- 否则其他人是无法用脑补来还原你的场景的
- 特此草拟如下提问模板,以便学员使用:

:

```
## 背景
- 系统:
- 版本:
- 代码:
- ...

## 现象
- 输入: ..
- 触发: ..
- 问题: 非期待...

## 分析
- 尝试0:
    - 参考:
    - 判断:
    - 实验:
    - 结论:
- 尝试1:
- ...

## 方案
- 解决思路0:
    - 参考:
    - 设想:
- 解决思路1:
...

哪种思路正确,或是其它思路?
```

**Comment by wwulfric** [comment]
## 2wd4 公开课重点回顾

~  以下为 2wd4 教练公开课随堂讲解手记,看录播的童鞋,可边看回放边参看教练手记,理解大妈课程重点

### python 类型转换

date, time, datetime, str 之间如何转换类型？python 中如何判断两个对象是否相等？有哪些判断方法？

### `__main__` 是个啥

python 中的 `__main__` 是什么？ `__name__` 是什么？如何模块化组织 python 代码？`__init__.py` 文件是做什么用的？为什么好像每个文件夹下都有？删掉会怎么样？

.pyc 是什么文件，和 .py 是什么关系？

python 中的 import 为什么很厉害？ [import 大法好](http://www.zhihu.com/question/25038841)

### pyenv 的使用（非必需，推荐使用）

我使用 python3 开发一个新的软件，但是旧的代码是 python2 怎么办？网上下了个开源软件，但是只支持 python2.6 怎么办？

python  包管理的历史

easy_install, pip

virtualenv, pyenv

### 终端环境的配置（非必需，推荐研究）

你使用 bash 遇到过那些不爽的地方？是否已经有人开发了插件或者配置来解决这个问题了？是否有更好的替代？

bash, bash_it, zsh

[win] powershell
[mac] terminal, iterm2
[linux] 你们最自由了，请自由选择发行版和各自的终端 -_-!

附本人的一些配置博文：[zsh](http://wulfric.me/2015/08/zsh/) [iTerm2](http://wulfric.me/2015/08/iterm2/)

**Comment by wp-lai** [comment]
- [代码](https://github.com/wp-lai/OMOOC2py/tree/master/_src/om2py3w/3wex0)
- [说明](https://github.com/wp-lai/OMOOC2py/blob/master/_src/om2py3w/3wex0/README.md)
- [开发记录](https://wp-lai.gitbooks.io/learn-python/content/1sTry/socket.html)

代码演示戳下图

[![ScreenShot](http://7xnrcy.com1.z0.glb.clouddn.com/mysocket_demo_screenshot.png)](http://7xnrcy.com1.z0.glb.clouddn.com/mysocket_demo.mov)

**Comment by WhaleChen** [comment]
# 背景

--系统：win 7   6.1.7601 Service Pack 1 Build 7601
--版本：python 2.7.9
--代码：

### 可以运行的代码：

[代码](https://github.com/WhaleChen/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py)

### 问题代码：

```
def write_files(diary):
    filename = "diary.log"
    if exists(filename) == True:
        diary =open(filename,'a+')

        diaryAlreadyWitten =diary.read()
        print diaryAlreadyWitten
    else:
        diary =open(filename,'w')
    diary.seek(0,2)


root = Tk()
root.geometry('200x200')
#To adjust the window size
app = App(master =root)
filename = "diary.log"
# if exists(filename) == True:
    # diary =open(filename,'a+')

    # diaryAlreadyWitten =diary.read()
    # print diaryAlreadyWitten
# else:
    # diary =open(filename,'w')
# diary.seek(0,2)
write_files(diary)
#I do not know how to make module with the name write_files()
app.mainloop()
root = destroy()

```

### 现象：

![q1](https://cloud.githubusercontent.com/assets/11818114/10851875/7c2e0a86-7f68-11e5-96b6-361a5d622e0e.png)

### 分析

  目的：希望将write_files 能够封起来，
  问题：出错。提示globle name not defined.
- ### 尝试0：
  - 参考: [global variable](https://docs.python.org/2/faq/programming.html?highlight=global%20variable#what-are-the-rules-for-local-and-global-variables-in-python)  
  - 判断: 需要加入全局变量声明  
  - 实验：加入代码：

```
global diary
write_files(diary)
```

```
    - 结论：依旧如故
```
- ### 尝试1：
  - 参考: [global variable](https://docs.python.org/2/faq/programming.html?highlight=global%20variable#what-are-the-rules-for-local-and-global-variables-in-python)  
    -判断：缺少声明，那么就使用diary =[] 试试
  - 实验：加入代码

```
diary = []
write_files(diary)
```

```
   -结论：开始运行良好，可是当输入，并按回车的时候，出现
```

   _diary.write("\n"+self.contents.get()) AttributeError: 'list' object has no attribute 'write'_ 出错提示

-### 尝试2：
    -判断：既然 'list' 不行，那么先找到 diary 的 type
       - 尝试：在之前[代码 第一周](https://github.com/WhaleChen/OMOOC2py/blob/master/_src/om2py0w/0wex1/main.py) 修改，加入

```
    diary = open(fileName,'w')
    print type(diary)

```

```
  - 结论: 'file'  #   test the type of diary is 'file'
```
- #### 尝试3：
  - 参考：[stackflow](http://stackoverflow.com/questions/664294/is-it-possible-only-to-declare-a-variable-without-assigning-any-value-in-python)
    - 尝试：文档没有 file declaration  的内容 用 google ” python declare file variable“ 得参考结果
  - 尝试：

```
diary = None
```

```
    结论：开始运行良好，可是当输入，并按回车的时候，出现
```

  ”diary.write("\n"+self.contents.get()) AttributeError: 'NoneType' object has no attribute 'write' “ 问题依旧

### 方案：

--思路0：我的思路是定义一个’file‘ 类的文件，然后就可以解决问题，可是就是无法找到这个方法。
--思路1：是否应该先赋值一个’file‘的文件，可是我不知道如何赋值’file‘类的文件。
感谢阅读~希望能够探究到答案,也特别需要帮助！谢谢！

#### 尝试4：

```
- 再思考：一直疑惑是否是 globle的使用方法有问题。
- 再实验：
```

```
def write_files():
    filename = "diary.log"
    global diary
    if exists(filename) == True:
        diary =open(filename,'a+')

        diaryAlreadyWitten =diary.read()
        print diaryAlreadyWitten
    else:
        diary =open(filename,'w')
    diary.seek(0,2)
```

```
 把global diary 内置 同时去 diary 参数 就可以了。 
```

如果建立 file 空 依旧是个问题。 不过前进了一步！！ 

 #### 尝试5
     - 参考：大妈回复：
    忘记俺反复提及的? **Python 中一切都是对象**
    所以, 你的 思路1 其实是非常接近方案了: 先形成一个可操作的 合适的 文件对象, 然后在合适的时机  来使用
     write_files() 的形式已经非常接近了
    注意, 函式不仅仅是行为的封装, 也应该是过程的封装, 完全可以返回一个你期望的对象哪
    - 判断：既然 一切都是对象，就冒险一下，写一个return diary？ 让 write_files()直接返回一个'file'类型的参数
    -实验：

```
def write_files():
    filename = "diary.log"
      # global diary
    if exists(filename) == True:
        diary =open(filename,'a+')

        diaryAlreadyWitten =diary.read()
        print diaryAlreadyWitten
    else:
        diary =open(filename,'w')
    diary.seek(0,2)
    return diary
...
diary = write_files()
```
- 结果：神奇般的可以了！
- 反思：为什么我思维上有一个要独立的declaration的梗呢？
  - 总认为过程和行为结果是两个不同的东西，下意识“一定要分开！"
  - 执行过程的同时可以返回结果，不是一个更高效的方式吗？
  - 这似乎意味者其实我们不需要事先定义任何东西，直到用的时候，专注于过程本身就可以完全接纳过程创造出来的新鲜玩意？ @ZoomQuiet 
    +谢谢大妈的点播：
  
  > Python 中一切都是对象; 函式不仅仅是行为的封装, 也应该是过程的封装!

有趣的旅程，中途的一个小小的MileStone~

**Comment by wzzlj** [comment]
# 交付任务~
- 代码：https://github.com/wzzlj/OMOOC2py/tree/master/_src/om2py3w/3wex0
- 讨论：
  - [Gitbook](https://wzzlj.gitbooks.io/wzzljomooc2py/content/_src/om2py3w/3wex0/think.html)
  - https://github.com/wzzlj/OMOOC2py/issues/5
- 感想：
  - 本次任务相对简单，一个 socket 模块解决了大部分问题。
  - 很多坑在之前的任务都踩过了，所以这次坑比较少，进行的比较流畅。
  - 虽然说还是叫『日记本』，但是多个客户端一启动，完全就是个聊天室了嘛~

# 更新~

弄了个桌面版客户端，等于把前三周的东西全部整在一起了~
逐渐开始理解为什么说python是面向对象的语言了！
![](http://7xn3v1.com1.z0.glb.clouddn.com/15-11-1/34437335.jpg)

**Comment by ZoomQuiet** [comment]
2015-10-31 1:28 GMT+08:00 WhaleChen notifications@github.com:
...

> ```
> 结论：开始运行良好，可是当输入，并按回车的时候，出现
> ```
> 
> ”diary.write("\n"+self.contents.get()) AttributeError: 'NoneType' object has no attribute 'write' “ 问题依旧
- 虽然尝试过程有点随意
- 但是,发挥了非常 Pythonic 的经验
- 每次对想法的检验都非常简洁!
- 从而能在少数迭代之后,走回正确的方向 ;-)

> 方案：
> 
> --思路0：我的思路是定义一个’file‘ 类的文件，然后就可以解决问题，可是就是无法找到这个方法。
> --思路1：是否应该先赋值一个’file‘的文件，可是我不知道如何赋值’file‘类的文件。
- 忘记俺反复提及的? Python 中一切都是对象
- 所以, 你的 思路1 其实是非常接近方案了: 先形成一个可操作的 合适的 文件对象, 然后在合适的时机来使用
- write_files() 的形式已经非常接近了
- 注意, 函式不仅仅是行为的封装, 也应该是过程的封装, 完全可以返回一个你期望的对象哪

**Comment by zoejane** [comment]
@OpenMindClub/py2student
- [代码](https://github.com/zoejane/OMOOC2py/tree/master/_src/om2py3w/3wex0)
- [说明](https://github.com/zoejane/OMOOC2py/blob/master/_src/om2py3w/3wex0/README.MD)
- [开发日记](https://zoejane.gitbooks.io/omooc2py/content/1sTry/diary-net.html)
- 感想
  - 喵，看到大家交作业好神速，觉得不可思议，因为当时还处于一头雾水什么也不知道的情况。结果自己一尝试，好像也没有想象中难耶。
  - 吸取上次教训，上次开始就想做一个有点复杂的功能，给自己挖了一堆坑，完全出不来啊，写的代码也不知道是个什么，这次就是从实现最简单的功能开始，过程更流畅。
  - 吸取上次教训，周三开始写代码，交作业急急忙忙，弄到很晚，还写得很烂。这次也是受到大家的影响，发现早点动手最最好，周六开发出来第一版，整周的节奏才更加的不紧不慢 ^_^
  - python编程就是这么简单，一点点代码就可以搞定问题，噢耶！
  - 回到熟悉的命令行模式，再次感受到命令行开发真的比GUI简单好用。

**Comment by bambooom** [comment]
@OpenMindClub/py2student 
- [代码](https://github.com/bambooom/OMOOC2py/tree/master/_src/om2py3w/3wex0)
- [说明](https://github.com/bambooom/OMOOC2py/blob/master/_src/om2py3w/3wex0/README.md)
- https://github.com/bambooom/OMOOC2py/issues/9
- 感想：
  - 一开始看演示觉得好神奇，认真读了一些教程之后才发现原理很好理解。理解了socket如何运作之后，任务就很直接了。
  - 看到多数教程都是使用TCP协议的，为啥这次要用UDP协议？
  - 总觉得应该可以直接调用1w任务的代码，但最后还是简单粗暴地copy+paste了某一些:disappointed:

**Comment by xpgeng** [comment]
@OpenMindClub/py2student 
- [代码](https://github.com/xpgeng/OMOOC2py/tree/master/_src/om2py3w/3wex0) 
- 讨论: [Gitbook](https://xpgeng.gitbooks.io/omooc2py/content/_src/om2py3w/3wex0/Mydaily-Version3.html)
- 感想: 
  - 实现基本功能, 吸收反馈, 快速迭代.
  - 没有一个好的开发节奏, 真的会一下乱了一整周.

Ps: 我最近整理的一个关于README的[教程](https://xpgeng.gitbooks.io/omooc2py/content/guide/README-guide.html). 欢迎大家补充, 纠错.希望对大家能有所帮助. ;-)

**Comment by suluren** [comment]
- 代码: https://github.com/suluren/OMOOC2py/tree/master/_src/om2py3w/3wex1
- 笔记/讨论: https://suluren.gitbooks.io/omooc2py/content/1sTry/net.html
- 功能实现简单, 同步上卡了一下, 但笔记写起来, 一些概念比较抽象...也很难验证...

**Comment by JeremiahZhang** [comment]
@OpenMindClub/py2student
- [代码](https://github.com/JeremiahZhang/OMOOC2py/tree/master/_src/om2py3w/3wex0)
- [说明](https://github.com/JeremiahZhang/OMOOC2py/blob/master/_src/om2py3w/README.md)
- [开发日志](https://jeremiahzhang.gitbooks.io/omooc2py/content/2nDev/week03_net_way.html)

**Comment by sunoonlee** [comment]
- [代码目录(含说明)](https://github.com/sunoonlee/OMOOC2py/tree/master/_src/om2py3w/3wex0) 
- [笔记/讨论-Gitbook](https://sunoonlee.gitbooks.io/omooc2py/content/_src/om2py3w/3wex0/notes.html)
- 感想
  - 上了这么多年网，总算对 数据在网络上的传输方式 有了一点儿了解
  - v0 -- 实现最基本的功能，v1.0 -- 区分不同客户端主机名
  - 若只是实现课程作业的基本要求，那么 python 技能是得不到足够操练的，需要自己再下功夫

**Comment by liangchaob** [comment]
@OpenMindClub/py2student
- 代码: https://github.com/liangchaob/OMOOC2py/tree/master/_src/om2py3w/3wex0
- 说明: https://github.com/liangchaob/OMOOC2py/blob/master/_src/om2py3w/3wex0/README.md
- 感想: 功能先简单地快速实现了,没有纠结太小的细节，遇到问题都先绕了过去，主要精力放在了优化w1的原型，尤其是遍历文件记录的操作上，调整了原有的逻辑，使其更好的可以直接作为模块调用，达到精简后期开发的效果，下一步如果还有精力的话会尝试着把服务器与客户端做在一起，然后以参数实现调用
  ![0.png](https://ooo.0o0.ooo/2015/11/02/563795fec3bc5.png)

**Comment by janice-lu-zeng** [comment]
@OpenMindClub/py2student 
代码: https://github.com/janice-lu-zeng/OMOOC2py/blob/master/_src/om2py3w/3wex0/
README: https://github.com/janice-lu-zeng/OMOOC2py/blob/master/_src/om2py3w/README.md
Gitbook: https://janice-lu-zeng.gitbooks.io/omooc2py-the-book/content/draft/netResources.html

**Comment by sherlockhoatszx** [comment]
@OpenMindClub/py2student 
代码：https://github.com/sherlockhoatszx/OMOOC2py/blob/master/_src/om2py3w/3wex2
README:https://github.com/sherlockhoatszx/OMOOC2py/blob/master/_src/om2py3w/3wex2/README.MD
Gitbook:https://sherlockhoatszx.gitbooks.io/pyjourney/content/w3ren_52a1-_udp.html

**Comment by dyelaine** [comment]
@OpenMindClub/py2student 
代码: https://github.com/dyelaine/OMOOC2py/tree/master/_src/om2py3w/3wex0
README:  https://github.com/dyelaine/OMOOC2py/blob/master/_src/om2py3w/README.md
Gitbook: https://dyelaine.gitbooks.io/pythonme/content/_src/om2py3w/index.html
感想：只是简单实现了作业的要求，细节方面没有太深究，但是写代码习惯不好，有待进一步提高。

**Comment by liangpeili** [comment]
@OpenMindClub/py2student 
[代码](https://liangpeili.gitbooks.io/omooc2py/content/week3/week3-code.html)
[README](https://liangpeili.gitbooks.io/omooc2py/content/week3/week3-guide.html)
[开发记录](https://liangpeili.gitbooks.io/omooc2py/content/week3/week3-day2-code.html)
效果图：
![pic1](http://7xlsh1.com1.z0.glb.clouddn.com/QQ截图20151103145148.png)

**Comment by fqlxxxxx** [comment]
@OpenMindClub/py2student 
- 代码: https://github.com/fqlxxxxx/OMOOC2py/tree/master/_src/om2py3w/3wex0
- README: https://github.com/fqlxxxxx/OMOOC2py/blob/master/_src/om2py3w/3wex0/README.md
- 开发记录整理中，稍后再补。
- 感想：
  - 2w(上周)的作业虽然勉强做完了, 但差点趴在坡上没起来, 难度有点大, 现在其实还有很多迷糊的地方, 提问都不知道从哪里开始, 只能自己啃.
  - 3w的任务基本搞定, 不过提交前看了看其他同学的, 发现自己的代码还有很大的改进空间, 提交后再做优化.
  - 重点学习对象wzzlj 和 zoe, 每次看完他们的代码都觉得很清晰, 很舒服, 能学到不少, 再看看自己的代码就是shit.

**Comment by jameszhou89** [comment]
## 现象
- 输入: 
  测试python官方网站上面的socket代码
  主要代码参考 https://docs.python.org/2/library/socket.html#example

1.server
import socket
import sys

HOST = 'localhost'                 # Symbolic name meaning all available interfaces
PORT = 57382            # Arbitrary non-privileged port
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((HOST, PORT))
s.listen(2)
conn, addr = s.accept()
print 'Connected by', addr
while 1:
    data = conn.recv(1024)
    if not data: break
    conn.sendall(data)
conn.close()

2.client

import socket
import sys

HOST = 'localhost'    # The remote host
PORT = 57382           # The same port as used by the server
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
s.sendall('Hello, world')
data = s.recv(1024)
s.close()
print 'Received', repr(data)
- 触发: ..
  当第一个client输入代码的时候，出现了 received "hello world"
  当在第二个client上输入代码的时候，出现了问题
- 问题: 出现了socket.error errno 61 connection refused
  ![2015 11 4 12-50-05](https://cloud.githubusercontent.com/assets/4163521/10914456/7cb3df80-828d-11e5-8340-df1a858c6bb7.png)

## 分析
- 尝试0:
  - 参考：https://pymotw.com/2/socket/udp.html
  - 判断:以为是port的数值问题
  - 实验:更换串口数值
  - 结论:依然出现错误
- 尝试1:
  - 参考：
    - 判断:以为是科学上网的问题
    - 实验:关闭VPN
    - 结论:依然出现错误

**Comment by faketooth** [comment]
@OpenMindClub/py2student 
- [代码](https://github.com/faketooth/OMOOC2py/tree/master/_src/om2py3w/3wex0)
- [功能说明](https://faketooth.gitbooks.io/omooc2py/content/_src/om2py3w/3wex0/index.html)
- [开发日记1](https://faketooth.gitbooks.io/omooc2py/content/0MOOC/3w/SprintLog_3wd1.html)
- [开发日记2](https://faketooth.gitbooks.io/omooc2py/content/0MOOC/3w/SprintLog_3wd2.html)
- 效果图

![readme-server-showcase](https://cloud.githubusercontent.com/assets/1687273/10924765/0ca71856-82c4-11e5-968e-a06dd24b7e28.png)

![readme-client-showcase](https://cloud.githubusercontent.com/assets/1687273/10924770/19b4a482-82c4-11e5-9d6e-58182532a8d6.png)

**Comment by faketooth** [comment]
@jameszhou89 
你用的是`socket.SOCK_STREAM`，这个不是`UDP`协议。

**Comment by junjielizero** [comment]
代码：https://github.com/junjielizero/OMOOC2py/tree/master/_src/om2py3w/3wex0
说明：https://github.com/junjielizero/OMOOC2py/blob/master/_src/om2py3w/3wex0/README.md
@OpenMindClub/py2student

**Comment by Awlter** [comment]
@OpenMindClub/py2student
请问大妈的3w演示的demo，没有启动server就能在用client更改server中的.log文件，这是怎么做到的

**Comment by Awlter** [comment]
@OpenMindClub/py2student 

when: 在研究完了UDP, C/S, 看完了这个[C/S的教程视频](https://www.youtube.com/watch?v=PkfwX6RjRaI) 后，准备再研究一下大妈的demo，准备开始写代码的时候发现了一个问题

where: 我的系统是mac os, python版本2.7.10， sublime text 3

what: 3w demo中，大妈没有启动server，就能实现client对server中 log文件的更新，我们可以看到，在启动client1输入文字之后，启动client2，历史信息自动显示了client1输入的信息，很明显client1是访问了server的log文件

why: 因为如果不运行server的程序，如何才能实现server与client连接呢？因为明显client程序所在的文件夹下是没有 log文件的

**Comment by ZoomQuiet** [comment]
@Awlter 
- `我猜大妈是在后台运行了server` ~ 有学员已经目测出来了 ;-)
- 就是这么简单,不可能不启动 server 的哪,只是 server 的 stdout 输出包含了无关细节,就没有在 tmux 面板组中显示而已

;-)

**Comment by hysic** [comment]
@OpenMindClub/py2student

系统: OS X 10.10
python 版本: 2.7.10 

代码及说明: https://github.com/hysic/OMOOC2py/tree/master/_src/om2py3w/3wex0
开发记录及 issue 讨论: [日记系统 net 版](https://github.com/hysic/OMOOC2py/issues/2)

**Comment by picklecai** [comment]
@OpenMindClub/py2student

服务器端程序：https://github.com/picklecai/OMOOC2py/blob/master/_src/om2py3w/3wex0/notebooknets.py

客户端程序：
https://github.com/picklecai/OMOOC2py/blob/master/_src/om2py3w/3wex0/notebooknetc.py

说明书：
https://github.com/picklecai/OMOOC2py/blob/master/_src/om2py3w/3wex0/README.md

潜在运行危险：如果两个程序不在一个文件夹下，一个如何能import到另一个？如果不能，这个程序就失败了。

**Comment by cxiaodian** [comment]
代码：https://github.com/cxiaodian/OMOOC2py/tree/master/_src/om2py3w/3wex0
gitbook：https://cxiaodian.gitbooks.io/omooc2py/content/_src/om2py3w/3wex0/index.html
细节需继续优化
@OpenMindClub/py2student

**Comment by aJiea** [comment]
代码：https://github.com/aJiea/OMOOC2py/tree/master/_src/om2py3w/3wex0
gitbook：https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/w3__upd.html

从win到linux到mac，终于可以在规定时间内交一份不太满意的作业了。。。

@OpenMindClub/py2student

**Comment by jasonycliu** [comment]
@OpenMindClub/py2student

代码: https://github.com/jasonycliu/OMOOC2py/tree/master/_src/om2py3w/3wex0 
说明: https://github.com/jasonycliu/OMOOC2py/blob/master/_src/om2py3w/README.md
开发日记: https://jasonycliu.gitbooks.io/omooc2py/content/1sTry/net101.html
感想: 感觉python用起来挺好的, 底层还有很多东西不懂.

**Comment by Cen74** [comment]
代码－服务器：https://github.com/Cen74/OMOOC2py/blob/master/_src/om2py3w/3wex0/server_3.py
代码－客户端：https://github.com/Cen74/OMOOC2py/blob/master/_src/om2py3w/3wex0/client_3.py
gitbook: https://cen74.gitbooks.io/omooc2py/content/note/w3_task.html
@OpenMindClub/py2student 

这周代码问题不断，上班用win, 在家用mac,  unicode的encode(),decode() 很坑了我一把。

**Comment by jameszhou89** [comment]
刚完成一半，哭....
代码
https://github.com/jameszhou89/OMOOC2py/blob/master/_src/om2py3w/3wex0/main.py

**Comment by wong-github** [comment]
客户端代码：https://github.com/wong-github/OMOOC2py/blob/master/_src/om2py3w/3wex0/client.py
服务器代码：https://github.com/wong-github/OMOOC2py/blob/master/_src/om2py3w/3wex0/server.py
使用说明：https://github.com/wong-github/OMOOC2py/blob/master/_src/om2py3w/3wex0/README.md
开发记录：https://github.com/wong-github/OMOOC2py/blob/master/0MOOC/Week3/Week3%20Programming%20Record.md
@OpenMindClub/py2student

运行效果图：（客户端是桌面版，服务器是命令行）
![xiaoguotu.png](https://raw.githubusercontent.com/wong-github/OMOOC2py/master/_src/om2py3w/3wex0/xiaoguotu.png)

**Comment by yangshaoshun** [comment]
https://github.com/yangshaoshun/OMOOC2py/tree/master/_src/om2py3w/3wex0/main_im.py
- 说明: https://github.com/yangshaoshun/OMOOC2py/blob/master/_src/om2py3w/README.md
- 讨论:
  - 待更新
- 感想: 
  - 静下心来学习 docopt ，给 main_im.py 添加参数选择。第一周看不懂的内容，畏惧的 docopt ，动手开始写，努力查例子和 stackoverflow 的问答，也能加入自己的代码中了。总结下自己的解决过程：好的基本教程让代码先跑起来，大量的代码实例增进理解（stackoverflow 对我最大的意义），现在对官方帮助文档使用仍然比较小。
  - 第三周卡片使用心得：接手任务之后，完全是按照大妈卡片给定的顺序去一点点执行和丰富代码；完成基本功能，按照卡片和大妈的 demo 去检验实现的效果（docopt也是这个阶段加入的）。

@OpenMindClub/py2student

**Comment by mac-naxin** [comment]
代码: https://github.com/mac-naxin/OMOOC2py/tree/master/_src/om2py3w/3wex0
说明: 见上述代码目录的README.MD 
感想：好不容易终于按时调试完成代码了，tmux刚装上还没开始用，图片就欠奉了。当然README说明也没写呢，晚上补上吧。现在基本理解怎么完成作业了，下次作业争取交上详细说明和开发日记。
讨论：这次看了几天socket的文档和视频，发现在1w、2w基础上实现起来似乎不难，后来又纠结于socketServer了，以为没有socketServer无法实现客户端同时输入和查看日记，后来看到有同侪用thread实现的，但我仅使用socket模块编写的代码，在三个系统上进行测试，发现是可以同时进行的，还不明白是怎么回事。

**Comment by shawn0lee0** [comment]
### 使用说明
1. 先启动server端文件，等待
2. 启动客户端py文件，并输入信息
3. 输入r可读取历史记录

[开发记录：](https://github.com/shawn0lee0/OMOOC2py/blob/master/_src/om2py3w/3wex0/README.md)
效果图：
 ![](http://i12.tietuku.com/7b96d07691098890.png)

**Comment by Awlter** [comment]
代码：https://github.com/awlter/OMOOC2py/tree/master/_src/om2py3w/3wex0
日记：https://awlter.gitbooks.io/omooc2py/content/2nDev/landiary.html  

这次写代码的过程在周二还完全不知道怎么办，我以为只用doc 17.2就能实现（其实可以），但是当时觉得自己不能，于是看了wzzj的笔记的第一段，原来她也google了其他的教程，然后我才开始找其他的教程，转了一圈发现，用17.2的命令真的就很简单的实现了我们这周想要的初级功能。  

此时此刻回想起这个过程，前期看了大量的各种协议的文章，历史啊，特点啊，看了简单的UDP和TCP的例程，觉得和想要实现的功能相差很远。以现在的hindsight来看，这个过程缺乏新知识和固有知识的整合，应该找机会好好反思，这么简单的东西为什么需要这么久。

现在这个代码的版本只是雏形的雏形。  

却少：
    多client联机
    时间module

还没弄懂：  
    threading  和 lock

**Comment by sunnyhuang42** [comment]
过期关闭

**Comment by Jessicamiejiu** [comment]
代码：https://github.com/Jessicamiejiu/OMOOC2py/tree/master/_src/om2py3w/3wex0
说明：下载server.py,client.py,diary.txt,本地运行

**Comment by tiezipy** [comment]
@OpenMindClub/py2student
说明：https://github.com/tiezipy/OMOOC2py/tree/master/_src/om2py3w/3wex0
代码：https://github.com/tiezipy/OMOOC2py/blob/master/_src/om2py3w/3wex0/client.py
          https://github.com/tiezipy/OMOOC2py/blob/master/_src/om2py3w/3wex0/server.py
测试效果：

![qq 20151120230910](https://cloud.githubusercontent.com/assets/14883241/11303618/cbb430c2-8fde-11e5-9ffd-4b016c07b21d.png)
