### ISSUE TITLE
[2wd4]广州 线下活动报名

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/OMOOC2py#58]
- 地点: 广州 天河区 珠江新城 华夏路30号 富力盈通31F 3110 会议室
- 时间: 周四 19:42~22:22
- 报名: 回复说明以下关键信息
  - github 帐号
  - 大约到达时间
  - 期望现场解决的技术问题
- 截止: 周四 10:10 前有效
- _提醒:_ 必须带上电脑,以便现场明确技术问题的细节 ;-)
## 记要
- 签到: ![151029c2t2gz_sign.jpg](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151029_2wd4/151029c2t2gz_sign.jpg?imageView2/2/w/240)
- 录音:
  - [om2py2wd4_09_c2t2_0_ZOOM0094.MP3](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151029_2wd4/om2py2wd4_09_c2t2_0_ZOOM0094.MP3)
  - [om2py2wd4_10_c2t2_1_ZOOM0095.MP3](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151029_2wd4/om2py2wd4_10_c2t2_1_ZOOM0095.MP3)
  - [om2py2wd4_11_c2t2_2_ZOOM0096.MP3](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151029_2wd4/om2py2wd4_11_c2t2_2_ZOOM0096.MP3)
  - [om2py2wd4_12_c2t2_sphinx_ZOOM0097.MP3](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151029_2wd4/om2py2wd4_12_c2t2_sphinx_ZOOM0097.MP3)
- 合影:

![151029c2t2gz_all.jpg](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151029_2wd4/151029c2t2gz_all.jpg?imageView2/2/w/360)

参考: [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)

@OpenMindClub/py2prd

**Comment by lixiguangzhou** [comment]
github 帐号：lixiguangzhou
大约到达时间：19:30

**Comment by penguinjing** [comment]
- github 帐号: penguinjing
- 大约到达时间: 19:20
- 期望现场解决的技术问题: 暂无

**Comment by demonmax** [comment]
github 帐号：demonmax
大约到达时间：19:30

**Comment by sunnyhuang42** [comment]
归档
