### ISSUE TITLE
[2w]任务 讨论

### ISSUE THREAD

**Issue by sunnyhuang42** [OpenMindClub/OMOOC2py#59]
- 参考: 
  - [缩写](https://github.com/OpenMindClub/OMOOC2py/wiki/HbShortRule)
  - [典章:说与菜鸟 | PyChina.org Static Wiki](http://wiki.pychina.org/hd/FreshProposeFor.html)
  - [提问的智慧](http://wiki.woodpecker.org.cn/moin/AskForHelp)
    - [5W1H](http://wiki.woodpecker.org.cn/moin/5W1H)
    - [SMART原则 - MBA智库百科](http://wiki.mbalib.com/wiki/SMART%E5%8E%9F%E5%88%99)
  - ...
- 技术讨论一定要认真的提供可以复现问题的足够信息
- 否则其他人是无法用脑补来还原你的场景的
- 特此草拟如下提问模板,以便学员使用:

:

```
## 背景
- 系统:
- 版本:
- 代码:
- ...

## 现象
- 输入: ..
- 触发: ..
- 问题: 非期待...

## 分析
- 尝试0:
    - 参考:
    - 判断:
    - 实验:
    - 结论:
- 尝试1:
    - 参考:
    - 判断:
    - 实验:
    - 结论:
- 尝试2:
    - 参考:
    - 判断:
    - 实验:
    - 结论:
- ...

## 方案
- 解决思路0:
    - 参考:
    - 设想:
- 解决思路1:
    - 参考:
    - 设想:
- 解决思路2:
    - 参考:
    - 设想:

哪种思路正确,或是其它思路?
```

**Comment by jameszhou89** [comment]
目前碰到的一个问题是，我应该怎样把键入Entry的信息及时显示在GUI里面？
尝试：
我找到了一个message的widget，但是问题好像只显示写死的信息
        e = Entry(master,width=50)
        e.pack()
        e.focus_set()
        w = Message(master, text="hello",width=100)
        w.pack(side=LEFT)

我尝试把上面的 text="hello"换成了text=x，期待可以把键入entry的参数可以及时显示在GUI上面
       e = Entry(master,width=50)
        e.pack()
        e.focus_set()
        x=str(e.get())
        w = Message(master, text=x,width=100)
        w.pack(side=LEFT)
但是好像没什么用...
我不知道问题出在哪里？

**Comment by ZoomQuiet** [comment]
@jameszhou89 

嗯哼, 完全看不出你的问题点哪,,,
- [The Tkinter Message Widget](http://effbot.org/tkinterbook/message.htm) 看过嘛?
- 对比: [The Tkinter Entry Widget](http://effbot.org/tkinterbook/entry.htm)
- 可以明确的知道两者区别哪
- 另外:
  - `...找到了一个message的widget` 
  - 在哪儿找到的?
    - 看到了什么?
    - 为什么一定要用这个 对象?
    - 你如何设想的?
    - 如何检验的?
    - 有什么预先的指标?
  - 如果不吻合设想,怎么办?
  - .....

**Comment by picklecai** [comment]
# 问题：怎么做到让用户给存的文件命名

## 背景
- 系统:win7 或win8
- 版本:python2.7.8
- 代码:
  <pre><code>
  def writenew():
  # 输入新的内容
  prompt = "今日记录，请输入： "
  l3 = Tkinter.Label(win, text=prompt)
  l3.grid(row=1, column=2)
  global newline
  newline = Tkinter.Entry(win)
  newline.grid(row=2, column=2)
  b4 = Tkinter.Button(win, text="保存新内容", command=savenew)
  b4.grid(row=3, column=2)
  </pre></code>
  <pre><code>
  def savenew():
  # 保存
  fn = Tkinter.Entry(win)
  fn.grid(row=4, column=2)
  fn.bind('<Key-Return>', fuzhi)
  filename = fuzhi(fn)
  output = open(filename + ".txt", 'w')  # 规定好扩展名，以免出现用户保存的文件打不开的情况。
  output.write(filename + ".txt"+"\n")  # 在文件中写入文件名。
  output.write(time.strftime("%d/%m/%Y %H:%M:%S"+"\n"))  # 写入当前时间。
  output.write(newline.get().encode("utf-8"))  # 可以输入汉字
  output = open(filename + ".txt")
  output.close
  # 暂存
  txt = open("tempfile.txt", 'a')
  txt.write(time.strftime("%d/%m/%Y %H:%M:%S"+"\n"))  # 在保存当前输入时，也保存当前时间。
  txt.write(newline.get().encode("utf-8"))  # 可以输入汉字
  txt.write("\n"+"\n")
  txt.close()
  </pre></code>

全部代码地址：https://github.com/picklecai/OMOOC2py/blob/master/_src/om2py2w/2wex0/main.py

## 现象

希望程序运行后，能把刚刚输入的文件存为独立文件。
问题：无法给独立文件命名。（上周的程序做到了给刚刚输入的内容存为可命名的文本文件。）

## 分析
- 尝试0:
  - 参考:在命令行的不算，那个用“raw_input”就可以轻松接受输入作为文件名。问题在于其他操作都在tkinter窗口里的，用户没法注意到这一步要到命令行去做。即使给了提示，也不美。
  - 判断:
  - 实验:
  - 结论:
- 尝试1:
  - 参考:用entry.bind(<'Key-Return'>)，见现在的代码。
  - 判断:本意是在新建立的文本框fn中输入，如果碰到输入了回车键，就把刚才的输入给新文件做文件名。
  - 实验:实际在运行时，不赋值。新文件名为空（.txt）。
  - 结论:
- 尝试2:
  - 参考:用按钮事件来触发输入结束。
  - 判断:借鉴上面的文件内容记录，触发了一个按钮操作后，可以记录文件内容。所以用按钮事件来存。
  - 实验:新写一个代码，command=fuzhi。运行结果跟bind一样，文件名也是空。
  - 结论:
- 尝试3:
  -参考:用if来判断是否接受了回车符。if fn.bind(<'Key-Return'>):……发现运行时全部被if包含的代码都被忽略了，也就是系统认为不符合这个条件。
  -...还试过该fuzhi函数的参数、返回等，后来统一用现在这个形式的fuzhi函数。
-    以上尝试都用print filename检验过，打印结果都是空，不接受任何从fn输入的内容。

为什么让用户输入文件名，没法像把输入内容放入文件里一样操作呢？同样是使用用户输入结果？

**Comment by ZoomQuiet** [comment]
all echo in 2wd4 ;-0
