### ISSUE TITLE
[2wd4]公开课 笔记汇总

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#61]
- 前提: 参加 2wd4 公开课,或是看过回放
- 资源:
  - [录音](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151029_2wd4/index.html)
  - [幻灯](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151029_2wd4/OMOOC2py2wd4_DUP.pdf)
  - 视频,见[芝麻星](http://www.iomooc.com/)系统卡包
  - [教练随堂讲解手记 ](https://github.com/OpenMindClub/OMOOC2py/issues/57#issuecomment-152456669)
- 时限: 3wd0 20:20 前
- 行动: 回复此 Issue 给出对应笔记的 URL
  - 不用 `@` 任何人
  - 仅仅是直达链接即可
- 内容: 
  - 公开课对自己触动最大的 top 3 内容
  - 对比自己过往行动, 应该有哪些可以应用以上三点建议进行改进的?
  - 给出具体改进的方案来
    - 针对当前具体的学习/技术/提问...问题
    - 方案描述尽可能包含所有 [5W1H](http://wiki.woodpecker.org.cn/moin/5W1H) 要素!

**Comment by shawn0lee0** [comment]
[公开课笔记](https://shawn0lee0.gitbooks.io/python-omooc2py/content/0MOOC/2015_10_22.html)

**Comment by JeremiahZhang** [comment]
> 资源:
>     录音
>     幻灯
>     视频,见芝麻星系统卡包
- 录音 与 幻灯       连接出错 点击 还是在此页面 补连接 http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151029_2wd4/index.html
- 视频 芝麻星系统 还未更新 2W 视频&课件:编程思维的实战 卡片

**Comment by sunnyhuang42** [comment]
@JeremiahZhang 多谢提醒,已经更新

**Comment by jameszhou89** [comment]
今晚完成
https://jameszhou89.gitbooks.io/moocpy2/content/2w4.html

**Comment by sunoonlee** [comment]
[2w-最小代价/详细记录/提问](https://sunoonlee.gitbooks.io/omooc2py/content/0MOOC/2wd4-notes.html)
文中我对课程核心目标及实现方法的想法如何？请指教

**Comment by jasonycliu** [comment]
https://jasonycliu.gitbooks.io/omooc2py/content/1sTry/2wd4.html
写得不好,请大家留言指正.谢谢!

**Comment by ZoomQuiet** [comment]
On Sat, Oct 31, 2015 at 11:20 PM, jasonycliu notifications@github.com wrote:

> https://jasonycliu.gitbooks.io/omooc2py/content/1sTry/2wd4.html
> 写得不好,请大家留言指正.谢谢!

嗯哼?! 此处有逻辑问题!
- 如果你自个儿知道哪里写的不好,为什么不改进好了再发布?!
- 如果你自个儿不知道写的好不好,为什么直接先否定了自个儿!?
- 其实吧,我们日常被灌输的各种所谓礼貌,其实包含了非常恶意的三观
- 要通过 编程思维的训练,能自我觉醒, 完成模因的升级,清除对自个儿心智成长没有好处的 D版软件!

**Comment by cxiaodian** [comment]
笔记
https://cxiaodian.gitbooks.io/omooc2py/content/0MOOC/lecture_four.html
另外，问下大妈，vim里面用于python编程的，推荐哪些插件？例如我看你视频里面，代码写错，vim有提示的那个插件是什么？

**Comment by xpgeng** [comment]
2wd4 NoTe
https://xpgeng.gitbooks.io/omooc2py/content/0MOOC/2wd4.html

**Comment by Cen74** [comment]
周六看的回放，请指正
https://cen74.gitbooks.io/omooc2py/content/note/w2d4_note.html

**Comment by faketooth** [comment]
周日观看回放
https://faketooth.gitbooks.io/omooc2py/content/0MOOC/2w/note_2wd4.html

**Comment by ZoomQuiet** [comment]
2015-11-01 19:56 GMT+08:00 cxiaodian notifications@github.com:

> 笔记
> https://cxiaodian.gitbooks.io/omooc2py/content/0MOOC/lecture_four.html
> 另外，问下大妈，vim里面用于python编程的，推荐哪些插件？例如我看你视频里面，代码写错，vim有提示的那个插件是什么？
- 真没注意,俺只是根据几篇配置指南配置好,再没有折腾过,,,

**Comment by zoejane** [comment]
[节奏与不断靠近 by Zoe](https://zoejane.gitbooks.io/omooc2py/content/1sTry/video3.html)

**Comment by WhaleChen** [comment]
[第三周笔记](https://whalechen.gitbooks.io/omooc2py/content/document/week2day4.html)

**Comment by bambooom** [comment]
https://bambooom.gitbooks.io/omooc2py/content/notes/2wd4.html

**Comment by liangpeili** [comment]
[week3公开课笔记](https://liangpeili.gitbooks.io/omooc2py/content/week3/week3-opencource.html)

**Comment by aJiea** [comment]
w2 笔记[《水母交响曲》](https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/3w_net.html)

**Comment by picklecai** [comment]
https://github.com/picklecai/OMOOC2py/blob/master/0MOOC/note3.md

**Comment by sunnyhuang42** [comment]
过期关闭
