### ISSUE TITLE
[3wd0] 深圳 C2T2 报名

### ISSUE THREAD

**Issue by demonmax** [OpenMindClub/OMOOC2py#62]
时间: 11.01 周日 13:42~15:42

地点: 南山区南海大道222号海王大厦A座18E 
(开智群友Kelly提供的场地 如有更好的场地提供 请回复留言)

交通引导  >> 
地铁:海岸城 需步行一段距离 
公交站: 海雅百货或亿利达大厦 

备注:本周属学员自行组织交流学习 技术教练不一定到场  free"可能"到场

报名: 回复说明以下关键信息

github 帐号
电脑操作系统
简述当前学习进度
描述希望现场讨论解决的问题

截止: 11.01周日 11:42 前有效

提醒: 尽可能带上电脑,以便现场重现和明确技术问题的细节 ;-)

@OpenMindClub/py2prd

**Comment by sherlockhoatszx** [comment]
报名。
github 帐号:sherlockhoatszx
电脑操作系统:Mac OS X
简述当前学习进度: GUI未完成，但是来之前我会做完的。
描述希望现场讨论解决的问题：大妈上课的操作界面是什么...W3的任务进度。

**Comment by bambooom** [comment]
github 帐号: bambooom
电脑操作系统: win7
简述当前学习进度: 3w任务前期调查
描述希望现场讨论解决的问题: 
    \* 3w任务讨论
    \* 待增补

**Comment by RichardSZ** [comment]
报名。
github 帐号:RichardSZ
电脑操作系统:Win 7
简述当前学习进度: 1W 任务
 描述希望现场讨论解决的问题：千头万绪待整理。

**Comment by rayxiehui** [comment]
报名。
github 帐号:rayxiehui
电脑操作系统:Mac OS X
简述当前学习进度: GUI未完成，

# 深圳python线下聚会

### 一句话，好高兴呀，好高兴，好高兴。

#### 大致过程：在天使巧玉提供的场地那里集合，先报告各自学习进度与问题，然后助教与学习领先者来回答。晚上聚餐聊聊天，扯扯淡。

#### 我所遇到的主要问题：
- mac使用不够熟练，当做window来用，导致很多他人的演示无法看懂。
- iterm 没有进行配置，也不知道需要什么配置。
- git 命令还是很不熟练，不太明白github与svn区别。
- 平时不够努力，进度有点慢，c/s还没有开始。

#### 所解决的：
- free 演示了iterm的分屏操作，知道了大概是怎么一回事，回去再去找资料。
- iterm 其它配置与形式，阳老博客有相关的，自己去看。
- 联想了mac的分屏功能，回去查资料解决，果然很棒。
- 动力，看到竹子的进度，汗颜。更有动力了。
- 讨论中，明白了git的更多用法，以及github的设计思想，但是还需要一次比较全面系统的学习一次。

#### 关于晚上聚会：
- 其实我记不住有什么重点了，就是大家都很开心的聊聊天。
- 学员背景相差很大,闲聊中对思维有一定的开拓。
- 增进了感情，感觉问问题时候可以更加的肆无忌惮了。

**Comment by leonpak** [comment]
github 帐号:leonpak
电脑操作系统:Mac OS X
简述当前学习进度: GUI未完成
描述希望现场讨论解决的问题：请教0week到2week碰到的各种小问题

**Comment by ivanlau** [comment]
账号: ivanlau
系统: win/linux
进度: gui未完成
问题: 待整理

**Comment by crazy-tea** [comment]
账号:  crazy-tea
系统: win
进度: gui
问题: gui和日记中部分函数的问题

**Comment by sherlockhoatszx** [comment]
本次交流心得：
缘起：深圳的小伙伴们太热情，深圳本周又组织了线下交流活动，并感谢kelly提供高大上的场地和Free的友情出席。
本次交流结束后，我发现我对原来看见了但是没有走心的开智solgan和八荣八耻有了更深的体会。比如这条：“不止学编程，更提升思维，同侪共进，交朋友”，这个是开智希望达到的目的，也是我们应该达到的结果啊。我只把注意力放在了学Python,而忽视了学习方法论和交朋友，现在想来是不对的。即便我们把大妈的作业都做完了，那以后再遇到新的问题呢，背景知识要怎么获取，程序出现问题要怎么分解和验证，这些方法也是同等重要的啊。所以本次的收获就试下从solgan的几个方面总结下：
学编程：1,Ivan同学再次热心的普及了git的工作原理（本地-缓存-服务器）和git命令，以及和SVN的不同。2、free展示了分屏的软件和操作方式。3,以最小的代价解决问题，不要自己给自己挖坑，聚焦问题，迭代的方式来解决。4,我带着W3的问题来请教的，Free告诉了我两点:a,打印日志试下；b,看文档要注意参数和return。 file.write()的输出是什么？（是string吗？还是None?）。就这样，我在程序里加了几行print，然后在终端一行行的看，找出了if模块下一段不运行的地方，去官方文档看file.read, file.write,file.write(‘a+’)的输出是什么，什么时候输出。成功改好了程序。现在回过头看，w1的日记虽然写好了代码，但是对里面的功能了解并不深入。5,最后，大家对类和对象又进行了讨论，free讲了面向对象的抽象关系，三个特征：封装，继承，多态。我觉得这跟柏拉图认知论中的原型和共相有点像。但是我预感这个话题会持续一段时间。
练思维：1,free表示虽然大妈的回复让大家有压力，但是大家依然要问。提问是获得新思维的起点。对此我在反省中。
同侪共进：大家根据进度分组讨论，对w1,w2的任务难点进行了分解。
交朋友：在友好的气氛中，大家围观了妹子跑代码，继承和发扬了深圳站的优良传统。

End

**Comment by csufuyi** [comment]
我先写个纪要, 坐等组织者@demonmax的活动总结和其它参与同学的总结.
学习内容的总结可以写到自己的gitbook里面, issue中增加uri就好.

# 3wd0 深圳 C2T2 纪要

## 活动召集

demonmax 发起了活动召集,共8位小伙伴参加线下活动
@rayxiehui
@demonmax
@sherlockhoatszx
@bambooom
@RichardSZ
@crazy-tea  
@ivanlau 
@leonpak
- [召集令](https://github.com/OpenMindClub/OMOOC2py/issues/62)

## 录音

本期没有特殊的讲解，由教练掌握进度，汇总问题,自由讨论居多，故没有录音,下次尝试具体问题录屏分享

## 照片

http://pan.baidu.com/s/1bnc8V9t

## 活动流程
- `30min`个人介绍和当前进展，问题
  - 个人信息
  - 学习进展，问题概述
- `3hour`学员内部交流+教练现场巡山
  ivanlau做了小手术住院了,病床上还听完了课,感动深圳
  ivanlau主动解答了回答学员github使用的困惑
  leonpak专程从东莞过来参加深圳线下聚会
  bambooom妹子进展最快,帮助学员解决问题

## 主要问题
- 芝麻星卡片有背面很多人不知道
- git的理解有待进一步挖掘, 使用过程中的报错信息要勇气看懂
- 学员好奇大妈tmux的使用和录屏软件的使用
- pyenv的使用场景困惑
- 如何使用打日志的方式定位问题
- 如何本地化查找官方文档

## 场地方面
- 感谢巧玉提供的场地支持,还买水果,好感动!
- 海王大厦的场地很好,但毕竟不能老麻烦巧玉;部分同学距离较远.
- 下次尝试福田金中环七楼的场地.
- 场地有小白板最佳

**Comment by leonpak** [comment]
本次深圳C2T2体会：
昨天匆匆来匆匆地走，赶地铁赶火车，回到家洗个澡已经很晚了，抱歉这迟来的总结啊_-_
感谢各位热情好客的深圳小伙伴们，感谢美女kelly提供的聚会场地和普及一些珠宝的课外知识，free老师耐心指导，ivan大胡子自告奋勇的讲解git工作原理，竹子妹子哗啦哗啦的演示代码。。。
1.自己对git工作原理有更深一次认识，之前遇到问题就直接百度，google，忽视了cli的英文提示，也了解到之前在cli同步时产生的错误是因为本地和网络端同时都修改了，产生了版本冲突。(pull后再push解决)。
2.自己对问题准备还是不足，从东莞去一趟深圳南山区来回时间成本还是不低的，没有充分利用C2T2聚会时间，下次要对问题吃透点吃多点再请教各位小伙伴。
3.对纯cli的使用还不是很习惯，向free老师基本上所有操作都在cli的习惯看齐
4.看了free老师演示tmux，自己要再深挖一下
5.学习是一个孤独的过程，但也是一个结伴同行的旅程，很高兴认识各位深圳小伙伴，希望以后能多交流学习。

**Comment by sunnyhuang42** [comment]
归档
