### ISSUE TITLE
[3wd4]广州 线下活动报名

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/OMOOC2py#64]
- 地点: 广州 天河区 珠江新城 华夏路30号 富力盈通31F 3110 会议室
- 时间: 周四 19:42~22:22
- 报名: 回复说明以下关键信息
  - github 帐号
  - 大约到达时间
  - 期望现场解决的技术问题
- 截止: 周四 10:10 前有效
- _提醒:_ 必须带上电脑,以便现场明确技术问题的细节 ;-)

![151105c2t2gz_sign.jpg](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151105_3wd4/151105c2t2gz_sign.jpg?imageView2/2/w/360)

~ 大家一致测定现场不来 MM 就不合影了...
- QA 录音:
  - [om2py3wd4_09_c2t2_class_ZOOM0122.MP3](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151105_3wd4/om2py3wd4_09_c2t2_class_ZOOM0122.MP3)
  -  [om2py3wd4_10_c2t2_flow_ZOOM0123.MP3](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151105_3wd4/om2py3wd4_10_c2t2_flow_ZOOM0123.MP3)
  -  [om2py3wd4_11_c2t2_subl_ZOOM0124.MP3](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151105_3wd4/om2py3wd4_11_c2t2_subl_ZOOM0124.MP3)
  -  [om2py3wd4_12_c2t2_try_ZOOM0125.MP3](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151105_3wd4/om2py3wd4_12_c2t2_try_ZOOM0125.MP3)
  -  [om2py3wd4_13_c2t2_local_ZOOM0126.MP3](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151105_3wd4/om2py3wd4_13_c2t2_local_ZOOM0126.MP3)

问及 subl 的配置,俺的公开过的....

``` json
{
    "caret_extra_bottom": 1,
    "caret_extra_top": 1,
    "caret_extra_width": 1,
    "caret_style": "phase",
    "color_scheme": "Packages/Theme - Spacegray/base16-eighties.dark.tmTheme",
    "draw_white_space": "selection",
    "env":
    {
        "GOPATH": "$HOME/Works/com.cmcm/CMB/cmbackup/trunk/bmts"
    },
    "file_exclude_patterns":
    [
        ".DS_Store"
    ],
    "findreplace_small": true,
    "folder_exclude_patterns":
    [
        "bin",
        ".bundle",
        ".hg",
        ".git",
        ".sass-cache",
        ".svn",
        "CVS",
        "__pycache__",
        "tmp"
    ],
    "font_face": "Input",
    "font_size": 18.0,
    "gutter": true,
    "highlight_line": true,
    "highlight_modified_tabs": true,
    "ignored_packages":
    [
        "Markdown",
        "Restructured Text (RST) Snippets",
        "Vintage"
    ],
    "indent_to_bracket": true,
    "installsuffix": "appengine",
    "line_numbers": true,
    "margin": 4,
    "open_files_in_new_window": false,
    "rulers":
    [
        79
    ],
    "save_on_focus_lost": true,
    "scroll_past_end": false,
    "show_encoding": true,
    "show_full_path": true,
    "sidebar_default": true,
    "spell_check": false,
    "tab_size": 4,
    "tabs_small": true,
    "theme": "predawn-DEV.sublime-theme",
    "translate_tabs_to_spaces": true,
    "wide_caret": true,
    "word_wrap": true,
    "wrap_width": 80
}
```

**Comment by lixiguangzhou** [comment]
github 帐号：lixiguangzhou
大约到达时间： 19:30

**Comment by junjielizero** [comment]
github 账号： junjielizero
大约到达时间：19:30
第一次来，且在天河下班高峰期赶来，如未能及时到达，请大家见谅

**Comment by penguinjing** [comment]
github 账号： penguinjing
大约到达时间：19:20

**Comment by ZoomQuiet** [comment]
过期无人交记要,,,
桑心关闭
