### ISSUE TITLE
[待定]杭州 C2T2 报名

### ISSUE THREAD

**Issue by wwulfric** [OpenMindClub/OMOOC2py#65]
本周周末有事请所以可能无法到场。如果杭州的学员希望我到场，可以选择：1.周四晚上（一起看课程并讨论），2.周日晚上，3.次周周一晚上。如不需要，则可以自己选择周末中任一天

地点: 同上次。西湖区万塘路 allface 咖啡厅

报名: 回复说明以下关键信息

github 帐号
电脑操作系统
简述当前学习进度
描述希望现场讨论解决的问题

截止: 11.06周日 11:42 前有效

提醒: 尽可能带上电脑,以便现场重现和明确技术问题的细节 ;-)

**Comment by shawn0lee0** [comment]
- 账号：[shawn0lee0](https://github.com/shawn0lee0/OMOOC2py)
- 系统：Win7 32
- 进度：Socket熟悉中
- 问题：
  -    [TK_GUI编程多窗口关闭陷入死循环](https://github.com/shawn0lee0/OMOOC2py/tree/master/_src/om2py2w/2wex0)
  -    Socket用于网页编程
  -    待定
- 时间：建议方案2或者周日下午

**Comment by conn820** [comment]
- 账户：conn820
- 系统：win7 64
- 进度：Socket
- 问题：
  - 缺乏对网络协议等概念的深入了解
  - class的熟练掌握
  - 待定
- 时间：
  - 周日晚
  - 次周一晚
