### ISSUE TITLE
[3wd6] 深圳C2T2报名

### ISSUE THREAD

**Issue by csufuyi** [OpenMindClub/OMOOC2py#66]
- C2T2 活动规则
  - 以`学员互助`为主，学员互助自由交流时间必须大于教练一对多单向输出的时间
  - 参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
    - 并附带 42 字内文字说说自己今天最大的收获
- 地点: 深圳福田区金中环酒店公寓7楼DreamHouse. 暂定于此,若被包场,另行通知.会展中心地铁站
- 时间: 周六 14:30~17:30
- 报名: 回复说明以下关键信息
  - github 帐号
  - 大约到达时间
  - 期望现场解决的技术问题
- 截止: 周五 24:00 前有效
- _提醒:_ 必须带上电脑,以便现场明确技术问题的细节 ;-)

参考:
-  [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)
-  [[1w] 各地 C2T2 要点汇总](https://github.com/OpenMindClub/OMOOC2py/issues/63)
- [[0w] 各地 C2T2 纪要及录音、讲演材料](https://github.com/OpenMindClub/OMOOC2py/issues/42)
- 注意:弃用`面基`一词, 这是个极其恶意的 KUSO 名词!

**Comment by RichardSZ** [comment]
github 帐号: RichardSZ
系统: win 7
大约到达时间: 2:30pm
期望现场解决的技术问题:  图形界面的文字输入和保存

**Comment by sherlockhoatszx** [comment]
github 帐号: sherlockhoatszx
系统: mac osx
大约到达时间: 2:30pm
期望现场解决的技术问题:tkinter的控件输入，w4 网页版任务

**Comment by Jessicamiejiu** [comment]
github 账号: jessicamiejiu
mac
2:30pm
把前面作业补上 TT

**Comment by csufuyi** [comment]
今天free要加班 @badboy315 和你们一起哈 有问题可以在线支持哈

**Comment by xiangzhendong** [comment]
github 帐号: xiangzhendong
系统: macosx10.10
大约到达时间: 2:30pm
期望现场解决的技术问题: tkinter多行文本输入与保存／中文输入与保存／开始web日记任务

**Comment by xiangzhendong** [comment]
3w6dC2T2纪要（主要是此次聚会的收获和事后思考与学习）
https://xiangzhendong.gitbooks.io/notesforpython/content/3w6dc2t2ji_yao.html

**Comment by rayxiehui** [comment]
3w6dC2T2纪要
https://github.com/rayxiehui/OMOOC2py/blob/master/_src/om2py3w/3wex0/%E7%BA%AA%E8%A6%81.md

# 纪要

### 整个过程感受:
- 只有努力才会有可能有收获,夏洛克每天时间很少但是任然可以每天抽出时间来学习.
- 自己的基础学习严重缺失,芝麻星很多坑没有填,很多课没有补上.
- 和大家一起交流是发现问题的最好方式.
- 美女好漂亮

### 过程:
1. 自我再次介绍,把记不清的人名再记一遍.
2. 自我报告学习进度,交流学习.
3. 我装ipython工具,填坑.
4. 阿东演示gui界面,详解代码.
5. 交流,相互解决问题,合影留恋.

### 我的坑
1. ipython没装,工作环境有点问题.
2. 装ipython过程中,遇到问题,开始以为是环境配置冲突.后来发现是没有使用管理员权限 sudo ,但是以前是不需要的,现在为什么需要?这个坑还没填.其中发现问题的过程解决比较慢,其实解决办法很简单,直接把报的错误Google搜索一下就行了,是自己还没有养成这种习惯,导致费时费力.
3. _main_ 这个坑发现了,是自执行函数的意思,在简单python教程里面有,而我还没有填这个坑.

### 人生苦短,精彩只有一瞬间,平时的努力决定了你是否能够享受到那一瞬间.

**Comment by RichardSZ** [comment]
主要是从自己出发总结了一些收获和思考，再次感谢教练和小伙伴们。
https://richardsz.gitbooks.io/szc2t2/content/chapter1.html

**Comment by badboy315** [comment]
## 3w6d ShenZhen C2T2

### 参会人员
- @弓和箭 [C2T2纪要](https://github.com/OpenMindClub/OMOOC2py/issues/66#issuecomment-154905924)
- @sherlockhoatszx [C2T2纪要](https://github.com/OpenMindClub/OMOOC2py/issues/66#issuecomment-154914888)
- @RichardSZ [C2T2纪要](https://richardsz.gitbooks.io/szc2t2/content/chapter1.html)
- @xiangzhendong [C2T2纪要](https://xiangzhendong.gitbooks.io/notesforpython/content/3w6dc2t2ji_yao.html)
- @Jessicamiejiu [C2T2纪要](https://github.com/OpenMindClub/OMOOC2py/issues/66#issuecomment-155010722)
- @rayxiehui [C2T2纪要](https://github.com/rayxiehui/OMOOC2py/blob/master/_src/om2py3w/3wex0/%E7%BA%AA%E8%A6%81.md)

### 地点

深圳福田区金中环酒店公寓7楼DreamHouse

![](http://ww4.sinaimg.cn/large/74311666jw1exuipjp135j20zk0qoh0c.jpg)

![](http://img-storage.qiniudn.com/15-11-9/44016573.jpg)

`感谢巧玉推荐美美的场地`

### 活动纪要

> 由于是自由零散讨论, 未录音

一开始的集结照

![](http://img-storage.qiniudn.com/15-11-9/74375926.jpg)
- c2t2 介绍
- 自我介绍
  - 鉴于大部分人都见过, 简单介绍  
- 讨论每周作业
  - 每人大致交流作业完成情况 
- 自由讨论
  - github
  - gui python
  - python basic
    - 类型和数据
    - 函数和控制流
    - 模块
    - 试错
- 邻座互助
  - 邻座交流每周作业知识点
  - 教练现场走动 
- 学员讲解作业
  - @xiangzhendong 讲解 gui 日记本诞生全过程.

![](http://img-storage.qiniudn.com/15-11-9/86442124.jpg)
- 技巧分享
  - 如何 google
    - 具备科学上网能力 
  - 如何小白建构知识
    - 关键字第一遍搜索
    - 知识点第二遍搜索
    - 整理知识点
    - 练习输出
    - 整合折腾 
  - 工具配置建议
    - iterm + ohmyzsh + sublime
  - 给六个月前的自己写教程
    - 给自己讲一个故事
    - 说清楚, 可以是费曼, 也可以是小黄鸭
    - 善用隐喻的力量, 从身边知识出发去解释  

### 活动合影

![](http://img-storage.qiniudn.com/15-11-9/43208188.jpg)

**Comment by sherlockhoatszx** [comment]
https://sherlockhoatszx.gitbooks.io/pyjourney/content/about_c2t2_szx.html

自己的收获：
1、从最小的单元做起，并不断迭代。掌握任务的节奏.貌似有本书叫rework(中文版：重来）里面提到的less mass,之类方法论比较切近需要。
2、网上搜索要靠近知识的源头。从官方文档开始，并通过官方文档来判断和排序其他资料的靠谱程度。

---

`弓和箭`[纪要地址已经增补](https://github.com/OpenMindClub/OMOOC2py/issues/66#issuecomment-154905924)

**Comment by Jessicamiejiu** [comment]
收获：
真的不能再用旧方式，觉得自己准备好了再写作业，笨方法看到40课了，才开始写第二周作业TT..
可以先尝试自己能够完成的部分，再慢慢根据作业要求去拓展知识
小伙伴的指导很暖心，耐心教同学的男生最帅了~

---

`弓和箭`[纪要地址已经增补](https://github.com/OpenMindClub/OMOOC2py/issues/66#issuecomment-154905924)

**Comment by badboy315** [comment]
纪要 100% 交齐!!!
开心 关闭.
