### ISSUE TITLE
[4wd0]上海 C2T2 报名

### ISSUE THREAD

**Issue by cp4** [OpenMindClub/OMOOC2py#68]
- 活动规则
      参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
      并附带 42 字内文字说说自己今天最大的收获
- 地点
       [白鸟咖啡](http://m.dianping.com/appshare/shop/22446101) 
       瑞金二路-198弄-1
- 时间
      周日 14:00~17:30
- 报名： _回复说明以下关键信息_
  - 本周学习处于哪一阶段（攻坚哪周作业）
  - 当周作业是否开始，进展程度？
  - 所有你无解的问题及你的OS（可以参考别人的问题）
  - 你的 gitbook 教程链接
- 提醒
       请带好个人电脑，笔纸等，准时到达

**Comment by jameszhou89** [comment]
本周学习处于哪一阶段（攻坚哪周作业）: 3W的课程
当周作业是否开始，进展程度？：刚刚开始做
所有你无解的问题及你的OS（可以参考别人的问题）：还在进行中，不确定
你的 gitbook 教程链接：https://www.gitbook.com/book/jameszhou89/moocpy2/details

**Comment by haruhi99** [comment]
本周学习处于哪一阶段（攻坚哪周作业）: 2w3w的作业
当周作业是否开始，进展程度？：第四周作业尚末开始作
所有你无解的问题及你的OS（可以参考别人的问题）：系统MAC，如何在自己系统上架设个服务器自己给自己测试。等等
你的 gitbook 教程链接：暂时没有更新。

**Comment by cp4** [comment]
## 活动纪要

### 与会同志

刘昌坤，陈衢，李青泉 @haruhi99 ，周慧明 @jameszhou89 ，小宇， 胡淑珍，Danny，刘丹（开智群友），王培炎

### 会议程序
- 教练讲解
  - 互联网协议结构
    - What: IP
    - Why: TCP, UDP
    - How:  FTP, Http
  - Socket 编程接口
  - 演示TCP / UDP/ HTTP 抓包
- 学员练习、交流

### 资料
- 照片
    链接：http://pan.baidu.com/s/1gdArg3p 密码：bj6m

@ishanshan

**Comment by WhaleChen** [comment]
## 活动记录：

[20151108 C2T2上海聚会记录](https://whalechen.gitbooks.io/omooc2py/content/document/C2T2_151108Notes.html)
@cp4 
谢谢教练的logo！教练费心了！谢谢！Enjoy coding~ 
_人生苦短，python当歌_

**Comment by cp4** [comment]
我讲了点基础概念，你自己又查了很多资料，赞！
之前的任务都及时完成了，也在教程里增补吧
disqus 再试试配置？上次 cherHu 的配置成功了
_logo是课程组为大家准备的，我借花献佛咯_
