### ISSUE TITLE
[4wd0]珠海 报名学习

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#71]
- C2T2 活动规则
  - 以`学员互助`为主，学员互助自由交流时间必须大于教练一对多单向输出的时间
  - 参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
    - 并附带 42 字内文字说说自己今天最大的收获
- 时间: 周日 15:15~17:17
- 地点: 珠海 吉大 景山路 莲山巷8号 金山软件大厦 F12 会议室
- 报名: 回复说明以下关键信息
  - github 帐号
  - 电脑操作系统
  - 当前课程 top3 问题, 参考: [[0w]当周课程 技术问题讨论](https://github.com/OpenMindClub/OMOOC2py/issues/3) 描述格式
- 截止: 周五 12:12 前有效
- _提醒:_ 尽可能带上电脑,以便现场明确技术问题的细节 ;-)
## 记要
- 录音: [151108_C2T2zh/](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151108_C2T2zh)
- 合影:

![151108OMzh.jpg（JPEG 图像，960x1440 像素） - 缩放 (55%)](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151108_C2T2zh/151108OMzh.jpg?imageView2/2/w/240)
- 记要: 老规矩, 48小时以内,回复记要内容或是记要链接

参考:
-  [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)
-  [[1w] 各地 C2T2 要点汇总](https://github.com/OpenMindClub/OMOOC2py/issues/63)
- [[0w] 各地 C2T2 纪要及录音、讲演材料](https://github.com/OpenMindClub/OMOOC2py/issues/42)
- 注意:弃用`面基`一词, 这是个极其恶意的 KUSO 名词!

**Comment by aJiea** [comment]
github账号  https://github.com/aJiea
mac
课程于我有两大福利
1.［编程知识］
     处于被动方式，为了完成任务而去编程。在实际生活中还没有用这个技能去实战过（其中也有时间因素）。编程流程：
- 芝麻星任务提示
- 不看背面教程如何完成任务的流程构想和会遇到的问题的构想
- 芝麻星背面攻略提示
- 根据提供的链接搜索信息
- 不明白处另行搜索案例
- 研究各种案例－ 看懂 －根据任务要求进行筛选
- 有用案例commit存成模版
- 根据搜索到的内容对自己的代码进行调整
- 运行，测试，对比，修改

2.［技术思维］
当时报名是为了让自己有技术方面的思维方式，就几周来学到的知识帮助我能够从另一个层面分析问题，也在这种思维方式下帮助团队解决了一些小的实际问题。

综上所述对［编程知识］运用是一个很被动的流程。
技术方面的问题，整理后在周日12pm之前更新于此。

**Comment by aJiea** [comment]
笔记
https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/2015-11-08.html

**Comment by douzhipin** [comment]
时间：2015年11月08日15:15~17:17

地点：珠海 吉大 景山路 莲山巷8号 金山软件大厦 F12 会议室

人员：大妈、阿捷、豆制品

## 前言
- 先自我介绍下，隔壁「像黑客一样创作」课程班（以下简称黑客创作班）的学员，借PY2期线下面基的机会，问关于黑客班作业中遇到的问题。
- 面基主要还是以PY2期课中的问题为主。

## 正题

每次和大妈面基后就会捡到很多坑在等着我，于是这次也不例外，除了我自身碰到的问题外，在阿捷与大妈对谈中，我也自对坑了下。

**“if this then that”**
- 关于PY2期班开班时，就报不报班这个问题，我问自己，对现在的工作有什么用处，现在自己有什么事情是需要用PY来解决的？似乎没有。
- 关于PY2期珠海线下面基，第一次线下活动的时候，我问自己，没上过课，不懂PY，去了线下面基对我有什么用处？似乎没有。

但是
- 如果没有报了黑客创作班，就不会知道原来敲对代码不会有人告诉那是对的，可以继续这件事。
- 如果没来线下面基，就不会知道原来用了那么多年的FF，其实我没有真正了解过它。

学习编程不是说以后自己要成为技术人员，而是可以利用编程的思维去做事情，如果工作中需要与技术人员沟通，也可以更好的表达，提升效率。

> IFTTT 是 If This Then That 的缩写，它是一个新生的网络服务平台。
> 
> 通俗的来讲，IFTTT 的作用就是如果触发了一件事，则执行设定好的另一件事。所谓的「事」，指的是各种应用、服务之间可以进行有趣的连锁反应。IFTTT 的宗旨是 Put the internet to work for you （让互联网为你服务）。用户可以在 IFTTT 里设定任何一个你需要的条件，当条件达到时，便会触发下一个指定好的动作。它就像是一座神奇的桥梁，能连接我们日常所用的各种网络服务。

**什么是黑客？**

> - 什么是「像黑客一样创作」
> - 什么是黑客

被大妈问了这两个问题。当然我当时没有回答上来，于是有了作业，还有指了两条路给我。
- 路1：阳老写的[像黑客一样学习与写作](http://www.douban.com/group/topic/39939196/)，其实黑客创作班也是基于了这篇文章。
- 路2：Eric Raymond写的[如何成为一名黑客](http://blog.chinaunix.net/uid-20676507-id-1899797.html)

**方地球  圆地球**

在我以为的世界里活了那么多年，突然打开了新世界，有点不太适应。
- 方式：对图形界面的依赖是基于长期使用Windows，但是要「像黑客一样创作」，我需要了解代码命令。
- 效率
  - 条条大路通罗马，我已经在一条路上走进了死胡同，为何不换条路走。
  - 根据自身需求，寻找工具。
- 课程教学：曾以为课程会像手把手教学的方式，但要像黑客一样，问别人前要先学会自问。入门教程和基础问题在网上是有大量的教学贴。

当你向前了一步，对世界的理解就更进一步。

**最后**

本次面基感想：原来跑火车可以如此的专业

听录音感想:大妈，你最近是打算学习如何打鼓吗

**Comment by ZoomQuiet** [comment]
按时提交了作业  happy close issue
