### ISSUE TITLE
[5wd0] 深圳C2T2报名

### ISSUE THREAD

**Issue by bambooom** [OpenMindClub/OMOOC2py#77]
- C2T2 活动规则
  - 以`学员互助`为主，学员互助自由交流时间必须大于教练一对多单向输出的时间
  - 参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
    - 并附带 42 字内文字说说自己今天最大的收获
- 地点: 深圳罗湖区鸿隆世纪广场A座24楼A（地铁1号线老街站B出口过铁路桥就是）感谢 @RichardSZ 提供场地
- 时间: 周日 13:30~17:00
- 报名: 回复说明以下关键信息
  - github 帐号
  - 大约到达时间
  - 期望现场解决的技术问题
- 截止: 周日 11:00 前有效
- 提醒: 必须带上电脑,以便现场明确技术问题的细节 ;-)

参考:
- [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)
- [[3w] C2T2 汇总](https://github.com/OpenMindClub/OMOOC2py/issues/76)
- [[1w] 各地 C2T2 要点汇总](https://github.com/OpenMindClub/OMOOC2py/issues/63)
- [[0w] 各地 C2T2 纪要及录音、讲演材料](https://github.com/OpenMindClub/OMOOC2py/issues/42)
- 注意:弃用面基一词, 这是个极其恶意的 KUSO 名词!

**Comment by sherlockhoatszx** [comment]
报名: 
github sherlockhoatszx
大约到达时间:1:30
期望现场解决的技术问题:w4 命令行request,数据库连接  w5 任务分解

**Comment by RichardSZ** [comment]
报名
RichardSZ
12:00

**Comment by rayxiehui** [comment]
### 报名

```
期望解决w4问题
```

**Comment by demonmax** [comment]
报名: demonmax
12:00

**Comment by jasonycliu** [comment]
报名:
github: jasonycliu
大约到达时间:12:00
期望现场交流5w任务

**Comment by Jessicamiejiu** [comment]
github:Jessicamiejiu
Mac
4W&5W任务讲解

**Comment by csufuyi** [comment]
## 5wd0 ShenZhen C2T2

### 参会人员

@rayxiehui
@ivanlau
@demonmax
@RichardSZ 
@Jessicamiejiu 
@sherlockhoatszx 
@bambooom 
@jasonycliu

### 地点

深圳罗湖区深南东路鸿隆世纪广场

### 照片及部分录音

照片:http://pan.baidu.com/s/1qWMk6Fa

部分录音:http://pan.baidu.com/s/1i3qAJlV
热烈讨论部分因为技术原因缺失, 只有部分自由讨论录音,吸取教训.

![围观妹子演示自己的代码](http://7xjfyz.com1.z0.glb.clouddn.com/c2t2_shenzhen_5wd0_1.jpg)

### 感慨

感谢@RichardSZ军哥提供高大上的场地, 美味的食物!
军哥下午要出差赶飞机, 依然坚持参加C2T2, 点赞!

@bambooom竹子妹子进展最快,给大家讲解自己的作业思路, 主动组织C2T2, 值得男同胞们奋起直追!  
追啊!(你懂的)

@jasonycliu 奶爸挤出时间参加活动, 可贵!

大大的会议室, 还真有当年自习课的感觉. 当年都是被动的学习,如今是职场人主动的自我升级修炼, 满满的正能量.

### 过程总结

@bambooom讲解了自己基于SAE部署的作业的思路, 过程中回答各种问题.
大家讨论了构建一个web应用过程中涉及到的技术层次.
重点提到了根据bottle官方文档结合大妈课程来完成作业.

教练提示可以用saecloud部署本地环境, 加快编程过程的反馈循环.
windows下的saecloud的部署问题需要解决.

@Jessicamiejiu演示了GUI的作业部分, @rayxiehui帮助补回用github的命令行管理代码.

@jasonycliu讲解了自己选用requests包过程中的周折过程.

### 改进建议

下次更好的录音;用上投影设备, 让每个人更好的讲解自己的解决问题的过程.

期待看到大家的总结与问题.

**Comment by ouyangzhiping** [comment]
## 被动 VS 主动

「大大的会议室, 还真有当年自习课的感觉. 当年都是被动的学习,如今是职场人主动的自我升级修炼, 满满的正能量.」 赞！

## 最小测试

「bambooom讲解了自己基于  SAE  部署的作业的思路, 过程中回答各种问题.」

这里可以延伸到一个话题，多数  API  、第三方软件是如何给大家提供「最小测试」环境的？ CLI  、GUI  、云端刷新，大家为什么一上来没有发现  SAE  也可以本地调试？

比如，SAE，不少同学一上来只发现推送到云端然后刷新页面提交的方式；Github 大家刚开始只发现页面配置双推的方式。如何用最快速度获得一个新的知识点的「最小测试」环境？

## 反馈

「加快编程过程的反馈循环」 ，反馈这个话题可以继续往前延伸，那么马上就是的Paul Graham雄文：如何创造财富了：[Paul Graham:如何创造财富](http://www.douban.com/note/517740126/)

各位同学可以尝试思考一下，
- 传统生物学&心理学实验，反馈周期的快慢；
- 来自计算机的反馈周期的快慢。

科学是个试错与寻找证据的过程。试错成本很低，仅需要一台笔记本电脑；试错很快，反复进行模拟与假设，快速迭代很多轮；哪样的学科，更容易创造财富？更容易获得更大成果？

同时，可以思考一下，获取**人的反馈**始终会存在**不稳定**等现象，那么，如何才能更快地获得自己想要的**积极反馈**？写下来、开源出去，显然是第一步。

再借助「物化在外」的东西，来获取人的反馈容易？还是用**头脑中杂乱的思想**获取反馈容易？

**Comment by sunnyhuang42** [comment]
其他人的纪要捏？ @OpenMindClub/py2prd 

 Issue 过期先关闭了

**Comment by bambooom** [comment]
感觉自己提的issue还是得交个总结比较好.

上次C2T2我发现其实还是很多同学习惯用百度以及表示看不懂英文文档. 就针对这两个问题我分享下自己的想法吧.

## 有关google

我不太记得大妈有没有具体说过为什么要用google. 那我说说我的情况吧.
- 因为前几年都是在香港,从大学开始就是用google和gmail.一直以来并不觉得有什么特别的. 但其实很简单,认真对比一下google和baidu出来的结果就可以很清晰的知道哪种好. 
- PS:其实当年google用中文搜索出来的结果并没有很好,我所谓的很好是第一页前3个链接就有我想要的答案. 但google一直在进步,baidu页面这么多年也没什么变化,嗯,而且长得丑
- 再以及因为上课学习的时候都是英文材料,所以一开始要努力面对英文的时候帮手也只能是google.
  - 例如有什么基础概念不懂的不记得的,google可以出来很多很多资源可供参考.一般第一个是wikipedia,大概读一下就了解了.其他往下的链接很可能是一些外国大学的课程页面资料,有些有example的也可以快速加深理解.这些都在搜索结果第一页就可以解决.
  - 如果不是这种新的概念理解或旧的知识复习,我想知道的只是一个很简单的东西,我的预期是不用打开页面,在每一条链接下方不是有预览嘛,这个里面我应该就可以看到我想要的答案了.
    - 比如我最近想练习各种excel的快捷键,今天遇到的问题就是下拉菜单怎么打开和选择.搜索excel+drop down list+shortcut,第一页就可以解决,不用点开网页链接,答案是Alt+Down Arrow.
- 来做个对比,比如说我想知道Binomial Distribution(二项式分布)是什么.
- google的结果:
  - 第一条是wikipedia的页面
  - 然后一部分是People also ask,是说一般对于这个topic其他人也会有这样的问题
  - 然后是Wolfram MathWorld的页面(Wolfram Alpha很牛逼的,几乎什么都能算而且长得很好看~)
  - 再接下来是Khan学院的教学视频
  - 再接下来是几个大学的数学系网站或者教学网站
  - 总结:第一页的内容已经非常丰富,肯定可以对一个知识点有个大概了解. google不仅提供了文字方面的说明,连教学视频都有,还有与此相关的其他问题链接.我个人的感觉是帮助我去学习,而且是多种形式的,甚至是发散式的引导我去问其他问题.
- baidu的结果(关键词"二项分布"):
  - 1.百度百科
  - 2.百度经验
  - 3.百度文库
  - 4.互动百科
  - 5.百度文库
  - 6.百度拇指医生(what???)
  - 7.MBA智库百科
  - ......
  - 不是说百度百科不能让我了解一下什么是二项分布,但是这个搜索出来的结果让我哪个都不想点开...........  
- **So Let's GOOGLE!**

## 有关英文文档
- 唔,这个的确对我来说基本无障碍.原因是我前面几年一直都在磨练.
- 回想一开始的时候也是不适应教科书资料作业都是英文,但这并不是解决不了的.
- 其实理工科真的还好,犹记得以前写作业写的最多的就是"Since....Therefore....And....So.....". 每次作业基本就用辣么几个单词用来用去.当然仅限理工科.
- 文科和社会科学,那种英文阅读量估计我这辈子都读不出来,里面的句子也是经常70%的单词不认得.考过GRE的话大概懂得是个什么感受.
- 总之还是不要怕,习惯英文文档只是个时间问题.
  - 不过并不是说单词句子都认得,你就能懂在说什么.
  - 我是数学系的,数学的重点在逻辑,所以即使一本数学书里的所有单词我都认得,但我理解不了逻辑,还是白搭.
  - 不过工科就比较直接了,有的时候不知道逻辑在哪里,但是知道怎么使用工具也可以.
    - 题外话:前天看了一篇博客说数学与编程,博主说编程是一门艺术,而数学语言是多么不规范的一种语言,总有些奇奇怪怪的希腊符号而且运算符号之间也不一致什么的..........╮(╯▽╰)╭我很想吐槽他,数学特么的重点又不在语言,为啥要和编程语言比较????
- 再后来,课业要求去读一些发表出来的学术论文,发现其实语句本身不难读懂,而且好的论文是逻辑非常清晰,结构也很清晰.
- 在学术领域,很多情况下,同样的东西如果用中文表述完全没有英文那么简洁和明了.(虽然反过来也是有可能的)
- 其实逼迫自己读英文文档,就算编程没学会,练习下英文也好嘛~!!
- 1个小建议:
  - 当初为了适(zhuang)应(bi),我把手机也设置为全英文的界面,一开始也很不习惯,而且有的时候要更改一些设置都看不懂是啥,那个时候就把手机再改回中文的,看准了在什么位置,再换回英文去找.来回几次,其实你就熟悉了适应了.
    - 以上这个还可以扩展到电脑操作系统,ipad,各种软件,gmail设定之类之类的...
    - 反正是,你见得多了自然就习惯了......

## 总之
- 其实这两个问题认真想也是同一个问题, that is **你是否想了解真实的世界**
- 在我看来, google就是我了解世界的窗口, 它让我知道有khan这样的教学视频清晰易懂, 有Wolfram MathWolrd这样的牛逼公司, 有各种英文材料让我能知道世界top的大学是怎么教授知识的.
- 所以我不想只局限在百度百科,百度文库.........
- 也希望小伙伴们不要局限自己.......
