### ISSUE TITLE
[5wd0]上海 C2T2 报名

### ISSUE THREAD

**Issue by jameszhou89** [OpenMindClub/OMOOC2py#78]
C2T2 活动规则
以学员互助为主

地点: Mlily梦百合咖啡厅

链接：http://map.baidu.com/detail?qt=ninf&uid=8b1a15e214544eafcf06a40c&wd=mlily%E6%A2%A6%E7%99%BE%E5%90%88%E5%92%96%E5%95%A1%E5%8E%85&b=(13517218.97,3633500.75;13534130.97,3644812.75)&query=&qid=&page_num=&detail=cater&from=map&ugc_ver=1

时间: 周日 9:00~12:00

报名: 回复说明以下关键信息
github 帐号
大约到达时间

截止: 周日 11:00 前有效
提醒: 必须带上电脑 ;-)

**Comment by jameszhou89** [comment]
@cnfeat 交作业啦
https://jameszhou89.gitbooks.io/moocpy2/content/offline_c2t2_w4.html

**Comment by sunnyhuang42** [comment]
哈，收到啦

> 发现两个同学停留在2w的作业里面，所以觉得应该有一部分同学还停留在比较早的作业里面。
> 同学们还是有点轴，希望可以循序渐进的做完作业。不过确实每个作业都是独立的，并不一定要一个接着一个做。

嗯，适时止损非常必要。尤其完成了 _w 的任务，对减少完成 （_+1)w 的任务时间帮助不大时，那还是先尽快空降到课程当前进度，跟上节奏增加成就感吧：D  @OpenMindClub/py2student
