### ISSUE TITLE
[5wd6] 深圳C2T2报名

### ISSUE THREAD

**Issue by csufuyi** [OpenMindClub/OMOOC2py#79]
- C2T2 活动规则
  - 以`学员互助`为主，学员互助自由交流时间必须大于教练一对多单向输出的时间
  - 参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
    - 并附带 42 字内文字说说自己今天最大的收获
- 地点:   [深圳华侨城如盒艺术空间](http://t.dianping.com/deal/8199297)
- 时间: 周六 14:30~17:30, 回帖建议
- 报名: 回复说明以下关键信息
  - github 帐号
  - 大约到达时间
  - 期望现场解决的技术问题
- 截止: 周五 24:00 前有效
- _提醒:_ 必须带上电脑,以便现场明确技术问题的细节 ;-)

参考:
-  [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)
-  [[1w] 各地 C2T2 要点汇总](https://github.com/OpenMindClub/OMOOC2py/issues/63)
- [[0w] 各地 C2T2 纪要及录音、讲演材料](https://github.com/OpenMindClub/OMOOC2py/issues/42)
- 注意:弃用`面基`一词, 这是个极其恶意的 KUSO 名词!

**Comment by bambooom** [comment]
- github账号: bambooom
- 大约到达时间: 2pm, prefer周日, 地点无特别建议 
- 问题待增补(貌似自己比较喜欢帮助别人解决问题)

**Comment by ivanlau** [comment]
ivanlau
大约两点半
观摩促进学习

**Comment by cxiaodian** [comment]
-  gitbub帐号:cxiaodian
- 大约到达时间:2点，先报名要晚点才能确定是否能去呢。
- 期望现场解决的技术问题: 调用数据库这块，还不是很理解，还有其他的相互学习。

**Comment by sherlockhoatszx** [comment]
github 帐号：sherlockhoatszx
大约到达时间:14:00
期望现场解决的技术问题:4w的任务已完成，5w的任务刚开始做,现在没什么问题。

**Comment by crazy-tea** [comment]
crazy-tea
2pm
刚弄完2W的课，抱着已死的心过来观摩进度，( ╯□╰ )

**Comment by xiangzhendong** [comment]
github账号:xiangzhendong
大约到达时间: 2：30pm

**Comment by csufuyi** [comment]
@bambooom
@crazy-tea
@cxiaodian
@xiangzhendong
@ivanlau 

参加者

**Comment by bambooom** [comment]
深圳第N次入冬失败......于是来写总结~
- @ivanlau 提出来说一直不去看别人的代码,因为觉得自己没有做,直接看别人的话会有种_抄作业_的感觉.所以引发讨论:  `该不该看别人的代码来学习? 如果看,应该以怎样的姿势看才能掌握成自己的知识?`
  - 唔, 个人认为**看!当然要看!**
  - 大致可分为几种情况:
    - 完全没有思路应该怎么进行: 此时看别人的代码的姿势可以是大致了解框架, 再自己想办法重现. 重现的过程中, 学到的东西也还是自己的嘛~ 
    - 在按照自己想的进行过程中被卡住: 此时与其自己死磕,不如借鉴他人的解决方法. 并且此时想解决的问题就是很具体的一个小地方, 在看懂他人的解决方法后可能就恍然大悟了,不用浪费太多时间.
    - 按照自己的想法完成了之后, 再看看他人的话, 就可以很明显看到差别. 此时自然是学习他人的好的地方, 更新/优化自己的代码.
- 另一个讨论是有关八荣八耻里的`以打印日志为荣 , 以单步跟踪为耻`是怎样理解的
  - 好的程序应该在查看日志的时候就可以定位问题所在, 而单步跟踪效率低下,并且某些场景无法重现,所以无从跟踪. 想到有一周公开课大妈给的自己研究出来的python import workflow是怎样的......
    ![1](https://cloud.githubusercontent.com/assets/14840170/11319129/4314ed78-90a7-11e5-9de1-61df95e49634.PNG)
  - 后面我又搜了一下有关这个方面的讨论, 其实看讨论来说感觉打日志logging和单步跟踪debugger并不是说完全互相排斥. 
    - [这篇知乎答案](http://www.zhihu.com/question/20626825/answer/19993716)里的观点就是说这两种工具优缺点是互补的, 在不同的场景选择使用不同的工具来解决问题.
    - 其他讨论/参考: 
      - [v2ex-为什么Python要以打印日志为荣 , 以单步跟踪为耻？](https://www.v2ex.com/t/49591)
      - http://victorlin.me/posts/2012/08/26/good-logging-practice-in-python
      - 怎样打印日志也是门学问......

其余的等其他小伙伴补充吧~~

**Comment by cxiaodian** [comment]
因为工作原因，周天一般没空，这是第一次参加，以后都会尽量参加！

参加现场聚会增加学python的动力，教练的解说，同学提到的各种陌生的概念，会有压力，特别看其他同学都按时完成作业，会逼自己快点跟上节奏，不能拉后腿。

两位教练很热情也特别愿意分享自己的想法观点，@csufuyi为我们分享了自己使用pyenv遇到的问题，避免我们后面同样踏坑，也帮我们解答了一些疑问，特别是关于class 方面的，@badboy315 鼓励我们，不要放弃，自己找课程跟不上的原因，突破原因，放弃其他的课程，从最后一节开始，还有关于组队的，多少人合适，如何去分工，认清自己的优势，自己在团队中适合做哪个角色，是要抱大腿还是要做大腿，抓紧时间，想项目。
- @ivanlau提出问题，关于课程跟不上是否参考其他同学的作业的问题。  
  - 我自己也有这疑问，当我没思路，我就想是否直接去看其他同学的，但看了之后内心有愧疚感，会想为什么这些同学他们在不看其他同学的作业，按照芝麻星后面给出来的链接，也照样能完成作业，为什么我就是不可以，很想弄清楚，他们是如何做到的。
  - 所以有时只通过芝麻星背面的链接，写代码的过程中发现的问题，就google找，找着找着把大量的时间消耗在这里，又把作业拖到明天，然后又明天。。。
  - 经过 @bambooom同学，还有@csufuyi @badboy315 他们的观点，我结合自己的情况，来解决自己的问题。
    - google什么的也找不到答案，看下其他同学的代码，但不能只抄，要问自己是否能理解，自己解答这代码为什么要这样写，就跟@bambooom再帮我们解释她写的6w作业，代码为什么要这么写，来反问自己，是否有更好的写法，最后能把代码优化的更好，改改这里，改改那里看是否能运行。
    - @csufuyi 说当代码运行起来，没报错会减少自己的焦虑。当我通过文档，试着让代码运行起来，总是报错，会很焦虑，甚至就停下了，这个时候看下其他同学怎么写，会加快自己步伐，不会死磕在一个地方卡死。
    - 如果实在做不出，先把作业完成了，再找机会问为什么是这样写。
- `八荣八耻`里面的 `以打印日志为荣 , 以单步跟踪为耻` 我是习惯单步跟踪的，打个比方：读跟写，我先确保是否可读取了，再来写，写入的这块函数，写入的函数如果报错，我先把读取的函数注释掉，只跟踪写入这块，所以我对于这条规则是很有疑问的，为什么没问呢？ 我是觉得当写的代码数量达到一定量之后，才能真正的理解这个问题，当一个新手只写几行代码的情况下，可能单步跟踪效率更高？
  - @csufuy 分享了他自己的经验，单步跟踪存在很大的运气成份，如果只单步跟踪没办法对程序的整体思路清晰的认识。每个点都打印输出日记，自然会逼着大脑要对整个程序的代码思路要足够清晰，解决问题会从宏观到微观，减少明明自己测试没问题，给其他人或者线上环境，就出问题。
- 关于阅读英文文档的
  - 我是倾向于有中英文档，两份一起看，有些概念只看英文，没有一个好的对应中文的概念很难记忆，例如：在读[简名python](http://www.swaroopch.com/notes/python/#function_parameters)关于`parameters`形参 `arguments`实参 在没有就中文文档，我知道这两个概念是不同的，但我就是不知道他们中文要如何去称呼，当我翻了下中文文档，知道如何翻译之后，会加深记忆。

暂时就这么多。

**Comment by cnfeat** [comment]
弓和箭教练的深圳 C2T2 短评回顾,

[完整版请见](https://github.com/OpenMindClub/OMOOC2py/issues/79#issuecomment-158890429)
- 妹子给你现场演示 5w 作业, 现场用猜代码来学习直觉. 
- 讨论什么是正确的学习姿势, 看别人的代码对吗? 
- 八荣八耻的细节讨论, 单步跟踪应该不? 
- Windows 和 mac 的使用感受, 到底每个人感觉的差异在哪? 

图片及录音地址：http://pan.baidu.com/s/1wprOE   [录音是 wav 格式, 请下载到本地后才能正常听取]

@badboy315

**Comment by badboy315** [comment]
## 深圳 C2T2 5W 纪要

### 地点:
- [深圳华侨城如盒艺术空间](http://t.dianping.com/deal/8199297)

### 参与人员:
- @free @badboy315 两位教练以及以下五位学员.
- @bambooom
- @crazy-tea
- @cxiaodian
- @xiangzhendong
- @ivanlau 

### 纪要内容

> 本周深圳如期召开 C2T2, 5位学员到场. 时长 14:30 - 17:45.

讨论主题内容:
- 5W 作业竹子@bambooom 讲解
  - 不懂代码猜意思
  - 代码的模块化组成
  - 如何可复用代码
- 现场直击 解析--> 为什么没有完成作业?
  - 学习的姿势
  - 借鉴的合理性, 该不该学员代码
  - 代码的直觉, 还是要 `码`
- 乱入主题讨论
  - 八荣八耻的细节讨论, 单步跟踪应该不?
  - Windows 和 mac 的使用感受, 到底每个人感觉的差异在哪?
  - 组团的分工

照片

@free 教练分享
![](http://i12.tietuku.com/b7fa759b6cc48f34.jpg)
![](http://i12.tietuku.com/c4a018cba0081d06.jpg)
![](http://i12.tietuku.com/35d245adb32260a6.jpg)

@@bambooom 讲解代码
![](http://i12.tietuku.com/5b4b6567ec23b03d.jpg)
![](http://i12.tietuku.com/b1546a406303d69b.jpg)

录音
- [现场录音, 请下载后收听](http://pan.baidu.com/s/1wprOE)---[录音是 wav 格式, 请下载到本地后才能正常听取]

**Comment by xiangzhendong** [comment]
# 深圳C2T2 5W纪要

## 背景

地点：深圳华侨城如盒艺术空间

时间：14:30-17:30

参与人员：@弓箭、@free、@竹子、@绿茶、@xiaodian、@ivanlau

课程进度：6w（微信公众平台）

本人进度：5w（PaaS）

## 本人收获和思考

### 1、什么是正确的学习方式？

@ivanlau怀疑直接看别人的代码是不是正确的学习方式。因为哪怕看懂了，自己去写时还是不知道如何下手。弓箭指出这牵涉到时机的问题。也就是说，在你真正尝试之后，遇到瓶颈了，看别人的代码可以提供新的启发和思路。

另外，这也牵涉到看完代码后的下一步的行为。如果只是把代码复制粘贴过来，运行OK就行了。显然，这段代码没有变成你自己的东西。问题的关键是，要如何把它变成自己的东西。有两种途径：一种是向别人讲解代码，如果能够简单地说清楚，说明基本理解；一种是在自己理解的基础上脱稿去完成这段代码，如果基本能够独立完成，说明已经在理解的基础能够运用（下一步是在新的情景中迁移，或曰创造）。

进一步，自己先写培养的是解决问题的能力，看别人的代码更多的是获取知识、学习的能力。前面的过程让我们更能反思自己的思维方式（元认知），获取新的解决问题的能力（比如到哪里去获取自己需要的信息和帮助，哪些来源是真正有效的，通过更多信息的涉入来进一步聚焦问题，提出恰当的提供解决线索的问题等），后者的过程更多的是如何在现有的知识背景下理解新概念的过程。

当我们刚刚接触新知识时，我们对基本概念了解甚少，这时更谈不上利用这些概念和知识去解决问题。因此，正确地学习至关重要：
- 示例代码是个好东西（当然也包括别人的作业）。这相当于概念的具体实例。对一行或一段代码的作用不了解，你可以去print它、打印日志，或注释掉，观察代码的反应。这就好像，你跟一个人交往越多，你对一个人的脾性就越了解。你对一段代码交互越多，你就越了解这些代码。
- 错误信息是个好东西（@竹子）。错误信息提供了解决问题的线索，要善于利用并认真阅读错误信息。然后利用错误信息提出问题，去文档或google寻找答案。当我们使用google时，我们会获得越来越多的信息或概念，这时我们应该使用更多的关键词去聚焦问题。

### 2、是不是一定要看英文文档？

文档肯定是要看的，但一定要看英文文档吗？
学员和教练们指出不看英文文档的原因：（1）英文水平有限；（2）先看中文，回过头来看英文更容易吸收理解。第一条没有指出看英文文档的好处，要当心。英文水平有限不能成为不看英文文档的充分理由，如果是这样永远没有看英文文档的机会了。实际上，一开始看肯定会比较艰辛，但有了开始，对词汇和表达慢慢熟悉，就会变得轻松。第二条理由背后有一个假设，就是英文文档更好，否则我为什么看完中文后还要回来看英文文档，如果中文文档已经解决了我的问题，还有什么必要看英文文档呢。所以，它也不能成为不看英文文档的有力理由。当然，看中文文档并非全然都是坏事。中文文档可以让我们快速吸收相关的概念和知识，但是，要看靠谱的中文文档，尤其是大妈组织翻译的教程和资源。网络上不靠谱的中文资源比比皆是，如果不善加筛选，反而会扰乱获取知识的节奏。鉴定是否靠谱的一种方法就是看文档背后的机构或个人是否可靠。

### 附上个人公网版私人笔记的创建过程，欢迎教练和各位先进斧正：

[公网版私人笔记](https://xiangzhendong.gitbooks.io/notesforpython/content/PaaS_diary.html)

**Comment by ivanlau** [comment]
Date: 2015-11-23
Title: C2T2(python) W5@深圳 纪要
Tags: C2T2 python 深圳
Category:Python之旅 
Slug: C2T2-W5-sz

# 1.关于学习进度的问题

这次聚会我提了好多问题，主要引起讨论的问题是：对于进度“落后”的状态，是否应该直接看其它同学的笔记，还是先在未知情况下先做完作业然后再参考其它同学的内容？ 

我先说一下我提这个问题的背景吧，当我在W1的时候参加了广州的一次现场课，作业也是按进度完成，并且在课后的一次C2T2里面基本解决了当时需要解决的课程问题。次周后因为各种原因（当然找理由是不对的），落后了一周，然后一直在落后，放在课程的时间越来越少，但心里压力却越来越大。一是我还是希望自己能“入门”；二是看到同侪的进步，而自己却停留在原地，追上整体进度的机会越发小了。到了上一周课，我把焦虑提到了群里，大妈以及各教练都建议我直接做这一周作业，坐电梯上楼（这点也认同，但要解决好落下的内容与时间之间的矛盾T_T），进度不需要太在意。但是这段时间积累的学习债造成了千头万绪无从入手的心理困境。此为背景。

经过一番讨论我吸收到各位的意见，我认同以下几点：
- 看代码是可行的，但必须是有所改进以及思考；
- 看明白后，自己要写写出来相关代码；
- 学习代码是必要的过程，不要因此有过多的心理负担；
- 同学们也有类似情况，需要及时调整好心理状态。

回去之后我思考了许久，觉得自己现在的状态如下：
- 由于挫败感太强，学习的节奏乱了；
- 尽可能专心和投入；
- 以同学们的学习成果为榜样，多看。

我对自己提出了以下改进建议：
- 尽快调整好心态和节奏，尽可能找到抒发或者调整的方式，因为输出了焦虑本身不能促进学习；
- （认同大妈以及教练的建议)不要太在意进度本身，而是从现在开始走好每一步（如一句名言，最好的时机是十年前，其次是现在）；
- 每天抽时间，集中能用的例如中午晚上等，分别分配适当的比例（可以一天干一种事情），学习或输出代码，或者输出文字，持续改进。

我回去之后做的事情：
- 因为之前落下内容，为了不把以前落下的内容成为后面进度的心理包袱，所以不打算更新需要更完整的内容架构的gitbook了，搭了一个静态博客，从现在开始并且坚持输出，让自己保持一个持续向前向上的状态（又在不务正业，Pelican的选型安装笔记也写了，欢迎勾搭，网址：http://ivanlau.com ）；
- 把活动记录写了，把工作笔记写了，踏实做好做好每一个事情；
- 抓紧看代码。

# 2. 其它问题

由于我最焦虑的问题是进度问题，所以把该问题单列出来。

活动也讨论了八荣八耻的内容，特别是单步执行的调试模式的问题，正好和公司的同事讨论过，值得回去考究每一点的用意。

**Comment by badboy315** [comment]
开心关闭!!!

上交 80%

**Comment by sunnyhuang42** [comment]
我看到这个 issue 也好开心!!!

关闭了也要追着留言表达一下
