### ISSUE TITLE
[0wd4]广州 C2T2 线下活动报名

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#8]
- 地点: 广州 天河区 珠江新城 华夏路30号 富力盈通31F 3110 会议室
- 时间: 周四 19:42~22:22
- 报名: 回复说明以下关键信息
  - github 帐号
  - T-shirt 尺寸(S|M|L|XXL)
  - 大约到达时间
- 截止: 周四 10:10 前有效
- _提醒:_ 尽可能带上电脑,以便现场明确技术问题的细节 ;-)

@OpenMindClub/py2prd 

参考: [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)

**Comment by simple2source** [comment]
离我上班地方1000米！！！！  果断报名O(∩_∩)O

```
github 帐号：simple2source
T-shirt 尺寸(S|M|L|XXL)：M【175cm】
大约到达时间：19:30
```

**Comment by lixiguangzhou** [comment]
github 帐号：lixiguangzhou
T-shirt 尺寸(S|M|L|XXL)：L【175cm】
大约到达时间：19:30

**Comment by yondjune** [comment]
github 账号：yondjune
T-shirt 尺寸(S or XS)
大约到达时间 20:05 吧 (路程遥远)

**Comment by Inspirabbits** [comment]
github 帐号：Inspirabbits
T-shirt 尺寸(S|M|L|XXL)：L【175cm】
大约到达时间：19:30

**Comment by hujianfei1989** [comment]
github 帐号：hujianfei1989
T-shirt 尺寸(S|M|L|XXL)：L【175cm】
大约到达时间：19:30

`不知道还能不能报上。`

**Comment by cnfeat** [comment]
github 账号：yondjune
T-shirt 尺寸(S or XS)
大约到达时间 20:05 吧 (路程遥远)
临时加班，取消报名

**Comment by ZoomQuiet** [comment]
成功达成, happy closed
