### ISSUE TITLE
[6wd0] 上海 C2T2 报名

### ISSUE THREAD

**Issue by cp4** [OpenMindClub/OMOOC2py#83]
- 活动规则
      参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
      学员互助为主
- 地点
       [Mlily梦百合咖啡厅](http://map.baidu.com/detail?qt=ninf&uid=8b1a15e214544eafcf06a40c&wd=mlily%E6%A2%A6%E7%99%BE%E5%90%88%E5%92%96%E5%95%A1%E5%8E%85&b=%2813517218.97,3633500.75;13534130.97,3644812.75%29&query=&qid=&page_num=&detail=cater&from=map&ugc_ver=1) 
      卢湾区 西藏南路1592号(西藏南路中山南一路交叉口，近第九人民医院)
- 时间
      周日 14:00~17:30
- 报名： _回复说明以下信息_
  - 问题及OS
  - 你的 gitbook 教程链接
- 提醒
       请带好个人电脑，笔纸等，准时到达

**Comment by WhaleChen** [comment]
### 报名 Whale

问题
- sea 的本地化实现的一个梗
- 美化Jinjia2 bootstrap 的使用方式？
- 网络抓取 unicode 中文 和 数据类型的转换 如何有效进行？
- cgwin 的使用的梗
  操作系统
  win 7  ubuntu 挂了~

**Comment by haruhi99** [comment]
haruhi99报名
OS:Mac OSX

问题  

1.函数和类调用的写法问题
2,IDE的一个怪BUG
3.bottle安装

**Comment by cp4** [comment]
### 参加学员：

  青泉， 陈衢， Danny

### 纪要：

#### 流程
- 提出各自的进展和问题
- 针对问题进行演示说明，一起观察探讨
- 自由编程和提问  

#### 提示
- 要衡量遇到问题的价值，学习外围的问题只要能解决不要深究
- 提问仍需主动，时间才是第一位的
- 对创作项目应在技术、协作等方面开始更仔细思考

#### 照片

  链接：http://pan.baidu.com/s/1mgm17iK 密码：ouaw

**Comment by sunnyhuang42** [comment]
没有参与者提交纪要吗？

**Comment by sunnyhuang42** [comment]
过期关闭
