### ISSUE TITLE
[5wd3]杭州 C2T2 报名

### ISSUE THREAD

**Issue by wwulfric** [OpenMindClub/OMOOC2py#85]
时间：本周三，视频直播的时候
地方：照旧，万塘路天目山路 allface 咖啡厅

@OpenMindClub/py2student

**Comment by wp-lai** [comment]
报名
wp-lai

**Comment by shawn0lee0** [comment]
报名

**Comment by wwulfric** [comment]
![img_0928](https://cloud.githubusercontent.com/assets/8315997/11337068/12ec95c2-9225-11e5-80da-df0e46cf4d3a.JPG)

![img_0929](https://cloud.githubusercontent.com/assets/8315997/11337144/9c4cd5e8-9225-11e5-916d-adba6ee5cca2.jpg)

学员进度很棒！能在完成基本任务的基础上添加不同的技能点。希望未完成的同学能够补上之前的作业

**Comment by sunnyhuang42** [comment]
哈哈，能在完成基本任务的基础上添加不同的技能点，这个好厉害~

@wwulfric 看是否有可以方便放电脑在桌子上的场地？大家电脑都放在膝盖上，感觉怪怪的

**Comment by wwulfric** [comment]
@ishanshan 你看我们的桌子的高度。。。这个真没有。下次摆拍一个～

**Comment by shawn0lee0** [comment]
## 感想
- 加密
  - 单一的加密算法会被撞库
  - 通过各种算法嵌套实现复杂加密
  - 服务器端增加sleep函数避免恶意攻击
- 迭代
  - MVP
  - 快速迭代
    - 迭代环境的搭建：先本地→上线验证
  - 工具的使用：学会利用插件、模块
- 每次仇恨一个东西，你就失去了向它学习的机会。
  [课程导图-大图链接](http://i5.tietuku.com/0d57e7b669d19020.png)
