### ISSUE TITLE
[讨论]和教练的一段对话 关于python 课程的一些感想

### ISSUE THREAD

**Issue by fqlxxxxx** [OpenMindClub/OMOOC2py#86]
今天和CnFeat微信上聊天, 他觉得我这种情况相当的典型, 能代表一部分 TX 的遇到的问题, 所以发个 issue, 欢迎大家讨论.

CnFeat:

> 你好，我是 Python 课程陪练陈素封，最近发现你在群和 github 发言少了呀，想问问是课程遇上难以解决的问题吗？还是最近实在无暇顾及？需要我们提供何种的课程帮助吗？另，对课程有什么意见也可以向我提出哈~

我:

> commit 的确实少了, 还在搞4w的作业. 可能在完成4w 的时候想的挺好, 但是很多细节实现的时候总是卡壳, 卡的多了有点没信心了, 现在只能再退到最简单的去做.
> 
> 这个课程确实实验性比较强, 所以有很多不适应的地方. 说实话有些怀疑这个课程是不是适合完全不懂编程的人, 确切的说是不是适合自己吧.
> 
> 有一些情况也顺便反馈一下, 有一些是自己看到的, 有一些是自己的体会:
> - 通过 issue 提问的越来越少, 最近几乎没有了,这是为什么!
> 
> 但并不是大家没有问题, 反而问题非常多, 都不知道从哪里下嘴问. 因为有的问题确实是比较细节的问题, 可能只需要有人能快速的点一下就解决了, 但如果形成文本描述清楚需要花费大量的时间整理和叙述出来, 通过 issue提问的成本过高.
> 知道想通过 issue提问过滤掉一部分"白痴问题", 但有的时候新手确实就容易被"白痴问题"卡住. 
> - 提交作业比例的人逐步减少, 课程的设置是否有问题?
> 
> 就拿4w 的任务指引来说吧, 要对 bottle  jinja2 bootstrap sqlit3都进行了解并能使用, 每天抽一个小时肯定不可能完成, 我还会利用上班的时间抽空看看, 但也只是了解一些表面的东西, 有些代码为什么这么写不知道!
> 有些学员完成的非常快, 我相信或多或少都有一些基础, 至少从我参加过线下活动来看, 能跟上的而且理解比较好的是有编程背景的或者是学理科的.
> - 公开课的风格, 其实是公开课的内容.
> 
> 每次公开课都基本上按时参加, 但完全体会不到有同学说挺完了很兴奋, "心流"一直无法进入. 比如每次大妈在放命令行视频的时候基本10秒后就开始走神了, 每次都感觉放的特别赶, 速度特别快, 最后都已经不知道在干啥, 加上大妈比较独特的文字风格解说, 难度又增加了数倍.
> 但其实当大妈切回到高桥流幻灯片或者公开课后给深圳C2T2现场答疑的时候反而能听进去. 
> - 对于文档, 大妈说文档放那都 n 年了, 自己看!!!
> 
> 这点真的不太同意, 如果按照这个逻辑, 那基本大家都无师自通了. 文档确实需要自己去细看, 反复看, 但看之前能否对一些新的知识做一个概况性的讲解, 大概是个什么结构. 比如 bottle 中的 route 我花了两天才搞清楚route 等同于什么, 简单的说其实就是控制链接和哪些页面能显示的. jinja2到底有什么用? 他和 bottle bootstrap 有什么关系? 看了很多实例, 花了很多时间才搞清楚.有一些背景的同学可能通过类比, 很快就能了解到这块知识的框架, 怎么去定位完成任务所需要的资料位置等等.但对于没有任何基础的同学来说要花 n 太多的时间先搞清楚他们之间怎么工作的.
> - 到现在为止自己在编程思维方面有没有成长?
> 
> 可能有吧, 但整体感觉脑子里的知识非常混乱.

CnFeat:

> - 很多细节实现的很多细节实现的时候总是卡壳, 卡的多了有点没信心了,
> 
> 大妈其实也期待可以看到卡壳的部分代码,然后作为典型的例子在课程中讲解,不知道卡壳的地方在哪里,是否可以在教程中体现?届时可以一个链接在问题中,大妈直接过教程看,这样对大家可能也比较有帮助.这样其实也是解决文本叙述过多的问题
> - 知道想通过 issue提问过滤掉一部分"白痴问题", 但有的时候新手确实就容易被"白痴问题"卡住. 
> 
> 对于"白痴问题",可能每个人都有不同的理解.
> 其实是不是"白痴问题"其实不重要,重要的是学员对于"白痴问题"的应对,这是新手必须迈过的一道坎,如果新手一直对"白痴问题"持续地等待,那对以后的学习是灾难性的.授之以鱼,不如授之以渔.
> - 就拿4w 的任务指引来说吧, 要对 bottle  jinja2 bootstrap sqlit3都进行了解并能使用, 每天抽一个小时肯定不可能完成, 我还会利用上班的时间抽空看看, 但也只是了解一些表面的东西, 
> 
> 课程虽独立并行,但难度毕竟也是逐步提高的,其实学一门东西,学到最后,靠的不是基础,而大多是毅力与坚持了.
> - 至少从我参加过线下活动来看, 能跟上的而且理解比较好的是有编程背景的或者是学理科的.
> 
> 有基础学得快,无基础学得慢,这是常理呀.
> 想一想,他们之前也付出过时间去学呀,
> 如此看来,他们堆积的效用是可能是50%,新手堆积的效用是80%,而且,你还可以去借用他们的经验,有基础的人出现在你的身边,未尝不是一件好事情.
> - 大妈说文档放那都 n 年了
> 
> 行动行动!如果不去做,那么后期你也无法搞懂 route 呀?
> 可能你在意的是时间吗?是否可以少走一点弯路是吧?
> 这个确实不能少呀,走弯路是验证基础是否扎实的重要手段呀
> 具体可以看看这篇:[#INFO# No.11 运动思维 与 编程思维 的相同点在哪里？](https://github.com/OpenMindClub/moment/issues/17)

 我:

> 其实我所谓的白痴问题不是在没有任何尝试的情况下就要答案, 是在尝试了很多情况下都解决不了. 但这个问题在老手眼里就是白痴问题 ,比如 为什么页面不显示信息 , 原来在 form 中没有设置属性 action 和 method, 我在这里卡了很久 , 搜索了很久也没有解决, 结果还是别人告诉我的. 这种问题其实就是没有 html 方面的基础知识, 没时间看, 即时有一定的时间也不知道怎么高效的去找到和任务相关的点去看

CnFeat:

> 其实我所谓的白痴问题不是在没有任何尝试的情况下就要答案, 是在尝试了很多情况下都解决不了. 但这个问题在老手眼里就是白痴问题
> 学会提问的智慧就是更好的提问呀,如此的问题完全可以问呀,不要憋屈,毕竟花了钱的,要将教练和大妈用尽

 我:

> 个人觉得有些问题直接问大妈有点杀鸡用牛刀的感觉, 大妈太牛了, 有距离感(我知道现场问大妈没什么问题, 视频里听到过其他人现场问大妈, 大妈解释的很清楚), 还有就是提问的成本问题, 如果有些基础问题教练能解决就好了.

**Comment by YixuanFranco** [comment]
讲一个我自己最近的经验,

我要玩 7 牛, 一个 配置文件搞了很久很久.
1. 为什么 运行 一个文件没反应. 我上网查了查, 试了几个命令, 发现我既没有思路也不知道错在哪儿.
   - 于是我很明确的告诉大妈了.
   - 并没有管这件事儿 到底是不是鸡, 也没有过多思考大妈是不是牛刀.
   - 核心的想法就是: 我去, 这个怎么解决, 我怎么弄不了.
   - 后来大妈说, 公约为 ./qrsync + conf.json. 
2. 配置conf 文件完毕, 文件怎么都上传不上去...
   - 一个设置一个设置的检查了, 觉得没什么错误. 
   - 甚至我也不知道错在哪儿了. 
   - 告诉大妈我实在找不到,
   - 大妈把他的配置文件给我看了一眼,
   - 于是发现了一个 buket 配置的问题.
   - **但是还是不行, 于是继续问...**
   - 大妈说, 自己对比.
   - 又貌似查出来一个 Key prefix 的问题.
   - **然而还是上传不上去....**
   - 最后跟大妈认怂, 觉得自己实在找不到. 
   - 大妈说, 配置文件中的 <> , {} 等符号需要删除掉.
   - =-=! 删除, 再试, 搞定.
3. 就不说我这些天在 iterm2, tmux, TermRecord 中遇到的无数多坑了....
4. 就不提 升级系统 后 Git 不能用, brew 不能用, jekyll 不知道到底怎么了 等无数多坑了...
5. 失败是一种太过正常的常态. 所以才要适应失败, 适应自我探索. 学会提问..
6. 而且, 探索过了+ 又不会, 为什么不敢问? 是不是用了牛刀杀鸡一点都不重要啊, 总之是要杀鸡不是吗. 

嗯嗯, 表怕. 你经历过的东西, 我们都经历过, 也正在经历, 也将和你一起经历下去.

**Comment by cnfeat** [comment]
@fqlxxxxx 同学 的关于提问止损的看法,也值得各位参考一下

我自己一般会控制问问题的次数, 不随便问, 但问的时候一般肯定都希望尽快有个答复.   以前其实一直憋着, 自己搞懂, 但这次实在花了太久还没有完成,  所以超过一天或者一定时间解决不了的问题可能就要问了,  算是个"止损时间点" , 这个词可能不太恰当, 大概这个意思

**Comment by cnfeat** [comment]
@bambooom 同学在看完大妈 对 @fqlxxxxx 问题反馈（芝麻星>5w视频>5wd3 课程QA:IT命名学+提问止损），并参用了其提问止损方法，成功解决问题，并在其私人教程详细地记录解决问题的过程，记录如下：

[5wd3 | 求助,分享,促馈](https://bambooom.gitbooks.io/omooc2py/content/notes/5wd3.html)

各位伙伴可以参考使用哈~

另 @bambooom  的教程还相当丰富，大家还可以去淘一下，有空还可以留个言嘛。

**Comment by ZoomQuiet** [comment]
happy end
