### ISSUE TITLE
【系统问题】win7/ubuntu14.04双系统 window下突然自动关机 ubuntu下运行正常

### ISSUE THREAD

**Issue by JeremiahZhang** [OpenMindClub/OMOOC2py#88]
- 机子: 惠普 [CQ35-105TX](http://support.hp.com/us-en/product/Compaq-Presario-CQ35-Notebook-PC-series/3884553/model/3938265/document/c01726942/) 加了1G内存 和 64G的SSD固态硬盘
- 背景: 前段时间在笔记本上安装 ubuntu14.04 系统, https://jeremiahzhang.gitbooks.io/omooc2py/content/0MOOC/01_02_ubuntu.html 原本机子系统为 win7, 安装好ubuntu 就是双系统了, 前段时间可以正常使用 win7 和 ubuntu 不过问题突然来了
- 问题: 最近 在 window 下 机子突然关机 机子也很热 但是在ubuntu系统下 不会出现这样的问题 
- 尝试：
  - 1 检查电源 没有问题
  - 2 风扇2周前 清过一次灰了 
  - 3 【分析】ubuntu下可以正常使用 说明硬件没有多大问题
  - 4 【现象】发现在window下 内存占用 比没有装ubuntu前的大 不明白
  - 5 【准备】更新机子 BIOS 不知是否有用
- 请教:
  - 到底该如何解决该问题呢?（都困扰2天了）

ps: 终于问了个问题 虽然和 python 编程关系不大 但也算是破壁了 恩

**Comment by cnfeat** [comment]
这问题无法重现~而且问题形成因较多，有硬件，也有软件的，教练们如果要回答这估计也挺困扰的。

**Comment by ZoomQuiet** [comment]
2015-11-20 13:49 GMT+08:00 JeremiahZhang notifications@github.com:

> 机子: 惠普 CQ35-105TX 加了1G内存 和 64G的SSD固态硬盘
> 背景: 前段时间在笔记本上安装 ubuntu14.04 系统, https://jeremiahzhang.gitbooks.io/omooc2py/content/0MOOC/01_02_ubuntu.html 原本机子系统为 win7, 安装好ubuntu 就是双系统了, 前段时间可以正常使用 win7 和 ubuntu 不过问题突然来了
> 问题: 最近 在 window 下 机子突然关机 机子也很热 但是在ubuntu系统下 不会出现这样的问题
> 尝试：
> 
> 1 检查电源 没有问题
> 2 风扇2周前 清过一次灰了
> 3 【分析】ubuntu下可以正常使用 说明硬件没有多大问题
> 4 【现象】发现在window下 内存占用 比没有装ubuntu前的大 不明白
- 嗯哼,其实,你对问题现象的挖掘远远不够哪
- 突然的具体时间点,那时你在作什么? 系统又在作什么?!
- 很明显,这和你安装双系统无关
- 请逐一排除: 硬盘/内存 问题后
- 就只能怀疑中毒了,一般情况, win 系统,每两个月必定要重新安装一下,否则过热死是必然的...
  嗯哼,俺的10年 winNT 使用经验.....

不过,整体上这是上天给你的一个机会,
直接升级到 Linux 的理性世界吧

> 5 【准备】更新机子 BIOS 不知是否有用
> 
> 请教:
> 
> 到底该如何解决该问题呢?（都困扰2天了）
> 
> ps: 终于问了个问题 虽然和 python 编程关系不大 但也算是破壁了 恩
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by JeremiahZhang** [comment]
@ZoomQuiet 
谢谢 大妈

> - 嗯哼,其实,你对问题现象的挖掘远远不够哪 
> - 突然的具体时间点,那时你在作什么? 系统又在作什么?!

嗯, 提问的智慧再得看几遍,
大妈一指出,发现自个儿问好问题,自己都没有仔细再 review 一下,真是惭愧 .不提问题不知道 ... 要提问题才知道

> 不过,整体上这是上天给你的一个机会, 直接升级到 Linux 的理性世界吧

恨不得直接放弃win 但在还得用win平台才能跑的软件, 用完直接抛弃, 去linux的理性世界
