### ISSUE TITLE
[1wd0]C2T2 珠海报名

### ISSUE THREAD

**Issue by ZoomQuiet** [OpenMindClub/OMOOC2py#9]
- 时间: 周日 15:15~17:17
- 地点: 珠海 吉大 景山路 莲山巷8号 金山软件大厦 F12 会议室
- 报名: 回复说明以下关键信息
  - github 帐号
  - T-shirt 尺寸(S|M|L|XXL)
  - 电脑操作系统
  - 当前课程 top3 问题, 参考: [[0w]当周课程 技术问题讨论](https://github.com/OpenMindClub/OMOOC2py/issues/3) 描述格式
- 截止: 周五 12:12 前有效
- _提醒:_ 尽可能带上电脑,以便现场明确技术问题的细节 ;-)

参考: [C2T2 活动](https://github.com/OpenMindClub/PRD/wiki/EventC2T2)/[历史记要](https://github.com/OpenMindClub/PRD/wiki)
## 大妈记要
- 录音: [151018_1wd0/](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151018_1wd0)
- 板书: 

![151018_1wd0_wbaord.jpg](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151018_1wd0/151018_1wd0_wbaord.jpg?imageView2/2/w/360)
- 合影: ![151018_1wd0_all.jpg](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151018_1wd0/151018_1wd0_all.jpg?imageView2/2/w/240)
- 记要:
  - 根据:[Chapter IV: Q&A | Miss Python and the Holy Geeks](https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/chapter_iv_q&a.html)
  - 进行了针对性演练
  - 明确 win 上的:
    - SSH 概念/工具
      - 发现竟然官方是和谐的
      - 特此提供下载: [putty.zip](http://openmindclub.qiniudn.com/res/software/putty.zip)
    - git 仓库形态/配置
    - 官方文档和具体编程演进的交互
- 作业:
  - 默认 24 小时以内,给出 学员自己的记要
  - 以及 @aJiea 单人辅导的附加作业:
    - 如何用 ssh 协议来读写自个儿的 github 仓库?
    - 如何配置本地 git 仓库,完成 [double-push](https://github.com/ZoomQuiet/OMOOC2py/blob/master/0MOOC/git.md#double-push)
    - 如何完成 `str` -> `datetime.date` 对象的改换?

**Comment by aJiea** [comment]
1. GITHUB ACCOUNT: [aJiea](https://github.com/aJiea)
2. Size **S**
3. Home: **Windows 8** ; Laptop: **Windows/Ubuntu French**
4. 遇到问题，尝试自己解决，特别是感觉自己有能力解决的问题。当前课程top3问题都属于后者，所以目前还未在当周问题中提问。如果该issue在周日12h还处于开放状态，会将在此之前给到还未自我解决的top3参考。

谢谢！<（￣︶￣）><（￣︶￣）><（￣︶￣）>

@OpenMindClub/py2prd
- 151018 11:11 
- 问题发布: [Chapter IV: Q&A | Miss Python and the Holy Geeks](https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/chapter_iv_q&a.html)

相关代码:

```
print "What's your name?" name = raw_input() print "Hi, %r!" % name

print " When were you born? (example: yy-mm-dd) "
bday = raw_input()

import datetime today = datetime.date.today() print "Today is" , today

if bday == today print "Happy birthday, %r!" % name else bday != today print "Have a nice day, %!" % name
```

**Comment by aJiea** [comment]
问题更新&排版优化
https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/chapter_iv_q&a.html

**Comment by ZoomQuiet** [comment]
@OpenMindClub/py2student 

C2T2珠海 媒体记要已经发布,欢迎大家参考

**Comment by aJiea** [comment]
C2T2 ZH 24h作业进行情况，还未完成。遇到很多问题，花了大量时间，希望得到指点后，超正确地方向高效解决问题。

https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/2015-10-18zh.html

**Comment by ZoomQuiet** [comment]
On Mon, Oct 19, 2015 at 10:49 PM, aJiea notifications@github.com wrote:

> C2T2 ZH 24h作业进行情况，还未完成。遇到很多问题，花了大量时间，希望得到指点后，超正确地方向高效解决问题。
> 
> https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/2015-10-18zh.html

在这儿统一回答吧:
- 现场作业1/2 其实是同一任务
  - 参考: [double-push](https://github.com/ZoomQuiet/OMOOC2py/blob/master/0MOOC/git.md#double-push)
- str -> datetime 的其实也并不是一定要完成的
  - 只是要求尝试
  - 给出为什么俺直觉判定将 datetime 转换为 str 进行比较
  - 而不是相反的原因以及背后的思考范围就好
- 重点是通过现场演示,得到启发
  - 将精力集中在当周的任务上来吧!

**Comment by lywpro008** [comment]
20151018_ 珠海开智第三次活动 _牛魔王总结版

##往期作业增补：
- 如何科学的挖坑：以我安利我好友进行每天工作记录为例，背景：好友为房地产中介，每天会被客户咨询大量问题。HOW：每个问题就是客户帮你挖的一个坑，但是有些问题显然过于宽广，短时间内难以回答，所以每天挑出三个有代表性，可以用120字进行基本完整回答的问题记录下来，预期在一百天积累三百个问题，一百天之后，再重新回答这些问题，并对比两次回答的异同，相同部分则为侧重点，差异部分找出背后的逻辑关系。最后再利用专业词汇，把高频问答行优化。 整理工具的话，推荐用印象笔记，每个问题再配上两个标签，成规模以后可以利用标签作为重新编排信息的视角。
- 珠海书友会&开智：最近一直在看oliveding先生关于社群组织的文集，慢点书友会成员在珠海本地是积极活跃的青年群体，两个社群如何交流，私以为我作为两个社群的交集人员，除了分享书籍以外，还可以把开智善用网络的经验分享给慢点书友会成员，交集肯定也不少，但是切入点就要找容易见效的。网络是现代社会生存的基础技能，但是对于这方面的教育，我们从小到大，除了电脑课走过场之外，几乎没有进行过有体系的网络技能学习，所以应该以此为切入点。比如利用先进的互联网工具提高工作效率，1.利用科大讯飞，把会议音频转为文字版，未来对录音的查找，就可以根据这部分文字快速查找对应的录音。2.阳老师博客上面的八股文和累赘词汇检查软件，可以帮助写作输出。

##对于编程课程的想法：
- 课前资料：课前资料信息量会不会过大（应该会），资料之间也存在二八定律吧，下次可否分出一个简版资料和完整版资料，方便一些本周工作过于忙碌的学员，花最少时间（比如三小时）就可以进行最基本的备课。

**Comment by ZoomQuiet** [comment]
完成汇总,关闭
