### ISSUE TITLE
[6wd3]广州 C2T2 报名

### ISSUE THREAD

**Issue by penguinjing** [OpenMindClub/OMOOC2py#90]
- 地点: 广州 天河区 珠江新城 华夏路30号 富力盈通31F 3110 会议室
- 时间: 周三 20:00~22:00
- 报名: 回复说明以下关键信息
  - github 帐号
  - 大约到达时间
  - 期望现场交流的技术问题
- 截止: 周三 10:10 前有效
- 提醒: 带上电脑带上你的疑问，我们现场编程交流学习。 
- 现场福利：有大妈在还不够吗. ;-)
- 录音: [151125_C2T2gz/](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151125_C2T2gz)
- 合照: ![151125C2T2gz_mm.jpg（JPEG 图像，1024x800 像素） - 缩放 (99%)](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151125_C2T2gz/151125C2T2gz_mm.jpg?imageView2/2/w/240)
- 签名: 
  - ![151125C2T2gz_signs.jpg（JPEG 图像，2448x2448 像素） - 缩放 (32%)](http://openmindclub.qiniudn.com/res/tapes/omooc/omooc2py/151125_C2T2gz/151125C2T2gz_signs.jpg?imageView2/2/w/240)

**Comment by yondjune** [comment]
沙发

github 帐号 : yondjune
大约到达时间 : 开始前到达
期望现场交流的技术问题: 自带小黄鸭属性

**Comment by junjielizero** [comment]
github账号： junjielizero
大约到达时间： 大概19:40-20:00之间

**Comment by yondjune** [comment]
向大妈陈述了一下自己项目的方向和想法。

围绕着python大数据分析能力进行讨论。

发现真正定义上的大数据，和自己想象的，完全不同

大妈叫其给出的建议就是

用谷歌搜去，国外的大数据分析案例去练手

并且还指出，我没有因为这个想法, 而开一个issue去讨论

然后我反省了一下看一个issue可以触发更多的同学去关注, 从而发掘更多相关的有用信息。


另外一个我关于，将google analysis 的代码写进网站的想法，被大妈指出国内环境无法实现， 但是，国内的其他服务商可以提供。具体是，什么他照例故弄玄虚不肯说。

小结:

1.大妈讲了，项目分组的一些规则。但是这些规则感觉说了等于没怎么说。

2.非明星学员的出路。抓紧剩余的时间，在项目组对中单身

3.对于我自己要开一个大数据相关的issue吸引关注。

4.寻找谷歌分析的替代产品。

**Comment by yondjune** [comment]
向大妈陈述了一下自己项目的方向和想法。

围绕着python大数据分析能力进行讨论。

发现真正定义上的大数据，和自己想象的，完全不同

大妈叫其给出的建议就是

用谷歌搜，国外的大数据分析案例去练手

并且还指出，我没有因为这个想法, 而开一个issue去讨论

然后我反省了一下，一个issue可以触发更多的同学去关注, 从而发掘更多相关的有用信息。

我还提出一个，将google analysis 的代码写进网站的想法，被大妈指出国内环境无法实现，国内的其他服务商可以提供。具体是什么，他照例故弄玄虚不肯说。

小结:

1.大妈讲了项目分组的一些规则。但是这些规则感觉说了等于没怎么说。

2.非明星学员的出路。抓紧剩余的时间，在项目组对中翻身

3.自己要做的是: 开一个大数据相关的issue吸引关注。

4.寻找谷歌分析的替代产品，按照我原来的计划去实现它。

**Comment by penguinjing** [comment]
[6wd3 C2T2 会议纪要提交](https://penguinjing.gitbooks.io/omooc2py/content/1sTry/6wd3C2T2.html)

**Comment by sunnyhuang42** [comment]
纪要提交 2/3 ， close happily ~
