### ISSUE TITLE
[6wd6]深圳C2T2报名

### ISSUE THREAD

**Issue by sherlockhoatszx** [OpenMindClub/OMOOC2py#97]
• C2T2 活动规则
o   以学员互助为主，学员互助自由交流时间必须大于教练一对多单向输出的时间
o   参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
 并附带 42 字内文字说说自己今天最大的收获
• 地点: 深圳华侨城如盒艺术空间（华侨城恩平街创意园东部工业区E6栋103(康佳集团）
• 时间: 周六 14:00~17:30, 回帖建议
• 报名: 回复说明以下关键信息
o   github 帐号
o   大约到达时间
o   期望现场解决的技术问题
• 截止: 周五 24:00 前有效
• 提醒: 必须带上电脑,以便现场明确技术问题的细节 ;-)
• 现场福利：虽然竹子已东渡传法，但是我们的颜值担当的妹纸依然会来哦

**Comment by badboy315** [comment]
重复 issue 

关闭
