### ISSUE TITLE
[6wd6]深圳C2T2报名

### ISSUE THREAD

**Issue by sherlockhoatszx** [OpenMindClub/OMOOC2py#98]
### C2T2 活动规则
- 以学员互助为主，学员互助自由交流时间必须大于教练一对多单向输出的时间
- 参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
- 并附带 42 字内文字说说自己今天最大的收获
### C2T2 地点及时间
- 地点: 深圳华侨城如盒艺术空间（华侨城恩平街创意园东部工业区E6栋103(康佳集团))
- 时间: 周六（2015-11-28） 14:00~17:30, 回帖建议
### 报名: 回复以下关键信息
- github 帐号
- 大约到达时间
- 期望现场解决的技术问题
-  截止: 周六 11:00am(2015-11-28,11am) 前有效
- 提醒: 必须带上电脑,以便现场明确技术问题的细节 

**现场福利**：虽然竹子已东渡传法，但是我们的**颜值担当**的妹纸依然会来哦

**Comment by sherlockhoatszx** [comment]
github 帐号:sherlockhoatszx
大约到达时间:14:00
期望现场解决的技术问题:
-  SAE 服务器端代码中application、index、wsgi的问题
-  git分布式部署版本管理的问题
-  微信公众号接口
-  项目设想：交流项目设想，以及请教项目规划的事宜，比如功能范围结合时间多大适宜，如何迭代，项目时间管理及里程碑。

**Comment by zjuguxi** [comment]
Github: zjuguxi
大约到达时间: 14:00
期望现场解决的技术问题: 我落后比较多，也不知道需要解决什么问题。准备现场看看大家的进度。

**Comment by Jessicamiejiu** [comment]
Github: Jessicamiejiu
大约到达：14：00
5W课程

**Comment by ivanlau** [comment]
ivanlau
大约14:00

**Comment by penguinjing** [comment]
Github: penguinjing
大约到达: 13:50
4W课程

**Comment by Langzzx** [comment]
github 帐号:Langp618
大约到达时间:14:00

期望现场解决的技术问题:
SAE 中如何运行 Bottle,  以及如何加密的问题（有个未完成的项目设想，需要运用加密的一些算法）。

由于个人问题，之前落下两次课程，导致后来追赶时很痛苦，导致压力很大，然后学习效率也很低，想讨论下项目如何解决计划拖后的问题（打算follow CnFeat的建议，从最新的任务开始）。

项目设想：交流项目设想

**Comment by junjielizero** [comment]
github: junjielizero
大约到达时间：14:00（第一次来深圳，人生地不熟，如果迟到，请见谅，大家可以先开始）
期望现场解决的技术问题：
- 代码如何优化（现场再说）
- SAE某个问题（现场再说）
- 大作业项目应该做什么与怎样组队

**Comment by rayxiehui** [comment]
github  rayxiehui
下午两点到达
问题很多.

**Comment by junjielizero** [comment]
大老远的第一次来深圳，哈哈！体验不错，就发表一下感想，顺便将现场观点补充一下：

# 大项目做什么

大家一开始想得有点大了，太过侧重解决效果的细节，不过最后项目核心回到解决日常生活或自身遇到的问题。

现场我提到项目做的程序必须解决用户的痛点(职业病在犯。。。大家请见谅)，用户痛点的产生在于原有解决方案十分不好，而乃们的项目就是解决原有解决方案的不好并取代之。以一期学员“小小书童”为例：
- 开智微信群有一帮喜欢读书的人（用户特征），他们有着到豆瓣标注想读哪些书的习惯（用户需求），见到微信群里有人提到书后，立马“默念书名：打开浏览器→进入豆瓣→输入关键字搜索→查看结果→进入书籍详情→标记想读→回到微信”（原有到豆瓣标记书本的解决方案）。步骤繁琐、时间之长想想就能感受到（用户痛点）。那么“小小书童”怎么解决原有方案问题呢？直接在微信公众号输入书名（语音、手动皆可），并输入数字“0”进行标记，3-4步，几秒就搞掂了。（现有解决方案核心功能与优势）

> 具体参考：[小小书童-作品视频](http://my.tv.sohu.com/us/81183704/80319223.shtml)

可以试着将上面例子进行模式化【Problem-Solution Fit】（职业病又犯了。。）：就是【什么样的】用户，有着【什么样的】习惯/需求，在进行【什么样的】操作中，遇到【什么样的】痛点/问题。而现有的解决方案就是进行【什么样的】操作，在【操作时间，使用步骤等】有着【什么样】的改善（量化或可视化）

以上是解决DAMA在Issue提到“问题场景以及解决思路”的想法。待需求解决方案的核心确认后，就要画出最终理想解的MVP了（现有解决方案操作的流程图），越具体越好。这时认真想之后细节怎么样落地，会顺利很多，不会做着做着重构代码和想法，三周的时间折腾不起。

PS：特意在这方面写那么长，主要是见过靠谱与不靠谱PM，一个差异就是在新产品、功能上太过深陷解决细节，忽视了满足核心用户的核心需求，以及所需的核心功能。这次聊的需求估计都是面向小白大众用户，他们才不关心你解决方案到底用了什么技术与高超的方案细节。一旦前面定义清楚，很多东西都能画出来，对应的代码比较容易写上。

小结：你的程序长什么样不重要，重要的是你能打动你想打动的人去用你的程序

至于“未来发展策划,市场/用户/系统压力预测...”,属于【Solution-Market Fit】范畴。今年这方面有做过，坑很多。不过分享一下大致做法：通常在3-5年内做一个规划，首先了解解决方案使用者特征，思考类似的群体有哪些，各自群体有多大（二手资料、现场调研搜集等），然后思考每个阶段（一般三个月一次）优先级满足哪类群体，同期实现什么样的功能，期间会与产品生命周期结合。

# 怎样用谷歌
- Google目前在大陆用不了，但依然有替代品，[AOL] www.aol.com 。内置的Google搜索引擎，谁用谁知道。
- 搜索请用至少三个关键词，这里以搜索SAE bottle教程为例（有童鞋表示较难找到这方面资料）：
1. 第一个关键词肯定是Python，因为做的任务程序就是这个，算是我搜索必备词了
2. 第二个当然是SAE了，这个不用说吧
3. 第三个当然是Bottle了

将第一页一个个打开，就能找到合适，尤其是最后一个[链接](https://kidult00.gitbooks.io/kidult-s-python-book/content/ProjectNote/SAE_ProjetNote.html)，里面提到[42分钟乱入 SAE 手册](http://chaos2sae.readthedocs.org/en/latest/)，打开后各种截图说明，这不是大家想要的吗？

当然，想更精确搜索，就加多一个关键词，既然是教程嘛——赶紧输"Zoom.Quiet"（python SAE bottle "Zoom.Quiet"）,为啥输这个，输了你就明白了。同理，大家可以尝试一下微信教程。

另一个例子是怎样处理微信token验证问题，搜了大家都以为只有SAE实名认证才能解决。认真搜索后，发现在[V2EX](https://www.v2ex.com/t/232490)提到response.content_type = 'content_type:text'（具体怎么找到，我忘了）,而之前貌似在Bottle官网见过，于是在Bottle官网搜索关键词，果然有说这个处理。于是在index.wsgi补充该代码，验证搞定。提这个是为了说明一旦明确知道想要的东西，那么利用浏览器的查找功能，在该网页快速找到，就无需从头到尾看。

小结：利用AOL代替谷歌，至少用三个关键词搜索，要看python教程必需尝试“Zoom.Quiet”关键词,利用浏览器搜索功能找到关键词对应内容

**Comment by sunnyhuang42** [comment]
> 要看python教程必需尝试“Zoom.Quiet”关键词

哈哈，嗯，我搜知识管理、团队协作类的东西，也一般会加速“Zoom.Quiet”关键词：P

**Comment by csufuyi** [comment]
## 深圳 C2T2 6Wd6 纪要

### 地点:
- [深圳华侨城如盒艺术空间](http://t.dianping.com/deal/8199297)

### 参与人员:

@ivanlau
@lang
@sherlockhoatszx
@rayxiehui
@Jessicamiejiu

广州来的小伙伴:
@penguinjing
@junjielizero

### 纪要内容

本周深圳如期召开 C2T2, 7位学员到场. 时长 14:30 - 17:45.

![ ](http://pan.baidu.com/s/1sjpFHjZ)
- 自我介绍:来了两位广州的小伙伴, 再来简短的自我介绍和当前进展,需要解决的问题
- 大作业项目讨论:

头脑风暴似的讨论了各自项目的可行性, 请大家补充各自的项目细节 
@ivanlau 逛街神器
@lang 密码保存项目
@sherlockhoatszx 选股策略
@rayxiehui 心理学火柴项目
@Jessicamiejiu
@penguinjing 照片一键归档
@junjielizero 亚马孙根据人来推荐图书
- 技术问题解决:互相帮助解决具体的技术问题(其它请补充)
  - 网页返回的模板报错问题
  - 何时开始重构函数
  - ajax的前端问题

### 照片

http://pan.baidu.com/s/16zpRC

### 录音

个人介绍部分:
http://7xjfyz.com1.z0.glb.clouddn.com/6w_C2T2_process_introduct.mp3

项目讨论部分:
http://7xjfyz.com1.z0.glb.clouddn.com/6w_c2t2_item.mp3

由于当天场地旁边也有团队进行其它活动以及不间断的装修噪音,录音不是很清晰.

**Comment by veratulips** [comment]
@sherlockhoatszx 选股策略 这个有啥具体想法嘛？求交流。

**Comment by sherlockhoatszx** [comment]
有的。我今晚发出来，一起交流！
