### ISSUE TITLE
[7wd0]珠海 报名学习

### ISSUE THREAD

**Issue by aJiea** [OpenMindClub/OMOOC2py#99]
## C2T2 活动规则
- 以学员互助为主，学员互助自由交流时间必须大于教练一对多单向输出的时间
- 参与者需要在活动结束 42 小时内发布纪要链接到本报名 issue 中
          并附带 42 字内文字说说自己今天最大的收获
## C2T2 时间地点

```
时间: 周日2015-11-29 15:42~17:42
地点: 珠海 吉大 景山路 莲山巷8号 金山软件大厦 F12 会议室
```
- 报名: 
  - 回复说明以下关键信息
    - github 帐号
    - 电脑操作系统
    - 当前课程 top3 问题
- 截止: 周五2015-11-27 20:42 前有效
- 提醒: 尽可能带上电脑,以便现场明确技术问题的细节
## 记要
- 录音: [151129_C2T2zh/](http://openmindclub.qiniudn.com/res/tapes/omprd/151129_C2T2zh)

**Comment by douzhipin** [comment]
隔壁黑客创作班学员报名旁听

github 帐号：douzhipin

**Comment by aJiea** [comment]
### github： [aJiea](https://github.com/aJiea)

### 操作系统
- Mac
- Android, iOS

### 三问
- 三周未命名编程项目疑问
- 问问题的矛盾性
  - 自己在某方面工作低效
  - 可以通过自己的方法解决，并希望靠自己的力量解决
  - 在什么时候将问题问出去
    （解决方法：尝试不同阶段提出问题，并进行记录，总结效果，找到适合自己的方式。想听听大家的意见）
- 技术问题临时更新

**Comment by lywpro008** [comment]
- 《人类简史》：人类的诞生只是偶然，地球上除了人类以外没有任何一个物种统治过地球。私以为人类所谓的统治地球，也甚是风雨飘摇。所谓的统治私以为可能只是一个和地球的误会，或者说是人类的幻觉，我们可能在更高级文明眼里，是一个不被打搅的星际动物园，人的力量，只是放在人堆里好使。by 折花哥
  
  > 十万年前，地球上至少有六种不同的人
  > 但今日，世界舞台为什么只剩下了我们自己？
  > 从只能啃食虎狼吃剩的残骨的猿人，到跃居食物链顶端的智人，
  > 从雪维洞穴壁上的原始人手印，到阿姆斯壮踩上月球的脚印，
  > 从认知革命、农业革命，到科学革命、生物科技革命，
  > 我们如何登上世界舞台成为万物之灵的？
  > 从公元前1776年的《汉摩拉比法典》，到1776年的美国独立宣言，
  > 从帝国主义、资本主义，到自由主义、消费主义，
  > 从兽欲，到物欲，从兽性、人性，到神性，
  > 我们了解自己吗？我们过得更快乐吗？
  > 我们究竟希望自己得到什么、变成什么？
- 贵族，什么贵族？这个我也无法理解，说一个我认识的贵族-折花哥，用王佩老师的原话就是折花哥是一个令人形容词匮乏的人。[花哥的博客](http://blog.sina.com.cn/u/1683861132) 他身上有着好法律人的样子，提出了很多划时代的超验法学设想，虽然没机会使用，但是扩宽了我的视野。按学科划分，应该算是金融法领域，为我国金融安全保驾护航，分业经营的守护者。包括王佩老师在内，很多人觉得花哥是五毛，总是替政府说话，我个人觉得他是知道政府部门的不易，特别是对金融监管部门的体谅。我们一个国家，建国才60多年，改开之后才算吃上饱饭，会有很多不尽人意的地方，希望大家可以静下来，少点冲突，多点谅解，花哥如是说。
  生如草木，方能活得安逸。早年文革受迫害的时候，花哥总会大声念心经，念完之后感觉心外无物。最后附上中岛美嘉的一首歌[《我也想过一了百了》](http://v.yinyuetai.com/video/2336115)
- 一个问题-为什么我总是选择背诵？  
  背诵是为了更好的理解工作内容，但不应该以背诵为终点，多年来养成的思维惯性，原文背诵是一种最保守最安全的方式，用以证明你本阶段的学习成果。如果要用自己的方式和理解复述，筛选出信息，就没有了标准答案。就要follow you heart 就要自己为答案兜底了。[《看见成长的自己》：成长型心智的完全使用手册 | 开智正典](http://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&mid=400374089&idx=1&sn=9e6c42413a2ca82dac852d17fd6439d8&3rd=MzA3MDU4NTYzMw==&scene=6#rd) 推荐也好，旁征博引也好，可以证明你很努力，只是你努力的一种，有诚意的努力是要有原创的内容，自己为自己的产品负责，这也是我们告别象牙塔，踏入真实世界的第一步。
  
  > 并不是只要努力就算得上成长型心智。要区分消极努力和积极努力。书中举到一个例子是，在一门比较困难的大学化学课上，有学生通过强记笔记、死记硬背的方式学习，而另一些学生则尝试各种办法、使用各种资源帮助学习，如研究考试错误、调整学习策略、找教授帮忙等。前者的努力是僵固型心智，而后者才是成长型心智的表现。现实中常见的例子是，不少人在切入正事前，常常会花过量时间查资料做准备，这时候就值得警觉一下了。查资料是相对容易的努力，而这样可能给自己造成“我已经非常努力”的错觉，从而避免真正有挑战的努力，这恰恰是僵固型心智的表现。

**Comment by aJiea** [comment]
[音频已更新](https://ajiea.gitbooks.io/miss-python-and-the-holy-geeks/content/2015-11-29.html)

![5 pic_hd](https://cloud.githubusercontent.com/assets/13810631/11476509/1307a242-97be-11e5-8f2c-91b77f06e0c8.jpg)

**Comment by douzhipin** [comment]
# 151129珠海开智及PY2期线下面基纪要

时间：2015年11月08日15:34~17: 42 
地点：珠海 吉大 景山路 莲山巷8号 金山软件大厦 F12 会议室
人员：大妈、阿捷、豆制品、犇魔王、jason
**关键词：问题**
![此处输入图片的描述](http://7xl5i1.com1.z0.glb.clouddn.com/760525088701059648.jpg)

### **1. 解决问题的方向**

在我们遇到问题的时候，我们应该怎么去解决问题？  
- 利用5W1H把问题产生的原因表述清楚，有一定的几率把问题解决了。
- 如解决不了问谷歌、问度娘、问导师、问同学，问业界权威
- 学会看官方文档，因为大部分的问题在那都可以找到答案。

### **2. 解题的过程**

人可以会拥有ドS心态，想虐待下问题，但是成本需要控制。  
- 如何控制成本？==>设置止损点（一搜都是与股票相关的，orz）
- 如何设置止损点？
  - 三线止损法，三分之一的三分之一的三分之一......
  - 尽量详细的罗列出问题，找出重点问题所在。

### **3. 关于我自己的那些问题**

拖延症（问完我自己觉得有点囧）
下面几个是自己现在有在做的：
- 环境营造：用耳机听自己喜欢而且听了很多次的音乐。
- 工具
  - 如果是处理工作类的，有个打着有快感的键盘很重要。
  - 纸和笔
  - aTimelogger：大妈推荐的，看完每天每周的计时很有“鞭子”作用
  - 关闭微信的红点提示

不过时间管理分配上还需要进行优化，例如压缩下看剧的时间orz

---

PS：大妈提到的海豚世界，事后想了下，怎么那么像瓦肯 囧

**Comment by sunnyhuang42** [comment]
合照是不是少了一位？不会是因为给其他人拍照所以自己没有出镜吧？哈哈

嗷！终于又一次纪要提交100%了，close happily!

**Comment by hemcjason** [comment]
Section1 - 思维&效率

• aJiea
o   Q：如何优化编程语言的学习流程、效率？
1.  理清思路再动手。开始动手前先整理清思路，做起来时效率便能高些。
2.  设定止损点。若想用最少代价解决问题/完成任务，需明白问题次序、设定解决时间。列出TOP3问题；首要的问题用2小时解决；确定大问题后分解子问题。用5w1h分析问题。如果过了2小时还是没解决，看下面。
3.  积极发问。对于学习编程语言，遇到问题，先查官方说明文档。在码农界（其他次元是线型的），官方说明文档的编写逻辑、路径更有规可循，与知识体系高度匹配，从里面找答案往往能耗费更少的心智。文档没有解答时，直接问作者。作为菜鸟可能被调戏，但积极的互动通常能更快地得到答案。

o   题外话：人生苦短，折腾当歌
 贵族。贵族存在，是要优雅地活着。但优雅是个「反自觉」的词，人天性总有春困秋乏。而贵族需强调饮食搭配（因为要有身材，身材，身材）。（走神了）
 智人。自然界里只有智人是折腾物种，对自己的处境不痛快，才渐渐发展出人类。同样智商高的海豚，则选择顺其自然。人类不满足现状，需要更多权利，资源，才会到每个大洲300年内搞定当地大型动物，许多灭绝的物种，基因中没来得及记录到人类原来是辣么危险的物种。
 殖民。欧洲，地少人多，更迫切通过殖民扩大疆土。（又走神了）
 生命在于折腾。课程设计更希望学生处于同一阶段，遇到类似困境时，可同理互助，先有解决方案的同学，共享出来，大家学习积极性更高。

• 牛魔王
o   Q： 如何解决“用常识判定时，第一选择总是错的”的问题？
o   世界奇妙物语有一期专门的探索，讲述一位“第一选择总能选错”的歪果仁，如何“反其道而择之”来避开错误选择的。

• aJiea
o   Q：解决问题时，有时也享受自我解决问题的过程，更愿意花更多时间独自探究？
o   碰到艰难问题才会提出：决策型的时间判定，谈时间。
o   一个好问题比一个好的答案更重要。关注问题本身，提出精确的问题。苏格拉底式问答。

• 豆制品
o   Q：如何让问题提问的情景尽量真实地复现？
o   GitHub是一种生态。大脑本能讨厌反复回答同一个问题，因此首先搜搜别人的提问，看是否有回答过这个问题。编程里面最容易解决这个问题。标准，对比。摘录出有疑问的代码片段，可以用神器Gist （https://gist.github.com/）。

Section2 - 课程设置
• 旗舰班与Python二期的课程设计异同？
o   旗舰班前四周刚好遇到Python入门公开课，一起先mooc了一下。
o   二期备课时间比旗舰班更多。
o   二期学员体验更佳。在直播解决方案 上了好多收费服务。
o   迭代次数从6次改成3次迭代，希望课程结束时展示得最感人，能打动大家。经过12周思维进步最好，养成编程思维。

豆制品：
• 上文提到的「止损点」，如何判定？
o   思维导图，三三制。三步走——探查/信息搜索，验证，实现。（策划，实验，解决）
o   举个栗子，在一个稻田里摘麦穗,要最大的麦穗，只能前进，并且只有一次机会，怎么摘？（Google books：http://t.cn/RUDqBZ7）

• 对于Markdown：
o   MS Word是很重的编辑环境。Markdown可以很迅速地记录所思所想，行文内容比结构更重要，编辑完可直接发布，markdown是最简化结构化文本约定，设计来源于具体需求的整合，强调使用最小的字符串。总之，是很棒的编辑器。

• Q：战拖——如何快速补回课程？
o   并非“忘记代表不重要，不知道代表不必要”。拖是个现实状态，要承认，但也需分清楚哪些是可以跳过，哪些是必要去补。课程不是工序，不需依赖每一步。
o   课程设计是给大家一个有限资源的极限环境，保证大家练习时间。每周十个小时，挤一挤还是有的（推聚会，不追剧）
o   拖延，也是主观上不想愿意做。但可以通过反复地机械式技巧，如弹钢琴，锻炼出的复杂的肌肉记忆，会再返回到思维，日渐改造思维方式。

• 战拖大法：
o   尝试短时间之内，改变感性诉求，忍一忍坚持做下去。但通常情况强迫地工作，作效率会很低。
o   尝试赋予仪式感，找到路径依赖的入口，快速转变思维模式，进入状态高效运转。e.g.海明威，通过单腿站着写作让文字尽可能简洁；一个作家写作时会放个烂苹果，迫使写作尽快完成。专业人士经过训练，甚至做到十秒钟就能进入解决问题的正确姿势。
o   尝试忽然中断，把中断变成主动中断 。非中断心智进程，而是切换工作方式。通过多领域切换，让大脑从新任务中短暂歇息，多向的工作输出，切换。
o   赋予成就感。将8小时任务，分解成16个半小时任务（类似番茄钟）。多考虑已经完成多少，达到的里程碑，能获得更多成就感，激励大脑不断前进。
o   其他情况。血糖低？士力架帮到你。

• 牛魔王
o   Q： 如何有效率处理1000多个档案？
o   立指标，分工 一team人，对人物进行切分，大家认领，1000个任务则变成个人的300个任务。能力强者高调做事，更有成就感。做得比较挫的，自觉请吃饭。
o   向上管理。为上级考虑，将期待之外的希望变成希望以内。（建立激励机制）
o   建立索引。先做全局图景/思维导图。

o   Q：如何有效协商？什么情况下他人愿意理解你并支持你？
o   用同理心理解对方。
o   作为作为中间人，可用专业知识，把困境和解决方法提出来。但专业名词是学术领域翻译成同一套语境，可以进行计算和研讨的一套语言，更适用于专业领域，较为抽象，也是常见的行业「黑话」。角色是调节的话，更应注重沟通过程，输出专业服务，沟通双方需求。
o   罗伯特议事规则十三条（http://www.jianshu.com/p/9d5905c23e80）
